// Generated by rust-js from test/imports/inner/leaf.rs. Do not edit.

import { join as join$1 } from "node:path";
import greet from "../greet.js";
import wave from "./wave.js";

function join(greeting) {
  return greeting;
}

export function hello() {
  return join(greet("leaf"));
}

export function bye() {
  return wave("leaf");
}

export function joined() {
  return join(join$1("a", "leaf"));
}
//# sourceMappingURL=leaf.js.map
