// Generated by rust-js from test/imports/inner/leaf.rs. Do not edit.

import greet from "../greet.js";
import wave from "./wave.js";

function join(greeting) {
  return greeting;
}

export function hello() {
  return join(greet("leaf"));
}

export function bye() {
  return wave("leaf");
}
//# sourceMappingURL=leaf.js.map
