// Generated by rust-js from test/corpus/array_repeat.rs. Do not edit.

const SIZE = 2;

function made(name, n) {
  console.log(`made ${name}`);
  return n;
}

function main() {
  const zeros = new Array(1024).fill(0);
  const flags = [true, true, true];
  console.log(
    `${zeros.length} ${zeros.map((b) => b).reduce((a, b) => (a + b) >>> 0, 0)} [${flags.map((item) => String(item)).join(", ")}]`,
  );
  const item = [0, 0, 0];
  let grid = Array.from({ length: 4 }, () => item.slice());
  grid[1][2] = 7;
  console.log(
    `[${grid
      .map((item) => item.slice())
      .map((item) => `[${item.map((item) => String(item)).join(", ")}]`)
      .join(", ")}]`,
  );
  const item$1 = { x: 1 };
  let points = Array.from({ length: 3 }, () => ({ ...item$1 }));
  points[0].x = 5;
  console.log(
    `[${points
      .map((item) => ({ ...item }))
      .map((item) => pDebug_fmt(item))
      .join(", ")}]`,
  );
  const once = new Array(3).fill(made("once", 4));
  const none = new Array(0).fill(made("none", 9));
  console.log(
    `[${once
      .slice()
      .map((item) => String(item))
      .join(", ")}] ${none.length}`,
  );
  const options = [2, 2];
  console.log(`[${options.map((item) => (item == null ? "None" : `Some(${item})`)).join(", ")}]`);
  let row = [0, 0, 0];
  row[1] = 5;
  const item$2 = [0, 0, 0];
  let pair = Array.from({ length: 2 }, () => item$2.slice());
  pair[0][1] = 5;
  console.log(
    `[${row
      .slice()
      .map((item) => String(item))
      .join(", ")}] [${pair
      .map((item) => item.slice())
      .map((item) => `[${item.map((item) => String(item)).join(", ")}]`)
      .join(", ")}]`,
  );
}

export function entry() {
  main();
}

function pDebug_fmt(p) {
  return `P { x: ${p.x} }`;
}
//# sourceMappingURL=case.js.map
