// Generated by rust-js from test/corpus/assignment_order_compound.rs. Do not edit.

import { $at } from "@rust-js/runtime";

export function entry() {
  main();
}

function value(x) {
  console.log("value");
  return x;
}

function main() {
  const v = [];
  const i = 0;
  const value$1 = value(1);
  v[$at(v, i)] = (v[$at(v, i)] + value$1) | 0;
}
//# sourceMappingURL=case.js.map
