// Generated by rust-js from test/corpus/associated_types.rs. Do not edit.

import { $debugStr, $someValue } from "@rust-js/runtime";

var $countSource, $wordsSource, $countLabeled, $wordsLabeled;

function drain(s, SSource) {
  const out = [];
  while (true) {
    const x = SSource.next_item(s);
    if (x != null) {
      const x$1 = $someValue(x);
      out.push(x$1);
    } else {
      break;
    }
  }
  return out;
}

function total(s, SSource) {
  return drain(s, SSource).reduce((a, b) => (a + b) >>> 0, 0);
}

function shown(s, SSource, SItemDebug) {
  return `[${drain(s, SSource)
    .map((item) => SItemDebug.fmt(item))
    .join(", ")}]`;
}

function tag(l, LLabeled) {
  return `<${LLabeled.LabelDisplay().fmt(LLabeled.label(l))}>`;
}

function all(i) {
  return Iterator.from(i).toArray();
}

function main() {
  const result = drain({ value: { n: 3 } }, countSource());
  console.log(`[${result.map((item) => String(item)).join(", ")}]`);
  const result$1 = drain({ value: { list: ["a", "b"] } }, wordsSource());
  console.log(`[${result$1.map((item) => $debugStr(item)).join(", ")}]`);
  const result$2 = total({ value: { n: 4 } }, countSource());
  const tmp = result$2;
  const result$3 = shown({ value: { list: ["x"] } }, wordsSource(), {
    fmt: (value) => $debugStr(value),
  });
  console.log(`${tmp} ${result$3}`);
  console.log(`${tag({ n: 7 }, countLabeled())} ${tag({ list: ["p", "q"] }, wordsLabeled())}`);
  console.log(
    `[${all([1, 2].map((n) => Math.imul(n, 10) >>> 0))
      .map((item) => String(item))
      .join(", ")}]`,
  );
  const source = { value: { n: 2 }, impl: countSource() };
  const arg = source.impl.next_item(source);
  const arg$1 = source.impl.next_item(source);
  console.log(
    `${arg == null ? "None" : `Some(${arg})`} ${arg$1 == null ? "None" : `Some(${arg$1})`}`,
  );
}

export function entry() {
  main();
}

function countSource_next_item(count) {
  if (count.n === 0) {
    return;
  }
  count.n = (count.n - 1) >>> 0;
  return count.n;
}

function wordsSource_next_item(words) {
  return words.list.pop();
}

function countLabeled_label(count) {
  return count.n;
}

function wordsLabeled_label(words) {
  return words.list.join("+");
}

function countSource() {
  if ($countSource === undefined) {
    $countSource = { next_item: (arg0) => countSource_next_item(arg0.value) };
  }
  return $countSource;
}

function wordsSource() {
  if ($wordsSource === undefined) {
    $wordsSource = { next_item: (arg0) => wordsSource_next_item(arg0.value) };
  }
  return $wordsSource;
}

function countLabeled() {
  if ($countLabeled === undefined) {
    $countLabeled = { LabelDisplay: () => ({ fmt: String }), label: countLabeled_label };
  }
  return $countLabeled;
}

function wordsLabeled() {
  if ($wordsLabeled === undefined) {
    $wordsLabeled = { LabelDisplay: () => ({ fmt: (value) => value }), label: wordsLabeled_label };
  }
  return $wordsLabeled;
}
//# sourceMappingURL=case.js.map
