// Generated by rust-js from test/corpus/associated_type_drops.rs. Do not edit.

import { $byteLen, $some, $someValue } from "@rust-js/runtime";

var $loudZone, $quietZone, $loudSource;

export function entry() {
  main();
}

function noisyDrop_drop(noisy) {
  console.log(`drop ${noisy[0]}`);
}

function loudZone() {
  if ($loudZone === undefined) {
    $loudZone = { offset: loudZone_offset, show: loudZone_show, $dropOffset: noisyDrop_drop };
  }
  return $loudZone;
}

function loudZone_offset(loud, name) {
  return [name];
}

function loudZone_show(offset) {
  return `loud ${offset[0]}`;
}

function quietZone() {
  if ($quietZone === undefined) {
    $quietZone = { offset: quietZone_offset, show: quietZone_show };
  }
  return $quietZone;
}

function quietZone_offset(quiet, name) {
  return $byteLen(name);
}

function quietZone_show(offset) {
  return `quiet ${offset}`;
}

function stamp(zone, at, name, ZZone) {
  return { at, offset: ZZone.offset(zone, name) };
}

function describe(zone, ZZone) {
  const first = ZZone.offset(zone, "first");
  try {
    console.log(`made ${ZZone.show(first)}`);
    const second = stamp(zone, 7n, "second", ZZone);
    try {
      console.log(`stamp ${second.at} ${ZZone.show(second.offset)}`);
      const maybe = $some(ZZone.offset(zone, "maybe"));
      try {
        console.log(`some ${maybe != null}`);
        const inner = ZZone.offset(zone, "inner");
        try {
          console.log(`inner ${ZZone.show(inner)}`);
        } finally {
          ZZone.$dropOffset?.(inner);
        }
        let replaced = ZZone.offset(zone, "old");
        try {
          console.log(`was ${ZZone.show(replaced)}`);
          const next = ZZone.offset(zone, "new");
          ZZone.$dropOffset?.(replaced);
          replaced = next;
          console.log(`replaced ${ZZone.show(replaced)}`);
          console.log("end");
        } finally {
          ZZone.$dropOffset?.(replaced);
        }
      } finally {
        if (maybe != null) {
          ZZone.$dropOffset?.($someValue(maybe));
        }
      }
    } finally {
      ZZone.$dropOffset?.(second.offset);
    }
  } finally {
    ZZone.$dropOffset?.(first);
  }
}

function loudSource() {
  if ($loudSource === undefined) {
    $loudSource = { make: loudSource_make, $dropItem: noisyDrop_drop };
  }
  return $loudSource;
}

function loudSource_make(loud) {
  return ["made"];
}

function take(source, SSource) {
  const _item = SSource.make(source);
  try {
    console.log("taken");
  } finally {
    SSource.$dropItem?.(_item);
  }
}

function main() {
  describe(undefined, loudZone());
  describe(undefined, quietZone());
  const kept = stamp(undefined, 1n, "kept", loudZone());
  try {
    console.log(`kept ${kept.at}`);
    const source = { impl: loudSource() };
    take(source, { make: (object) => object.impl.make(object.value), $dropItem: noisyDrop_drop });
    take(undefined, loudSource());
  } finally {
    noisyDrop_drop(kept.offset);
  }
}
//# sourceMappingURL=case.js.map
