// Generated by rust-js from test/corpus/begin_panic_str.rs. Do not edit.

export function entry() {
  main();
}

function check(n, expected) {
  if (n !== expected) {
    throw new Error("the answer isn't 41");
  }
}

function never(n) {
  if (n < 0) {
    throw new Error("explicit panic");
  }
  if (n > 100) {
    throw new Error("{}");
  }
}

function main() {
  never(5);
  check(41, 41);
  console.log("checked");
  check(42, 41);
}
//# sourceMappingURL=case.js.map
