// Generated by rust-js from test/corpus/block_modules.rs. Do not edit.

import { NAME as NAME$1 } from "./names$1.js";
import { name } from "./names$2.js";
import { NAME } from "./names.js";
import { $debugStr } from "@rust-js/runtime";

export function entry() {
  main();
}

function first() {
  return NAME$1;
}

function second() {
  return name();
}

const ALL = ["constant", "and more"];

function main() {
  console.log(`${NAME} ${first()} ${second()} [${ALL.map((item) => $debugStr(item)).join(", ")}]`);
}
//# sourceMappingURL=case.js.map
