// Generated by rust-js from test/corpus/btree_end_entries.rs. Do not edit.

import {
  $cmp,
  $debugStr,
  $endEntry,
  $entryGet,
  $entryInsert,
  $entryRemove,
  $range,
  $sortedEntries,
  $unwrap,
} from "@rust-js/runtime";

export function entry() {
  main();
}

function main() {
  const names = new Map($range(1, 4 + 1).map((i) => [i, String(i)]));
  const first = $endEntry(names, $cmp, false);
  if (first) {
    const first$1 = first;
    const cell = $entryGet(first$1, true);
    cell.value += "!";
    console.log(`${first$1[1]} ${$entryGet(first$1)}`);
  }
  const last = $endEntry(names, $cmp, true);
  if (last) {
    const arg = $entryRemove(last, true);
    console.log(`(${arg[0]}, ${$debugStr(arg[1])})`);
  }
  console.log(
    `{${Array.from($sortedEntries(names, $cmp))
      .map(([key, value]) => `${key}: ${$debugStr(value)}`)
      .join(", ")}}`,
  );
  const counts = new Map([
    ["b", 2],
    ["a", 1],
    ["c", 3],
  ]);
  const first$2 = $endEntry(counts, $cmp, false);
  if (first$2) {
    const first$3 = first$2;
    const cell$1 = $entryGet(first$3, true);
    cell$1.value = (cell$1.value + 10) | 0;
    const old = $entryInsert(first$3, 100);
    const arg$1 = $entryGet(first$3);
    console.log(`${old} ${arg$1}`);
  }
  const cell$2 = $entryGet($unwrap($endEntry(counts, $cmp, true)), true);
  cell$2.value = Math.imul(cell$2.value, 7);
  console.log(
    `{${Array.from($sortedEntries(counts, $cmp))
      .map(([key, value]) => `${$debugStr(key)}: ${value}`)
      .join(", ")}}`,
  );
  const e = $endEntry(counts, $cmp, false);
  const arg$2 = e ? $entryRemove(e) : undefined;
  console.log(`${arg$2 == null ? "None" : `Some(${arg$2})`}`);
  console.log(
    `{${Array.from($sortedEntries(counts, $cmp))
      .map(([key, value]) => `${$debugStr(key)}: ${value}`)
      .join(", ")}}`,
  );
  const empty = new Map();
  console.log(`${!$endEntry(empty, $cmp, false)} ${!$endEntry(empty, $cmp, true)}`);
}
//# sourceMappingURL=case.js.map
