// Generated by rust-js from test/corpus/btree_range_mut.rs. Do not edit.

import {
  $cmp,
  $debugStr,
  $insertStr,
  $iter,
  $mutEntries,
  $next,
  $print,
  $range,
  $rest,
  $sortedEntries,
  $treeRange,
} from "@rust-js/runtime";

export function entry() {
  main();
}

function main() {
  const scores = new Map($range(1, 6 + 1).map((k) => [k, Math.imul(k | 0, 10)]));
  for (const item of $mutEntries(
    scores,
    $treeRange(scores, $cmp, false, "BTreeMap", true, 2, true, 5, false),
  )) {
    item[1].value = (item[1].value + (item[0] | 0)) | 0;
  }
  console.log(
    `{${Array.from($sortedEntries(scores, $cmp))
      .map(([key, value]) => `${key}: ${value}`)
      .join(", ")}}`,
  );
  const total = $mutEntries(
    scores,
    $treeRange(scores, $cmp, false, "BTreeMap", false, undefined, true, 3, true),
  )
    .map((param) => {
      param[1].value = Math.imul(param[1].value, 2);
      return param[1].value;
    })
    .reduce((a, b) => (a + b) | 0, 0);
  console.log(
    `${total} {${Array.from($sortedEntries(scores, $cmp))
      .map(([key, value]) => `${key}: ${value}`)
      .join(", ")}}`,
  );
  const names = new Map([
    ["ann", "a"],
    ["bob", "b"],
    ["cy", "c"],
  ]);
  for (const item$1 of $mutEntries(
    names,
    $treeRange(names, $cmp, false, "BTreeMap", true, "b", false, undefined, false),
  )) {
    item$1[1].value = item$1[1].value + "!";
  }
  const value = $mutEntries(
    names,
    $treeRange(names, $cmp, false, "BTreeMap", false, undefined, true, "ann", true),
  ).at(-1);
  if (value) {
    value[1].value = $insertStr(value[1].value, 0, ">");
    console.log(`${value[0]}`);
  }
  const last = $iter(
    $mutEntries(names, $treeRange(names, $cmp, false, "BTreeMap", true, "a", true, "c", false)),
  );
  const value$1 = $next(last);
  if (value$1) {
    value$1[1].value = value$1[1].value.toUpperCase();
  }
  const arg = $rest(last).length;
  console.log(
    `{${Array.from($sortedEntries(names, $cmp))
      .map(([key, value]) => `${$debugStr(key)}: ${$debugStr(value)}`)
      .join(", ")}} ${arg}`,
  );
  const points = new Map($range(0, 4).map((k) => [k, [k, 0]]));
  for (const [, p] of $treeRange(points, $cmp, false, "BTreeMap", true, 1, true, 3, false)) {
    p[1] = (p[1] + 5) | 0;
  }
  const arg$1 = $treeRange(
    points,
    $cmp,
    false,
    "BTreeMap",
    true,
    9,
    false,
    undefined,
    false,
  ).length;
  console.log(
    `{${Array.from($sortedEntries(points, $cmp))
      .map(([key, value]) => `${key}: (${value[0]}, ${value[1]})`)
      .join(", ")}} ${arg$1}`,
  );
  const set = new Set($range(0, 5));
  for (const x of $treeRange(set, $cmp, true, "BTreeSet", true, 2, true, 4, false)) {
    $print(`${x} `);
  }
  console.log("");
}
//# sourceMappingURL=case.js.map
