// Generated by rust-js from test/corpus/by_ref_chains.rs. Do not edit.

import {
  $byteLen,
  $debugStr,
  $iter,
  $lazyTakeWhile,
  $next,
  $position,
  $range,
  $rest,
  $restStr,
} from "@rust-js/runtime";

export function entry() {
  main();
}

function main() {
  const v = [1, 2, 3, 4, 5, 6, 7, 8];
  const it = $iter(v);
  const first = Iterator.from(it).take(2).toArray();
  const small = $lazyTakeWhile(Iterator.from(it), (x) => x < 5).toArray();
  const arg = $next(it);
  console.log(
    `[${first.map((item) => String(item)).join(", ")}] [${small.map((item) => String(item)).join(", ")}] ${arg == null ? "None" : `Some(${arg})`}`,
  );
  const found = Iterator.from(it).find((x) => x % 7 === 0);
  const arg$1 = it.items.slice(it.at, it.end);
  console.log(
    `${found == null ? "None" : `Some(${found})`} [${arg$1.map((item) => String(item)).join(", ")}]`,
  );
  const words = $iter("one two three four five".split(" "));
  const sum = Iterator.from(words)
    .map((w) => $byteLen(w))
    .take(3)
    .reduce((a, b) => (a + b) >>> 0, 0);
  const any = Iterator.from(words).some((w) => w.startsWith("f"));
  const arg$2 = $next(words);
  console.log(`${sum} ${any} ${arg$2 == null ? "None" : `Some(${$debugStr(arg$2)})`}`);
  const chars = $iter(Array.from("abcdef"));
  const skipped = $next(Iterator.from(chars).drop(1));
  const pos = $position(Iterator.from(chars), (c) => c === "e");
  const arg$3 = $restStr(chars);
  console.log(
    `${skipped == null ? "None" : `Some(${$debugStr(skipped, "'")})`} ${pos == null ? "None" : `Some(${pos})`} ${$debugStr(arg$3)}`,
  );
  const nums = $iter($range(10, 20));
  const evens = Iterator.from(nums)
    .filter((n) => n % 2 === 0)
    .take(2)
    .toArray().length;
  const rest = $rest(nums).reduce((a, b) => (a + b) >>> 0, 0);
  console.log(`${evens} ${rest}`);
}
//# sourceMappingURL=case.js.map
