// Generated by rust-js from test/corpus/byte_ascii.rs. Do not edit.

import { $debugUtf8Error, $fromUtf8, $range, $unwrapOk } from "@rust-js/runtime";

export function entry() {
  main();
}

function digits(text) {
  let n = 0;
  for (const b of Array.from(new TextEncoder().encode(text))) {
    if (!(b >= 48 && b <= 57)) {
      break;
    }
    n = ((Math.imul(n, 10) >>> 0) + ((b - 48) & 255)) >>> 0;
  }
  return n;
}

function main() {
  console.log(`${digits("2024-10-05")}`);
  const tests = [
    ["digit", (x) => x >= 48 && x <= 57],
    ["hexdigit", (x) => (x >= 48 && x <= 57) || (x >= 65 && x <= 70) || (x >= 97 && x <= 102)],
    ["alphabetic", (x) => (x >= 65 && x <= 90) || (x >= 97 && x <= 122)],
    ["alphanumeric", (x) => (x >= 48 && x <= 57) || (x >= 65 && x <= 90) || (x >= 97 && x <= 122)],
    ["uppercase", (x) => x >= 65 && x <= 90],
    ["lowercase", (x) => x >= 97 && x <= 122],
    ["whitespace", (x) => (x >= 9 && x <= 10) || (x >= 12 && x <= 13) || x === 32],
    [
      "punctuation",
      (x) =>
        (x >= 33 && x <= 47) ||
        (x >= 58 && x <= 64) ||
        (x >= 91 && x <= 96) ||
        (x >= 123 && x <= 126),
    ],
    ["graphic", (x) => x >= 33 && x <= 126],
    ["control", (x) => x <= 31 || x === 127],
    ["ascii", (x) => x <= 127],
  ];
  for (const [name, test] of tests) {
    const count = $range(0, 255 + 1).filter((b) => test(b)).length;
    const first = $range(0, 255 + 1).find((b) => test(b)) ?? 0;
    const last =
      $range(0, 255 + 1)
        .toReversed()
        .find((b) => test(b)) ?? 0;
    console.log(`${name} ${count} ${first} ${last}`);
  }
  const b = 103;
  console.log(
    `${(b >= 65 && b <= 90) || (b >= 97 && b <= 122)} ${(b >= 48 && b <= 57) || (b >= 65 && b <= 70) || (b >= 97 && b <= 102)} ${(70 >= 48 && 70 <= 57) || (70 >= 65 && 70 <= 70) || (70 >= 97 && 70 <= 102)}`,
  );
  console.log(
    `${(32 >= 9 && 32 <= 10) || (32 >= 12 && 32 <= 13) || 32 === 32} ${(11 >= 9 && 11 <= 10) || (11 >= 12 && 11 <= 13) || 11 === 32}`,
  );
  console.log(
    `${b >= 97 && b <= 122 ? b - 32 : b} ${81 >= 65 && 81 <= 90 ? 81 + 32 : 81} ${55 >= 97 && 55 <= 122 ? 55 - 32 : 55}`,
  );
  const word = [72, 101, 108, 108, 111, 44, 32, 87, 111, 114, 108, 100, 33].map((b) =>
    b >= 97 && b <= 122 ? b - 32 : b,
  );
  console.log(`${$unwrapOk($fromUtf8(word, true), undefined, (e) => $debugUtf8Error(e, true))}`);
}
//# sourceMappingURL=case.js.map
