// Generated by rust-js from test/corpus/byte_strings.rs. Do not edit.

import { $cmp, $cmpItems, $eq, $slice } from "@rust-js/runtime";

function method(line) {
  if (line.length === 3 && line[0] === 71 && line[1] === 69 && line[2] === 84) {
    return "get";
  } else if (
    line.length === 4 &&
    line[0] === 80 &&
    line[1] === 79 &&
    line[2] === 83 &&
    line[3] === 84
  ) {
    return "post";
  } else if (line.length === 0) {
    return "empty";
  } else {
    return "other";
  }
}

function checksum(bytes) {
  return bytes.map((b) => b).reduce((a, b) => (a + b) >>> 0, 0);
}

function main() {
  const get = [71, 69, 84];
  console.log(`[${get.map((item) => String(item)).join(", ")}] ${get.length} ${method(get)}`);
  console.log(`${method([80, 79, 83, 84])} ${method([])}`);
  const raw = [97, 1, 255, 10, 92, 34];
  console.log(`[${raw.map((item) => String(item)).join(", ")}] ${checksum(raw)}`);
  const joined = [97, 98, 99, 100];
  console.log(
    `[${joined.map((item) => String(item)).join(", ")}] ${$eq(joined, [97, 98, 99, 100])}`,
  );
  const left = [122, 122];
  const right = [122, 97];
  console.log(`${$cmpItems(left, right, $cmp) > 0}`);
  const word = "héllo €";
  const bytes = Array.from(new TextEncoder().encode(word));
  console.log(
    `${Array.from(word).length} ${bytes.length} [${$slice(bytes, 0, 3)
      .map((item) => String(item))
      .join(", ")}]`,
  );
  console.log(`${checksum(Array.from(new TextEncoder().encode("abc")))}`);
  console.log(`${method(Array.from(new TextEncoder().encode("GET")))}`);
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
