// Generated by rust-js from test/corpus/calculator.rs. Do not edit.

import {
  $cmp,
  $collectResults,
  $debugF64,
  $debugStr,
  $displayF64,
  $eq,
  $f64Max,
  $f64Min,
  $index,
  $iter,
  $next,
  $nextIf,
  $parseF64,
  $peek,
  $powf,
  $slice,
} from "@rust-js/runtime";

var $calcErrorDisplay;

const Parser = {
  peek(parser) {
    return parser.tokens[parser.at];
  },
  next(parser) {
    const token = parser.tokens[parser.at];
    parser.at = (parser.at + 1) >>> 0;
    return token;
  },
  expect(parser, token, what) {
    const match = Parser.next(parser);
    if (match != null && $eq(match, token)) {
      return { TAG: "Ok", _0: undefined };
    }
    return { TAG: "Err", _0: { TAG: "Expected", _0: what } };
  },
  expr(parser) {
    const result = Parser.term(parser);
    if (result.TAG === "Err") {
      return result;
    }
    let left = result._0;
    while (true) {
      const value = Parser.peek(parser);
      if (value != null && value.TAG === "Op" && (value._0 === "+" || value._0 === "-")) {
        Parser.next(parser);
        const result$1 = Parser.term(parser);
        if (result$1.TAG === "Err") {
          return result$1;
        }
        const right = result$1._0;
        left = { TAG: "Bin", _0: left, _1: value._0, _2: right };
      } else {
        break;
      }
    }
    return { TAG: "Ok", _0: left };
  },
  term(parser) {
    const result = Parser.power(parser);
    if (result.TAG === "Err") {
      return result;
    }
    let left = result._0;
    while (true) {
      const value = Parser.peek(parser);
      if (value != null && value.TAG === "Op" && (value._0 === "*" || value._0 === "/")) {
        Parser.next(parser);
        const result$1 = Parser.power(parser);
        if (result$1.TAG === "Err") {
          return result$1;
        }
        const right = result$1._0;
        left = { TAG: "Bin", _0: left, _1: value._0, _2: right };
      } else {
        break;
      }
    }
    return { TAG: "Ok", _0: left };
  },
  power(parser) {
    const result = Parser.unary(parser);
    if (result.TAG === "Err") {
      return result;
    }
    const base = result._0;
    const value = Parser.peek(parser);
    if (value != null && value.TAG === "Op" && value._0 === "^") {
      Parser.next(parser);
      const result$1 = Parser.power(parser);
      if (result$1.TAG === "Err") {
        return result$1;
      }
      const exponent = result$1._0;
      return { TAG: "Ok", _0: { TAG: "Bin", _0: base, _1: "^", _2: exponent } };
    }
    return { TAG: "Ok", _0: base };
  },
  unary(parser) {
    const match = Parser.next(parser);
    if (match != null && match.TAG === "Op" && match._0 === "-") {
      const result = Parser.unary(parser);
      if (result.TAG === "Err") {
        return result;
      }
      return { TAG: "Ok", _0: { TAG: "Neg", _0: result._0 } };
    }
    if (match != null && match.TAG === "Num") {
      return { TAG: "Ok", _0: { TAG: "Num", _0: match._0 } };
    }
    if (match != null && match.TAG === "Ident") {
      const value = Parser.peek(parser);
      if (value === "LParen") {
        Parser.next(parser);
        const args = [];
        if (Parser.peek(parser) !== "RParen") {
          const result$1 = Parser.expr(parser);
          if (result$1.TAG === "Err") {
            return result$1;
          }
          args.push(result$1._0);
          while (true) {
            const value$1 = Parser.peek(parser);
            if (value$1 === "Comma") {
              Parser.next(parser);
              const result$2 = Parser.expr(parser);
              if (result$2.TAG === "Err") {
                return result$2;
              }
              args.push(result$2._0);
            } else {
              break;
            }
          }
        }
        const result$3 = Parser.expect(parser, "RParen", "')'");
        if (result$3.TAG === "Err") {
          return result$3;
        }
        return { TAG: "Ok", _0: { TAG: "Call", _0: match._0, _1: args } };
      }
      return { TAG: "Ok", _0: { TAG: "Var", _0: match._0 } };
    }
    if (match === "LParen") {
      const result$4 = Parser.expr(parser);
      if (result$4.TAG === "Err") {
        return result$4;
      }
      const inner = result$4._0;
      const result$5 = Parser.expect(parser, "RParen", "')'");
      if (result$5.TAG === "Err") {
        return result$5;
      }
      return { TAG: "Ok", _0: inner };
    }
    if (match != null) {
      return { TAG: "Err", _0: { TAG: "Expected", _0: `a value, not ${tokenDebug_fmt(match)}` } };
    }
    return { TAG: "Err", _0: "UnexpectedEnd" };
  },
};

const Calculator = {
  new() {
    const functions = new Map();
    functions.set("max", [2, (a) => $f64Max($index(a, 0), $index(a, 1))]);
    functions.set("min", [2, (a) => $f64Min($index(a, 0), $index(a, 1))]);
    functions.set("sqrt", [1, (a) => Math.sqrt($index(a, 0))]);
    functions.set("abs", [1, (a) => Math.abs($index(a, 0))]);
    const vars = new Map();
    vars.set("pi", 3.141592653589793);
    return { vars, functions };
  },
  eval(calculator, expr) {
    let tmp;
    if (expr.TAG === "Num") {
      tmp = expr._0;
    } else if (expr.TAG === "Var") {
      const option = calculator.vars.get(expr._0);
      const result =
        option != null
          ? { TAG: "Ok", _0: option }
          : { TAG: "Err", _0: { TAG: "Unknown", _0: expr._0 } };
      if (result.TAG === "Err") {
        return result;
      }
      tmp = result._0;
    } else if (expr.TAG === "Neg") {
      const result$1 = Calculator.eval(calculator, expr._0);
      if (result$1.TAG === "Err") {
        return result$1;
      }
      tmp = -result$1._0;
    } else if (expr.TAG === "Bin") {
      const result$2 = Calculator.eval(calculator, expr._0);
      if (result$2.TAG === "Err") {
        return result$2;
      }
      const tmp$1 = result$2._0;
      const result$3 = Calculator.eval(calculator, expr._2);
      if (result$3.TAG === "Err") {
        return result$3;
      }
      const [a, b] = [tmp$1, result$3._0];
      if (expr._1 === "+") {
        tmp = a + b;
      } else if (expr._1 === "-") {
        tmp = a - b;
      } else if (expr._1 === "*") {
        tmp = a * b;
      } else if (expr._1 === "/" && b === 0) {
        return { TAG: "Err", _0: "DivideByZero" };
      } else if (expr._1 === "/") {
        tmp = a / b;
      } else {
        tmp = $powf(a, b);
      }
    } else {
      const option$1 = calculator.functions.get(expr._0);
      const result$4 =
        option$1 != null
          ? { TAG: "Ok", _0: option$1 }
          : { TAG: "Err", _0: { TAG: "Unknown", _0: expr._0 } };
      if (result$4.TAG === "Err") {
        return result$4;
      }
      const [wanted, f] = result$4._0;
      if (expr._1.length !== wanted) {
        return { TAG: "Err", _0: { TAG: "Arity", name: expr._0, wanted, got: expr._1.length } };
      }
      const result$5 = $collectResults(
        expr._1.values().map((a$1) => Calculator.eval(calculator, a$1)),
      );
      if (result$5.TAG === "Err") {
        return result$5;
      }
      const values = result$5._0;
      tmp = f(values);
    }
    return { TAG: "Ok", _0: tmp };
  },
  run(calculator, line) {
    const result = tokenize(line);
    if (result.TAG === "Err") {
      return result;
    }
    const tokens = result._0;
    const value = tokens;
    if (value.length >= 2 && value[0].TAG === "Ident" && value[1] === "Assign") {
      const name = value[0]._0;
      const parser = { tokens: $slice(tokens, 2).slice(), at: 0 };
      const result$1 = Parser.expr(parser);
      if (result$1.TAG === "Err") {
        return result$1;
      }
      const result$2 = Calculator.eval(calculator, result$1._0);
      if (result$2.TAG === "Err") {
        return result$2;
      }
      const value$1 = result$2._0;
      calculator.vars.set(name, value$1);
      return { TAG: "Ok", _0: undefined };
    }
    const parser$1 = { tokens, at: 0 };
    const result$3 = Parser.expr(parser$1);
    if (result$3.TAG === "Err") {
      return result$3;
    }
    const expr = result$3._0;
    const extra = Parser.peek(parser$1);
    if (extra != null) {
      return { TAG: "Err", _0: { TAG: "Expected", _0: `the end, not ${tokenDebug_fmt(extra)}` } };
    }
    return Calculator.eval(calculator, expr);
  },
};

function number(chars) {
  let text = "";
  while (true) {
    const value = $peek(chars);
    if (value != null) {
      if (/^[0-9]$/.test(value) || value === ".") {
        text += value;
        $next(chars);
      } else {
        break;
      }
    } else {
      break;
    }
  }
  const result = $parseF64(text);
  return result.TAG === "Ok" ? result._0 : 0;
}

function tokenize(source) {
  const tokens = [];
  const chars = $iter(Array.from(source));
  while (true) {
    const value = $peek(chars);
    if (value != null) {
      if (value === " ") {
        $next(chars);
      } else if ((value >= "0" && value <= "9") || value === ".") {
        tokens.push({ TAG: "Num", _0: number(chars) });
      } else if (
        (value >= "a" && value <= "z") ||
        (value >= "A" && value <= "Z") ||
        value === "_"
      ) {
        let name = "";
        while (true) {
          const c = $nextIf(chars, (c) => /^[\p{Alphabetic}\p{N}]$/u.test(c) || c === "_");
          if (c != null) {
            name += c;
          } else {
            break;
          }
        }
        tokens.push({ TAG: "Ident", _0: name });
      } else if (
        value === "+" ||
        value === "-" ||
        value === "*" ||
        value === "/" ||
        value === "^"
      ) {
        tokens.push({ TAG: "Op", _0: value });
        $next(chars);
      } else if (value === "(") {
        tokens.push("LParen");
        $next(chars);
      } else if (value === ")") {
        tokens.push("RParen");
        $next(chars);
      } else if (value === ",") {
        tokens.push("Comma");
        $next(chars);
      } else if (value === "=") {
        tokens.push("Assign");
        $next(chars);
      } else {
        return { TAG: "Err", _0: { TAG: "Unexpected", _0: value } };
      }
    } else {
      break;
    }
  }
  return { TAG: "Ok", _0: tokens };
}

function main() {
  const calc = Calculator.new();
  const lines = [
    "1 + 2 * 3",
    "(1 + 2) * 3",
    "2 ^ 3 ^ 2",
    "-4 + 10 / 4",
    "x = 7",
    "y = x * 2 - 1",
    "max(x, y) + min(1, sqrt(16))",
    "abs(-2.5) * pi",
    "10 / (x - 7)",
    "foo + 1",
    "max(1)",
    "3 $ 4",
    "(1 + 2",
    "1 2",
  ];
  for (const line of lines) {
    const match = Calculator.run(calc, line);
    if (match.TAG === "Ok" && match._0 != null) {
      console.log(`${line} => ${$displayF64(match._0)}`);
    } else if (match.TAG === "Ok" && match._0 == null) {
      console.log(`${line}`);
    } else {
      console.log(`${line} !! ${calcErrorDisplay_fmt(match._0)}`);
    }
  }
  const names = Array.from(calc.vars.keys());
  names.sort($cmp);
  console.log(`${names.join(", ")}`);
}

export function entry() {
  main();
}

function tokenDebug_fmt(token) {
  if (token.TAG === "Num") {
    return `Num(${$debugF64(token._0)})`;
  }
  if (token.TAG === "Ident") {
    return `Ident(${$debugStr(token._0)})`;
  }
  if (token.TAG === "Op") {
    return `Op(${$debugStr(token._0, "'")})`;
  }
  if (token === "LParen") {
    return "LParen";
  }
  if (token === "RParen") {
    return "RParen";
  }
  if (token === "Comma") {
    return "Comma";
  }
  return "Assign";
}

function calcErrorDisplay_fmt(calcError) {
  if (calcError.TAG === "Unexpected") {
    return `unexpected '${calcError._0}'`;
  }
  if (calcError === "UnexpectedEnd") {
    return "unexpected end of input";
  }
  if (calcError.TAG === "Expected") {
    return `expected ${calcError._0}`;
  }
  if (calcError.TAG === "Unknown") {
    return `unknown name \`${calcError._0}\``;
  }
  if (calcError === "DivideByZero") {
    return "division by zero";
  }
  return `${calcError.name} takes ${calcError.wanted} argument${calcError.wanted === 1 ? "" : "s"}, got ${calcError.got}`;
}

export function calcErrorDisplay() {
  if ($calcErrorDisplay === undefined) {
    $calcErrorDisplay = { fmt: calcErrorDisplay_fmt };
  }
  return $calcErrorDisplay;
}
//# sourceMappingURL=case.js.map
