// Generated by rust-js from test/corpus/cell_const.rs. Do not edit.

export function entry() {
  main();
}

const START = { value: 5 };
const LIMIT = {};

function bump() {
  const c = { value: 5 };
  c.value = (c.value + 1) | 0;
  return c.value;
}

function main() {
  console.log(`${bump()} ${bump()} 5`);
  const limit = {};
  limit.value = 3;
  console.log(`${limit.value == null ? "None" : `Some(${limit.value})`} None`);
}
//# sourceMappingURL=case.js.map
