// Generated by rust-js from test/corpus/char_from_code.rs. Do not edit.

import { $debugStr, $fromU32, $index, $unwrap } from "@rust-js/runtime";

export function entry() {
  main();
}

function decode(bytes) {
  const out = [];
  let i = 0;
  while (i < bytes.length) {
    const b = $index(bytes, i);
    const [point, width] =
      b < 128
        ? [b, 1]
        : b < 224
          ? [
              (((((b & 31) >>> 0) << 6) >>> 0) | (($index(bytes, (i + 1) >>> 0) & 63) >>> 0)) >>> 0,
              2,
            ]
          : b < 240
            ? [
                (((((((b & 15) >>> 0) << 12) >>> 0) |
                  (((($index(bytes, (i + 1) >>> 0) & 63) >>> 0) << 6) >>> 0)) >>>
                  0) |
                  (($index(bytes, (i + 2) >>> 0) & 63) >>> 0)) >>>
                  0,
                3,
              ]
            : [
                (((((((((b & 7) >>> 0) << 18) >>> 0) |
                  (((($index(bytes, (i + 1) >>> 0) & 63) >>> 0) << 12) >>> 0)) >>>
                  0) |
                  (((($index(bytes, (i + 2) >>> 0) & 63) >>> 0) << 6) >>> 0)) >>>
                  0) |
                  (($index(bytes, (i + 3) >>> 0) & 63) >>> 0)) >>>
                  0,
                4,
              ];
    out.push(String.fromCodePoint(point));
    i = (i + width) >>> 0;
  }
  return out;
}

function main() {
  const chars = decode(Array.from(new TextEncoder().encode("aé€😀")));
  console.log(`[${chars.map((item) => $debugStr(item, "'")).join(", ")}] ${chars.length}`);
  console.log(
    `[${chars
      .map((c) => c === $unwrap($fromU32(c.codePointAt(0))))
      .map((item) => String(item))
      .join(", ")}]`,
  );
}
//# sourceMappingURL=case.js.map
