// Generated by rust-js from test/corpus/closure_mut_ref.rs. Do not edit.

export function entry() {
  main();
}

function call(f) {
  f();
  f();
}

function passed_on(f) {
  call(f);
}

function apply(f, x) {
  return (f(x) + f(x)) | 0;
}

function dynamic(f) {
  return (Math.imul(f(), 10) + f()) | 0;
}

function square(x) {
  return Math.imul(x, x);
}

function main() {
  let count = 0;
  const tick = () => {
    count = (count + 1) | 0;
  };
  call(tick);
  passed_on(tick);
  tick();
  console.log(`${count}`);
  let total = 0;
  console.log(
    `${apply((x) => {
      total = (total + x) | 0;
      return total;
    }, 3)}`,
  );
  console.log(`${apply(square, 4)}`);
  let n = 0;
  console.log(
    `${dynamic(() => {
      n = (n + 1) | 0;
      return n;
    })}`,
  );
  console.log(`${total} ${n}`);
}
//# sourceMappingURL=case.js.map
