// Generated by rust-js from test/corpus/collect_fallible.rs. Do not edit.

import {
  $collectOptions,
  $collectResults,
  $debugParseError,
  $debugStr,
  $parseInt,
  $some,
} from "@rust-js/runtime";

function parse_all(v) {
  return $collectResults(v.values().map((s) => $parseInt(s, 0, 4294967295)));
}

function halves(v) {
  return $collectOptions(
    v.map((n) => {
      if (n % 2 === 0) {
        return (n / 2) >>> 0;
      }
      return undefined;
    }),
  );
}

function main() {
  const arg = parse_all(["1", "22"]);
  const arg$1 = parse_all(["1", "x", "3"]);
  console.log(
    `${arg.TAG === "Ok" ? `Ok([${arg._0.map((item) => String(item)).join(", ")}])` : `Err(${$debugParseError(arg._0, "ParseIntError")})`} ${arg$1.TAG === "Ok" ? `Ok([${arg$1._0.map((item) => String(item)).join(", ")}])` : `Err(${$debugParseError(arg$1._0, "ParseIntError")})`}`,
  );
  const arg$2 = halves([2, 4]);
  const arg$3 = halves([2, 3, 4]);
  console.log(
    `${arg$2 == null ? "None" : `Some([${arg$2.map((item) => String(item)).join(", ")}])`} ${arg$3 == null ? "None" : `Some([${arg$3.map((item) => String(item)).join(", ")}])`}`,
  );
  let seen = [];
  const r = $collectResults(
    [1, -2, 3].values().map((n) => {
      seen.push(n);
      if (n < 0) {
        return { TAG: "Err", _0: `negative ${n}` };
      }
      return { TAG: "Ok", _0: Math.imul(n, 10) };
    }),
  );
  console.log(
    `${r.TAG === "Ok" ? `Ok([${r._0.map((item) => String(item)).join(", ")}])` : `Err(${$debugStr(r._0)})`} [${seen.map((item) => String(item)).join(", ")}]`,
  );
  const nested = $collectOptions([1, $some(undefined)], true);
  const none = $collectOptions([1, undefined], true);
  console.log(
    `${nested == null ? "None" : `Some([${nested.map((item) => (item == null ? "None" : `Some(${item})`)).join(", ")}])`} ${none == null ? "None" : `Some([${none.map((item) => (item == null ? "None" : `Some(${item})`)).join(", ")}])`}`,
  );
  const deque = $collectResults([
    { TAG: "Ok", _0: 1 },
    { TAG: "Ok", _0: 2 },
  ]);
  console.log(
    `${deque.TAG === "Ok" ? `Ok([${deque._0.map((item) => String(item)).join(", ")}])` : "Err(())"}`,
  );
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
