// Generated by rust-js from test/corpus/compound_assignment_order.rs. Do not edit.

import { $at, $index } from "@rust-js/runtime";

function main() {
  let log = [];
  let grid = [
    [1, 2],
    [3, 4],
  ];
  let ps = [{ x: 1 }, { x: 2 }];
  let arr = [{ x: 5 }, { x: 6 }];
  let v = [10, 20, 30];
  let at = (i) => {
    log.push(i);
    return i;
  };
  const items = $index(grid, at(1));
  const index = $at(items, at(0));
  items[index] = (items[index] + 10) | 0;
  const value = at(3) | 0;
  const items$1 = $index(grid, at(0));
  const index$1 = $at(items$1, at(1));
  items$1[index$1] = Math.imul(items$1[index$1], value);
  const item = $index(ps, at(1));
  item.x = (item.x + 5) | 0;
  const value$1 = at(2) | 0;
  const item$1 = $index(arr, at(0));
  item$1.x = (item$1.x - value$1) | 0;
  const index$2 = $at(v, at(2));
  v[index$2] = (v[index$2] + 1) | 0;
  const value$2 = at(7) | 0;
  v[$at(v, 1)] = (v[$at(v, 1)] + value$2) | 0;
  console.log(
    `[${grid.map((item) => `[${item.map((item) => String(item)).join(", ")}]`).join(", ")}] [${ps.map((item) => pDebug_fmt(item)).join(", ")}] [${arr.map((item) => pDebug_fmt(item)).join(", ")}] [${v.map((item) => String(item)).join(", ")}]`,
  );
  console.log(`[${log.map((item) => String(item)).join(", ")}]`);
}

export function entry() {
  main();
}

function pDebug_fmt(p) {
  return `P { x: ${p.x} }`;
}
//# sourceMappingURL=case.js.map
