// Generated by rust-js from test/corpus/conditional_regions.rs. Do not edit.

export function entry() {
  main();
}

function bump(x) {
  x.value = (x.value + 1) | 0;
  return x.value;
}

function pick(take) {
  let x = 0;
  let tmp;
  if (take) {
    const x$1 = { value: x };
    const result = bump(x$1);
    x = x$1.value;
    tmp = result;
  } else {
    tmp = 7;
  }
  const picked = tmp;
  return (Math.imul(x, 10) + picked) | 0;
}

function both(take) {
  let x = 0;
  let y = 10;
  let tmp;
  if (take) {
    const x$1 = { value: x };
    const result = bump(x$1);
    x = x$1.value;
    tmp = result;
  } else {
    const x = { value: y };
    const result = bump(x);
    y = x.value;
    tmp = result;
  }
  const picked = tmp;
  return (((Math.imul(x, 1000) + Math.imul(y, 100)) | 0) + picked) | 0;
}

function guard(value) {
  let calls = 0;
  let tmp;
  if (value != null) {
    const x = { value: calls };
    const result = bump(x);
    calls = x.value;
    tmp = result === value;
  } else {
    tmp = false;
  }
  const matched = tmp;
  return (Math.imul(calls, 10) + (matched ? 1 : 0)) | 0;
}

function nested(take, inner) {
  let x = 0;
  let tmp$1;
  if (take) {
    let tmp;
    if (inner) {
      const x$1 = { value: x };
      const result = bump(x$1);
      x = x$1.value;
      tmp = result;
    } else {
      tmp = 3;
    }
    tmp$1 = tmp;
  } else {
    tmp$1 = 7;
  }
  const picked = tmp$1;
  return (Math.imul(x, 10) + picked) | 0;
}

function main() {
  console.log(`${pick(false)} ${pick(true)}`);
  console.log(`${both(false)} ${both(true)}`);
  console.log(`${guard(undefined)} ${guard(1)} ${guard(2)}`);
  console.log(`${nested(false, true)} ${nested(true, false)} ${nested(true, true)}`);
  let x = 0;
  const x$1 = { value: x };
  const result = bump(x$1);
  x = x$1.value;
  let tmp;
  if (result === 1) {
    const x$1 = { value: x };
    const result = bump(x$1);
    x = x$1.value;
    tmp = result;
  } else {
    const x$1 = { value: x };
    const result = bump(x$1);
    x = x$1.value;
    tmp = (result + 10) | 0;
  }
  const picked = tmp;
  console.log(`${x} ${picked}`);
  let total = 0;
  for (let i = 0; i < 4; i++) {
    let tmp;
    if (i % 2 === 0) {
      const x = { value: total };
      const result = bump(x);
      total = x.value;
      tmp = result;
    } else {
      tmp = 7;
    }
    const picked = tmp;
    console.log(`${total} ${picked}`);
  }
}
//# sourceMappingURL=case.js.map
