// Generated by rust-js from test/corpus/conditional_move_drops.rs. Do not edit.

export function entry() {
  main();
}

function noisyDrop_drop(noisy) {
  console.log(`drop ${noisy[0]}`);
}

function take(n) {
  try {
    console.log(`took ${n[0]}`);
  } finally {
    noisyDrop_drop(n);
  }
}

function main() {
  for (let i = 0; i < 2; i++) {
    const give = i === 0;
    const n = [give ? "given" : "kept"];
    let n$live = true;
    try {
      if (give) {
        n$live = false;
        take(n);
      }
      console.log(`end of ${give}`);
    } finally {
      if (n$live) {
        noisyDrop_drop(n);
      }
    }
  }
}
//# sourceMappingURL=case.js.map
