// Generated by rust-js from test/corpus/const_generic_traits.rs. Do not edit.

import { $traitImpl } from "@rust-js/runtime";

var $sevenRepeat, $metersScaled10, $metersScaled100, $anyScaled, $dotsPad;

export function entry() {
  main();
}

function sevenRepeat() {
  if ($sevenRepeat === undefined) {
    $sevenRepeat = { repeat: sevenRepeat_repeat, twice: (self) => sevenRepeat_repeat(self, 2) };
  }
  return $sevenRepeat;
}

function sevenRepeat_repeat(seven, N) {
  return new Array(N).fill(7);
}

function three(r, RRepeat) {
  return RRepeat.repeat(r, 3);
}

function metersScaled10() {
  if ($metersScaled10 === undefined) {
    $metersScaled10 = { scaled: metersScaled10_scaled, factor: (self) => 10 };
  }
  return $metersScaled10;
}

function metersScaled10_scaled(meters) {
  return Math.imul(meters[0], 10) >>> 0;
}

function metersScaled100() {
  if ($metersScaled100 === undefined) {
    $metersScaled100 = { scaled: metersScaled100_scaled, factor: (self) => 100 };
  }
  return $metersScaled100;
}

function metersScaled100_scaled(meters) {
  return Math.imul(meters[0], 100) >>> 0;
}

function anyScaled(K) {
  if ($anyScaled === undefined) {
    $anyScaled = new Map();
  }
  return $traitImpl($anyScaled, [K], () => ({
    scaled: (arg0) => anyScaled_scaled(arg0, K),
    factor: (self) => K,
  }));
}

function anyScaled_scaled(any, K) {
  return Math.imul(any[0], K) >>> 0;
}

function dotsPad() {
  if ($dotsPad === undefined) {
    $dotsPad = { pad: dotsPad_pad };
  }
  return $dotsPad;
}

function dotsPad_pad(dots, value, N, TDisplay) {
  return ".".repeat(N) + TDisplay.fmt(value);
}

function padded(p, PPad) {
  return PPad.pad(p, 42, 3, { fmt: String });
}

function by_ten(s, SScaled) {
  return (SScaled.scaled(s) + SScaled.factor(s)) >>> 0;
}

function by(s, K, SScaled) {
  return [SScaled.scaled(s), SScaled.factor(s)];
}

function main() {
  console.log(
    `[${sevenRepeat_repeat(undefined, 4)
      .map((item) => String(item))
      .join(", ")}] [${sevenRepeat()
      .twice(undefined)
      .map((item) => String(item))
      .join(", ")}] [${three(undefined, sevenRepeat())
      .map((item) => String(item))
      .join(", ")}]`,
  );
  const m = [3];
  console.log(
    `${metersScaled10_scaled(m)} ${metersScaled100_scaled(m)} ${metersScaled100().factor(m)} ${by_ten(m, metersScaled10())}`,
  );
  const arg = by(m, 100, metersScaled100());
  const arg$1 = by([2], 5, anyScaled(5));
  const arg$2 = by([3], 7, anyScaled(7));
  console.log(`(${arg[0]}, ${arg[1]}) (${arg$1[0]}, ${arg$1[1]}) (${arg$2[0]}, ${arg$2[1]})`);
  console.log(
    `${padded(undefined, dotsPad())} ${dotsPad_pad(undefined, "x", 1, { fmt: (value) => value })}`,
  );
}
//# sourceMappingURL=case.js.map
