// Generated by rust-js from test/corpus/const_block_values.rs. Do not edit.

import { $byteLen } from "@rust-js/runtime";

export function entry() {
  main();
}

const mainConst = "";
const mainConst$1 = "";
const mainConst$2 = undefined;

function main() {
  let s = mainConst;
  s += "a";
  const arg = $byteLen(mainConst$1);
  console.log(`${s} ${arg}`);
  let slot = mainConst$2;
  slot = [1, 2];
  console.log(`(${slot[0]}, ${slot[1]})`);
}
//# sourceMappingURL=case.js.map
