// Generated by rust-js from test/corpus/copy_from_slice_panic.rs. Do not edit.

import { $copyFromSlice } from "@rust-js/runtime";

export function entry() {
  main();
}

function main() {
  const target = [0, 0, 0];
  $copyFromSlice(target, [1, 2]);
  console.log(`[${target.map((item) => String(item)).join(", ")}]`);
}
//# sourceMappingURL=case.js.map
