// Generated by rust-js from test/corpus/cows.rs. Do not edit.

import { $at, $cowMut, $debugStr } from "@rust-js/runtime";

export function entry() {
  main();
}

function shout(text) {
  if (text.endsWith("!")) {
    return { TAG: "Borrowed", _0: text };
  }
  return { TAG: "Owned", _0: `${text}!` };
}

function main() {
  const hi = shout("hi");
  const hey = shout("hey!");
  console.log(`${hi._0} ${hey._0} ${$debugStr(hey._0)} ${hey.TAG === "Borrowed"}`);
  const owned = { ...hey }._0;
  console.log(`${owned} ${hi._0}`);
  const text = shout("wow!");
  const cell = $cowMut(text);
  cell.value += "!!";
  console.log(`${text._0} ${text.TAG === "Owned"}`);
  const items = [1, 2, 3];
  const list = { TAG: "Borrowed", _0: items };
  console.log(`[${list._0.map((item) => String(item)).join(", ")}]`);
  if (list.TAG === "Borrowed") {
    list.TAG = "Owned";
    list._0 = list._0.slice();
  }
  list._0.push(4);
  if (list.TAG === "Borrowed") {
    list.TAG = "Owned";
    list._0 = list._0.slice();
  }
  list._0[$at(list._0, 0)] = 0;
  console.log(
    `[${list._0.map((item) => String(item)).join(", ")}] [${items.map((item) => String(item)).join(", ")}] ${list._0.length}`,
  );
  const vec = list.TAG === "Borrowed" ? list._0.slice() : list._0;
  console.log(`[${vec.map((item) => String(item)).join(", ")}]`);
  const borrowed = { TAG: "Borrowed", _0: items };
  const copy = borrowed.TAG === "Borrowed" ? borrowed._0.slice() : borrowed._0;
  copy.push(9);
  const arg = { TAG: "Owned", _0: copy.slice() };
  console.log(
    `[${copy.map((item) => String(item)).join(", ")}] [${items.map((item) => String(item)).join(", ")}] [${arg._0.map((item) => String(item)).join(", ")}]`,
  );
  const path = { TAG: "Borrowed", _0: "a/b" };
  const buf = path._0;
  console.log(`${path._0} ${$debugStr(path._0)} ${buf}`);
}
//# sourceMappingURL=case.js.map
