// Generated by rust-js from test/corpus/deque_range_mut_panic.rs. Do not edit.

import { $mutItems, $view } from "@rust-js/runtime";

export function entry() {
  main();
}

function main() {
  const d = [1, 2, 3];
  for (const x of $mutItems($view(d, 1, 9))) {
    x.value = (x.value + 1) | 0;
  }
}
//# sourceMappingURL=case.js.map
