// Generated by rust-js from test/corpus/destructuring_assignment.rs. Do not edit.

function fibonacci(n) {
  let [a, b] = [0n, 1n];
  for (let i = 0; i < n; i++) {
    const [lhs, lhs$1] = [b, BigInt.asUintN(64, a + b)];
    a = lhs;
    b = lhs$1;
  }
  return a;
}

function main() {
  let a;
  let b;
  const [lhs, lhs$1] = [1, 2];
  a = lhs;
  b = lhs$1;
  let c;
  let d;
  let e;
  const tmp = [3, [4, 5]];
  c = tmp[0];
  d = tmp[1][0];
  e = tmp[1][1];
  c = (c + 1) | 0;
  e = Math.imul(e, 2);
  let x;
  let y;
  const { x: lhs$2, y: lhs$3 } = { x: 7, y: 8 };
  x = lhs$2;
  y = lhs$3;
  console.log(`${a} ${b} ${c} ${d} ${e} ${x} ${y}`);
  const slots = [0, 0, 0, 0];
  const tmp$1 = [9, 10, 11, 12];
  slots[0] = tmp$1[0];
  slots[3] = tmp$1[3];
  let first;
  let last;
  const tmp$2 = [1, 2, 3, 4];
  first = tmp$2[0];
  last = tmp$2[3];
  console.log(
    `[${slots.map((item) => String(item)).join(", ")}] ${first} ${last} ${fibonacci(10)}`,
  );
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
