// Generated by rust-js from test/corpus/drop_impl_indirect.rs. Do not edit.

import { $traitImpl } from "@rust-js/runtime";

var $wrapPeek, $wrapPass, $rcValue, $wrapTake, $pairTake, $loudTake;

function helper(u, UClone, dropU) {
  const _copy = UClone.clone(u);
  dropU?.(_copy);
}

function peeked(p, PPeek, dropP) {
  return PPeek.peek(p);
}

function helper_taking(_u, dropU) {
  dropU?.(_u);
}

function valued(v, VValue) {
  return VValue.value(v);
}

function take(value, TTake, dropT) {
  TTake.take(value);
}

function main() {
  const lent = [["lent"]];
  try {
    console.log(
      `${peeked(lent, wrapPeek({ clone: (value) => value }, loudDrop_drop), (wrap) => {
        loudDrop_drop(wrap[0]);
      })}`,
    );
    take([["taken by a default"]], wrapTake(loudDrop_drop), (wrap$1) => {
      loudDrop_drop(wrap$1[0]);
    });
    take(
      [["first of a pair"], ["second of a pair"]],
      pairTake(loudDrop_drop, loudDrop_drop),
      (pair) => {
        loudDrop_drop(pair[0]);
        loudDrop_drop(pair[1]);
      },
    );
    take(["taken itself"], loudTake(), loudDrop_drop);
    wrapPass(loudDrop_drop).pass([["passed to a helper"]]);
    console.log(`${valued(1, rcValue())}`);
    console.log("end");
  } finally {
    loudDrop_drop(lent[0]);
  }
}

export function entry() {
  main();
}

function wrapPeek_peek(wrap, TClone, dropT) {
  helper(wrap[0], TClone, dropT);
  return 1;
}

function loudDrop_drop(loud) {
  console.log(`drop ${loud[0]}`);
}

function wrapPeek(TClone, dropT) {
  if ($wrapPeek === undefined) {
    $wrapPeek = new WeakMap();
  }
  return $traitImpl($wrapPeek, [TClone, dropT], () => ({
    peek: (arg0) => wrapPeek_peek(arg0, TClone, dropT),
    $drop: (wrap) => {
      dropT?.(wrap[0]);
    },
  }));
}

function wrapPass(dropT) {
  if ($wrapPass === undefined) {
    $wrapPass = new WeakMap();
  }
  return $traitImpl($wrapPass, [dropT], () => ({
    pass: (self) => {
      const dropSelf = (wrap) => {
        dropT?.(wrap[0]);
      };
      helper_taking(self, dropSelf);
    },
    $drop: (wrap$1) => {
      dropT?.(wrap$1[0]);
    },
  }));
}

function rcValue(dropT) {
  if ($rcValue === undefined) {
    $rcValue = new WeakMap();
  }
  return $traitImpl($rcValue, [dropT], () => ({ value: (self) => 7 }));
}

function wrapTake(dropT) {
  if ($wrapTake === undefined) {
    $wrapTake = new WeakMap();
  }
  return $traitImpl($wrapTake, [dropT], () => ({
    take: (self) => {
      const dropSelf = (wrap) => {
        dropT?.(wrap[0]);
      };
      dropSelf?.(self);
    },
    $drop: (wrap$1) => {
      dropT?.(wrap$1[0]);
    },
  }));
}

function pairTake(dropA, dropB) {
  if ($pairTake === undefined) {
    $pairTake = new WeakMap();
  }
  return $traitImpl($pairTake, [dropA, dropB], () => ({
    take: (self) => {
      const dropSelf = (pair) => {
        dropA?.(pair[0]);
        dropB?.(pair[1]);
      };
      dropSelf?.(self);
    },
    $drop: (pair$1) => {
      dropA?.(pair$1[0]);
      dropB?.(pair$1[1]);
    },
  }));
}

function loudTake() {
  if ($loudTake === undefined) {
    $loudTake = {
      take: (self) => {
        loudDrop_drop?.(self);
      },
      $drop: loudDrop_drop,
    };
  }
  return $loudTake;
}
//# sourceMappingURL=case.js.map
