// Generated by rust-js from test/corpus/drop_functions.rs. Do not edit.

export function entry() {
  main();
}

function noisyDrop_drop(noisy) {
  console.log(`drop ${noisy[0]}`);
}

function many(base) {
  return {
    a: [base],
    b: [(base + 1) >>> 0],
    c: [(base + 2) >>> 0],
    d: [(base + 3) >>> 0],
    e: [(base + 4) >>> 0],
    f: [(base + 5) >>> 0],
    g: [(base + 6) >>> 0],
    h: [(base + 7) >>> 0],
    i: [(base + 8) >>> 0],
  };
}

function list(n) {
  const dropList = (list$1) => {
    if (list$1.TAG === "Cons") {
      noisyDrop_drop(list$1._0);
      dropList(list$1._1);
    }
  };
  let at = "Nil";
  let at$live = true;
  try {
    for (let i = 0; i < n; i++) {
      const tmp = [(100 + i) >>> 0];
      at$live = false;
      if (at$live) {
        dropList(at);
      }
      at = { TAG: "Cons", _0: tmp, _1: at };
      at$live = true;
    }
    at$live = false;
    return at;
  } finally {
    if (at$live) {
      dropList(at);
    }
  }
}

function main() {
  const dropMany = (many$1) => {
    noisyDrop_drop(many$1.a);
    noisyDrop_drop(many$1.b);
    noisyDrop_drop(many$1.c);
    noisyDrop_drop(many$1.d);
    noisyDrop_drop(many$1.e);
    noisyDrop_drop(many$1.f);
    noisyDrop_drop(many$1.g);
    noisyDrop_drop(many$1.h);
    noisyDrop_drop(many$1.i);
  };
  const dropTwo = (two) => {
    if (two[0] != null) {
      dropMany(two[0]);
    }
    if (two[1] != null) {
      dropMany(two[1]);
    }
  };
  const dropList = (list$1) => {
    if (list$1.TAG === "Cons") {
      noisyDrop_drop(list$1._0);
      dropList(list$1._1);
    }
  };
  const _two = [undefined, many(10)];
  try {
    console.log("two made");
  } finally {
    dropTwo(_two);
  }
  const _first = [many(20), undefined];
  dropTwo(_first);
  const _list = list(3);
  try {
    console.log("end");
  } finally {
    dropList(_list);
  }
}
//# sourceMappingURL=case.js.map
