// Generated by rust-js from test/corpus/drop_generic.rs. Do not edit.

import { $index } from "@rust-js/runtime";

var $noisyDisplay;

const Wrapper = {
  replace(wrapper, value, dropT) {
    dropT?.(wrapper.inner);
    wrapper.inner = value;
    console.log("replaced");
  },
};

function consume(value, dropT) {
  try {
    console.log("consume");
  } finally {
    dropT?.(value);
  }
}

function keep(value) {
  return value;
}

function first(items, TClone, dropT) {
  try {
    return TClone.clone($index(items, 0));
  } finally {
    for (const item of items) {
      dropT?.(item);
    }
  }
}

function relay(value, dropU) {
  consume(value, dropU);
  console.log("relayed");
}

function shown(x, Display, dropDisplay) {
  try {
    return `<${Display.fmt(x)}>`;
  } finally {
    dropDisplay?.(x);
  }
}

function main() {
  consume(["a"], noisyDrop_drop);
  consume(5);
  const kept = keep(["b"]);
  try {
    const copy = first([["c"], ["d"]], { clone: (value) => value }, noisyDrop_drop);
    try {
      relay(["e"], noisyDrop_drop);
      relay("text");
      consume({ a: ["p"], b: 1 }, (pair) => {
        noisyDrop_drop(pair.a);
      });
      const wrapper = { inner: ["w1"] };
      try {
        Wrapper.replace(wrapper, ["w2"], noisyDrop_drop);
        console.log(`${shown(["s"], noisyDisplay(), noisyDrop_drop)} ${shown(7, { fmt: String })}`);
        console.log(`${kept[0]} ${copy[0]} ${wrapper.inner[0]} end`);
      } finally {
        noisyDrop_drop(wrapper.inner);
      }
    } finally {
      noisyDrop_drop(copy);
    }
  } finally {
    noisyDrop_drop(kept);
  }
}

export function entry() {
  main();
}

function noisyDrop_drop(noisy) {
  console.log(`drop ${noisy[0]}`);
}

function noisyDisplay_fmt(noisy) {
  return noisy[0];
}

export function noisyDisplay() {
  if ($noisyDisplay === undefined) {
    $noisyDisplay = { fmt: noisyDisplay_fmt, $drop: noisyDrop_drop };
  }
  return $noisyDisplay;
}
//# sourceMappingURL=case.js.map
