// Generated by rust-js from test/corpus/drop_params.rs. Do not edit.

export function entry() {
  main();
}

function noisyDrop_drop(noisy) {
  console.log(`drop ${noisy[0]}`);
}

function by_value(n) {
  try {
    console.log(`by value ${n[0]}`);
  } finally {
    noisyDrop_drop(n);
  }
}

function by_ref(n) {
  try {
    console.log(`by ref ${n[0]}`);
  } finally {
    noisyDrop_drop(n);
  }
}

function ignored(_) {
  try {
    console.log("ignored");
  } finally {
    noisyDrop_drop(_);
  }
}

function both(a, _, b) {
  try {
    console.log(`both ${a[0]} ${b[0]}`);
  } finally {
    noisyDrop_drop(b);
    noisyDrop_drop(_);
    noisyDrop_drop(a);
  }
}

function main() {
  by_value(["a"]);
  by_ref(["b"]);
  ignored(["c"]);
  both(["d"], ["e"], ["f"]);
  const kept = ["g"];
  const same = ["h"];
  const borrowed = same;
  const keptToo = ["i"];
  try {
    console.log(`${kept[0]} ${borrowed[0]}`);
    console.log("end");
  } finally {
    noisyDrop_drop(keptToo);
    noisyDrop_drop(same);
    noisyDrop_drop(kept);
  }
}
//# sourceMappingURL=case.js.map
