// Generated by rust-js from test/corpus/drop_scopes.rs. Do not edit.

import { $position } from "@rust-js/runtime";

export function entry() {
  main();
}

function noisyDrop_drop(noisy) {
  console.log(`drop ${noisy[0]}`);
}

function pairDrop_drop(pair) {
  console.log(`drop pair of ${pair.first[0]} and ${pair.second[0]}`);
}

function unitDrop_drop(self) {
  console.log("drop unit");
}

function consume(n) {
  try {
    console.log(`consume ${n[0]}`);
  } finally {
    noisyDrop_drop(n);
  }
}

function early(stop) {
  const _a = ["early a"];
  try {
    if (stop) {
      return 1;
    }
    const _b = ["early b"];
    try {
      return 2;
    } finally {
      noisyDrop_drop(_b);
    }
  } finally {
    noisyDrop_drop(_a);
  }
}

function find(items, wanted) {
  const _guard = ["find guard"];
  try {
    const at = $position(items, (x) => x === wanted);
    if (at == null) {
      return;
    }
    return (at + 1) >>> 0;
  } finally {
    noisyDrop_drop(_guard);
  }
}

function made(name) {
  const n = [name];
  let n$live = true;
  try {
    console.log(`made ${n[0]}`);
    n$live = false;
    return n;
  } finally {
    if (n$live) {
      noisyDrop_drop(n);
    }
  }
}

function main() {
  const _x = ["x"];
  const _y = ["y"];
  try {
    const _z = ["z"];
    noisyDrop_drop(_z);
    console.log("inner done");
  } finally {
    noisyDrop_drop(_y);
    noisyDrop_drop(_x);
  }
  const moved = ["moved"];
  consume(moved);
  const maybe = ["maybe"];
  let maybe$live = true;
  try {
    if (early(true) === 1) {
      maybe$live = false;
      consume(maybe);
    }
    const arg = early(false);
    const arg$1 = find([4, 5], 5);
    const arg$2 = find([4], 5);
    console.log(
      `${arg} ${arg$1 == null ? "None" : `Some(${arg$1})`} ${arg$2 == null ? "None" : `Some(${arg$2})`}`,
    );
    const kept = made("kept");
    let kept$live = true;
    let slot = ["old"];
    try {
      noisyDrop_drop(slot);
      slot = ["new"];
      console.log(`slot is ${slot[0]}`);
      kept$live = false;
      noisyDrop_drop(kept);
      noisyDrop_drop(["statement"]);
      noisyDrop_drop(["ignored"]);
      const unit = undefined;
      unitDrop_drop({ value: unit });
      for (let i = 0; i < 3; i++) {
        const _each = [i === 1 ? "one" : "other"];
        try {
          if (i === 1) {
            break;
          }
        } finally {
          noisyDrop_drop(_each);
        }
      }
      const _pair = { first: ["first"], second: ["second"] };
      try {
        const _holder = { label: "h", inner: ["held"], count: 2 };
        try {
          const _list = [["v0"], ["v1"]];
          const _some = ["some"];
          const _none = undefined;
          const _boxed = ["boxed"];
          const _tuple = [["t0"], 7, ["t1"]];
          const _shapes = [
            "Empty",
            { TAG: "One", _0: ["one"] },
            { TAG: "Two", a: ["a"], b: ["b"] },
          ];
          try {
            console.log("end of main");
          } finally {
            for (const item of _shapes) {
              if (item.TAG === "One") {
                noisyDrop_drop(item._0);
              }
              if (item.TAG === "Two") {
                noisyDrop_drop(item.a);
                noisyDrop_drop(item.b);
              }
            }
            noisyDrop_drop(_tuple[0]);
            noisyDrop_drop(_tuple[2]);
            noisyDrop_drop(_boxed);
            if (_none != null) {
              noisyDrop_drop(_none);
            }
            if (_some != null) {
              noisyDrop_drop(_some);
            }
            for (const item of _list) {
              noisyDrop_drop(item);
            }
          }
        } finally {
          noisyDrop_drop(_holder.inner);
        }
      } finally {
        pairDrop_drop(_pair);
        noisyDrop_drop(_pair.first);
        noisyDrop_drop(_pair.second);
      }
    } finally {
      noisyDrop_drop(slot);
      if (kept$live) {
        noisyDrop_drop(kept);
      }
    }
  } finally {
    if (maybe$live) {
      noisyDrop_drop(maybe);
    }
  }
}
//# sourceMappingURL=case.js.map
