// Generated by rust-js from test/corpus/drop_operand_panic.rs. Do not edit.

export function entry() {
  main();
}

function noisyDrop_drop(noisy) {
  console.log(`drop ${noisy[0]}`);
}

function pair(a, b) {
  try {
    console.log(`pair ${a[0]} ${b}`);
    return b;
  } finally {
    noisyDrop_drop(a);
  }
}

function second(fail) {
  if (fail) {
    throw new Error("no second");
  }
  return 2;
}

function main() {
  const first = ["first"];
  let first$live = true;
  try {
    const arg = second(false);
    first$live = false;
    console.log(`${pair(first, arg)}`);
    const again = ["again"];
    let again$live = true;
    try {
      const arg = second(true);
      again$live = false;
      console.log(`${pair(again, arg)}`);
    } finally {
      if (again$live) {
        noisyDrop_drop(again);
      }
    }
  } finally {
    if (first$live) {
      noisyDrop_drop(first);
    }
  }
}
//# sourceMappingURL=case.js.map
