// Generated by rust-js from test/corpus/drop_impl_param_call.rs. Do not edit.

import { $traitImpl } from "@rust-js/runtime";

var $wrapPeek;

function discard(_u, dropU) {
  dropU?.(_u);
}

function peeked(p, PPeek) {
  return PPeek.peek(p);
}

function main() {
  const w = [undefined];
  let w$live = true;
  try {
    console.log(
      `${peeked(
        w,
        wrapPeek({ clone: (value) => value }, (loud) => {
          loudDrop_drop({ value: loud });
        }),
      )}`,
    );
    w$live = false;
    console.log(`${peeked(["text"], wrapPeek({ clone: (value) => value }))}`);
  } finally {
    if (w$live) {
      loudDrop_drop({ value: w[0] });
    }
  }
}

export function entry() {
  main();
}

function wrapPeek_peek(wrap, TClone, dropT) {
  const value = TClone.clone(wrap[0]);
  dropT?.(value);
  discard(TClone.clone(wrap[0]), dropT);
  return 1;
}

function loudDrop_drop(self) {
  console.log("dropped");
}

function wrapPeek(TClone, dropT) {
  if ($wrapPeek === undefined) {
    $wrapPeek = new WeakMap();
  }
  return $traitImpl($wrapPeek, [TClone, dropT], () => ({
    peek: (arg0) => wrapPeek_peek(arg0, TClone, dropT),
    $drop: (wrap) => {
      dropT?.(wrap[0]);
    },
  }));
}
//# sourceMappingURL=case.js.map
