// Generated by rust-js from test/corpus/duration_overflow.rs. Do not edit.

import { $debugDuration, $durationNew } from "@rust-js/runtime";

function main() {
  console.log(`${$debugDuration($durationNew(18446744073709551615n, 999999999))}`);
  const d = $durationNew(18446744073709551615n, 1000000000);
  console.log(`${$debugDuration(d)}`);
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
