// Generated by rust-js from test/corpus/duration.rs. Do not edit.

import {
  $bigMax,
  $cmp,
  $debugDuration,
  $durationAdd,
  $durationChecked,
  $durationNew,
  $durationSub,
} from "@rust-js/runtime";

function main() {
  const d = $durationNew(5n, 1500000000);
  console.log(
    `${d / 1000000000n} ${Number(d % 1000000000n)} ${Number((d % 1000000000n) / 1000000n)} ${Number((d % 1000000000n) / 1000n)}`,
  );
  console.log(`${d / 1000000n} ${d / 1000n} ${d}`);
  const made = [
    90n * 1000000000n,
    1250n * 1000000n,
    3n * 1000n,
    1000000007n,
    0n,
    $durationNew(0n, 1),
  ];
  for (const m of made) {
    console.log(`${$debugDuration(m)} ${m === 0n} ${m / 1000000000n}`);
  }
  console.log(
    `${18446744073709551615999999999n / 1000000000n} ${Number(18446744073709551615999999999n % 1000000000n)}`,
  );
  const a = 1500n * 1000000n;
  const b = 700n * 1000000n;
  const tmp = $durationAdd(a, b);
  const tmp$1 = $durationSub(a, b);
  const b$1 = 2n * 1000000000n;
  const arg = a < b$1 ? undefined : a - b$1;
  console.log(
    `${$debugDuration(tmp)} ${$debugDuration(tmp$1)} ${arg == null ? "None" : `Some(${$debugDuration(arg)})`}`,
  );
  const arg$1 = $durationChecked(18446744073709551615999999999n + $durationNew(0n, 1));
  const arg$2 = $durationChecked(a + b);
  console.log(
    `${arg$1 == null ? "None" : `Some(${$debugDuration(arg$1)})`} ${arg$2 == null ? "None" : `Some(${$debugDuration(arg$2)})`}`,
  );
  console.log(
    `${a > b} ${a === $durationNew(1n, 500000000)} ${$bigMax(a, b) === a} ${
      ["Less", "Equal", "Greater"][$cmp(a, b) + 1]
    }`,
  );
  const v = [a, b, 0n, 1n * 1000000000n];
  v.sort($cmp);
  console.log(`[${v.map((item) => $debugDuration(item)).join(", ")}]`);
  const set = new Set([a, b, 1500000n * 1000n]);
  console.log(`${set.size}`);
  console.log(
    `${$debugDuration(1n * 1000000000n)} ${$debugDuration(10n * 1000000n)} ${$debugDuration($durationNew(3n, 40))}`,
  );
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
