// Generated by rust-js from test/corpus/dyn_any.rs. Do not edit.

import { $debugStr } from "@rust-js/runtime";

var $pointComponent;

export function entry() {
  main();
}

function pointDebug_fmt(point) {
  return `Point { x: ${point.x} }`;
}

function pointComponent() {
  if ($pointComponent === undefined) {
    $pointComponent = { Any: () => ({ type_id: () => "lib::Point" }), name: pointComponent_name };
  }
  return $pointComponent;
}

function pointComponent_name(point) {
  return "point";
}

function describe(value) {
  const n = value.impl.type_id() === "i32" ? value.value : undefined;
  if (n != null) {
    return `i32 ${n}`;
  }
  const s = value.impl.type_id() === "alloc::string::String" ? value.value : undefined;
  if (s != null) {
    return `string ${s}`;
  }
  if (value.impl.type_id() === "lib::Point") {
    const arg = value.impl.type_id() === "lib::Point" ? value.value : undefined;
    return `point ${arg == null ? "None" : `Some(${pointDebug_fmt(arg)})`}`;
  }
  return "other";
}

function key(_, TAny) {
  return TAny.type_id();
}

function boxed(value, TAny) {
  return { value, impl: TAny };
}

function main() {
  const items = [
    { value: 5, impl: { type_id: () => "i32" } },
    { value: "s", impl: { type_id: () => "alloc::string::String" } },
    { value: { x: 1 }, impl: { type_id: () => "lib::Point" } },
    { value: 1.5, impl: { type_id: () => "f64" } },
  ];
  for (const item of items) {
    console.log(`${describe(item)}`);
  }
  const number = { value: 7, impl: { type_id: () => "u8" } };
  const n = number.impl.type_id() === "u8" ? number : undefined;
  if (n != null) {
    n.value = (n.value + 1) & 255;
  }
  const arg = number.impl.type_id() === "u8" ? number.value : undefined;
  const arg$1 = number.impl.type_id() === "i8" ? number.value : undefined;
  console.log(
    `${arg == null ? "None" : `Some(${arg})`} ${arg$1 == null ? "None" : `Some(${arg$1})`}`,
  );
  const match =
    number.impl.type_id() === "u8" ? { TAG: "Ok", _0: number.value } : { TAG: "Err", _0: number };
  if (match.TAG === "Ok") {
    console.log(`u8 ${match._0}`);
  } else {
    console.log("not u8");
  }
  const text = boxed("t", { type_id: () => "alloc::string::String" });
  const match$1 =
    text.impl.type_id() === "i32" ? { TAG: "Ok", _0: text.value } : { TAG: "Err", _0: text };
  if (match$1.TAG === "Ok") {
    console.log(`i32 ${match$1._0}`);
  } else {
    const arg =
      match$1._0.impl.type_id() === "alloc::string::String" ? match$1._0.value : undefined;
    console.log(`back ${arg == null ? "None" : `Some(${$debugStr(arg)})`}`);
  }
  console.log(
    `${"i32" === key(3, { type_id: () => "i32" })} ${key(3, { type_id: () => "u8" }) === "i32"}`,
  );
  const seen = new Map();
  seen.set("lib::Point", "point");
  seen.set("i64", "i64");
  const arg$2 = seen.get("i64");
  console.log(`${arg$2 == null ? "None" : `Some(${$debugStr(arg$2)})`} ${seen.size}`);
  console.log(
    `${"lib::Point".endsWith("::Point")} alloc::vec::Vec<core::option::Option<&str>> f64`,
  );
  const component = { value: { x: 2 }, impl: pointComponent() };
  const any = { value: component.value, impl: component.impl.Any() };
  const arg$3 = component.impl.name(component.value);
  const arg$4 = any.impl.type_id() === "lib::Point" ? any.value : undefined;
  console.log(`${arg$3} ${arg$4 == null ? "None" : `Some(${pointDebug_fmt(arg$4)})`} Any { .. }`);
  console.log(`${component.impl.Any().type_id() === "lib::Point"}`);
}
//# sourceMappingURL=case.js.map
