// Generated by rust-js from test/corpus/dyn_mut.rs. Do not edit.

import { $index } from "@rust-js/runtime";

var $cCounter, $i32Counter, $i32Sub;

export function entry() {
  main();
}

function cDebug_fmt(c) {
  return `C { n: ${c.n} }`;
}

function cCounter() {
  if ($cCounter === undefined) {
    $cCounter = {
      bump: (arg0) => cCounter_bump(arg0.value),
      get: cCounter_get,
      twice: (self) => {
        cCounter_bump(self.value);
        cCounter_bump(self.value);
      },
    };
  }
  return $cCounter;
}

function cCounter_bump(c) {
  c.n = (c.n + 1) | 0;
}

function cCounter_get(c) {
  return c.n;
}

function i32Counter() {
  if ($i32Counter === undefined) {
    $i32Counter = {
      bump: i32Counter_bump,
      get: i32Counter_get,
      twice: (self) => {
        i32Counter_bump(self);
        i32Counter_bump(self);
      },
    };
  }
  return $i32Counter;
}

function i32Counter_bump(self) {
  self.value = (self.value + 10) | 0;
}

function i32Counter_get(self) {
  return self;
}

function i32Sub() {
  if ($i32Sub === undefined) {
    $i32Sub = { Counter: () => i32Counter(), name: i32Sub_name };
  }
  return $i32Sub;
}

function i32Sub_name(self) {
  return `i${self}`;
}

function up(s) {
  return {
    impl: s.impl.Counter(),
    get value() {
      return s.value;
    },
    set value(value) {
      s.value = value;
    },
  };
}

function use_it(c) {
  c.impl.bump(c);
  c.impl.twice(c);
  return c.impl.get(c.value);
}

function main() {
  const c = { n: 1 };
  let n = 5;
  console.log(
    `${use_it({ value: c, impl: cCounter() })} ${use_it({
      impl: i32Counter(),
      get value() {
        return n;
      },
      set value(value) {
        n = value;
      },
    })}`,
  );
  console.log(`${cDebug_fmt(c)} ${n}`);
  const d = {
    impl: i32Counter(),
    get value() {
      return n;
    },
    set value(value) {
      n = value;
    },
  };
  d.impl.bump(d);
  const shared = d;
  console.log(`${shared.impl.get(shared.value)} ${n}`);
  const s = {
    impl: i32Sub(),
    get value() {
      return n;
    },
    set value(value) {
      n = value;
    },
  };
  const receiver = up(s);
  receiver.impl.bump(receiver);
  console.log(`${s.impl.name(s.value)} ${n}`);
  const boxed = { value: 7, impl: i32Counter() };
  boxed.impl.bump(boxed);
  const list = [
    { value: { n: 0 }, impl: cCounter() },
    { value: 1, impl: i32Counter() },
  ];
  for (let i = 0; i < list.length; i++) {
    list[i].impl.twice(list[i]);
  }
  const tmp = boxed.impl.get(boxed.value);
  const receiver$1 = $index(list, 0);
  const tmp$1 = receiver$1.impl.get(receiver$1.value);
  const receiver$2 = $index(list, 1);
  console.log(`${tmp} ${tmp$1} ${receiver$2.impl.get(receiver$2.value)}`);
}
//# sourceMappingURL=case.js.map
