// Generated by rust-js from test/corpus/enum_discriminants_wide.rs. Do not edit.

export function entry() {
  main();
}

function big(b) {
  return { Small: 3n, Past: 9007199254740993n, Max: 18446744073709551615n }[b];
}

function signed(s) {
  return { Low: -9223372036854775808n, Odd: -9007199254740993n, Zero: 0n }[s];
}

function main() {
  for (const b of ["Small", "Past", "Max"]) {
    console.log(`${big(b)} ${Number(BigInt.asUintN(8, big(b)))}`);
  }
  for (const s of ["Low", "Odd", "Zero"]) {
    console.log(`${signed(s)} ${Number(BigInt.asIntN(32, signed(s)))}`);
  }
}
//# sourceMappingURL=case.js.map
