// Generated by rust-js from test/corpus/exp_format.rs. Do not edit.

import { $lowerExp, $plus, $zeroPad } from "@rust-js/runtime";

export function entry() {
  main();
}

function main() {
  console.log(
    `${$lowerExp(Infinity).replace("e", "E")} ${$lowerExp(NaN).replace("e", "E")} ${$lowerExp(-Infinity)} ${$lowerExp(-0).replace("e", "E")}`,
  );
  console.log(
    `${$lowerExp(0)} ${$lowerExp(1000)} ${$lowerExp(-1234n)} ${$lowerExp(18446744073709551615n)} ${$lowerExp(120).replace("e", "E")}`,
  );
  console.log(
    `${$lowerExp(Math.fround(0.1), true)} ${$lowerExp(Math.fround(1.5e-7), true)} ${$lowerExp(Math.fround(3.4028235e38), true)} ${$lowerExp(16777216, true)}`,
  );
  console.log(`${$lowerExp(1e21)} ${$lowerExp(5e-324)} ${$lowerExp(0.3)} ${$lowerExp(-0, true)}`);
  console.log(
    `[${$lowerExp(1234.5).padStart(12)}] [${$lowerExp(7).padEnd(10)}] [${$plus($lowerExp(2.5))}] [${$zeroPad($lowerExp(-1.5), 10)}]`,
  );
}
//# sourceMappingURL=case.js.map
