// Generated by rust-js from test/corpus/extract_if_past_len.rs. Do not edit.

import { $extractIf } from "@rust-js/runtime";

export function entry() {
  main();
}

function main() {
  const v = [1, 2, 3];
  const end = (v.length + 6) >>> 0;
  const taken = $extractIf(v, 0, end, () => true, true);
  console.log("made");
}
//# sourceMappingURL=case.js.map
