// Generated by rust-js from test/corpus/f32_parse.rs. Do not edit.

import { $debugF32, $debugStr, $displayF32, $parseF32 } from "@rust-js/runtime";

export function entry() {
  main();
}

function show(s) {
  const match = $parseF32(s);
  if (match.TAG === "Ok") {
    console.log(`${$debugStr(s)} -> ${$displayF32(match._0)} ${$debugF32(match._0)}`);
  } else {
    console.log(`${$debugStr(s)} -> error: ${match._0}`);
  }
}

function main() {
  for (const s of [
    "0.1",
    "1.5",
    "-2.75",
    "3.4028235e38",
    "1e-45",
    "7e-46",
    "1e-50",
    "+12",
    ".5",
    "5.",
    "1E3",
  ]) {
    show(s);
  }
  for (const s$1 of [
    "3.4028236e38",
    "1e39",
    "340282356779733661637539395458142568448",
    "340282356779733661637539395458142568447",
  ]) {
    show(s$1);
  }
  for (const s$2 of ["inf", "-Infinity", "NaN", "", "abc", "1.2.3", "1e", "0x10", " 1"]) {
    show(s$2);
  }
  for (const s$3 of [
    "1.000000059604644775390625",
    "1.000000059604644775390625000001",
    "1.000000059604644775390624999999",
    "1.000000178813934326171875",
    "1.000000178813934326171874999999",
    "1.000000178813934326171875000001",
    "7.00649232162408535461864791644958065640130970938257885878534141944895541342930300743319094181060791015625e-46",
    "7.00649232162408535461864791644958065640130970938257885878534141944895541342930300743319094181060791015626e-46",
  ]) {
    show(s$3);
  }
}
//# sourceMappingURL=case.js.map
