// Generated by rust-js from test/corpus/fmt_error_to_string.rs. Do not edit.

import { $fmtError, $fmtOrPanic, $fmtWritten } from "@rust-js/runtime";

var $hoursDisplay, $spanDisplay;

function main() {
  console.log("before");
  const s = $fmtOrPanic(
    () => spanDisplay_fmt([[1], [99]]),
    "a Display implementation returned an error unexpectedly: Error",
  );
  console.log(`${s}`);
}

export function entry() {
  main();
}

function hoursDisplay_fmt(hours) {
  let f = "";
  try {
    if (hours[0] > 23) {
      $fmtError();
      return f;
    }
    f += `${String(hours[0]).padStart(2, "0")}h`;
  } catch (error) {
    throw $fmtWritten(error, f);
  }
  return f;
}

function spanDisplay_fmt(span) {
  let f = "";
  try {
    f += hoursDisplay_fmt(span[0]);
    f += "-";
    f += hoursDisplay_fmt(span[1]);
  } catch (error) {
    throw $fmtWritten(error, f);
  }
  return f;
}

export function hoursDisplay() {
  if ($hoursDisplay === undefined) {
    $hoursDisplay = { fmt: hoursDisplay_fmt };
  }
  return $hoursDisplay;
}

export function spanDisplay() {
  if ($spanDisplay === undefined) {
    $spanDisplay = { fmt: spanDisplay_fmt };
  }
  return $spanDisplay;
}
//# sourceMappingURL=case.js.map
