// Generated by rust-js from test/corpus/fmt_error_println.rs. Do not edit.

import { $fmtError, $fmtPrintFailed, $fmtWritten, $print } from "@rust-js/runtime";

var $hoursDisplay, $spanDisplay;

export function entry() {
  main();
}

export function hoursDisplay() {
  if ($hoursDisplay === undefined) {
    $hoursDisplay = { fmt: hoursDisplay_fmt };
  }
  return $hoursDisplay;
}

function hoursDisplay_fmt(hours) {
  let f = "";
  try {
    if (hours[0] > 23) {
      $fmtError();
      return f;
    }
    f += `${String(hours[0]).padStart(2, "0")}h`;
  } catch (error) {
    throw $fmtWritten(error, f);
  }
  return f;
}

export function spanDisplay() {
  if ($spanDisplay === undefined) {
    $spanDisplay = { fmt: spanDisplay_fmt };
  }
  return $spanDisplay;
}

function spanDisplay_fmt(span) {
  let f = "";
  try {
    f += hoursDisplay_fmt(span[0]);
    f += "-";
    f += hoursDisplay_fmt(span[1]);
  } catch (error) {
    throw $fmtWritten(error, f);
  }
  return f;
}

function main() {
  console.log("before");
  let text = "";
  try {
    text += "<";
    text += spanDisplay_fmt([[1], [99]]);
    text += ">\n";
  } catch (error) {
    $fmtPrintFailed(error, text, false);
  }
  $print(text);
  console.log("after");
}
//# sourceMappingURL=case.js.map
