// Generated by rust-js from test/corpus/fmt_error_write.rs. Do not edit.

import {
  $debugStr,
  $fmtError,
  $fmtPartial,
  $fmtPrintFailed,
  $fmtTry,
  $fmtWritten,
  $print,
} from "@rust-js/runtime";

var $hoursDisplay, $spanDisplay;

function show(s, h) {
  try {
    s.value += "[";
    s.value += hoursDisplay_fmt(h);
    s.value += "]";
  } catch (error) {
    s.value += $fmtPartial(error);
    throw error;
  }
  s.value += ".";
  return;
}

function main() {
  let t = ">";
  const r = $fmtTry(() => {
    try {
      t += spanDisplay_fmt([[9], [17]]);
      t += " and ";
      t += spanDisplay_fmt([[9], [30]]);
    } catch (error) {
      t += $fmtPartial(error);
      throw error;
    }
  });
  console.log(`${r !== undefined} ${r === undefined} ${$debugStr(t)}`);
  let u = "";
  const arg = $fmtTry(() => {
    try {
      u += hoursDisplay_fmt([5]);
    } catch (error$1) {
      u += $fmtPartial(error$1);
      throw error$1;
    }
  });
  console.log(`${arg === undefined ? "Ok(())" : "Err(Error)"} ${$debugStr(u)}`);
  let v = "";
  const s = { value: v };
  const arg$1 = [7];
  const result = $fmtTry(() => show(s, arg$1));
  v = s.value;
  const tmp = result;
  const s$1 = { value: v };
  const arg$2 = [70];
  const result$1 = $fmtTry(() => show(s$1, arg$2));
  v = s$1.value;
  console.log(
    `${tmp === undefined ? "Ok(())" : "Err(Error)"} ${result$1 === undefined ? "Ok(())" : "Err(Error)"} ${$debugStr(v)}`,
  );
  let text = "";
  try {
    text += spanDisplay_fmt([[1], [2]]);
    text += "\n";
  } catch (error$2) {
    $fmtPrintFailed(error$2, text, false);
  }
  $print(text);
}

export function entry() {
  main();
}

function hoursDisplay_fmt(hours) {
  let f = "";
  try {
    if (hours[0] > 23) {
      $fmtError();
      return f;
    }
    f += `${String(hours[0]).padStart(2, "0")}h`;
  } catch (error) {
    throw $fmtWritten(error, f);
  }
  return f;
}

function spanDisplay_fmt(span) {
  let f = "";
  try {
    f += hoursDisplay_fmt(span[0]);
    f += "-";
    f += hoursDisplay_fmt(span[1]);
  } catch (error) {
    throw $fmtWritten(error, f);
  }
  return f;
}

export function hoursDisplay() {
  if ($hoursDisplay === undefined) {
    $hoursDisplay = { fmt: hoursDisplay_fmt };
  }
  return $hoursDisplay;
}

export function spanDisplay() {
  if ($spanDisplay === undefined) {
    $spanDisplay = { fmt: spanDisplay_fmt };
  }
  return $spanDisplay;
}
//# sourceMappingURL=case.js.map
