// Generated by rust-js from test/corpus/fn_item_referenced.rs. Do not edit.

export function entry() {
  main();
}

function hello() {
  console.log("hello");
}

function call(f) {
  f();
}

function main() {
  call(hello);
}
//# sourceMappingURL=case.js.map
