// Generated by rust-js from test/corpus/fn_pointer_of_borrowed_struct.rs. Do not edit.

import { $byteLen } from "@rust-js/runtime";

export function entry() {
  main();
}

function length(props) {
  return $byteLen(props.text);
}

function main() {
  const measure = length;
  console.log(`${measure({ text: "abc" })}`);
}
//# sourceMappingURL=case.js.map
