// Generated by rust-js from test/corpus/format_width_arguments.rs. Do not edit.

import { $pad, $toFixed } from "@rust-js/runtime";

export function entry() {
  main();
}

function main() {
  const w = 6;
  const p = 2;
  console.log(
    `[${$pad("ab", w, ">")}] [${$toFixed(1.23456, p)}] [${"7".padEnd(p)}] [${$pad($toFixed(3.14159, p), (w + 1) >>> 0, "^")}]`,
  );
}
//# sourceMappingURL=case.js.map
