// Generated by rust-js from test/corpus/generic_iterator_rest_lazy.rs. Do not edit.

import { $iterator, $next } from "@rust-js/runtime";

export function entry() {
  main();
}

function counterIterator_next(counter) {
  if (counter[0] === 4) {
    return;
  }
  counter[0] = (counter[0] + 1) >>> 0;
  console.log(`made ${counter[0]}`);
  return counter[0];
}

function after_first(it) {
  it = Iterator.from(it);
  $next(it);
  for (const x of Iterator.from(it)) {
    console.log(`took ${x}`);
    if (x >= 2) {
      break;
    }
  }
}

function main() {
  after_first($iterator([0], counterIterator_next));
}
//# sourceMappingURL=case.js.map
