// Generated by rust-js from test/corpus/generic_mut_map.rs. Do not edit.

import { $cmp } from "@rust-js/runtime";

var $hashMapGrow;

export function entry() {
  main();
}

function hashMapGrow() {
  if ($hashMapGrow === undefined) {
    $hashMapGrow = { grow: (arg0) => hashMapGrow_grow(arg0.value) };
  }
  return $hashMapGrow;
}

function hashMapGrow_grow(hashMap) {
  const n = hashMap.size;
  hashMap.set(n, Math.imul(n, 10) >>> 0);
}

function twice(t, TGrow) {
  TGrow.grow(t);
  TGrow.grow(t);
}

function main() {
  let m = new Map();
  m.set(7, 70);
  const t = { value: m };
  twice(t, hashMapGrow());
  m = t.value;
  const pairs = Array.from(m).map(([k, v]) => [k, v]);
  pairs.sort((a, b) => $cmp(a[0], b[0]) || $cmp(a[1], b[1]));
  console.log(`[${pairs.map((item) => `(${item[0]}, ${item[1]})`).join(", ")}]`);
}
//# sourceMappingURL=case.js.map
