// Generated by rust-js from test/corpus/generic_associated_types.rs. Do not edit.

import {
  $byteLen,
  $checked,
  $debugStr,
  $nextSome,
  $someAt,
  $someValue,
  $successors,
} from "@rust-js/runtime";

var $shelfContainer, $countsContainer, $countdownContainer, $byteFilled;

export function entry() {
  main();
}

function shelfContainer() {
  if ($shelfContainer === undefined) {
    $shelfContainer = {
      ItemDebug: () => ({ fmt: (value) => $debugStr(value) }),
      items: shelfContainer_items,
      last: (self) => {
        const items = Iterator.from(shelfContainer_items(self)).toArray();
        return $someAt(items, items.length - 1);
      },
    };
  }
  return $shelfContainer;
}

function shelfContainer_items(shelf) {
  return shelf.books;
}

function countsContainer() {
  if ($countsContainer === undefined) {
    $countsContainer = {
      ItemDebug: () => ({ fmt: (value) => String(value) }),
      items: countsContainer_items,
      last: (self) => {
        const items = Iterator.from(countsContainer_items(self)).toArray();
        return $someAt(items, items.length - 1);
      },
    };
  }
  return $countsContainer;
}

function countsContainer_items(counts) {
  return counts[0];
}

function countdownContainer() {
  if ($countdownContainer === undefined) {
    $countdownContainer = {
      ItemDebug: () => ({ fmt: (value) => String(value) }),
      items: countdownContainer_items,
      last: (self) => {
        const items = Iterator.from(countdownContainer_items(self)).toArray();
        return $someAt(items, items.length - 1);
      },
    };
  }
  return $countdownContainer;
}

function countdownContainer_items(countdown) {
  return $successors(countdown[0], (n) => $checked(n - 1, 0, 4294967295));
}

function count(c, CContainer) {
  return Iterator.from(CContainer.items(c)).toArray().length;
}

function first(c, CContainer) {
  return $nextSome(Iterator.from(CContainer.items(c)));
}

function show(c, CContainer) {
  const arg = CContainer.last(c);
  return arg == null ? "None" : `Some(${CContainer.ItemDebug().fmt($someValue(arg))})`;
}

function byteFilled() {
  if ($byteFilled === undefined) {
    $byteFilled = { filled: byteFilled_filled };
  }
  return $byteFilled;
}

function byteFilled_filled(byte, N) {
  return new Array(N).fill(byte[0]);
}

function main() {
  const shelf = { books: ["Dune", "Emma"] };
  const counts = [[3, 1, 4]];
  const arg = shelfContainer().last(shelf);
  const arg$1 = countsContainer().last(counts);
  console.log(
    `${arg == null ? "None" : `Some(${$debugStr(arg)})`} ${arg$1 == null ? "None" : `Some(${arg$1})`}`,
  );
  console.log(
    `${count(shelf, shelfContainer())} ${count(counts, countsContainer())} ${count([3], countdownContainer())}`,
  );
  const arg$2 = countdownContainer().last([2]);
  console.log(
    `${arg$2 == null ? "None" : `Some(${arg$2})`} ${show(shelf, shelfContainer())} ${show([1], countdownContainer())}`,
  );
  const arg$3 = first(shelf, shelfContainer());
  const arg$4 = first(counts, countsContainer());
  const arg$5 = first([5], countdownContainer());
  console.log(
    `${arg$3 == null ? "None" : `Some(${$debugStr(arg$3)})`} ${arg$4 == null ? "None" : `Some(${arg$4})`} ${arg$5 == null ? "None" : `Some(${arg$5})`}`,
  );
  console.log(
    `[${shelfContainer_items(shelf)
      .map((b) => $byteLen(b))
      .map((item) => String(item))
      .join(", ")}]`,
  );
  console.log(
    `[${byteFilled_filled([7], 3)
      .map((item) => String(item))
      .join(", ")}] [${byteFilled_filled([1], 0)
      .map((item) => String(item))
      .join(", ")}]`,
  );
}
//# sourceMappingURL=case.js.map
