// Generated by rust-js from test/corpus/generic_bitwise_operators.rs. Do not edit.

var $flagsBitOr;

function either(a, b, TBitOr) {
  return TBitOr.bitor(a, b);
}

function masked(value, mask, TBitAnd, TBitXor) {
  return [TBitAnd.bitand(value, mask), TBitXor.bitxor(value, mask)];
}

function shifted(value, by, TShlU32, TShrU32) {
  return [TShlU32.shl(value, by), TShrU32.shr(value, by)];
}

function shifted_far(value, by, TShlU64) {
  return TShlU64.shl(value, by);
}

function main() {
  console.log(
    `${either(5, 3, { bitor: (a, b) => a | b })} ${either(false, true, { bitor: (a, b) => !!(a | b) })} ${flagsDebug_fmt(either([1], [4], flagsBitOr()))}`,
  );
  const arg = masked(
    61680,
    65280,
    { bitand: (a, b) => (a & b) >>> 0 },
    { bitxor: (a, b) => (a ^ b) >>> 0 },
  );
  const arg$1 = masked(
    264913582817280n,
    281470681743360n,
    { bitand: (a, b) => a & b },
    { bitxor: (a, b) => a ^ b },
  );
  console.log(`(${arg[0]}, ${arg[1]}) (${arg$1[0]}, ${arg$1[1]})`);
  const arg$2 = masked(-6, 3, { bitand: (a, b) => a & b }, { bitxor: (a, b) => a ^ b });
  const arg$3 = masked(true, false, { bitand: (a, b) => !!(a & b) }, { bitxor: (a, b) => a !== b });
  console.log(`(${arg$2[0]}, ${arg$2[1]}) (${arg$3[0]}, ${arg$3[1]})`);
  const arg$4 = shifted(
    193,
    2,
    { shl: (a, b) => (a << (b & 7)) & 255 },
    { shr: (a, b) => a >>> (b & 7) },
  );
  const arg$5 = shifted(-64, 3, { shl: (a, b) => (a << b) | 0 }, { shr: (a, b) => a >> b });
  const arg$6 = shifted(
    BigInt.asUintN(64, 1n << 40n),
    4,
    { shl: (a, b) => BigInt.asUintN(64, a << (BigInt(b) & 63n)) },
    { shr: (a, b) => a >> (BigInt(b) & 63n) },
  );
  console.log(`(${arg$4[0]}, ${arg$4[1]}) (${arg$5[0]}, ${arg$5[1]}) (${arg$6[0]}, ${arg$6[1]})`);
  console.log(
    `${shifted_far(3, 4n, { shl: (a, b) => (a << Number(b & 63n)) >>> 0 })} ${shifted_far(1, 17n, { shl: (a, b) => (a << (Number(b & 63n) & 15)) & 65535 })}`,
  );
  const a = 12;
  const b = 10;
  console.log(`${(a & b) >>> 0} ${(a | b) >>> 0} ${(a ^ b) >>> 0} ${(a << 2) >>> 0}`);
  let c = 255;
  c = (c & b) >>> 0;
  c = (c | 256) >>> 0;
  c = (c ^ 1) >>> 0;
  c = c >>> 1;
  c = (c << 3) >>> 0;
  const far = 33n;
  console.log(`${c} ${(a << Number(far & 63n)) >>> 0}`);
  const total = [1, 2, 4].reduce((all, bit) => all | bit, 0);
  console.log(`${total}`);
}

export function entry() {
  main();
}

function flagsDebug_fmt(flags) {
  return `Flags(${flags[0]})`;
}

function flagsBitOr_bitor(flags, other) {
  return [flags[0] | other[0]];
}

export function flagsBitOr() {
  if ($flagsBitOr === undefined) {
    $flagsBitOr = { bitor: flagsBitOr_bitor };
  }
  return $flagsBitOr;
}
//# sourceMappingURL=case.js.map
