// Generated by rust-js from test/corpus/generic_from_str.rs. Do not edit.

import {
  $collectResults,
  $debugF64,
  $debugParseError,
  $debugStr,
  $parseBig,
  $parseBool,
  $parseChar,
  $parseF64,
  $parseInt,
  $some,
  $trim,
} from "@rust-js/runtime";

var $unitDebug, $unitFromStr;

function read(s, TFromStr) {
  const result = TFromStr.from_str(s);
  return result.TAG === "Ok" ? $some(result._0) : undefined;
}

function read_or(s, fallback, TFromStr) {
  const result = TFromStr.from_str($trim(s));
  return result.TAG === "Ok" ? result._0 : fallback;
}

function parse_all(parts, TFromStr) {
  return $collectResults(parts.values().map((p) => TFromStr.from_str(p)));
}

function explain(s, TFromStr, TDebug, TErrDebug) {
  const match = TFromStr.from_str(s);
  if (match.TAG === "Ok") {
    return TDebug.fmt(match._0);
  } else {
    return `error ${TErrDebug.fmt(match._0)}`;
  }
}

function main() {
  const arg = read("42", { from_str: (s) => $parseInt(s, -2147483648, 2147483647) });
  const arg$1 = read("x", { from_str: (s) => $parseF64(s) });
  const arg$2 = read("true", { from_str: (s) => $parseBool(s) });
  const arg$3 = read("kg", unitFromStr());
  const arg$4 = read("18446744073709551615", {
    from_str: (s) => $parseBig(s, 0n, 18446744073709551615n),
  });
  console.log(
    `${arg == null ? "None" : `Some(${arg})`} ${arg$1 == null ? "None" : `Some(${$debugF64(arg$1)})`} ${arg$2 == null ? "None" : `Some(${arg$2})`} ${arg$3 == null ? "None" : `Some(${arg$3})`} ${arg$4 == null ? "None" : `Some(${arg$4})`}`,
  );
  console.log(
    `${read_or("  7 ", 0, { from_str: (s) => $parseInt(s, 0, 255) })} ${read_or("nope", "Lb", unitFromStr())}`,
  );
  const arg$5 = parse_all(["1", "2"], { from_str: (s) => $parseInt(s, 0, 65535) });
  console.log(
    `${arg$5.TAG === "Ok" ? `Ok([${arg$5._0.map((item) => String(item)).join(", ")}])` : `Err(${$debugParseError(arg$5._0, "ParseIntError")})`} ${parse_all(["1", "300"], { from_str: (s) => $parseInt(s, -128, 127) }).TAG !== "Ok"}`,
  );
  const arg$6 = parse_all(["lb", "st"], unitFromStr());
  console.log(
    `${arg$6.TAG === "Ok" ? `Ok([${arg$6._0.map((item) => item).join(", ")}])` : `Err(${$debugStr(arg$6._0)})`}`,
  );
  console.log(
    `${explain("ab", { from_str: (s) => $parseChar(s) }, { fmt: (value) => $debugStr(value, "'") }, { fmt: (value) => $debugParseError(value, "ParseCharError") })} | ${explain("g", unitFromStr(), unitDebug(), { fmt: (value) => $debugStr(value) })} | ${explain(
      "s",
      { from_str: (s) => ({ TAG: "Ok", _0: s }) },
      { fmt: (value) => $debugStr(value) },
      { fmt: (value) => "" },
    )} | ${explain("-9", { from_str: (s) => $parseBig(s, -9223372036854775808n, 9223372036854775807n) }, { fmt: (value) => String(value) }, { fmt: (value) => $debugParseError(value, "ParseIntError") })}`,
  );
}

export function entry() {
  main();
}

function unitDebug_fmt(unit) {
  let f = "";
  let tmp;
  if (unit === "Kg") {
    tmp = "Kg";
  } else {
    tmp = "Lb";
  }
  f += tmp;
  return f;
}

function unitFromStr_from_str(s) {
  if (s === "kg") {
    return { TAG: "Ok", _0: "Kg" };
  } else if (s === "lb") {
    return { TAG: "Ok", _0: "Lb" };
  } else {
    return { TAG: "Err", _0: `unit ${s}` };
  }
}

export function unitDebug() {
  if ($unitDebug === undefined) {
    $unitDebug = { fmt: unitDebug_fmt };
  }
  return $unitDebug;
}

export function unitFromStr() {
  if ($unitFromStr === undefined) {
    $unitFromStr = { from_str: unitFromStr_from_str };
  }
  return $unitFromStr;
}
//# sourceMappingURL=case.js.map
