// Generated by rust-js from test/corpus/generic_writers.rs. Do not edit.

import { $byteLen, $mutStringWriter, $pad, $stringWriter, $zeroPad } from "@rust-js/runtime";

var $timeDisplay, $counterWrite, $flagsDisplay;

export function entry() {
  main();
}

function write_digit(w, v, Write) {
  return Write.write_char(w, String.fromCharCode((48 + v) & 255));
}

function write_two(w, v, Write) {
  write_digit(w, (v / 10) & 255, Write);
  return write_digit(w, v % 10, Write);
}

function write_time(w, hours, minutes, label, WWrite) {
  write_two(w, hours, WWrite);
  WWrite.write_char(w, ":");
  write_two(w, minutes, WWrite);
  if (label) {
    WWrite.write_str(w, " ");
    WWrite.write_fmt(w, `[${label}:${String((hours + minutes) & 255).padStart(3)}]`);
  }
  return;
}

export function timeDisplay() {
  if ($timeDisplay === undefined) {
    $timeDisplay = { fmt: timeDisplay_fmt };
  }
  return $timeDisplay;
}

function timeDisplay_fmt(time) {
  let f = "at ";
  const w = { value: f };
  write_time(w, time.hours, time.minutes, "", $stringWriter);
  f = w.value;
  f += ".";
  return f;
}

export function counterWrite() {
  if ($counterWrite === undefined) {
    const write_str = (arg0, arg1) => counterWrite_write_str(arg0.value, arg1);
    $counterWrite = { write_str, write_char: write_str, write_fmt: write_str };
  }
  return $counterWrite;
}

function counterWrite_write_str(counter, s) {
  const value = Array.from(s).length;
  counter.chars = (counter.chars + value) >>> 0;
  counter.text += s;
  return;
}

function to_writer(bits, writer, Write) {
  Write.write_str(
    {
      get value() {
        return writer;
      },
      set value(value) {
        writer = value;
      },
    },
    "bits",
  );
  Write.write_char(
    {
      get value() {
        return writer;
      },
      set value(value) {
        writer = value;
      },
    },
    "=",
  );
  return Write.write_fmt(
    {
      get value() {
        return writer;
      },
      set value(value) {
        writer = value;
      },
    },
    $zeroPad("0x" + bits.toString(16), 4),
  );
}

export function flagsDisplay() {
  if ($flagsDisplay === undefined) {
    $flagsDisplay = { fmt: flagsDisplay_fmt };
  }
  return $flagsDisplay;
}

function flagsDisplay_fmt(flags) {
  let f = "";
  const writer = { value: f };
  to_writer(flags[0], writer, $mutStringWriter);
  f = writer.value;
  return f;
}

function main() {
  let s = "> ";
  const w = { value: s };
  write_time(w, 9, 5, "am", $stringWriter);
  s = w.value;
  console.log(`${s}`);
  const time = { hours: 23, minutes: 59 };
  const arg = timeDisplay_fmt(time);
  const arg$1 = $byteLen(timeDisplay_fmt(time));
  console.log(`${timeDisplay_fmt(time)} [${$pad(arg, 12, ">")}] ${arg$1}`);
  let counter = { text: "", chars: 0 };
  const w$1 = { value: counter };
  write_time(w$1, 7, 30, "c", counterWrite());
  counter = w$1.value;
  console.log(`${counter.text} ${counter.chars}`);
  let alone = "";
  const w$2 = { value: alone };
  write_two(w$2, 42, $stringWriter);
  alone = w$2.value;
  const w$3 = { value: alone };
  write_digit(w$3, 7, $stringWriter);
  alone = w$3.value;
  console.log(`${alone}`);
  let bits = "[";
  const writer = { value: bits };
  to_writer(5, writer, $mutStringWriter);
  bits = writer.value;
  bits += "]";
  const arg$2 = [10];
  const arg$3 = flagsDisplay_fmt([255]);
  console.log(`${bits} ${flagsDisplay_fmt(arg$2)} ${$pad(arg$3, 12, ">")}|`);
  to_writer(9, counter, counterWrite());
  console.log(`${counter.text} ${counter.chars}`);
}
//# sourceMappingURL=case.js.map
