// Generated by rust-js from test/corpus/generic_mut_ref.rs. Do not edit.

var $i32Bump, $cBump;

export function entry() {
  main();
}

function cDebug_fmt(c) {
  return `C { n: ${c.n} }`;
}

function i32Bump() {
  if ($i32Bump === undefined) {
    $i32Bump = {
      bump: i32Bump_bump,
      get: i32Bump_get,
      bumped_twice: (self) => {
        i32Bump_bump(self);
        i32Bump_bump(self);
        return i32Bump_get(self.value);
      },
    };
  }
  return $i32Bump;
}

function i32Bump_bump(self) {
  self.value = (self.value + 1) | 0;
}

function i32Bump_get(self) {
  return self;
}

function cBump() {
  if ($cBump === undefined) {
    $cBump = {
      bump: (arg0) => cBump_bump(arg0.value),
      get: cBump_get,
      bumped_twice: (self) => {
        cBump_bump(self.value);
        cBump_bump(self.value);
        return cBump_get(self.value);
      },
    };
  }
  return $cBump;
}

function cBump_bump(c) {
  c.n = (c.n + 1) | 0;
}

function cBump_get(c) {
  return c.n;
}

function twice(x, TBump) {
  TBump.bump(x);
  TBump.bump(x);
}

function set(x, v) {
  x.value = v;
}

function bumped(t, TBump) {
  const self = { value: t };
  TBump.bump(self);
  t = self.value;
  return t;
}

function main() {
  let n = 1;
  let c = { n: 10 };
  const x = { value: n };
  twice(x, i32Bump());
  n = x.value;
  const x$1 = { value: c };
  twice(x$1, cBump());
  c = x$1.value;
  console.log(`${n} ${c.n}`);
  const x$2 = { value: n };
  set(x$2, 7);
  n = x$2.value;
  const x$3 = { value: c };
  const arg = { n: 20 };
  set(x$3, arg);
  c = x$3.value;
  console.log(`${n} ${cDebug_fmt(c)}`);
  console.log(`${bumped(1, i32Bump())} ${bumped({ n: 3 }, cBump()).n}`);
  const self = { value: n };
  const result = i32Bump().bumped_twice(self);
  n = self.value;
  const tmp = result;
  const self$1 = { value: c };
  const result$1 = cBump().bumped_twice(self$1);
  c = self$1.value;
  console.log(`${tmp} ${result$1}`);
  console.log(`${n} ${c.n}`);
}
//# sourceMappingURL=case.js.map
