// Generated by rust-js from test/corpus/generic_fmt_traits.rs. Do not edit.

import { $traitImpl } from "@rust-js/runtime";

var $varPointer, $varLowerHex, $handlePointer, $handleLowerHex;

function hex(t, TLowerHex) {
  return `${TLowerHex.fmt(t)}|${TLowerHex.fmt(t, { alternate: true })}`;
}

function main() {
  console.log(
    `${varPointer_fmt([[7]], undefined, handlePointer())} ${varLowerHex_fmt([[255]], undefined, handleLowerHex())} ${varLowerHex_fmt([[16]], { alternate: true }, handleLowerHex())}`,
  );
  console.log(`${hex([10], handleLowerHex())} ${hex([[11]], varLowerHex(handleLowerHex()))}`);
}

export function entry() {
  main();
}

function varPointer_fmt(var$, options, TPointer) {
  return TPointer.fmt(var$[0], options);
}

function varLowerHex_fmt(var$, options, TLowerHex) {
  return TLowerHex.fmt(var$[0], options);
}

function handlePointer_fmt(handle, options) {
  return `@${handle[0]}`;
}

function handleLowerHex_fmt(handle, options) {
  let f = "";
  if (options?.alternate === true) {
    f += "0x";
  }
  f += handle[0].toString(16);
  return f;
}

export function varPointer(TPointer) {
  if ($varPointer === undefined) {
    $varPointer = new WeakMap();
  }
  return $traitImpl($varPointer, [TPointer], () => ({
    fmt: (arg0, arg1) => varPointer_fmt(arg0, arg1, TPointer),
  }));
}

export function varLowerHex(TLowerHex) {
  if ($varLowerHex === undefined) {
    $varLowerHex = new WeakMap();
  }
  return $traitImpl($varLowerHex, [TLowerHex], () => ({
    fmt: (arg0, arg1) => varLowerHex_fmt(arg0, arg1, TLowerHex),
  }));
}

export function handlePointer() {
  if ($handlePointer === undefined) {
    $handlePointer = { fmt: handlePointer_fmt };
  }
  return $handlePointer;
}

export function handleLowerHex() {
  if ($handleLowerHex === undefined) {
    $handleLowerHex = { fmt: handleLowerHex_fmt };
  }
  return $handleLowerHex;
}
//# sourceMappingURL=case.js.map
