// Generated by rust-js from test/corpus/generic_iterator_items.rs. Do not edit.

import { $byteLen, $nextSome, $range } from "@rust-js/runtime";

var $deltaAdd;

export function entry() {
  main();
}

function noisyDrop_drop(noisy) {
  console.log(`drop ${noisy[0]}`);
}

function deltaDebug_fmt(delta) {
  return `Delta(${delta[0]})`;
}

export function deltaAdd() {
  if ($deltaAdd === undefined) {
    $deltaAdd = { add: deltaAdd_add };
  }
  return $deltaAdd;
}

function deltaAdd_add(delta, other) {
  return [BigInt.asIntN(64, delta[0] + other[0])];
}

function deltaSum_sum(iter, dropI) {
  return Iterator.from(iter).reduce((acc, x) => deltaAdd_add(acc, x), [0n]);
}

function first_long(items, BAsRefStr) {
  for (const item of Iterator.from(items)) {
    const text = BAsRefStr.as_ref(item);
    if ($byteLen(text) > 2) {
      return $byteLen(text);
    }
  }
  return;
}

function second(items) {
  items = Iterator.from(items);
  $nextSome(items);
  return $nextSome(items);
}

function main() {
  const words = ["a", "bb", "ccc", "dddd"];
  const arg = first_long(words, { as_ref: (value) => value });
  const arg$1 = first_long(["x"], { as_ref: (value) => value });
  console.log(
    `${arg == null ? "None" : `Some(${arg})`} ${arg$1 == null ? "None" : `Some(${arg$1})`}`,
  );
  const arg$2 = first_long(["abcd"], { as_ref: (value) => value });
  console.log(`${arg$2 == null ? "None" : `Some(${arg$2})`}`);
  const arg$3 = second($range(1, 5));
  const arg$4 = second([7]);
  console.log(
    `${arg$3 == null ? "None" : `Some(${arg$3})`} ${arg$4 == null ? "None" : `Some(${arg$4})`}`,
  );
  const total = deltaSum_sum([[3n], [4n], [-1n]]);
  console.log(`${deltaDebug_fmt(total)}`);
  const loud = [9];
  try {
    console.log(`${loud[0]}`);
  } finally {
    noisyDrop_drop(loud);
  }
}
//# sourceMappingURL=case.js.map
