// Generated by rust-js from test/corpus/ilog_zero.rs. Do not edit.

import { $ilog } from "@rust-js/runtime";

function main() {
  for (const n of [100, 9, 0]) {
    console.log(`${$ilog(n, 10)}`);
  }
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
