// Generated by rust-js from test/corpus/index_out_of_bounds.rs. Do not edit.

import { $index } from "@rust-js/runtime";

export function entry() {
  main();
}

function main() {
  const v = [1, 2, 3];
  const i = (v.length + 2) >>> 0;
  console.log(`reading ${i}`);
  console.log(`${$index(v, i)}`);
}
//# sourceMappingURL=case.js.map
