// Generated by rust-js from test/corpus/iter_next_back.rs. Do not edit.

import {
  $cmp,
  $debugStr,
  $iter,
  $next,
  $nextBack,
  $nextBackSome,
  $nextIf,
  $peek,
  $peekSome,
  $print,
  $range,
  $rest,
  $restStr,
  $sizeHint,
  $slice,
  $someAt,
  $someValue,
  $sortedEntries,
  $treeRange,
} from "@rust-js/runtime";

export function entry() {
  main();
}

function hint(it) {
  return $sizeHint(it);
}

function main() {
  const v = [1, 2, 3, 4, 5];
  const it = $iter(v);
  const arg = $next(it);
  const arg$1 = $nextBack(it);
  const arg$2 = $nextBack(it);
  console.log(
    `${arg == null ? "None" : `Some(${arg})`} ${arg$1 == null ? "None" : `Some(${arg$1})`} ${arg$2 == null ? "None" : `Some(${arg$2})`}`,
  );
  const tmp = it.end - it.at;
  const len = it.end - it.at;
  const arg$3 = [len, len];
  const arg$4 = hint(it);
  console.log(
    `${tmp} (${arg$3[0]}, ${arg$3[1] == null ? "None" : `Some(${arg$3[1]})`}) (${arg$4[0]}, ${arg$4[1] == null ? "None" : `Some(${arg$4[1]})`}) [${it.items
      .slice(it.at, it.end)
      .map((item) => String(item))
      .join(", ")}]`,
  );
  const rest = it.items.slice(it.at, it.end);
  console.log(`[${rest.map((item) => String(item)).join(", ")}]`);
  const taken = $iter(v);
  $nextBack(taken);
  const front = $rest(taken);
  console.log(`[${front.map((item) => String(item)).join(", ")}]`);
  for (const x of it) {
    $print(`${x} `);
  }
  const arg$5 = $next(it);
  const arg$6 = $nextBack(it);
  console.log(
    `${arg$5 == null ? "None" : `Some(${arg$5})`} ${arg$6 == null ? "None" : `Some(${arg$6})`}`,
  );
  const both = $iter($range(1, 4 + 1));
  while (true) {
    const value = $next(both);
    const value$1 = $nextBack(both);
    if (value != null && value$1 != null) {
      $print(`(${value}, ${value$1}) `);
    } else {
      break;
    }
  }
  const arg$7 = $next(both);
  console.log(`${arg$7 == null ? "None" : `Some(${arg$7})`}`);
  const tree = new Map([
    [1, "a"],
    [2, "b"],
    [3, "c"],
  ]);
  const arg$8 = $treeRange(tree, $cmp, false, "BTreeMap", false, undefined, true, 3, false).at(-1);
  const arg$9 = $sortedEntries(tree, $cmp).at(-1);
  console.log(
    `${arg$8 == null ? "None" : `Some((${arg$8[0]}, ${$debugStr(arg$8[1])}))`} ${arg$9 == null ? "None" : `Some((${arg$9[0]}, ${$debugStr(arg$9[1])}))`}`,
  );
  const arg$10 = v.map((x) => Math.imul(x, 10)).at(-1);
  console.log(`${arg$10 == null ? "None" : `Some(${arg$10})`}`);
  const arg$11 = Array.from("héllo").at(-1);
  const arg$12 = "a,b,c".split(",").at(-1);
  console.log(
    `${arg$11 == null ? "None" : `Some(${$debugStr(arg$11, "'")})`} ${arg$12 == null ? "None" : `Some(${$debugStr(arg$12)})`}`,
  );
  const maybe = [1, undefined];
  const options = $iter(maybe);
  const arg$13 = $nextBackSome(options);
  const arg$14 = $nextBackSome(options);
  const arg$15 = $nextBackSome(options);
  console.log(
    `${((value) => (value == null ? "None" : `Some(${((value) => (value == null ? "None" : `Some(${value})`))($someValue(value))})`))(arg$13)} ${((value) => (value == null ? "None" : `Some(${((value) => (value == null ? "None" : `Some(${value})`))($someValue(value))})`))(arg$14)} ${((value) => (value == null ? "None" : `Some(${((value) => (value == null ? "None" : `Some(${value})`))($someValue(value))})`))(arg$15)}`,
  );
  const tmp$1 = $someAt(maybe, maybe.length - 1);
  const items = $slice(maybe, 0, 1);
  const arg$16 = $someAt(items, items.length - 1);
  console.log(
    `${((value) => (value == null ? "None" : `Some(${((value) => (value == null ? "None" : `Some(${value})`))($someValue(value))})`))(tmp$1)} ${((value) => (value == null ? "None" : `Some(${((value) => (value == null ? "None" : `Some(${value})`))($someValue(value))})`))(arg$16)}`,
  );
  const peeked = $iter(maybe);
  $nextBackSome(peeked);
  $nextBackSome(peeked);
  const arg$17 = $peekSome(peeked);
  const arg$18 = $range(0, 4).at(-1);
  console.log(
    `${((value) => (value == null ? "None" : `Some(${((value) => (value == null ? "None" : `Some(${value})`))($someValue(value))})`))(arg$17)} ${arg$18 == null ? "None" : `Some(${arg$18})`}`,
  );
  const peeking = $iter(v);
  const first = $peek(peeking);
  const arg$19 = $nextBack(peeking);
  console.log(
    `${first == null ? "None" : `Some(${first})`} ${arg$19 == null ? "None" : `Some(${arg$19})`}`,
  );
  while ($nextBack(peeking) != null) {}
  const left = $peek(peeking);
  const arg$20 = $nextIf(peeking, () => true);
  console.log(
    `${left == null ? "None" : `Some(${left})`} ${arg$20 == null ? "None" : `Some(${arg$20})`}`,
  );
  const chars = $iter(Array.from("xyz"));
  $nextBack(chars);
  console.log(`${$debugStr($restStr(chars))}`);
}
//# sourceMappingURL=case.js.map
