// Generated by rust-js from test/corpus/iterator_back_ends.rs. Do not edit.

import {
  $iter,
  $iterator,
  $next,
  $nextBack,
  $nextIf,
  $peek,
  $range,
  $rangeNext,
  $rangeNextBack,
} from "@rust-js/runtime";

export function entry() {
  main();
}

function spanIterator_next(span) {
  if (span[0] < span[1]) {
    span[0] = (span[0] + 1) >>> 0;
    return (span[0] - 1) >>> 0;
  }
  return;
}

function spanDoubleEndedIterator_next_back(span) {
  if (span[0] < span[1]) {
    span[1] = (span[1] - 1) >>> 0;
    return span[1];
  }
  return;
}

function main() {
  const down = $range(1, 4).toReversed();
  const top = $range(250, 255 + 1).toReversed();
  const own = $iterator([0, 3], spanDoubleEndedIterator_next_back).toArray();
  console.log(
    `[${down.map((item) => String(item)).join(", ")}] [${top.map((item) => String(item)).join(", ")}] [${own.map((item) => String(item)).join(", ")}]`,
  );
  const v = [10, 20, 30, 40];
  const it = $iter(v);
  const back = $nextBack(it);
  const front = $next(it);
  const arg = it.end - it.at;
  const arg$1 = it.items.slice(it.at, it.end);
  console.log(
    `${back == null ? "None" : `Some(${back})`} ${front == null ? "None" : `Some(${front})`} ${arg} [${arg$1.map((item) => String(item)).join(", ")}]`,
  );
  const range = { start: 0, end: 5 };
  const arg$2 = $rangeNextBack(range);
  const arg$3 = $rangeNext(range);
  console.log(
    `${arg$2 == null ? "None" : `Some(${arg$2})`} ${arg$3 == null ? "None" : `Some(${arg$3})`}`,
  );
  const p = $iter(v);
  const peeked = $peek(p);
  const ten = $nextIf(p, (item) => item === 10);
  const big = $nextIf(p, (x) => x > 100);
  const arg$4 = $next(p);
  console.log(
    `${peeked == null ? "None" : `Some(${peeked})`} ${ten == null ? "None" : `Some(${ten})`} ${big == null ? "None" : `Some(${big})`} ${arg$4 == null ? "None" : `Some(${arg$4})`}`,
  );
}
//# sourceMappingURL=case.js.map
