// Generated by rust-js from test/corpus/iter_by_ref.rs. Do not edit.

import { $debugStr, $iter, $iterator, $rest } from "@rust-js/runtime";

function split_number(text) {
  let cs = $iter(Array.from(text).map((x, i) => [i, x]));
  let digits = "";
  for (const [, c] of cs) {
    if (c === "e") {
      break;
    }
    digits += c;
  }
  const rest = $rest(cs)
    .map(([i, c]) => String(i) + c)
    .join("");
  return [digits, rest];
}

function split_mut(text) {
  let cs = $iter(Array.from(text));
  let head = "";
  for (const c of cs) {
    if (c === ":") {
      break;
    }
    head += c;
  }
  return [head, $rest(cs).length];
}

function main() {
  const arg = split_number("12e34");
  const arg$1 = split_number("7");
  console.log(
    `(${$debugStr(arg[0])}, ${$debugStr(arg[1])}) (${$debugStr(arg$1[0])}, ${$debugStr(arg$1[1])})`,
  );
  const arg$2 = split_mut("key:value");
  const arg$3 = split_mut("none");
  console.log(`(${$debugStr(arg$2[0])}, ${arg$2[1]}) (${$debugStr(arg$3[0])}, ${arg$3[1]})`);
  const names = $iterator({ inner: { at: 0 }, bits: 3 }, equalNamesIterator_next).toArray();
  console.log(`[${names.map((item) => $debugStr(item)).join(", ")}]`);
  let all = { at: 0 };
  for (const [n] of $iterator(all, namesIterator_next)) {
    if (n === "B") {
      break;
    }
  }
  const arg$4 = namesIterator_next(all);
  console.log(
    `${arg$4 == null ? "None" : `Some((${$debugStr(arg$4[0])}, ${arg$4[1]}))`} ${all.at}`,
  );
}

export function entry() {
  main();
}

function namesIterator_next(names) {
  const all = [
    ["A", 1],
    ["B", 2],
    ["AB", 3],
    ["C", 4],
  ];
  const item = all[names.at];
  names.at = (names.at + 1) >>> 0;
  return item;
}

function equalNamesIterator_next(equalNames) {
  for (const [n, bits] of $iterator(equalNames.inner, namesIterator_next)) {
    if (bits === equalNames.bits) {
      return n;
    }
  }
  return undefined;
}
//# sourceMappingURL=case.js.map
