// Generated by rust-js from test/corpus/kept_generic_iterators.rs. Do not edit.

import { $iterator, $next, $nextSome, $someValue, $successors } from "@rust-js/runtime";

export function entry() {
  main();
}

function sum(it) {
  it = Iterator.from(it);
  let total = 0;
  while (true) {
    const x = $next(it);
    if (x != null) {
      total = (total + x) >>> 0;
    } else {
      break;
    }
  }
  return total;
}

function pairs(it) {
  const it$1 = Iterator.from(it);
  const out = [];
  while (true) {
    const value = $next(it$1);
    const value$1 = $next(it$1);
    if (value != null && value$1 != null) {
      out.push([value, value$1]);
    } else {
      break;
    }
  }
  return out;
}

function after_first(it) {
  it = Iterator.from(it);
  const first = $next(it);
  const rest = [];
  for (const x of Iterator.from(it)) {
    rest.push(Math.imul(x, 10) >>> 0);
  }
  return [first, rest];
}

function firsts(it) {
  it = Iterator.from(it);
  const a = $nextSome(it);
  const b = $nextSome(it);
  return [a, b];
}

function countdownIterator_next(countdown) {
  if (countdown[0] === 0) {
    return;
  }
  countdown[0] = (countdown[0] - 1) >>> 0;
  return countdown[0];
}

function main() {
  const v = [1, 2, 3, 4, 5];
  console.log(
    `${sum(v)} ${sum($iterator([4], countdownIterator_next))} ${sum($successors(1, (n) => (n < 4 ? (n + 1) >>> 0 : undefined)))}`,
  );
  console.log(
    `[${pairs(v)
      .map((item) => `(${item[0]}, ${item[1]})`)
      .join(", ")}] [${pairs($iterator([5], countdownIterator_next))
      .map((item) => `(${item[0]}, ${item[1]})`)
      .join(", ")}]`,
  );
  const arg = after_first(v);
  const arg$1 = after_first($iterator([3], countdownIterator_next));
  console.log(
    `(${arg[0] == null ? "None" : `Some(${arg[0]})`}, [${arg[1].map((item) => String(item)).join(", ")}]) (${arg$1[0] == null ? "None" : `Some(${arg$1[0]})`}, [${arg$1[1].map((item) => String(item)).join(", ")}])`,
  );
  const arg$2 = firsts([undefined, 2]);
  console.log(
    `(${((value) => (value == null ? "None" : `Some(${((value) => (value == null ? "None" : `Some(${value})`))($someValue(value))})`))(arg$2[0])}, ${((value) => (value == null ? "None" : `Some(${((value) => (value == null ? "None" : `Some(${value})`))($someValue(value))})`))(arg$2[1])})`,
  );
  const arg$3 = firsts([]);
  console.log(
    `(${arg$3[0] == null ? "None" : "Some(())"}, ${arg$3[1] == null ? "None" : "Some(())"})`,
  );
}
//# sourceMappingURL=case.js.map
