// Generated by rust-js from test/corpus/lent_iterators.rs. Do not edit.

import {
  $iter,
  $iterator,
  $lent,
  $next,
  $nextIf,
  $rest,
  $successors,
  $toDigit,
  $unwrap,
} from "@rust-js/runtime";

export function entry() {
  main();
}

function skip(it, n) {
  it = $lent(it);
  for (let i = 0; i < n; i++) {
    $next(it);
  }
}

function first(it) {
  it = $lent(it);
  return $next(it);
}

function number(it) {
  let n = 0;
  while (true) {
    const c = $nextIf(it, (c) => /^[0-9]$/.test(c));
    if (c != null) {
      n = ((Math.imul(n, 10) >>> 0) + $unwrap($toDigit(c, 10))) >>> 0;
    } else {
      break;
    }
  }
  return n;
}

function word(it) {
  it = $lent(it);
  let s = "";
  while (true) {
    const c = $next(it);
    if (c != null) {
      if (c === " ") {
        break;
      }
      s += c;
    } else {
      break;
    }
  }
  return s;
}

function take2(it) {
  it = $lent(it);
  return Iterator.from(it).take(2).toArray();
}

function until_zero(it) {
  it = $lent(it);
  let sum = 0;
  for (const x of Iterator.from(it)) {
    if (x === 0) {
      break;
    }
    sum = (sum + x) >>> 0;
  }
  return sum;
}

function countdownIterator_next(countdown) {
  if (countdown[0] === 0) {
    return;
  }
  countdown[0] = (countdown[0] - 1) >>> 0;
  return countdown[0];
}

function main() {
  const it = $iter([1, 2, 3, 4, 5]);
  skip(it, 2);
  const arg = first(it);
  console.log(
    `${arg == null ? "None" : `Some(${arg})`} [${$rest(it)
      .map((item) => String(item))
      .join(", ")}]`,
  );
  const c = [5];
  skip($iterator(c, countdownIterator_next), 1);
  const arg$1 = first($iterator(c, countdownIterator_next));
  const arg$2 = countdownIterator_next(c);
  console.log(
    `${arg$1 == null ? "None" : `Some(${arg$1})`} ${arg$2 == null ? "None" : `Some(${arg$2})`}`,
  );
  const chars = $iter(Array.from("12+345"));
  const a = number(chars);
  $next(chars);
  console.log(`${a} ${number(chars)}`);
  const words = $iter(Array.from("hello big world"));
  const [x, y] = [word(words), word(words)];
  console.log(`${x} ${y} ${word(words)}`);
  const lazy = $successors(1, (n) => Math.imul(n, 2) >>> 0).map((n) => (n + 1) >>> 0);
  const a$1 = take2(lazy);
  const arg$3 = $next(lazy);
  console.log(
    `[${a$1.map((item) => String(item)).join(", ")}] ${arg$3 == null ? "None" : `Some(${arg$3})`}`,
  );
  const v = $iter([1, 2, 0, 3, 4, 0, 5]);
  const s1 = until_zero(v);
  const s2 = until_zero(v);
  const arg$4 = $next(v);
  console.log(`${s1} ${s2} ${arg$4 == null ? "None" : `Some(${arg$4})`}`);
}
//# sourceMappingURL=case.js.map
