// Generated by rust-js from test/corpus/map_drops.rs. Do not edit.

import {
  $cmp,
  $insert,
  $orInsertWith,
  $rcClone,
  $rcDrop,
  $remove,
  $sortedEntries,
} from "@rust-js/runtime";

export function entry() {
  main();
}

function noisyDrop_drop(noisy) {
  console.log(`drop ${noisy[0]}`);
}

function main() {
  const sorted = new Map();
  let sorted$live = true;
  try {
    const value = $insert(sorted, 3, ["c"]);
    if (value != null) {
      noisyDrop_drop(value);
    }
    const value$1 = $insert(sorted, 1, ["a"]);
    if (value$1 != null) {
      noisyDrop_drop(value$1);
    }
    const value$2 = $insert(sorted, 2, ["b"]);
    if (value$2 != null) {
      noisyDrop_drop(value$2);
    }
    const old = $insert(sorted, 2, ["b2"]);
    const map = (n) => {
      try {
        return n[0];
      } finally {
        noisyDrop_drop(n);
      }
    };
    console.log(`replaced ${(old ? map(old) : undefined) ?? "none"}`);
    const taken = $remove(sorted, 1);
    let taken$live = true;
    try {
      console.log(`took ${!!taken} ${sorted.size}`);
      taken$live = false;
      if (taken != null) {
        noisyDrop_drop(taken);
      }
      const n = sorted.get(3);
      if (n) {
        console.log(`has ${n[0]}`);
      }
      sorted$live = false;
      for (const [, value$3] of $sortedEntries(sorted, $cmp)) {
        noisyDrop_drop(value$3);
      }
      console.log("sorted dropped");
      const byName = new Map();
      try {
        const value$4 = $insert(byName, "x", ["x"]);
        if (value$4 != null) {
          noisyDrop_drop(value$4);
        }
        $orInsertWith(byName, "y", () => ["y"]);
        console.log(`${byName.size} ${byName.has("y")}`);
        const x = $remove(byName, "x");
        try {
          console.log(`${!!x}`);
          const shared = { value: 5, strong: 1, weak: 0 };
          try {
            const handles = new Map();
            let handles$live = true;
            try {
              const value$5 = $insert(handles, "a", $rcClone(shared));
              if (value$5 != null) {
                $rcDrop(value$5);
              }
              const value$6 = $insert(handles, "b", $rcClone(shared));
              if (value$6 != null) {
                $rcDrop(value$6);
              }
              console.log(`${shared.strong}`);
              const value$7 = $remove(handles, "a");
              if (value$7 != null) {
                $rcDrop(value$7);
              }
              console.log(`${shared.strong}`);
              handles$live = false;
              for (const item of handles.values()) {
                $rcDrop(item);
              }
              console.log(`${shared.strong}`);
            } finally {
              if (handles$live) {
                for (const item$1 of handles.values()) {
                  $rcDrop(item$1);
                }
              }
            }
          } finally {
            $rcDrop(shared);
          }
        } finally {
          if (x != null) {
            noisyDrop_drop(x);
          }
        }
      } finally {
        for (const item$2 of byName.values()) {
          noisyDrop_drop(item$2);
        }
      }
    } finally {
      if (taken$live) {
        if (taken != null) {
          noisyDrop_drop(taken);
        }
      }
    }
  } finally {
    if (sorted$live) {
      for (const [, value$8] of $sortedEntries(sorted, $cmp)) {
        noisyDrop_drop(value$8);
      }
    }
  }
}
//# sourceMappingURL=case.js.map
