// Generated by rust-js from test/corpus/marker_traits.rs. Do not edit.

const COUNTER = { hits: { value: 0 } };

function hit() {
  COUNTER.hits.value = (COUNTER.hits.value + 1) >>> 0;
  return COUNTER.hits.value;
}

function shared(value) {
  return value;
}

function main() {
  console.log(`${hit()} ${hit()} ${COUNTER.hits.value}`);
  const handle = { id: 7 };
  console.log(`${shared(handle).id} ${shared(3)}`);
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
