// Generated by scripts/matrix.ts (ADR 0182): each integer operation on each pair of a type's boundary values. Edit it there.

// One line per value, and per pair: each result, by `{:?}`; a float's by its
// bits, as a NaN's differ by platform.

fn f64_bits(x: f64) -> String {
    if x.is_nan() { "NaN".to_string() } else { format!("{:016x}", x.to_bits()) }
}

fn f32_bits(x: f32) -> String {
    if x.is_nan() { "NaN".to_string() } else { format!("{:08x}", x.to_bits()) }
}

macro_rules! integers {
    ($t:ident, $signed:ident) => {{
        let values: [$t; 9] = [
            $t::MIN,
            $t::MIN + 1,
            (0 as $t).wrapping_sub(1),
            0,
            1,
            2,
            7,
            $t::MAX - 1,
            $t::MAX,
        ];
        let bits = $t::BITS;
        for a in values {
            println!(
                "{} {a}: zeros {} {} ones {} {} swap {} rev {} rot {} {} neg {} {:?} pow {} {} {} {:?}",
                stringify!($t),
                a.leading_zeros(),
                a.trailing_zeros(),
                a.count_ones(),
                a.count_zeros(),
                a.swap_bytes(),
                a.reverse_bits(),
                a.rotate_left(1),
                a.rotate_right(3),
                a.wrapping_neg(),
                a.checked_neg(),
                a.wrapping_pow(0),
                a.wrapping_pow(2),
                a.wrapping_pow(bits - 1),
                a.checked_pow(3),
            );
            println!(
                "{} {a}: fmt {:x} {:b} {:o} {:#X} [{:>6}] [{:<6}] [{:^7}] [{:+}] [{:06}] parse {:?} {:?}",
                stringify!($t),
                a,
                a,
                a,
                a,
                a,
                a,
                a,
                a,
                a,
                a.to_string().parse::<$t>(),
                $t::from_str_radix(&format!("{:x}", a), 16),
            );
            println!(
                "{} {a}: as {} {} {} {} {} {} {} {} {} {} f32 {} f64 {}",
                stringify!($t),
                a as i8,
                a as i16,
                a as i32,
                a as i64,
                a as i128,
                a as u8,
                a as u16,
                a as u32,
                a as u64,
                a as u128,
                f32_bits(a as f32),
                f64_bits(a as f64),
            );
            for s in [0, 1, bits - 1, bits, bits + 1] {
                println!(
                    "{} {a} shift {s}: {} {} {:?} {:?}",
                    stringify!($t),
                    a.wrapping_shl(s),
                    a.wrapping_shr(s),
                    a.checked_shl(s),
                    a.checked_shr(s),
                );
            }
            $signed!($t, a);
            for b in values {
                let quotient = match a.checked_div(b) {
                    Some(_) => format!("{} {}", a / b, a % b),
                    None => "-".to_string(),
                };
                println!(
                    "{} {a} {b}: wrap {} {} {} chk {:?} {:?} {:?} {:?} {:?} sat {} {} {} over {:?} {:?} {:?} div {quotient} euclid {:?} {:?} cmp {} {} {:?} {} {} {}",
                    stringify!($t),
                    a.wrapping_add(b),
                    a.wrapping_sub(b),
                    a.wrapping_mul(b),
                    a.checked_add(b),
                    a.checked_sub(b),
                    a.checked_mul(b),
                    a.checked_div(b),
                    a.checked_rem(b),
                    a.saturating_add(b),
                    a.saturating_sub(b),
                    a.saturating_mul(b),
                    a.overflowing_add(b),
                    a.overflowing_sub(b),
                    a.overflowing_mul(b),
                    a.checked_div_euclid(b),
                    a.checked_rem_euclid(b),
                    a < b,
                    a == b,
                    a.cmp(&b),
                    a.min(b),
                    a.max(b),
                    a.abs_diff(b),
                );
            }
        }
    }};
}

macro_rules! signed {
    ($t:ident, $a:ident) => {
        println!(
            "{} {}: signed {} {} {:?} {}",
            stringify!($t),
            $a,
            $a.signum(),
            $a.wrapping_abs(),
            $a.checked_abs(),
            $a.unsigned_abs(),
        );
    };
}

macro_rules! unsigned {
    ($t:ident, $a:ident) => {
        println!(
            "{} {}: unsigned {}",
            stringify!($t),
            $a,
            $a.is_power_of_two(),
        );
    };
}

fn main() {
    integers!(i8, signed);
    integers!(i16, signed);
    integers!(i32, signed);
    integers!(i64, signed);
    integers!(i128, signed);
    integers!(u8, unsigned);
    integers!(u16, unsigned);
    integers!(u32, unsigned);
    integers!(u64, unsigned);
    integers!(u128, unsigned);
}
