// Generated by scripts/matrix.ts (ADR 0182): each char method on each char, and each pair of them, where characters go wrong. Edit it there.

// Each result by `{:?}`. A pair's order is "listed" where the semantics
// page's difference shows, strings and chars comparing by UTF-16 units.

const CHARS: &[char] = &[
    '\0', '\t', '\n', ' ', '0', '7', '9', 'a', 'f', 'g', 'z', 'A', 'F', 'Z', '_', '~', '\u{7f}',
    '\u{85}', '\u{a0}', '\u{e9}', '\u{df}', '\u{1c5}', '\u{130}', '\u{fb01}', '\u{3a3}', '\u{3c3}',
    '\u{3c2}', '\u{663}', '\u{2167}', '\u{2028}', '\u{3000}', '\u{feff}', '\u{e000}', '\u{fffd}',
    '\u{1f980}', '\u{10ffff}',
];

fn units(c: char) -> Vec<u32> {
    let c = c as u32;
    match c > 0xffff {
        true => vec![0xd800 + ((c - 0x10000) >> 10), 0xdc00 + (c & 0x3ff)],
        false => vec![c],
    }
}

fn main() {
    for &c in CHARS {
        println!(
            "{c:?}: is {} {} {} {} {} {} {} ascii {} {} {} {} {} {} {} {} {} {} {} {}",
            c.is_alphabetic(),
            c.is_numeric(),
            c.is_alphanumeric(),
            c.is_whitespace(),
            c.is_uppercase(),
            c.is_lowercase(),
            c.is_control(),
            c.is_ascii(),
            c.is_ascii_digit(),
            c.is_ascii_hexdigit(),
            c.is_ascii_alphabetic(),
            c.is_ascii_alphanumeric(),
            c.is_ascii_uppercase(),
            c.is_ascii_lowercase(),
            c.is_ascii_punctuation(),
            c.is_ascii_graphic(),
            c.is_ascii_whitespace(),
            c.is_ascii_control(),
            c.is_digit(8),
        );
        println!(
            "{c:?}: case {:?} {:?} {:?} {:?} digit {:?} {:?} {:?} len {} {} as {} {} {:?} {:?} fmt [{:>4}] [{:<3}] {}",
            c.to_uppercase().collect::<String>(),
            c.to_lowercase().collect::<String>(),
            c.to_ascii_uppercase(),
            c.to_ascii_lowercase(),
            c.to_digit(10),
            c.to_digit(16),
            c.to_digit(36),
            c.len_utf8(),
            c.len_utf16(),
            c as u32,
            c as u8,
            (c as u8) as char,
            char::from_u32(c as u32 + 1),
            c,
            c,
            c.to_string().len(),
        );
        for &d in CHARS {
            let order = match (c as u32).cmp(&(d as u32)) != units(c).cmp(&units(d)) {
                true => "listed".to_string(),
                false => format!("{:?} {} {}", c.cmp(&d), c < d, c.max(d)),
            };
            println!("{c:?} {d:?}: {order} {} {}", c == d, c.eq_ignore_ascii_case(&d));
        }
    }
    for n in [0, 7, 9, 10, 15, 35, 36] {
        println!("{n}: {:?} {:?} {:?}", char::from_digit(n, 10), char::from_digit(n, 16), char::from_digit(n, 36));
    }
}
