// Generated by scripts/matrix.ts (ADR 0182): each float operation on each pair of a type's boundary values. Edit it there.

// One line per value, and per pair: each result, a float by its bits, as a
// NaN's differ by platform, then as it's written.

fn f64_bits(x: f64) -> String {
    if x.is_nan() { "NaN".to_string() } else { format!("{:016x}", x.to_bits()) }
}

fn f32_bits(x: f32) -> String {
    if x.is_nan() { "NaN".to_string() } else { format!("{:08x}", x.to_bits()) }
}

macro_rules! floats {
    ($t:ident, $bits:ident, $values:expr) => {{
        let values: &[$t] = &$values;
        for &a in values {
            println!(
                "{} {}: round {} {} {} {} {} abs {} {} {} sqrt {} powi {} {} recip {} neg {} clamp {}",
                stringify!($t),
                $bits(a),
                $bits(a.floor()),
                $bits(a.ceil()),
                $bits(a.round()),
                $bits(a.trunc()),
                $bits(a.fract()),
                $bits(a.abs()),
                $bits(a.signum()),
                $bits(a.to_degrees()),
                $bits(a.sqrt()),
                $bits(a.powi(3)),
                $bits(a.powi(-2)),
                $bits(a.recip()),
                $bits(-a),
                $bits(a.clamp(-1.0, 1.0)),
            );
            println!(
                "{} {}: is {} {} {} {} {} {} {:?} bits {}",
                stringify!($t),
                $bits(a),
                a.is_nan(),
                a.is_finite(),
                a.is_infinite(),
                a.is_sign_negative(),
                a.is_normal(),
                a.is_subnormal(),
                a.classify(),
                $bits($t::from_bits(a.to_bits())),
            );
            println!(
                "{} {}: fmt {} {:?} {:e} {:E} {:.0} {:.1} {:.3} [{:>12.2}] {:+} [{:08.2}] parse {:?}",
                stringify!($t),
                $bits(a),
                a,
                a,
                a,
                a,
                a,
                a,
                a,
                a,
                a,
                a,
                a.to_string().parse::<$t>().map($bits),
            );
            println!(
                "{} {}: as {} {} {} {} {} {} {} {} f32 {} f64 {}",
                stringify!($t),
                $bits(a),
                a as i8,
                a as i32,
                a as i64,
                a as i128,
                a as u8,
                a as u32,
                a as u64,
                a as u128,
                f32_bits(a as f32),
                f64_bits(a as f64),
            );
            for &b in values {
                println!(
                    "{} {} {}: {} {} {} {} {} min {} max {} pow {} cmp {:?} {:?} {} {} {}",
                    stringify!($t),
                    $bits(a),
                    $bits(b),
                    $bits(a + b),
                    $bits(a - b),
                    $bits(a * b),
                    $bits(a / b),
                    $bits(a % b),
                    // Of inputs that compare equal, +0.0 and -0.0, either may be
                    // returned: x86's native max gives -0.0, arm64's and JS's
                    // +0.0. So their sign isn't printed then.
                    if a == b && a == 0.0 { "±0".to_string() } else { $bits(a.min(b)) },
                    if a == b && a == 0.0 { "±0".to_string() } else { $bits(a.max(b)) },
                    if b.fract() == 0.0 || !b.is_finite() { $bits(a.powf(b)) } else { "-".to_string() },
                    a.total_cmp(&b),
                    a.partial_cmp(&b),
                    a == b,
                    a < b,
                    a >= b,
                );
            }
        }
    }};
}

fn main() {
    floats!(
        f64,
        f64_bits,
        [
            0.0,
            -0.0,
            1.0,
            -1.0,
            0.5,
            1.5,
            2.5,
            -2.5,
            0.1,
            1e-7,
            1e21,
            123456789.125,
            9007199254740993.0,
            1e-310,
            f64::MIN_POSITIVE,
            f64::EPSILON,
            f64::MAX,
            f64::MIN,
            f64::INFINITY,
            f64::NEG_INFINITY,
            f64::NAN,
        ]
    );
    floats!(
        f32,
        f32_bits,
        [
            0.0,
            -0.0,
            1.0,
            -1.0,
            0.5,
            2.5,
            -2.5,
            0.1,
            1e-7,
            16777217.0,
            1e-40,
            f32::MIN_POSITIVE,
            f32::EPSILON,
            f32::MAX,
            f32::MIN,
            f32::INFINITY,
            f32::NEG_INFINITY,
            f32::NAN,
        ]
    );
}
