// Generated by rust-js from test/corpus/moved_closure.rs. Do not edit.

export function entry() {
  main();
}

function main() {
  let n = 0;
  const f = () => {
    n = (n + 1) | 0;
    return n;
  };
  const g = f;
  g();
  console.log(`${g()}`);
  const k = 41;
  const h = () => (k + 1) | 0;
  const h2 = h;
  console.log(`${h()} ${h2()}`);
}
//# sourceMappingURL=case.js.map
