// Generated by rust-js from test/corpus/mut_ref_to_ref.rs. Do not edit.

import { $byteLen, $debugStr, $strSlice } from "@rust-js/runtime";

export function entry() {
  main();
}

function shorten(s) {
  s.value = $strSlice(s.value, 1);
}

function pick(slot, other) {
  if (other.length > slot.value.length) {
    slot.value = other;
  }
}

function main() {
  let s = "hello";
  const s$1 = { value: s };
  shorten(s$1);
  s = s$1.value;
  const s$2 = { value: s };
  shorten(s$2);
  s = s$2.value;
  console.log(`${s}`);
  const a = [1, 2];
  const b = [3, 4, 5];
  let longest = a;
  const slot = { value: longest };
  pick(slot, b);
  longest = slot.value;
  console.log(`[${longest.map((item) => String(item)).join(", ")}]`);
  const words = ["a", "bb", "c"];
  for (let i = 0; i < words.length; i++) {
    if ($byteLen(words[i]) === 1) {
      words[i] = "one";
    }
  }
  console.log(`[${words.map((item) => $debugStr(item)).join(", ")}]`);
  s = "x";
  console.log(`${s}`);
  const cursor = { rest: "abc" };
  const s$3 = { value: cursor.rest };
  shorten(s$3);
  cursor.rest = s$3.value;
  console.log(`${cursor.rest}`);
}
//# sourceMappingURL=case.js.map
