// Generated by rust-js from test/corpus/mut_ref_local.rs. Do not edit.

import { $at, $index } from "@rust-js/runtime";

export function entry() {
  main();
}

function bump(n) {
  n.value = (n.value + 1) | 0;
}

function main() {
  let x = 3;
  x = 5;
  x = (x + 2) | 0;
  console.log(`${x}`);
  const arg = {
    get value() {
      return x;
    },
    set value(value) {
      x = value;
    },
  };
  console.log(`${arg.value} ${arg.value}`);
  const n = { value: x };
  bump(n);
  x = n.value;
  const n$1 = { value: x };
  bump(n$1);
  x = n$1.value;
  console.log(`${x}`);
  const v = [1, 2, 3];
  let i = 0;
  const at = $at(v, i);
  i = 2;
  v[at] = (v[at] + 10) | 0;
  console.log(`[${v.map((item) => String(item)).join(", ")}] ${i}`);
  let name = "ada";
  name += " lovelace";
  name = name.toUpperCase();
  console.log(`${name}`);
  let o;
  o = 4;
  if (o != null) {
    o = (o + 1) >>> 0;
  }
  console.log(`${o == null ? "None" : `Some(${o})`}`);
  const pt = { x: 1, y: 2 };
  pt.x = Math.imul(pt.x, 10);
  console.log(`${pt.x} ${pt.y}`);
  const a = { count: 1 };
  const b = { count: 10 };
  let cur = a;
  const o$1 = cur;
  cur = b;
  o$1.count = (o$1.count + 1) | 0;
  cur.count = (cur.count + 5) | 0;
  console.log(`${a.count} ${b.count}`);
  const xs = [1, 2];
  const ys = [10, 20];
  let list = xs;
  const o$2 = list;
  const at$1 = $at(list, 0);
  list = ys;
  o$2[at$1] = (o$2[at$1] + 1) | 0;
  list[$at(list, 1)] = (list[$at(list, 1)] + 1) | 0;
  console.log(
    `[${xs.map((item) => String(item)).join(", ")}] [${ys.map((item) => String(item)).join(", ")}]`,
  );
  let [xs$1, ys$1] = [
    [1, 2],
    [10, 20],
  ];
  let [na, nb] = [{ count: 1 }, { count: 10 }];
  const h = { list: xs$1, node: na };
  const o$3 = h.list;
  const at$2 = $at(h.list, 0);
  const o$4 = h.node;
  h.list = ys$1;
  h.node = nb;
  o$3[at$2] = (o$3[at$2] + 1) | 0;
  o$4.count = (o$4.count + 1) | 0;
  h.list[$at(h.list, 1)] = (h.list[$at(h.list, 1)] + 1) | 0;
  console.log(
    `[${xs$1.map((item) => String(item)).join(", ")}] [${ys$1.map((item) => String(item)).join(", ")}] ${na.count} ${nb.count}`,
  );
  let [xs$2, ys$2] = [
    [1, 2],
    [10, 20],
  ];
  const refs = [xs$2];
  const o$5 = refs[0];
  const at$3 = $at(refs[0], 0);
  refs[0] = ys$2;
  o$5[at$3] = (o$5[at$3] + 1) | 0;
  console.log(
    `[${xs$2.map((item) => String(item)).join(", ")}] [${ys$2.map((item) => String(item)).join(", ")}]`,
  );
  let [xs$3, ys$3] = [
    [1, 2],
    [10, 20],
  ];
  let list$1 = xs$3;
  const o$6 = list$1;
  const at$4 = $at(list$1, 0);
  list$1 = ys$3;
  o$6[at$4] = (o$6[at$4] + 1) | 0;
  console.log(
    `[${xs$3.map((item) => String(item)).join(", ")}] [${ys$3.map((item) => String(item)).join(", ")}]`,
  );
  const nodes = [{ count: 1 }, { count: 2 }];
  let j = 1;
  const item = $index(nodes, j);
  j = 0;
  item.count = Math.imul(item.count, 7);
  console.log(`${$index(nodes, 0).count} ${$index(nodes, 1).count} ${j}`);
  const grid = [
    [1, 2],
    [3, 4],
  ];
  const [row, col] = [1, 0];
  const items = $index(grid, row);
  const at$5 = $at(items, col);
  items[at$5] = 30;
  console.log(
    `[${grid.map((item) => `[${item.map((item) => String(item)).join(", ")}]`).join(", ")}]`,
  );
  let z = 1;
  z = (z + 1) | 0;
  z = (z + 1) | 0;
  console.log(`${z}`);
}
//# sourceMappingURL=case.js.map
