// Generated by rust-js from test/corpus/mut_ref_kept.rs. Do not edit.

import { $at, $index } from "@rust-js/runtime";

var $refMutI32Bump;

export function entry() {
  main();
}

function gridIndexUsize_index(grid, i) {
  return $index(grid[0], i);
}

function gridIndexMutUsize_index_mut(grid, i) {
  const at = $at(grid[0], i);
  return {
    get value() {
      return grid[0][at];
    },
    set value(value) {
      grid[0][at] = value;
    },
  };
}

const Counter = {
  get_mut(counter) {
    return {
      get value() {
        return counter.n;
      },
      set value(value) {
        counter.n = value;
      },
    };
  },
};

function refMutI32Bump() {
  if ($refMutI32Bump === undefined) {
    $refMutI32Bump = { bump: refMutI32Bump_bump };
  }
  return $refMutI32Bump;
}

function refMutI32Bump_bump(self) {
  self.value = (self.value + 1) | 0;
}

function go(t, TBump) {
  TBump.bump(t);
}

function main() {
  const g = [[1, 2, 3]];
  const cell = gridIndexMutUsize_index_mut(g, 1);
  cell.value = 20;
  const cell$1 = gridIndexMutUsize_index_mut(g, 2);
  cell$1.value = (cell$1.value + 5) >>> 0;
  console.log(
    `${gridIndexUsize_index(g, 0)} ${gridIndexUsize_index(g, 1)} ${gridIndexUsize_index(g, 2)}`,
  );
  const c = { n: 1 };
  const cell$2 = Counter.get_mut(c);
  cell$2.value = (cell$2.value + 41) | 0;
  const n = Counter.get_mut(c);
  n.value = Math.imul(n.value, 2);
  console.log(`${c.n}`);
  let a = 1;
  const h = {
    r: {
      get value() {
        return a;
      },
      set value(value) {
        a = value;
      },
    },
  };
  h.r.value = 4;
  console.log(`${a}`);
  let b = 1;
  go(
    {
      get value() {
        return b;
      },
      set value(value) {
        b = value;
      },
    },
    refMutI32Bump(),
  );
  console.log(`${b}`);
}
//# sourceMappingURL=case.js.map
