// Generated by rust-js from test/corpus/mut_ref_loop.rs. Do not edit.

import { $at, $debugF64, $debugStr, $sliceEnd } from "@rust-js/runtime";

function main() {
  const ints = [1, 2, 3];
  for (let i = 0; i < ints.length; i++) {
    ints[i] = (ints[i] + 22) | 0;
  }
  console.log(`[${ints.map((item) => String(item)).join(", ")}]`);
  const halves = [1.5, 2.5];
  for (let i$1 = 0; i$1 < halves.length; i$1++) {
    halves[i$1] = halves[i$1] * 2;
  }
  console.log(`[${halves.map((item) => $debugF64(item)).join(", ")}]`);
  const counts = [1, 2];
  for (let i$2 = 0; i$2 < counts.length; i$2++) {
    counts[i$2] = (counts[i$2] * 200) & 255;
  }
  console.log(`[${counts.map((item) => String(item)).join(", ")}]`);
  const words = ["a", "b"];
  for (let i$3 = 0; i$3 < words.length; i$3++) {
    words[i$3] = words[i$3] + "!";
  }
  console.log(`[${words.map((item) => $debugStr(item)).join(", ")}]`);
  const end = $sliceEnd(ints, 1);
  for (let i$4 = 1; i$4 < end; i$4++) {
    ints[i$4] = 0;
  }
  console.log(`[${ints.map((item) => String(item)).join(", ")}]`);
  const ns = [1, 2, 3, 4];
  const end$1 = $sliceEnd(ns, 1, 3);
  for (let i$5 = 1; i$5 < end$1; i$5++) {
    ns[i$5] = -ns[i$5] | 0;
  }
  const end$2 = $sliceEnd(ns, 0, 1);
  for (let i$6 = 0; i$6 < end$2; i$6++) {
    ns[i$6] = 9;
  }
  console.log(`[${ns.map((item) => String(item)).join(", ")}]`);
  const v = [1, 2, 3, 4, 5];
  for (let i$7 = 0; i$7 < v.length; i$7++) {
    if (v[i$7] % 2 === 0) {
      continue;
    }
    v[i$7] = Math.imul(v[i$7], 10);
    if (v[i$7] > 20) {
      break;
    }
  }
  console.log(`[${v.map((item) => String(item)).join(", ")}]`);
  const a = [1, 2];
  const b = [10, 20];
  let cur = a;
  const items = cur;
  for (let i$8 = 0; i$8 < items.length; i$8++) {
    cur = b;
    items[i$8] = (items[i$8] + 1) | 0;
    break;
  }
  cur[$at(cur, 0)] = (cur[$at(cur, 0)] + 5) | 0;
  console.log(
    `[${a.map((item) => String(item)).join(", ")}] [${b.map((item) => String(item)).join(", ")}]`,
  );
  let [a$1, b$1] = [
    [1, 2],
    [10, 20],
  ];
  const h = { list: a$1 };
  const items$1 = h.list;
  for (let i$9 = 0; i$9 < items$1.length; i$9++) {
    h.list = b$1;
    items$1[i$9] = (items$1[i$9] + 1) | 0;
    break;
  }
  h.list[$at(h.list, 0)] = (h.list[$at(h.list, 0)] + 5) | 0;
  console.log(
    `[${a$1.map((item) => String(item)).join(", ")}] [${b$1.map((item) => String(item)).join(", ")}]`,
  );
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
