// Generated by rust-js from test/corpus/mut_number_handles.rs. Do not edit.

export function entry() {
  main();
}

function pick(takeFirst, a, b) {
  return takeFirst ? a : b;
}

function main() {
  let [a, b] = [1, 2];
  const result = pick(
    true,
    {
      get value() {
        return a;
      },
      set value(value) {
        a = value;
      },
    },
    {
      get value() {
        return b;
      },
      set value(value) {
        b = value;
      },
    },
  );
  result.value = (result.value + 10) >>> 0;
  const result$1 = pick(
    false,
    {
      get value() {
        return a;
      },
      set value(value) {
        a = value;
      },
    },
    {
      get value() {
        return b;
      },
      set value(value) {
        b = value;
      },
    },
  );
  result$1.value = (result$1.value + 20) >>> 0;
  const h = {
    count: {
      get value() {
        return a;
      },
      set value(value) {
        a = value;
      },
    },
  };
  h.count.value = Math.imul(h.count.value, 2) >>> 0;
  const r =
    a > 5
      ? {
          get value() {
            return a;
          },
          set value(value) {
            a = value;
          },
        }
      : {
          get value() {
            return b;
          },
          set value(value) {
            b = value;
          },
        };
  r.value = (r.value + 1) >>> 0;
  console.log(`${a} ${b}`);
}
//# sourceMappingURL=case.js.map
