// Generated by rust-js from test/corpus/mut_ref_handle.rs. Do not edit.

import { $at, $debugStr } from "@rust-js/runtime";

function pick(takeFirst, a, b) {
  return takeFirst ? a : b;
}

function first(v) {
  const at = $at(v, 0);
  return {
    get value() {
      return v[at];
    },
    set value(value) {
      v[at] = value;
    },
  };
}

function main() {
  let drops = 0;
  for (let i = 0; i < 2; i++) {
    const _c = [
      {
        get value() {
          return drops;
        },
        set value(value) {
          drops = value;
        },
      },
    ];
    counterDrop_drop(_c);
  }
  console.log(`${drops}`);
  let n = 1;
  let s = "a";
  const p = {
    left: {
      get value() {
        return n;
      },
      set value(value) {
        n = value;
      },
    },
    right: {
      get value() {
        return s;
      },
      set value(value) {
        s = value;
      },
    },
  };
  p.left.value = (p.left.value + 10) | 0;
  p.right.value += "b";
  console.log(`${p.left.value} ${$debugStr(p.right.value)}`);
  console.log(`${n} ${s}`);
  let [a, b] = [1, 2];
  for (const take of [true, false]) {
    const r = take
      ? {
          get value() {
            return a;
          },
          set value(value) {
            a = value;
          },
        }
      : {
          get value() {
            return b;
          },
          set value(value) {
            b = value;
          },
        };
    r.value = Math.imul(r.value, 10);
  }
  console.log(`${a} ${b}`);
  let [x, y] = [0, 0];
  let cur = {
    get value() {
      return x;
    },
    set value(value) {
      x = value;
    },
  };
  cur.value = (cur.value + 1) | 0;
  cur = {
    get value() {
      return y;
    },
    set value(value) {
      y = value;
    },
  };
  cur.value = (cur.value + 5) | 0;
  console.log(`${cur.value}`);
  console.log(`${x} ${y}`);
  let m = 3;
  const o = {
    get value() {
      return m;
    },
    set value(value) {
      m = value;
    },
  };
  if (o != null) {
    o.value = (o.value + 1) | 0;
  }
  console.log(`${m}`);
  let [i$1, j] = [1, 2];
  const refs = [
    {
      get value() {
        return i$1;
      },
      set value(value) {
        i$1 = value;
      },
    },
    {
      get value() {
        return j;
      },
      set value(value) {
        j = value;
      },
    },
  ];
  for (const r$1 of refs) {
    r$1.value = Math.imul(r$1.value, 7);
  }
  console.log(`${i$1} ${j}`);
  let [u, w] = [5, 6];
  const result = pick(
    false,
    {
      get value() {
        return u;
      },
      set value(value) {
        u = value;
      },
    },
    {
      get value() {
        return w;
      },
      set value(value) {
        w = value;
      },
    },
  );
  result.value = 60;
  const result$1 = pick(
    true,
    {
      get value() {
        return u;
      },
      set value(value) {
        u = value;
      },
    },
    {
      get value() {
        return w;
      },
      set value(value) {
        w = value;
      },
    },
  );
  const got = result$1;
  got.value = (got.value + 1) | 0;
  console.log(`${u} ${w}`);
  const v = [1, 2];
  const cell = first(v);
  cell.value = 9;
  console.log(`[${v.map((item) => String(item)).join(", ")}]`);
}

export function entry() {
  main();
}

function counterDrop_drop(counter) {
  counter[0].value = (counter[0].value + 1) | 0;
}
//# sourceMappingURL=case.js.map
