// Generated by rust-js from test/corpus/nested_type_chain.rs. Do not edit.

function main() {
  const deep = { TAG: "Second", _0: "Empty" };
  const top = { TAG: "Third", _0: { TAG: "First", _0: { TAG: "Fourth", _0: undefined } } };
  console.log(`${c19Debug_fmt(deep)} ${c2Debug_fmt(top)} ${deep.TAG === "Second"}`);
}

export function entry() {
  main();
}

function c0Debug_fmt(c0) {
  if (c0 === "Empty") {
    return "Empty";
  } else if (c0.TAG === "First") {
    return "First(())";
  } else if (c0.TAG === "Second") {
    return "Second(())";
  } else if (c0.TAG === "Third") {
    return "Third(())";
  } else {
    return "Fourth(())";
  }
}

function c1Debug_fmt(c1) {
  if (c1 === "Empty") {
    return "Empty";
  } else if (c1.TAG === "First") {
    return `First(${c0Debug_fmt(c1._0)})`;
  } else if (c1.TAG === "Second") {
    return `Second(${c0Debug_fmt(c1._0)})`;
  } else if (c1.TAG === "Third") {
    return `Third(${c0Debug_fmt(c1._0)})`;
  } else {
    return `Fourth(${c0Debug_fmt(c1._0)})`;
  }
}

function c2Debug_fmt(c2) {
  if (c2 === "Empty") {
    return "Empty";
  } else if (c2.TAG === "First") {
    return `First(${c1Debug_fmt(c2._0)})`;
  } else if (c2.TAG === "Second") {
    return `Second(${c1Debug_fmt(c2._0)})`;
  } else if (c2.TAG === "Third") {
    return `Third(${c1Debug_fmt(c2._0)})`;
  } else {
    return `Fourth(${c1Debug_fmt(c2._0)})`;
  }
}

function c3Debug_fmt(c3) {
  if (c3 === "Empty") {
    return "Empty";
  } else if (c3.TAG === "First") {
    return `First(${c2Debug_fmt(c3._0)})`;
  } else if (c3.TAG === "Second") {
    return `Second(${c2Debug_fmt(c3._0)})`;
  } else if (c3.TAG === "Third") {
    return `Third(${c2Debug_fmt(c3._0)})`;
  } else {
    return `Fourth(${c2Debug_fmt(c3._0)})`;
  }
}

function c4Debug_fmt(c4) {
  if (c4 === "Empty") {
    return "Empty";
  } else if (c4.TAG === "First") {
    return `First(${c3Debug_fmt(c4._0)})`;
  } else if (c4.TAG === "Second") {
    return `Second(${c3Debug_fmt(c4._0)})`;
  } else if (c4.TAG === "Third") {
    return `Third(${c3Debug_fmt(c4._0)})`;
  } else {
    return `Fourth(${c3Debug_fmt(c4._0)})`;
  }
}

function c5Debug_fmt(c5) {
  if (c5 === "Empty") {
    return "Empty";
  } else if (c5.TAG === "First") {
    return `First(${c4Debug_fmt(c5._0)})`;
  } else if (c5.TAG === "Second") {
    return `Second(${c4Debug_fmt(c5._0)})`;
  } else if (c5.TAG === "Third") {
    return `Third(${c4Debug_fmt(c5._0)})`;
  } else {
    return `Fourth(${c4Debug_fmt(c5._0)})`;
  }
}

function c6Debug_fmt(c6) {
  if (c6 === "Empty") {
    return "Empty";
  } else if (c6.TAG === "First") {
    return `First(${c5Debug_fmt(c6._0)})`;
  } else if (c6.TAG === "Second") {
    return `Second(${c5Debug_fmt(c6._0)})`;
  } else if (c6.TAG === "Third") {
    return `Third(${c5Debug_fmt(c6._0)})`;
  } else {
    return `Fourth(${c5Debug_fmt(c6._0)})`;
  }
}

function c7Debug_fmt(c7) {
  if (c7 === "Empty") {
    return "Empty";
  } else if (c7.TAG === "First") {
    return `First(${c6Debug_fmt(c7._0)})`;
  } else if (c7.TAG === "Second") {
    return `Second(${c6Debug_fmt(c7._0)})`;
  } else if (c7.TAG === "Third") {
    return `Third(${c6Debug_fmt(c7._0)})`;
  } else {
    return `Fourth(${c6Debug_fmt(c7._0)})`;
  }
}

function c8Debug_fmt(c8) {
  if (c8 === "Empty") {
    return "Empty";
  } else if (c8.TAG === "First") {
    return `First(${c7Debug_fmt(c8._0)})`;
  } else if (c8.TAG === "Second") {
    return `Second(${c7Debug_fmt(c8._0)})`;
  } else if (c8.TAG === "Third") {
    return `Third(${c7Debug_fmt(c8._0)})`;
  } else {
    return `Fourth(${c7Debug_fmt(c8._0)})`;
  }
}

function c9Debug_fmt(c9) {
  if (c9 === "Empty") {
    return "Empty";
  } else if (c9.TAG === "First") {
    return `First(${c8Debug_fmt(c9._0)})`;
  } else if (c9.TAG === "Second") {
    return `Second(${c8Debug_fmt(c9._0)})`;
  } else if (c9.TAG === "Third") {
    return `Third(${c8Debug_fmt(c9._0)})`;
  } else {
    return `Fourth(${c8Debug_fmt(c9._0)})`;
  }
}

function c10Debug_fmt(c10) {
  if (c10 === "Empty") {
    return "Empty";
  } else if (c10.TAG === "First") {
    return `First(${c9Debug_fmt(c10._0)})`;
  } else if (c10.TAG === "Second") {
    return `Second(${c9Debug_fmt(c10._0)})`;
  } else if (c10.TAG === "Third") {
    return `Third(${c9Debug_fmt(c10._0)})`;
  } else {
    return `Fourth(${c9Debug_fmt(c10._0)})`;
  }
}

function c11Debug_fmt(c11) {
  if (c11 === "Empty") {
    return "Empty";
  } else if (c11.TAG === "First") {
    return `First(${c10Debug_fmt(c11._0)})`;
  } else if (c11.TAG === "Second") {
    return `Second(${c10Debug_fmt(c11._0)})`;
  } else if (c11.TAG === "Third") {
    return `Third(${c10Debug_fmt(c11._0)})`;
  } else {
    return `Fourth(${c10Debug_fmt(c11._0)})`;
  }
}

function c12Debug_fmt(c12) {
  if (c12 === "Empty") {
    return "Empty";
  } else if (c12.TAG === "First") {
    return `First(${c11Debug_fmt(c12._0)})`;
  } else if (c12.TAG === "Second") {
    return `Second(${c11Debug_fmt(c12._0)})`;
  } else if (c12.TAG === "Third") {
    return `Third(${c11Debug_fmt(c12._0)})`;
  } else {
    return `Fourth(${c11Debug_fmt(c12._0)})`;
  }
}

function c13Debug_fmt(c13) {
  if (c13 === "Empty") {
    return "Empty";
  } else if (c13.TAG === "First") {
    return `First(${c12Debug_fmt(c13._0)})`;
  } else if (c13.TAG === "Second") {
    return `Second(${c12Debug_fmt(c13._0)})`;
  } else if (c13.TAG === "Third") {
    return `Third(${c12Debug_fmt(c13._0)})`;
  } else {
    return `Fourth(${c12Debug_fmt(c13._0)})`;
  }
}

function c14Debug_fmt(c14) {
  if (c14 === "Empty") {
    return "Empty";
  } else if (c14.TAG === "First") {
    return `First(${c13Debug_fmt(c14._0)})`;
  } else if (c14.TAG === "Second") {
    return `Second(${c13Debug_fmt(c14._0)})`;
  } else if (c14.TAG === "Third") {
    return `Third(${c13Debug_fmt(c14._0)})`;
  } else {
    return `Fourth(${c13Debug_fmt(c14._0)})`;
  }
}

function c15Debug_fmt(c15) {
  if (c15 === "Empty") {
    return "Empty";
  } else if (c15.TAG === "First") {
    return `First(${c14Debug_fmt(c15._0)})`;
  } else if (c15.TAG === "Second") {
    return `Second(${c14Debug_fmt(c15._0)})`;
  } else if (c15.TAG === "Third") {
    return `Third(${c14Debug_fmt(c15._0)})`;
  } else {
    return `Fourth(${c14Debug_fmt(c15._0)})`;
  }
}

function c16Debug_fmt(c16) {
  if (c16 === "Empty") {
    return "Empty";
  } else if (c16.TAG === "First") {
    return `First(${c15Debug_fmt(c16._0)})`;
  } else if (c16.TAG === "Second") {
    return `Second(${c15Debug_fmt(c16._0)})`;
  } else if (c16.TAG === "Third") {
    return `Third(${c15Debug_fmt(c16._0)})`;
  } else {
    return `Fourth(${c15Debug_fmt(c16._0)})`;
  }
}

function c17Debug_fmt(c17) {
  if (c17 === "Empty") {
    return "Empty";
  } else if (c17.TAG === "First") {
    return `First(${c16Debug_fmt(c17._0)})`;
  } else if (c17.TAG === "Second") {
    return `Second(${c16Debug_fmt(c17._0)})`;
  } else if (c17.TAG === "Third") {
    return `Third(${c16Debug_fmt(c17._0)})`;
  } else {
    return `Fourth(${c16Debug_fmt(c17._0)})`;
  }
}

function c18Debug_fmt(c18) {
  if (c18 === "Empty") {
    return "Empty";
  } else if (c18.TAG === "First") {
    return `First(${c17Debug_fmt(c18._0)})`;
  } else if (c18.TAG === "Second") {
    return `Second(${c17Debug_fmt(c18._0)})`;
  } else if (c18.TAG === "Third") {
    return `Third(${c17Debug_fmt(c18._0)})`;
  } else {
    return `Fourth(${c17Debug_fmt(c18._0)})`;
  }
}

function c19Debug_fmt(c19) {
  if (c19 === "Empty") {
    return "Empty";
  } else if (c19.TAG === "First") {
    return `First(${c18Debug_fmt(c19._0)})`;
  } else if (c19.TAG === "Second") {
    return `Second(${c18Debug_fmt(c19._0)})`;
  } else if (c19.TAG === "Third") {
    return `Third(${c18Debug_fmt(c19._0)})`;
  } else {
    return `Fourth(${c18Debug_fmt(c19._0)})`;
  }
}
//# sourceMappingURL=case.js.map
