// Generated by rust-js from test/corpus/nested_element_writes.rs. Do not edit.

import { $at, $index } from "@rust-js/runtime";

function main() {
  let grid = [
    [0, 0, 0],
    [0, 0, 0],
  ];
  const row = grid[0].slice();
  grid[0][1] = 5;
  grid[1][2] = (grid[1][2] + 7) | 0;
  console.log(
    `[${grid.map((item) => `[${item.map((item) => String(item)).join(", ")}]`).join(", ")}] [${row.map((item) => String(item)).join(", ")}]`,
  );
  let rows = [
    [0, 0],
    [0, 0],
  ];
  $index(rows, 1)[0] = 3;
  console.log(
    `[${rows.map((item) => `[${item.map((item) => String(item)).join(", ")}]`).join(", ")}]`,
  );
  let cells = [[{ value: 1 }, { value: 2 }]];
  cells[0][1].value = Math.imul(cells[0][1].value, 10);
  console.log(
    `[${cells.map((item) => `[${item.map((item) => cellDebug_fmt(item)).join(", ")}]`).join(", ")}]`,
  );
  const i = 1;
  let deep = [
    [
      [0, 0],
      [0, 0],
    ],
    [
      [0, 0],
      [0, 0],
    ],
  ];
  const items = $index(deep, i)[0];
  items[$at(items, i)] = 9;
  console.log(
    `[${deep.map((item) => `[${item.map((item) => `[${item.map((item) => String(item)).join(", ")}]`).join(", ")}]`).join(", ")}] ${deep[1][0][1]}`,
  );
}

export function entry() {
  main();
}

function cellDebug_fmt(cell) {
  return `Cell { value: ${cell.value} }`;
}
//# sourceMappingURL=case.js.map
