// Generated by rust-js from test/corpus/opaque_iterators.rs. Do not edit.

import { $iter, $max, $next, $position, $range } from "@rust-js/runtime";

function tens(v) {
  return v.map((x) => Math.imul(x, 10));
}

function evens(n) {
  return $range(0, n).filter((x) => x % 2 === 0);
}

function main() {
  const v = [1, 2, 3];
  const arg = tens(v)[0];
  const arg$1 = tens(v)[1];
  const arg$2 = tens(v)[5];
  console.log(
    `${arg == null ? "None" : `Some(${arg})`} ${arg$1 == null ? "None" : `Some(${arg$1})`} ${arg$2 == null ? "None" : `Some(${arg$2})`}`,
  );
  console.log(`${tens(v).some((x) => x > 25)} ${tens(v).every((x) => x > 5)}`);
  const arg$3 = tens(v).find((x) => x > 15);
  const arg$4 = $position(tens(v), (x) => x === 20);
  console.log(
    `${arg$3 == null ? "None" : `Some(${arg$3})`} ${arg$4 == null ? "None" : `Some(${arg$4})`}`,
  );
  const arg$5 = $max(tens(v));
  const arg$6 = tens(v).length;
  const arg$7 = tens(v).at(-1);
  console.log(
    `${arg$5 == null ? "None" : `Some(${arg$5})`} ${arg$6} ${arg$7 == null ? "None" : `Some(${arg$7})`}`,
  );
  let kept = $iter(tens(v));
  const arg$8 = $next(kept);
  const arg$9 = $next(kept);
  console.log(
    `${arg$8 == null ? "None" : `Some(${arg$8})`} ${arg$9 == null ? "None" : `Some(${arg$9})`}`,
  );
  const arg$10 = evens(7)[0];
  const arg$11 = evens(7).find((x) => x > 2);
  console.log(
    `${arg$10 == null ? "None" : `Some(${arg$10})`} ${arg$11 == null ? "None" : `Some(${arg$11})`}`,
  );
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
