// Generated by rust-js from test/corpus/operands_before_replace.rs. Do not edit.

export function entry() {
  main();
}

const HITS = { value: 1 };

function main() {
  let x = 1;
  const tmp = (x + 0) >>> 0;
  const old = x;
  x = 5;
  console.log(`${tmp} ${old}`);
  console.log(`${x}`);
  const tmp$1 = HITS.value;
  const previous = HITS.value;
  HITS.value = (previous + 10) >>> 0;
  console.log(`${tmp$1} ${previous}`);
  console.log(`${HITS.value}`);
}
//# sourceMappingURL=case.js.map
