// Generated by rust-js from test/corpus/option_rest_pattern.rs. Do not edit.

function main() {
  const none = undefined;
  const some = 3;
  if (none != null) {
    console.log("None matched Some(..)");
  }
  if (some != null) {
    console.log("Some matched Some(..)");
  }
  for (const value of [none, some]) {
    const name = value != null ? "some" : "none";
    console.log(`${name} ${value != null}`);
  }
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
