// Generated by rust-js from test/corpus/option_as_deref.rs. Do not edit.

export function entry() {
  main();
}

function path_is(path, want) {
  return path == want;
}

function first(items) {
  return items != null ? items[0] : undefined;
}

function main() {
  console.log(
    `${path_is("/learn", "/learn")} ${path_is("/a", "/learn")} ${path_is(undefined, "/learn")}`,
  );
  const arg = first([4, 5]);
  const arg$1 = first([]);
  const arg$2 = first(undefined);
  console.log(
    `${arg == null ? "None" : `Some(${arg})`} ${arg$1 == null ? "None" : `Some(${arg$1})`} ${arg$2 == null ? "None" : `Some(${arg$2})`}`,
  );
}
//# sourceMappingURL=case.js.map
