// Generated by rust-js from test/corpus/pin_box.rs. Do not edit.

import { $byteLen, $cmp, $cmpItems, $eq } from "@rust-js/runtime";

var $anyPartialEq;

export function entry() {
  main();
}

const Counter = {
  bump(pin) {
    const this$ = pin;
    this$.count = (this$.count + 1) >>> 0;
    return this$.count;
  },
};

function noisyDrop_drop(noisy) {
  console.log(`drop ${noisy[0]}`);
}

export function anyPartialEq() {
  if ($anyPartialEq === undefined) {
    $anyPartialEq = { eq: anyPartialEq_eq };
  }
  return $anyPartialEq;
}

function anyPartialEq_eq(any, _) {
  console.log("any ==");
  return true;
}

function total(numbers) {
  return numbers.reduce((a, b) => (a + b) | 0, 0);
}

function main() {
  let pinned = 5;
  console.log(`${(pinned + 1) | 0}`);
  pinned = 6;
  console.log(`${pinned} ${pinned}`);
  const counter = { count: 0 };
  Counter.bump(counter);
  console.log(`${Counter.bump(counter)} ${counter.count}`);
  const list = [1, 2, 3];
  console.log(`${total(list)}`);
  const boxed = "pinned";
  const text = boxed;
  console.log(`${text} ${$byteLen(text)}`);
  let number = 7;
  const pin = {
    get value() {
      return number;
    },
    set value(value) {
      number = value;
    },
  };
  pin.value = (pin.value + 1) | 0;
  pin.value = Math.imul(pin.value, 2);
  console.log(`${number}`);
  const pair = { count: 1, name: "pair" };
  const name = pair.name;
  console.log(`${$byteLen(name)}`);
  const count = {
    get value() {
      return pair.count;
    },
    set value(value) {
      pair.count = value;
    },
  };
  count.value = (count.value + 9) >>> 0;
  console.log(`${pair.count} ${pair.name}`);
  let seven = 7;
  const shown = {
    get value() {
      return seven;
    },
    set value(value) {
      seven = value;
    },
  };
  console.log(`${shown.value} ${shown.value}`);
  const [a, b] = [
    [1, 2],
    [1, 3],
  ];
  const copy = a.slice();
  console.log(
    `${$eq(a, copy)} ${$cmpItems(a, b, $cmp) < 0} [${copy.map((item) => String(item)).join(", ")}]`,
  );
  const changed = a.slice();
  changed.push(9);
  console.log(
    `[${a.map((item) => String(item)).join(", ")}] [${changed.map((item) => String(item)).join(", ")}]`,
  );
  const _noisy = [1];
  try {
    console.log("pinned");
  } finally {
    noisyDrop_drop(_noisy);
  }
  console.log(`${anyPartialEq_eq(undefined)} ${anyPartialEq_eq(undefined)}`);
  console.log("end");
}
//# sourceMappingURL=case.js.map
