// Generated by rust-js from test/corpus/prepared_places.rs. Do not edit.

import { $orInsert, $unwrap } from "@rust-js/runtime";

function key(log) {
  log.push(1);
  return 0;
}

function value(log) {
  log.push(2);
  return 3;
}

function slots(take) {
  let map = new Map();
  map.set(0, 1);
  let n = map.get(0);
  if (n != null) {
    let tmp;
    if (take) {
      const next = (n + 3) | 0;
      tmp = next;
    } else {
      const next$1 = (n + 5) | 0;
      tmp = next$1;
    }
    n = tmp;
    map.set(0, n);
    n = (n + 2) | 0;
    map.set(0, n);
    const rhs = 3;
    n = (n + rhs) | 0;
    map.set(0, n);
  }
  console.log(`${$unwrap(map.get(0), "no entry found for key")}`);
}

function main() {
  slots(false);
  slots(true);
  let map = new Map();
  let log = [];
  const value$1 = value(log);
  const key$1 = key(log);
  const current = $orInsert(map, key$1, 10);
  map.set(key$1, (current + value$1) | 0);
  console.log(
    `[${log.map((item) => String(item)).join(", ")}] ${$unwrap(map.get(0), "no entry found for key")}`,
  );
  log.length = 0;
  const key$2 = key(log);
  const current$1 = $orInsert(map, key$2, 10);
  map.set(key$2, (current$1 + value(log)) | 0);
  console.log(
    `[${log.map((item) => String(item)).join(", ")}] ${$unwrap(map.get(0), "no entry found for key")}`,
  );
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
