// Generated by rust-js from test/corpus/pretty_debug.rs. Do not edit.

import {
  $cmp,
  $debugF64,
  $debugFields,
  $debugStr,
  $pretty,
  $sortedEntries,
  $traitImpl,
} from "@rust-js/runtime";

var $wrapDebug, $builtDebug, $listyDebug, $rawDebug, $asksDebug, $shownDisplay, $delegateDebug;

function pretty(value, TDebug) {
  return TDebug.fmt(value, { alternate: true });
}

function main() {
  console.log(
    `${$pretty(
      "[",
      [1, 2].map((item) => String(item)),
      "]",
    )} ${$pretty(
      "[",
      [].map((item) => String(item)),
      "]",
    )}`,
  );
  const arg = [["a", 1.5]];
  console.log(
    `${
      arg == null
        ? "None"
        : $pretty(
            "Some(",
            [
              $pretty(
                "[",
                arg.map((item) => $pretty("(", [$debugStr(item[0]), $debugF64(item[1])], ")")),
                "]",
              ),
            ],
            ")",
          )
    }`,
  );
  const arg$1 = [1, "x", undefined];
  const arg$2 = [7];
  console.log(
    `${$pretty(
      "(",
      [
        String(arg$1[0]),
        $debugStr(arg$1[1]),
        arg$1[2] == null ? "None" : $pretty("Some(", [String(arg$1[2])], ")"),
      ],
      ")",
    )} ${$pretty("(", [String(arg$2[0])], ")")}`,
  );
  const map = new Map();
  map.set("k", [1]);
  const failed = { TAG: "Err", _0: "bad" };
  console.log(
    `${$pretty(
      "{",
      Array.from($sortedEntries(map, $cmp)).map(
        ([key, value]) =>
          `${$debugStr(key)}: ${$pretty(
            "[",
            value.map((item) => (item == null ? "None" : $pretty("Some(", [String(item)], ")"))),
            "]",
          )}`,
      ),
      "}",
    )} ${$pretty(
      "RefCell {",
      [
        `value: ${$pretty(
          "[",
          { value: [1] }.value.map((item) => String(item)),
          "]",
        )}`,
      ],
      "}",
    )} ${failed.TAG === "Ok" ? $pretty("Ok(", [String(failed._0)], ")") : $pretty("Err(", [$debugStr(failed._0)], ")")}`,
  );
  console.log(`1..4 ${$debugStr("text")} [${[1].map((item) => String(item)).join(", ")}]`);
  const point = { x: 1, label: "a" };
  console.log(`${pointDebug_fmt(point, { alternate: true })}\n${pointDebug_fmt(point)}`);
  console.log(`${pairDebug_fmt([2, { x: 3, label: "b" }], { alternate: true })}`);
  console.log(
    `${$pretty(
      "[",
      [
        "Dot",
        { TAG: "Circle", r: 1.5 },
        { TAG: "Line", _0: { x: 0, label: "s" }, _1: { x: 9, label: "e" } },
      ].map((item) => shapeDebug_fmt(item, { alternate: true })),
      "]",
    )}`,
  );
  console.log(
    `${unitDebug_fmt(undefined, { alternate: true })} ${wideDebug_fmt(
      { a: 1, b: 2, c: 3, d: 4, e: 5, f: 6 },
      { alternate: true },
    )}`,
  );
  console.log(
    `${wrapDebug_fmt(
      { inner: 1, list: [2, 3] },
      { alternate: true },
      { fmt: (value, options) => String(value) },
    )}`,
  );
  console.log(
    `${builtDebug_fmt(
      { x: 1, tags: [2] },
      { alternate: true },
    )} ${listyDebug_fmt([[5]], { alternate: true })} ${listyDebug_fmt([[]], { alternate: true })}`,
  );
  console.log(
    `${rawDebug_fmt([4], { alternate: true })} ${rawDebug_fmt([4])} ${asksDebug_fmt(undefined, { alternate: true })} ${asksDebug_fmt(undefined)} ${shownDisplay_fmt([7], { alternate: true })} ${shownDisplay_fmt([7])}`,
  );
  console.log(`${delegateDebug_fmt([[9]], { alternate: true })}`);
  console.log(
    `${pretty([1, "a"], { fmt: (value, options) => (value == null ? "None" : options?.alternate ? $pretty("Some(", [options?.alternate ? $pretty("(", [String(value[0]), $debugStr(value[1])], ")") : `(${value[0]}, ${$debugStr(value[1])})`], ")") : `Some(${options?.alternate ? $pretty("(", [String(value[0]), $debugStr(value[1])], ")") : `(${value[0]}, ${$debugStr(value[1])})`})`) })}\n${pretty(
      { inner: [1], list: [] },
      wrapDebug(rawDebug()),
    )}`,
  );
  const kept = [1, undefined];
  console.error(`${pairDebug_fmt(kept, { alternate: true })}`);
  console.log(`${pairDebug_fmt(kept)}`);
}

export function entry() {
  main();
}

function pointDebug_fmt(point, options) {
  const shown = String(point.x);
  const shown$1 = $debugStr(point.label);
  return options?.alternate
    ? $pretty("Point {", [`x: ${shown}`, `label: ${shown$1}`], "}")
    : `Point { x: ${shown}, label: ${shown$1} }`;
}

function pairDebug_fmt(pair, options) {
  const shown = String(pair[0]);
  const shown$1 =
    pair[1] == null
      ? "None"
      : options?.alternate
        ? $pretty("Some(", [pointDebug_fmt(pair[1], options)], ")")
        : `Some(${pointDebug_fmt(pair[1], options)})`;
  return options?.alternate
    ? $pretty("Pair(", [shown, shown$1], ")")
    : `Pair(${shown}, ${shown$1})`;
}

function shapeDebug_fmt(shape, options) {
  let f = "";
  if (shape === "Dot") {
    f += "Dot";
  } else if (shape.TAG === "Circle") {
    const shown = $debugF64(shape.r);
    f += options?.alternate ? $pretty("Circle {", [`r: ${shown}`], "}") : `Circle { r: ${shown} }`;
  } else {
    const shown$1 = pointDebug_fmt(shape._0, options);
    const shown$2 = pointDebug_fmt(shape._1, options);
    f += options?.alternate
      ? $pretty("Line(", [shown$1, shown$2], ")")
      : `Line(${shown$1}, ${shown$2})`;
  }
  return f;
}

function unitDebug_fmt(unit, options) {
  return "Unit";
}

function wideDebug_fmt(wide, options) {
  const names = ["a", "b", "c", "d", "e", "f"];
  const values = [
    String(wide.a),
    String(wide.b),
    String(wide.c),
    String(wide.d),
    String(wide.e),
    String(wide.f),
  ];
  return $debugFields("Wide", names, values, options?.alternate);
}

function wrapDebug_fmt(wrap, options, TDebug) {
  const shown = TDebug.fmt(wrap.inner, options);
  const shown$1 = options?.alternate
    ? $pretty(
        "[",
        wrap.list.map((item) => TDebug.fmt(item, options)),
        "]",
      )
    : `[${wrap.list.map((item) => TDebug.fmt(item, options)).join(", ")}]`;
  return options?.alternate
    ? $pretty("Wrap {", [`inner: ${shown}`, `list: ${shown$1}`], "}")
    : `Wrap { inner: ${shown}, list: ${shown$1} }`;
}

function builtDebug_fmt(built, options) {
  return options?.alternate
    ? $pretty(
        "Built {",
        [
          `x: ${built.x}`,
          `tags: ${
            options?.alternate
              ? $pretty(
                  "[",
                  built.tags.map((item) => String(item)),
                  "]",
                )
              : `[${built.tags.map((item) => String(item)).join(", ")}]`
          }`,
        ],
        "}",
        true,
      )
    : `Built { x: ${built.x}, tags: ${
        options?.alternate
          ? $pretty(
              "[",
              built.tags.map((item) => String(item)),
              "]",
            )
          : `[${built.tags.map((item) => String(item)).join(", ")}]`
      }, .. }`;
}

function listyDebug_fmt(listy, options) {
  return options?.alternate
    ? $pretty("[", ["0"].concat(Array.from(listy[0], (entry) => String(entry))), "]")
    : `[${["0"].concat(Array.from(listy[0], (entry) => String(entry))).join(", ")}]`;
}

function rawDebug_fmt(raw, options) {
  return `[${raw[0]} [${[raw[0]].map((item) => String(item)).join(", ")}]]`;
}

function asksDebug_fmt(asks, options) {
  if (options?.alternate === true) {
    return "pretty";
  }
  return "plain";
}

function shownDisplay_fmt(shown, options) {
  if (options?.alternate === true) {
    return `#${shown[0]}`;
  }
  return String(shown[0]);
}

function delegateDebug_fmt(delegate, options) {
  return options?.alternate
    ? $pretty(
        "[",
        delegate[0].map((item) => String(item)),
        "]",
      )
    : `[${delegate[0].map((item) => String(item)).join(", ")}]`;
}

export function wrapDebug(TDebug) {
  if ($wrapDebug === undefined) {
    $wrapDebug = new WeakMap();
  }
  return $traitImpl($wrapDebug, [TDebug], () => ({
    fmt: (arg0, arg1) => wrapDebug_fmt(arg0, arg1, TDebug),
  }));
}

export function builtDebug() {
  if ($builtDebug === undefined) {
    $builtDebug = { fmt: builtDebug_fmt };
  }
  return $builtDebug;
}

export function listyDebug() {
  if ($listyDebug === undefined) {
    $listyDebug = { fmt: listyDebug_fmt };
  }
  return $listyDebug;
}

export function rawDebug() {
  if ($rawDebug === undefined) {
    $rawDebug = { fmt: rawDebug_fmt };
  }
  return $rawDebug;
}

export function asksDebug() {
  if ($asksDebug === undefined) {
    $asksDebug = { fmt: asksDebug_fmt };
  }
  return $asksDebug;
}

export function shownDisplay() {
  if ($shownDisplay === undefined) {
    $shownDisplay = { fmt: shownDisplay_fmt };
  }
  return $shownDisplay;
}

export function delegateDebug() {
  if ($delegateDebug === undefined) {
    $delegateDebug = { fmt: delegateDebug_fmt };
  }
  return $delegateDebug;
}
//# sourceMappingURL=case.js.map
