// Generated by rust-js from test/corpus/radix_negative.rs. Do not edit.

export function entry() {
  main();
}

function show(a, b, c, d) {
  console.log(
    `${(a & 255).toString(16)} ${(b & 65535).toString(16)} ${(c >>> 0).toString(16)} ${BigInt.asUintN(64, d).toString(16)}`,
  );
  console.log(
    `0x${BigInt.asUintN(64, d).toString(16)} 0x${BigInt.asUintN(64, d).toString(16).toUpperCase()} ${BigInt.asUintN(64, d).toString(2)} ${BigInt.asUintN(64, d).toString(8)}`,
  );
  console.log(`${9223372036854775808n.toString(16)} 0x${18446744071562067968n.toString(16)}`);
}

function main() {
  show(-1, -2, -3, -4n);
  show(-128, -32768, -2147483648, -9223372036854775808n);
}
//# sourceMappingURL=case.js.map
