// Generated by rust-js from test/corpus/rc_counts.rs. Do not edit.

import {
  $debugStr,
  $downgrade,
  $intoInner,
  $makeMut,
  $rcClone,
  $rcDrop,
  $tryUnwrap,
  $unwrap,
  $unwrapOrClone,
  $upgrade,
  $weakCount,
  $weakDrop,
} from "@rust-js/runtime";

export function entry() {
  main();
}

function main() {
  const a = { value: 5, strong: 1, weak: 0 };
  let a$live = true;
  try {
    console.log(`${a.strong} ${a.weak}`);
    const b = $rcClone(a);
    let b$live = true;
    try {
      const c = $rcClone(a);
      try {
        console.log(`${a.strong} ${(c.value + b.value) | 0}`);
      } finally {
        $rcDrop(c);
      }
      console.log(`${a.strong} ${a === b}`);
      b$live = false;
      $rcDrop(b);
      console.log(`${a.strong}`);
      a$live = false;
      let a$1 = a;
      let a$1$live = true;
      try {
        const cell = $unwrap(a$1.strong === 1 && a$1.weak === 0 ? a$1 : undefined);
        cell.value = (cell.value + 1) | 0;
        const weak = $downgrade(a$1);
        try {
          const tmp = a$1.weak;
          const option = $upgrade(weak);
          let option$live = true;
          let map;
          let arg;
          try {
            option$live = false;
            map = (n) => {
              try {
                return n.value;
              } finally {
                $rcDrop(n);
              }
            };
            arg = option ? map(option) : undefined;
            console.log(`${tmp} ${arg == null ? "None" : `Some(${arg})`}`);
          } finally {
            if (option$live) {
              if (option != null) {
                $rcDrop(option);
              }
            }
          }
          const shared = $rcClone(a$1);
          let shared$live = true;
          try {
            const arg$1 = a$1.strong === 1 && a$1.weak === 0 ? a$1 : undefined;
            console.log(`${arg$1 == null ? "None" : `Some(${arg$1.value})`}`);
            a$1 = $makeMut(a$1);
            console.log(`${(a$1.value + 1) | 0}`);
            a$1 = $makeMut(a$1);
            a$1.value = (a$1.value + 10) | 0;
            console.log(`${a$1.value} ${shared.value} ${a$1 === shared}`);
            shared$live = false;
            const result = $tryUnwrap(shared);
            try {
              console.log(
                `${result.TAG === "Ok" ? `Ok(${result._0})` : `Err(${result._0.value})`}`,
              );
            } finally {
              if (result.TAG === "Err") {
                $rcDrop(result._0);
              }
            }
            const option$1 = $upgrade(weak);
            let tmp$1;
            let arg$2;
            try {
              tmp$1 = option$1;
              a$1$live = false;
              arg$2 = $intoInner(a$1);
              console.log(
                `${tmp$1 == null ? "None" : `Some(${tmp$1.value})`} ${arg$2 == null ? "None" : `Some(${arg$2})`}`,
              );
            } finally {
              if (option$1 != null) {
                $rcDrop(option$1);
              }
            }
            const option$2 = $upgrade(weak);
            try {
              console.log(
                `${option$2 == null ? "None" : `Some(${option$2.value})`} ${weak.strong} ${$weakCount(weak)}`,
              );
            } finally {
              if (option$2 != null) {
                $rcDrop(option$2);
              }
            }
            const refCell = { value: { strong: 0, weak: 0 } };
            let refCell$live = true;
            let leaf;
            try {
              refCell$live = false;
              leaf = {
                value: { name: "leaf", parent: refCell, children: { value: [] } },
                strong: 1,
                weak: 0,
              };
            } finally {
              if (refCell$live) {
                $weakDrop(refCell.value);
              }
            }
            try {
              const option$3 = $upgrade(leaf.value.parent.value);
              let option$3$live = true;
              let map$1;
              let arg$3;
              try {
                option$3$live = false;
                map$1 = (p) => {
                  try {
                    return p.value.name;
                  } finally {
                    const dropNode = (node) => {
                      $weakDrop(node.parent.value);
                      for (const item of node.children.value) {
                        $rcDrop(item, dropNode);
                      }
                    };
                    $rcDrop(p, dropNode);
                  }
                };
                arg$3 = option$3 ? map$1(option$3) : undefined;
                console.log(`${arg$3 == null ? "None" : `Some(${$debugStr(arg$3)})`}`);
              } finally {
                if (option$3$live) {
                  const dropNode = (node) => {
                    $weakDrop(node.parent.value);
                    for (const item of node.children.value) {
                      $rcDrop(item, dropNode);
                    }
                  };
                  if (option$3 != null) {
                    $rcDrop(option$3, dropNode);
                  }
                }
              }
              const refCell$1 = { value: { strong: 0, weak: 0 } };
              let refCell$1$live = true;
              let arg$4;
              let branch;
              try {
                arg$4 = { value: [$rcClone(leaf)] };
                refCell$1$live = false;
                branch = {
                  value: { name: "branch", parent: refCell$1, children: arg$4 },
                  strong: 1,
                  weak: 0,
                };
              } finally {
                if (refCell$1$live) {
                  $weakDrop(refCell$1.value);
                }
              }
              try {
                const next = $downgrade(branch);
                $weakDrop(leaf.value.parent.value);
                leaf.value.parent.value = next;
                const option$4 = $upgrade(leaf.value.parent.value);
                let option$4$live = true;
                let map$2;
                let arg$5;
                try {
                  option$4$live = false;
                  map$2 = (p) => {
                    try {
                      return p.value.name;
                    } finally {
                      const dropNode = (node) => {
                        $weakDrop(node.parent.value);
                        for (const item of node.children.value) {
                          $rcDrop(item, dropNode);
                        }
                      };
                      $rcDrop(p, dropNode);
                    }
                  };
                  arg$5 = option$4 ? map$2(option$4) : undefined;
                  console.log(
                    `${arg$5 == null ? "None" : `Some(${$debugStr(arg$5)})`} ${branch.strong} ${branch.weak} ${branch.value.children.value.length}`,
                  );
                } finally {
                  if (option$4$live) {
                    const dropNode$1 = (node$1) => {
                      $weakDrop(node$1.parent.value);
                      for (const item$1 of node$1.children.value) {
                        $rcDrop(item$1, dropNode$1);
                      }
                    };
                    if (option$4 != null) {
                      $rcDrop(option$4, dropNode$1);
                    }
                  }
                }
                console.log(`${leaf.strong}`);
              } finally {
                const dropNode$2 = (node$2) => {
                  $weakDrop(node$2.parent.value);
                  for (const item$2 of node$2.children.value) {
                    $rcDrop(item$2, dropNode$2);
                  }
                };
                $rcDrop(branch, dropNode$2);
              }
              const option$5 = $upgrade(leaf.value.parent.value);
              let option$5$live = true;
              let map$3;
              let arg$6;
              try {
                option$5$live = false;
                map$3 = (p) => {
                  try {
                    return p.value.name;
                  } finally {
                    const dropNode = (node) => {
                      $weakDrop(node.parent.value);
                      for (const item of node.children.value) {
                        $rcDrop(item, dropNode);
                      }
                    };
                    $rcDrop(p, dropNode);
                  }
                };
                arg$6 = option$5 ? map$3(option$5) : undefined;
                console.log(
                  `${arg$6 == null ? "None" : `Some(${$debugStr(arg$6)})`} ${leaf.strong}`,
                );
              } finally {
                if (option$5$live) {
                  const dropNode$3 = (node$3) => {
                    $weakDrop(node$3.parent.value);
                    for (const item$3 of node$3.children.value) {
                      $rcDrop(item$3, dropNode$3);
                    }
                  };
                  if (option$5 != null) {
                    $rcDrop(option$5, dropNode$3);
                  }
                }
              }
              const text = { value: "hi", strong: 1, weak: 0 };
              let text$live = true;
              try {
                const other = $rcClone(text);
                try {
                  text$live = false;
                  console.log(`${$unwrapOrClone(text)} ${other.strong}`);
                } finally {
                  $rcDrop(other);
                }
              } finally {
                if (text$live) {
                  $rcDrop(text);
                }
              }
            } finally {
              const dropNode$4 = (node$4) => {
                $weakDrop(node$4.parent.value);
                for (const item$4 of node$4.children.value) {
                  $rcDrop(item$4, dropNode$4);
                }
              };
              $rcDrop(leaf, dropNode$4);
            }
          } finally {
            if (shared$live) {
              $rcDrop(shared);
            }
          }
        } finally {
          $weakDrop(weak);
        }
      } finally {
        if (a$1$live) {
          $rcDrop(a$1);
        }
      }
    } finally {
      if (b$live) {
        $rcDrop(b);
      }
    }
  } finally {
    if (a$live) {
      $rcDrop(a);
    }
  }
}
//# sourceMappingURL=case.js.map
