// Generated by rust-js from test/corpus/refcell_unwind_releases.rs. Do not edit.

import { $tryBorrow, $unborrow, $withBorrowMut } from "@rust-js/runtime";

export function entry() {
  main();
}

const LOG = { value: [] };

function asksDrop_drop(self) {
  ((log) => {
    const result = $tryBorrow(log, true);
    try {
      console.log(`free as it unwinds: ${result.TAG === "Ok"}`);
    } finally {
      if (result.TAG === "Ok") {
        $unborrow(result._0);
      }
    }
  })(LOG);
}

function main() {
  const _asks = undefined;
  try {
    $withBorrowMut(LOG, (log) => {
      log.push(1);
      if (log.length === 1) {
        throw new Error("boom");
      }
    });
  } finally {
    asksDrop_drop({ value: _asks });
  }
}
//# sourceMappingURL=case.js.map
