// Generated by rust-js from test/corpus/refcell_borrows.rs. Do not edit.

import {
  $borrow,
  $borrowMut,
  $byteLen,
  $cellReplace,
  $debugParseError,
  $debugStr,
  $eq,
  $index,
  $showBorrowed,
  $tryBorrow,
  $unborrow,
} from "@rust-js/runtime";

export function entry() {
  main();
}

const Counter = {
  hit(counter) {
    const cell = $borrowMut(counter.hits);
    cell.value = (cell.value + 1) >>> 0;
    return $borrow(counter.hits).value;
  },
};

function main() {
  const cell = { value: [1, 2] };
  const a = $borrow(cell, true);
  try {
    const b = $borrow(cell, true);
    try {
      const tmp = a.value.length;
      const tmp$1 = $index(b.value, 0);
      const result = $tryBorrow(cell, true);
      try {
        console.log(`${tmp} ${tmp$1} ${result.TAG !== "Ok"}`);
      } finally {
        if (result.TAG === "Ok") {
          $unborrow(result._0);
        }
      }
    } finally {
      $unborrow(b);
    }
  } finally {
    $unborrow(a);
  }
  $borrowMut(cell).value.push(3);
  const writing = $borrowMut(cell, true);
  let writing$live = true;
  try {
    const result = $tryBorrow(cell);
    try {
      console.log(`${result.TAG !== "Ok"} ${writing.value.length}`);
    } finally {
      if (result.TAG === "Ok") {
        $unborrow(result._0);
      }
    }
    writing$live = false;
    $unborrow(writing);
    const result$1 = $tryBorrow(cell);
    let result$2$live = true;
    let map;
    let tmp;
    let result$2;
    try {
      result$2$live = false;
      map = (v) => {
        try {
          return v.value.length;
        } finally {
          $unborrow(v);
        }
      };
      tmp = result$1.TAG === "Ok" ? { TAG: "Ok", _0: map(result$1._0) } : result$1;
      result$2 = $tryBorrow(cell, true);
      try {
        console.log(
          `${tmp.TAG === "Ok" ? `Ok(${tmp._0})` : `Err(${$debugParseError(tmp._0, "BorrowError")})`} ${result$2.TAG === "Ok"}`,
        );
      } finally {
        if (result$2.TAG === "Ok") {
          $unborrow(result$2._0);
        }
      }
    } finally {
      if (result$2$live) {
        if (result$1.TAG === "Ok") {
          $unborrow(result$1._0);
        }
      }
    }
    const value = [7];
    const refMut = $borrowMut(cell, true);
    try {
      refMut.value = value;
    } finally {
      $unborrow(refMut);
    }
    const number = { value: 1 };
    const cell$1 = $borrowMut(number);
    cell$1.value = 5;
    const text = { value: "" };
    const cell$2 = $borrowMut(text);
    cell$2.value = "t";
    console.log(
      `[${$borrow(cell)
        .value.map((item) => String(item))
        .join(", ")}] ${$borrow(number).value} ${$borrow(text).value}`,
    );
    const grid = { value: [1, 2, 3] };
    $borrowMut(grid).value[0] = 3;
    const items = $borrowMut(grid).value;
    items[1] = (items[1] + 3) | 0;
    console.log(
      `[${$borrow(grid)
        .value.map((item) => String(item))
        .join(", ")}] ${$borrow(grid).value[2]}`,
    );
    const counter = { hits: { value: 0 } };
    Counter.hit(counter);
    console.log(`${Counter.hit(counter)}`);
    const shared = { value: "a" };
    const other = shared;
    const cell$3 = $borrowMut(other);
    cell$3.value += "b";
    for (let i = 0; i < 2; i++) {
      const cell = $borrowMut(shared);
      cell.value += "c";
    }
    console.log(`${$borrow(shared).value} ${$byteLen($borrow(other).value)}`);
    const held = $borrowMut(shared, true);
    let held$live = true;
    try {
      console.log(
        `RefCell { value: ${$showBorrowed(shared, (value) => $debugStr(value))} } ${$debugStr(held.value)}`,
      );
      held$live = false;
      $unborrow(held);
      const copy = { value: $borrow(shared).value };
      console.log(`${$eq(copy, shared)}`);
      console.log(
        `${$debugStr($cellReplace($borrowMut(shared), "z"))} ${$eq(copy, shared)} ${$cellReplace($borrowMut(shared), "")}`,
      );
      const reading = $borrow(copy, true);
      try {
        const result = $tryBorrow(copy, true);
        try {
          console.log(
            `RefCell { value: ${$showBorrowed(copy, (value) => $debugStr(value))} } ${$debugStr(reading.value)} ${result.TAG !== "Ok"}`,
          );
        } finally {
          if (result.TAG === "Ok") {
            $unborrow(result._0);
          }
        }
      } finally {
        $unborrow(reading);
      }
    } finally {
      if (held$live) {
        $unborrow(held);
      }
    }
  } finally {
    if (writing$live) {
      $unborrow(writing);
    }
  }
}
//# sourceMappingURL=case.js.map
