// Generated by rust-js from test/corpus/refcell_replace_while_borrowed.rs. Do not edit.

import { $borrow, $borrowMut, $cellReplace, $unborrow } from "@rust-js/runtime";

export function entry() {
  main();
}

function main() {
  const cell = { value: 1 };
  const reading = $borrow(cell, true);
  try {
    $cellReplace($borrowMut(cell), 2);
    console.log(`${reading.value}`);
  } finally {
    $unborrow(reading);
  }
}
//# sourceMappingURL=case.js.map
