// Generated by rust-js from test/corpus/replace_through_mut.rs. Do not edit.

import {
  $assign,
  $at,
  $debugF64,
  $debugStr,
  $eq,
  $exchange,
  $index,
  $take,
} from "@rust-js/runtime";

const Counter = {
  reset(counter) {
    $assign(counter, { n: 0, label: "", items: [] });
  },
  restart(counter, n) {
    $assign(counter, { n, label: `from ${counter.n}`, items: [] });
    counter.items.push(n);
  },
};

const Light = {
  toggle(self) {
    self.value = self.value === "Off" ? { TAG: "On", level: 5 } : "Off";
  },
};

function replace_with(c, n) {
  return $take(c, { n, label: "new", items: [n] });
}

function swap_two(a, b) {
  $exchange(a, b);
}

function take_all(v) {
  return $take(v, []);
}

function origin(p) {
  $assign(p, { x: 0, y: 0 });
}

function through_ref_mut() {
  let a = { x: 1, y: 0 };
  const cur = a;
  $assign(cur, { x: 2, y: 3 });
  return (a.x + a.y) | 0;
}

function swap_points(a, b) {
  $exchange(a, b);
}

function set(l, level) {
  l.value = { TAG: "On", level };
}

function brighter(l) {
  if (l.value.TAG === "On") {
    l.value.level = (l.value.level + 1) & 255;
  }
}

function flip(s) {
  let tmp;
  if (s.TAG === "Circle") {
    tmp = { TAG: "Square", side: s.r * 2 };
  } else {
    tmp = { TAG: "Circle", r: s.side };
  }
  $assign(s, tmp);
}

function shout(s) {
  s.value = `${s.value}!`;
}

function refill(v) {
  $assign(v, [9, 8]);
}

function zero(t) {
  $assign(t, [0, "zero"]);
}

function main() {
  let c = { n: 3, label: "a", items: [1, 2] };
  const kept = { ...c, items: c.items.slice() };
  Counter.reset(c);
  console.log(`${counterDebug_fmt(c)} ${counterDebug_fmt(kept)}`);
  Counter.restart(c, 4);
  console.log(`${counterDebug_fmt(c)}`);
  const old = replace_with(c, 7);
  console.log(`${counterDebug_fmt(old)} ${counterDebug_fmt(c)}`);
  let d = { n: 1, label: "", items: [] };
  swap_two(c, d);
  console.log(`${counterDebug_fmt(c)} ${counterDebug_fmt(d)}`);
  let row = [
    { n: 0, label: "", items: [] },
    { n: 2, label: "", items: [] },
  ];
  Counter.restart($index(row, 1), 6);
  console.log(`[${row.map((item) => counterDebug_fmt(item)).join(", ")}]`);
  let items = [4, 5];
  console.log(
    `[${take_all(items)
      .map((item) => String(item))
      .join(", ")}] [${items.map((item) => String(item)).join(", ")}]`,
  );
  const a = { x: 1, y: 2 };
  let b = { ...a };
  origin(b);
  console.log(`${pDebug_fmt(a)} ${pDebug_fmt(b)}`);
  console.log(`${through_ref_mut()}`);
  const first = { x: 3 };
  let second = { ...first };
  let third = { x: 5 };
  swap_points(second, third);
  console.log(`${qDebug_fmt(first)} ${qDebug_fmt(second)} ${qDebug_fmt(third)}`);
  let l = "Off";
  const self = { value: l };
  Light.toggle(self);
  l = self.value;
  const l$1 = { value: l };
  brighter(l$1);
  l = l$1.value;
  console.log(`${lightDebug_fmt(l)}`);
  const self$1 = { value: l };
  Light.toggle(self$1);
  l = self$1.value;
  console.log(`${lightDebug_fmt(l)}`);
  const l$2 = { value: l };
  set(l$2, 9);
  l = l$2.value;
  const arg = $eq(l, { TAG: "On", level: 9 });
  console.log(`${lightDebug_fmt(l)} ${arg}`);
  let lights = ["Off", { TAG: "On", level: 1 }];
  for (let i = 0; i < lights.length; i++) {
    const self$2 = { value: lights[i] };
    Light.toggle(self$2);
    lights[i] = self$2.value;
  }
  const l$3 = { value: $index(lights, 0) };
  brighter(l$3);
  lights[$at(lights, 0)] = l$3.value;
  console.log(`[${lights.map((item) => lightDebug_fmt(item)).join(", ")}]`);
  let s = { TAG: "Circle", r: 1.5 };
  flip(s);
  const arg$1 = $eq(s, { TAG: "Square", side: 3 });
  console.log(`${shapeDebug_fmt(s)} ${arg$1}`);
  flip(s);
  const arg$2 = $eq(s, { TAG: "Circle", r: 3 });
  console.log(`${shapeDebug_fmt(s)} ${arg$2}`);
  let v = [1, 2, 3];
  refill(v);
  console.log(`[${v.map((item) => String(item)).join(", ")}]`);
  let name = "pen";
  const copy = name;
  const s$1 = { value: name };
  shout(s$1);
  name = s$1.value;
  console.log(`${name} ${copy}`);
  let t = [5, "five"];
  zero(t);
  console.log(`(${t[0]}, ${$debugStr(t[1])})`);
}

export function entry() {
  main();
}

function counterDebug_fmt(counter) {
  return `Counter { n: ${counter.n}, label: ${$debugStr(counter.label)}, items: [${counter.items.map((item) => String(item)).join(", ")}] }`;
}

function pDebug_fmt(p) {
  return `P { x: ${p.x}, y: ${p.y} }`;
}

function qDebug_fmt(q) {
  return `Q { x: ${q.x} }`;
}

function lightDebug_fmt(light) {
  if (light === "Off") {
    return "Off";
  } else {
    return `On { level: ${light.level} }`;
  }
}

function shapeDebug_fmt(shape) {
  if (shape.TAG === "Circle") {
    return `Circle { r: ${$debugF64(shape.r)} }`;
  } else {
    return `Square { side: ${$debugF64(shape.side)} }`;
  }
}
//# sourceMappingURL=case.js.map
