// Generated by rust-js from test/corpus/returned_references.rs. Do not edit.

import { $debugStr, $unwrap } from "@rust-js/runtime";

function pick(items, log) {
  log.push("pick");
  return $unwrap(items.at(-1));
}

function value(log) {
  log.push("value");
  return 5;
}

function main() {
  let items = [
    { name: "a", count: 1 },
    { name: "b", count: 2 },
  ];
  $unwrap(items.at(-1)).count = 9;
  const item = $unwrap(items[1]);
  item.count = (item.count + 1) >>> 0;
  let log = [];
  const value$1 = value(log);
  pick(items, log).count = value$1;
  console.log(
    `[${items.map((item) => itemDebug_fmt(item)).join(", ")}] [${log.map((item) => $debugStr(item)).join(", ")}]`,
  );
  let stock = new Map();
  stock.set("pen", { name: "pen", count: 3 });
  const item$1 = $unwrap(stock.get("pen"));
  item$1.count = Math.imul(item$1.count, 4) >>> 0;
  console.log(`${$unwrap(stock.get("pen"), "no entry found for key").count}`);
}

export function entry() {
  main();
}

function itemDebug_fmt(item) {
  return `Item { name: ${$debugStr(item.name)}, count: ${item.count} }`;
}
//# sourceMappingURL=case.js.map
