// Generated by rust-js from test/corpus/slice_start_past_len.rs. Do not edit.

import { $slice } from "@rust-js/runtime";

export function entry() {
  main();
}

function main() {
  const v = [1, 2, 3, 4];
  const start = (v.length + 1) >>> 0;
  console.log(
    `[${$slice(v, start, (start + 1) >>> 0)
      .map((item) => String(item))
      .join(", ")}]`,
  );
}
//# sourceMappingURL=case.js.map
