// Generated by rust-js from test/corpus/slice_prefix_eq.rs. Do not edit.

import {
  $debugF64,
  $eq,
  $slice,
  $sliceStartsWith,
  $sliceStrip,
  $sliceStripCircumfix,
} from "@rust-js/runtime";

var $loosePartialEq;

export function entry() {
  main();
}

function pointDebug_fmt(point) {
  return `Point { x: ${point.x}, y: ${point.y} }`;
}

function looseDebug_fmt(loose) {
  return `Loose(${loose[0]})`;
}

export function loosePartialEq() {
  if ($loosePartialEq === undefined) {
    $loosePartialEq = { eq: loosePartialEq_eq };
  }
  return $loosePartialEq;
}

function loosePartialEq_eq(loose, other) {
  return (Math.abs((loose[0] - other[0]) | 0) | 0) <= 1;
}

function framed(items, edge, TPartialEq) {
  return (
    $sliceStartsWith(items, edge, false, (a, b) => TPartialEq.eq(a, b)) &&
    $sliceStartsWith(items, edge, true, (a, b) => TPartialEq.eq(a, b))
  );
}

function main() {
  const path = [
    { x: 0, y: 0 },
    { x: 1, y: 2 },
    { x: 0, y: 0 },
  ];
  const origin = [{ x: 0, y: 0 }];
  console.log(
    `${$sliceStartsWith(path, origin, false, $eq)} ${$sliceStartsWith(path, $slice(path, 1), true, $eq)}`,
  );
  const arg = $sliceStrip(path, origin, false, $eq);
  console.log(
    `${arg == null ? "None" : `Some([${arg.map((item) => pointDebug_fmt(item)).join(", ")}])`}`,
  );
  const arg$1 = $sliceStrip(path, [{ x: 9, y: 9 }], true, $eq);
  console.log(
    `${arg$1 == null ? "None" : `Some([${arg$1.map((item) => pointDebug_fmt(item)).join(", ")}])`}`,
  );
  const arg$2 = $sliceStripCircumfix(path, origin, origin, $eq);
  console.log(
    `${arg$2 == null ? "None" : `Some([${arg$2.map((item) => pointDebug_fmt(item)).join(", ")}])`}`,
  );
  const arg$3 = $sliceStripCircumfix($slice(path, 0, 1), origin, origin, $eq);
  console.log(
    `${arg$3 == null ? "None" : `Some([${arg$3.map((item) => pointDebug_fmt(item)).join(", ")}])`}`,
  );
  const loose = [[1], [5], [9]];
  console.log(
    `${$sliceStartsWith(loose, [[2]], false, loosePartialEq_eq)} ${$sliceStartsWith(loose, [[7]], true, loosePartialEq_eq)}`,
  );
  const arg$4 = $sliceStrip(loose, [[0], [6]], false, loosePartialEq_eq);
  console.log(
    `${arg$4 == null ? "None" : `Some([${arg$4.map((item) => looseDebug_fmt(item)).join(", ")}])`}`,
  );
  console.log(`${framed(path, origin, { eq: $eq })} ${framed(loose, [[1]], loosePartialEq())}`);
  const arg$5 = $sliceStripCircumfix([1.5, 2], [1.5], [2]);
  console.log(
    `${arg$5 == null ? "None" : `Some([${arg$5.map((item) => $debugF64(item)).join(", ")}])`}`,
  );
}
//# sourceMappingURL=case.js.map
