// Generated by rust-js from test/corpus/slice_view_past_len.rs. Do not edit.

import { $at, $view } from "@rust-js/runtime";

export function entry() {
  main();
}

function main() {
  const v = [1, 2, 3, 4];
  const end = (v.length + 5) >>> 0;
  const part = $view(v, 2, end);
  console.log("made");
  part[$at(part, 0)] = 0;
}
//# sourceMappingURL=case.js.map
