// Generated by rust-js from test/corpus/slice_split.rs. Do not edit.

import { $slice, $sliceGet, $sliceSplitAt } from "@rust-js/runtime";

function halves(bytes) {
  const [high, low] = $sliceSplitAt(bytes, (bytes.length / 2) >>> 0);
  const fold = (part) => part.reduce((acc, b) => ((Math.imul(acc, 256) >>> 0) + b) >>> 0, 0);
  return [fold(high), fold(low)];
}

function main() {
  const v = [1, 2, 3, 4, 5];
  const [left, right] = $sliceSplitAt(v, 2);
  console.log(
    `[${left.map((item) => String(item)).join(", ")}] [${right.map((item) => String(item)).join(", ")}]`,
  );
  const [none, all] = $sliceSplitAt(v, 0);
  const [whole, empty] = $sliceSplitAt($slice(v, 1), 4);
  console.log(
    `[${none.map((item) => String(item)).join(", ")}] [${all.map((item) => String(item)).join(", ")}] [${whole.map((item) => String(item)).join(", ")}] [${empty.map((item) => String(item)).join(", ")}]`,
  );
  const arg = halves([1, 0, 0, 2]);
  console.log(`(${arg[0]}, ${arg[1]})`);
  const words = ["a", "b", "c"];
  const [first, rest] = $sliceSplitAt(words, 1);
  console.log(`${first.join("+")} ${rest.join("+")}`);
  const arg$1 = $sliceGet(v, 1, 3);
  const arg$2 = $sliceGet(v, 3);
  const arg$3 = $sliceGet(v, 0, 2);
  console.log(
    `${arg$1 == null ? "None" : `Some([${arg$1.map((item) => String(item)).join(", ")}])`} ${arg$2 == null ? "None" : `Some([${arg$2.map((item) => String(item)).join(", ")}])`} ${arg$3 == null ? "None" : `Some([${arg$3.map((item) => String(item)).join(", ")}])`}`,
  );
  const arg$4 = $sliceGet(v, 0);
  const arg$5 = $sliceGet(v, 4, 9);
  const arg$6 = $sliceGet(v, 2, 5);
  console.log(
    `${arg$4 == null ? "None" : `Some([${arg$4.map((item) => String(item)).join(", ")}])`} ${arg$5 == null ? "None" : `Some([${arg$5.map((item) => String(item)).join(", ")}])`} ${arg$6 == null ? "None" : `Some([${arg$6.map((item) => String(item)).join(", ")}])`}`,
  );
  const [start, end] = [3, 1];
  const arg$7 = $sliceGet(v, start, end);
  const arg$8 = $sliceGet(v, 5);
  console.log(
    `${arg$7 == null ? "None" : `Some([${arg$7.map((item) => String(item)).join(", ")}])`} ${arg$8 == null ? "None" : `Some([${arg$8.map((item) => String(item)).join(", ")}])`}`,
  );
  const match = $sliceGet(words, 1);
  if (match != null) {
    console.log(`${match.length}`);
  } else {
    console.log("none");
  }
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
