// Generated by rust-js from test/corpus/slice_bytes_text.rs. Do not edit.

import { $byteLen, $debugStr, $escapeAscii, $utf8Chunks } from "@rust-js/runtime";

export function entry() {
  main();
}

function main() {
  const bytes = [
    116, 97, 98, 9, 104, 101, 114, 101, 32, 34, 113, 117, 111, 116, 101, 100, 34, 32, 39, 105, 116,
    39, 32, 92, 32, 127, 0, 255, 126,
  ];
  console.log(`${$escapeAscii(bytes)}`);
  const escaped = $escapeAscii([97, 10, 98]);
  const arg = $byteLen(escaped);
  console.log(`${escaped} ${arg}`);
  console.log(`[${$escapeAscii([])}]`);
  const mixed = [111, 107, 255, 104, 195, 169, 226, 130, 32, 101, 110, 100, 240, 159];
  for (const chunk of $utf8Chunks(mixed)) {
    console.log(
      `${$debugStr(chunk.valid)} [${chunk.invalid.map((item) => String(item)).join(", ")}]`,
    );
  }
  const text = $utf8Chunks([99, 97, 102, 195, 169, 195])
    .map((c) => c.valid)
    .join("");
  const arg$1 = $utf8Chunks([]).length;
  console.log(`${text} ${arg$1}`);
}
//# sourceMappingURL=case.js.map
