// Generated by rust-js from test/corpus/sort_unstable_wasm32.rs. Do not edit.

import { $byteLen, $cmp, $range, $selectNthUnstable, $sortUnstable } from "@rust-js/runtime";

export function entry() {
  main();
}

function main() {
  const text =
    "a bb cc d eee ff g hh ii j kkk ll m nn o pp qqq rr s tt uu v ww x yy zz aa bbb c dd ee f gg";
  const words = text.split(" ");
  const key = (w) => $byteLen(w);
  $sortUnstable(words, (a, b) => key(a) < key(b), "network");
  console.log(`${words.join(",")}`);
  const pairs = $range(0, 40).map((i) => [(Math.imul(i, 7) >>> 0) % 4, i]);
  const key$1 = (p) => p[0];
  $sortUnstable(pairs, (a, b) => key$1(a) < key$1(b), "network");
  console.log(
    `[${pairs
      .map((p) => p[1])
      .map((item) => String(item))
      .join(", ")}]`,
  );
  const owned = text.split(" ").map((s) => s);
  $sortUnstable(owned, (a, b) => $cmp($byteLen(b), $byteLen(a)) < 0, "general8");
  console.log(`${owned.join(",")}`);
  const wide = $range(0, 50).map((i) => [
    i % 3,
    i,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
  ]);
  const key$2 = (w) => w[0];
  $sortUnstable(wide, (a, b) => key$2(a) < key$2(b), "general");
  console.log(
    `[${wide
      .map((w) => w[1])
      .map((item) => String(item))
      .join(", ")}]`,
  );
  const picked = text.split(" ");
  const middle = (picked.length / 2) >>> 0;
  const key$3 = (w) => $byteLen(w);
  $selectNthUnstable(picked, middle, (a, b) => key$3(a) < key$3(b), "network", true);
  console.log(`${picked.join(",")}`);
}
//# sourceMappingURL=case.js.map
