// Generated by rust-js from test/corpus/sort_unstable_adversary.rs. Do not edit.

import {
  $at,
  $borrowMut,
  $cmp,
  $index,
  $range,
  $selectNthUnstable,
  $slice,
  $sortUnstable,
  $unborrow,
} from "@rust-js/runtime";

export function entry() {
  main();
}

function adversary(n, select) {
  const gas = n;
  const start = new Array(n).fill(gas);
  start[$at(start, 0)] = (gas + 2) >>> 0;
  start[$at(start, 1)] = (gas + 1) >>> 0;
  const values = { value: start };
  let solid = 0;
  let candidate = 0;
  let asked = 0;
  const compare = (x, y) => {
    asked = (asked + 1) >>> 0;
    const v = $borrowMut(values, true);
    try {
      if ($index(v.value, x) === gas && $index(v.value, y) === gas) {
        if (x === candidate) {
          v.value[$at(v.value, x)] = solid;
        } else {
          v.value[$at(v.value, y)] = solid;
        }
        solid = (solid + 1) >>> 0;
      }
      if ($index(v.value, x) === gas) {
        candidate = x;
      } else if ($index(v.value, y) === gas) {
        candidate = y;
      }
      return $cmp($index(v.value, x), $index(v.value, y));
    } finally {
      $unborrow(v);
    }
  };
  const items = $range(0, n);
  if (select != null) {
    $selectNthUnstable(items, select, (a, b) => compare(a, b) < 0, "network", true);
  } else {
    $sortUnstable(items, (a, b) => compare(a, b) < 0, "network");
  }
  return [items, asked];
}

function main() {
  for (const n of [64, 300, 1000]) {
    const [sorted, asked] = adversary(n);
    const arg = $slice(sorted, 0, 12);
    console.log(`${n} sorted after ${asked}: [${arg.map((item) => String(item)).join(", ")}]`);
    const [picked, asked$1] = adversary(n, (n / 3) >>> 0);
    const arg$1 = $slice(picked, 0, 12);
    console.log(`${n} picked after ${asked$1}: [${arg$1.map((item) => String(item)).join(", ")}]`);
  }
}
//# sourceMappingURL=case.js.map
