// Generated by rust-js from test/corpus/statics.rs. Do not edit.

import { NAME, SIDES } from "./shapes.js";
import { $debugF64, $debugStr, $print } from "@rust-js/runtime";

export function entry() {
  main();
}

function pointDebug_fmt(point) {
  return `Point { x: ${point.x}, y: ${point.y} }`;
}

function levelDebug_fmt(level) {
  if (level === "Low") {
    return "Low";
  }
  return `High(${level._0})`;
}

const ORIGIN = { x: 0, y: 0 };
const CORNER = { x: 2, y: -3 };
const LIMIT = 1099511627776n;
const GREETING = "hi";
const NAMES = ["ann", "bo", "cy"];
const PRIMES = [2, 3, 5, 7];
const EMPTY = [];
const LEVELS = ["Low", { TAG: "High", _0: 9 }];
const MAYBE = "z";
const PAIR = [true, 2.5];
const BOXED = { x: 3, y: 4 };
const COMPUTED = -42;

function moved(dx) {
  const p = { ...ORIGIN };
  p.x = (p.x + dx) | 0;
  return p;
}

const WORDS = ["one", "two"];

function counted() {
  return WORDS.length;
}

function main() {
  console.log(`${pointDebug_fmt(moved(5))} ${pointDebug_fmt(ORIGIN)} ${pointDebug_fmt(moved(-2))}`);
  console.log(`${LIMIT} ${GREETING} ${NAMES.join(",")}`);
  console.log(
    `[${PRIMES.map((item) => String(item)).join(", ")}] ${PRIMES.reduce((a, b) => (a + b) >>> 0, 0)} [${EMPTY.map((item) => String(item)).join(", ")}]`,
  );
  console.log(
    `[${LEVELS.map((item) => levelDebug_fmt(item)).join(", ")}] ${MAYBE == null ? "None" : `Some(${$debugStr(MAYBE, "'")})`} (${PAIR[0]}, ${$debugF64(PAIR[1])})`,
  );
  console.log(`${(BOXED.x + BOXED.y) | 0} ${COMPUTED} ${counted()}`);
  console.log(
    `${pointDebug_fmt(CORNER)} [${SIDES.map((item) => String(item)).join(", ")}] ${NAME}`,
  );
  for (const name of NAMES) {
    $print(`${name} `);
  }
  console.log("");
}
//# sourceMappingURL=case.js.map
