// Generated by rust-js from test/corpus/std_mut_items.rs. Do not edit.

import {
  $cmp,
  $debugF64,
  $debugStr,
  $mutAt,
  $mutEntries,
  $mutGet,
  $mutItems,
  $mutValues,
  $sortedEntries,
  $unwrap,
} from "@rust-js/runtime";

export function entry() {
  main();
}

function bump(n) {
  n.value = (n.value + 100) | 0;
}

function peek(o) {
  return o != null ? o.value : 0;
}

function main() {
  const scores = [1, 2, 3];
  $mutItems(scores).forEach((s) => {
    s.value = Math.imul(s.value, 10);
  });
  $mutItems(scores)
    .filter((s) => s.value > 10)
    .forEach((s) => {
      s.value = (s.value + 1) | 0;
    });
  for (const item of $mutItems(scores).entries()) {
    item[1].value = (item[1].value + (item[0] | 0)) | 0;
  }
  console.log(`[${scores.map((item) => String(item)).join(", ")}]`);
  const names = ["ann", "bo"];
  $mutItems(names).forEach((n) => {
    n.value += "!";
  });
  console.log(`[${names.map((item) => $debugStr(item)).join(", ")}]`);
  const stock = new Map([
    ["apples", 3],
    ["pears", 0],
  ]);
  for (const n of $mutValues(stock)) {
    n.value = (n.value + 1) | 0;
  }
  for (const item$1 of $mutEntries(stock)) {
    if (item$1[0].startsWith("a")) {
      item$1[1].value = Math.imul(item$1[1].value, 2);
    }
  }
  const sorted = Array.from(stock).map(([k, v]) => [k, v]);
  sorted.sort((a, b) => $cmp(a[0], b[0]) || $cmp(a[1], b[1]));
  console.log(`[${sorted.map((item) => `(${$debugStr(item[0])}, ${item[1]})`).join(", ")}]`);
  const ordered = new Map([
    [2, 0.5],
    [1, 1.5],
  ]);
  $mutValues(ordered, $sortedEntries(ordered, $cmp)).forEach((x) => {
    x.value *= 2;
  });
  for (const item$2 of $mutEntries(ordered, $sortedEntries(ordered, $cmp))) {
    item$2[1].value = item$2[1].value + 0.25;
  }
  const visited = [];
  for (const item$3 of $mutEntries(ordered, $sortedEntries(ordered, $cmp))) {
    visited.push(item$3[0]);
    item$3[1].value = item$3[1].value - 0.5;
  }
  const halves = $mutValues(ordered, $sortedEntries(ordered, $cmp)).map((x) => x.value / 2);
  console.log(
    `{${Array.from($sortedEntries(ordered, $cmp))
      .map(([key, value]) => `${key}: ${$debugF64(value)}`)
      .join(
        ", ",
      )}} [${visited.map((item) => String(item)).join(", ")}] [${halves.map((item) => $debugF64(item)).join(", ")}]`,
  );
  const counts = new Map();
  counts.set("a", 1);
  const a = $mutGet(counts, "a");
  if (a != null) {
    a.value = (a.value + 1) | 0;
    bump(a);
  }
  const row = [5, 6];
  const last = $unwrap($mutAt(row, -1));
  last.value = 60;
  bump($unwrap($mutAt(row, 0)));
  const x = $mutAt(row, 1);
  if (x != null) {
    bump(x);
  }
  console.log(
    `{${Array.from(counts)
      .map(([key, value]) => `${$debugStr(key, "'")}: ${value}`)
      .join(", ")}} [${row.map((item) => String(item)).join(", ")}]`,
  );
  const seen = (peek($mutGet(counts, "a")) + peek($mutGet(counts, "z"))) | 0;
  const r = $mutGet(counts, "a");
  let found;
  if (r != null) {
    r.value = (r.value - 2) | 0;
    found = r.value;
  } else {
    found = 0;
  }
  const cells = [1, 2, 3];
  const refs = $mutItems(cells).filter((c) => c.value !== 2);
  for (const r$1 of refs) {
    r$1.value = -r$1.value | 0;
  }
  console.log(`${seen} ${found} [${cells.map((item) => String(item)).join(", ")}]`);
}
//# sourceMappingURL=case.js.map
