// Generated by rust-js from test/corpus/std_function_value_panic.rs. Do not edit.

import { $unwrap } from "@rust-js/runtime";

function main() {
  const inspect = (o) => {
    console.log(`${o == null ? "None" : `Some(${o})`}`);
  };
  const seen = [1, undefined, 3]
    .values()
    .map((item) => {
      inspect(item);
      return item;
    })
    .map((x) => $unwrap(x))
    .toArray();
  console.log(`[${seen.map((item) => String(item)).join(", ")}]`);
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
