// Generated by rust-js from test/corpus/stepped_nested.rs. Do not edit.

import { $iter, $next, $rest } from "@rust-js/runtime";

var $numbersSecond;

function main() {
  const skipOne = (v) => {
    const it = $iter(v);
    $next(it);
    return $rest(it).map((x) => Math.imul(x, 10) >>> 0);
  };
  console.log(
    `[${skipOne([1, 2, 3])
      .map((item) => String(item))
      .join(", ")}] ${numbersSecond().second(undefined)}`,
  );
}

export function entry() {
  main();
}

function numbersSecond_items(numbers) {
  return [4, 5, 6];
}

function numbersSecond() {
  if ($numbersSecond === undefined) {
    $numbersSecond = {
      items: numbersSecond_items,
      second: (self) => {
        const items = numbersSecond_items(self);
        const it = $iter(items);
        $next(it);
        return $next(it) ?? 0;
      },
    };
  }
  return $numbersSecond;
}
//# sourceMappingURL=case.js.map
