// Generated by rust-js from test/corpus/str_mut_boundary.rs. Do not edit.

import { $asciiCase } from "@rust-js/runtime";

export function entry() {
  main();
}

function main() {
  let s = "éa";
  s = $asciiCase(s, true, 1);
  console.log(`${s}`);
}
//# sourceMappingURL=case.js.map
