// Generated by rust-js from test/corpus/string_slice_boundary.rs. Do not edit.

import { $strSlice } from "@rust-js/runtime";

export function entry() {
  main();
}

function main() {
  const s = "héllo";
  console.log(`${$strSlice(s, 0, 1)}`);
  console.log(`${$strSlice(s, 2, 4)}`);
}
//# sourceMappingURL=case.js.map
