// Generated by rust-js from test/corpus/string_pushes.rs. Do not edit.

import { $print } from "@rust-js/runtime";

export function entry() {
  main();
}

const Log = {
  add(log, line) {
    log.text += line;
    log.text += "\n";
  },
};

function main() {
  let s = "";
  s += "ab";
  s += "c";
  s += "-7";
  const log = { text: "" };
  Log.add(log, "one");
  Log.add(log, s);
  $print(log.text);
}
//# sourceMappingURL=case.js.map
