// Generated by rust-js from test/corpus/swap_replace.rs. Do not edit.

function settle(done) {
  const old = done.value;
  done.value = true;
  return old;
}

function main() {
  let [a, b] = [1, 2];
  const t = a;
  a = b;
  b = t;
  console.log(`${a} ${b}`);
  let pair = { left: [1, 2], right: [3], label: "p" };
  const t$1 = pair.left;
  pair.left = pair.right;
  pair.right = t$1;
  let other = "q";
  const t$2 = pair.label;
  pair.label = other;
  other = t$2;
  console.log(
    `[${pair.left.map((item) => String(item)).join(", ")}] [${pair.right.map((item) => String(item)).join(", ")}] ${pair.label} ${other}`,
  );
  const old = pair.left;
  pair.left = [9];
  console.log(
    `[${old.map((item) => String(item)).join(", ")}] [${pair.left.map((item) => String(item)).join(", ")}]`,
  );
  a = 6;
  console.log(`${a}`);
  let done = false;
  const done$1 = { value: done };
  const result = settle(done$1);
  done = done$1.value;
  console.log(`${result} ${done}`);
  const done$2 = { value: done };
  const result$1 = settle(done$2);
  done = done$2.value;
  console.log(`${result$1} ${done}`);
  let loud = ["first"];
  try {
    const old$2 = loud;
    loud = ["second"];
    const first = old$2;
    try {
      console.log(`replaced ${first[0]}`);
      let third = ["third"];
      try {
        const t$3 = loud;
        loud = third;
        third = t$3;
        console.log(`holding ${loud[0]} ${third[0]}`);
        console.log("42");
      } finally {
        loudDrop_drop(third);
      }
    } finally {
      loudDrop_drop(first);
    }
  } finally {
    loudDrop_drop(loud);
  }
}

export function entry() {
  main();
}

function loudDrop_drop(loud) {
  console.log(`drop ${loud[0]}`);
}
//# sourceMappingURL=case.js.map
