// Generated by rust-js from test/corpus/text_predicates.rs. Do not edit.

import {
  $byteLen,
  $charBoundary,
  $debugStr,
  $findBy,
  $range,
  $splitBy,
  $startsBy,
  $strGet,
  $trimMatches,
} from "@rust-js/runtime";

function main() {
  const line = "id=42; name=Zoë, age 31";
  const arg = $findBy(line, (c) => /^[0-9]$/.test(c), false);
  const arg$1 = $findBy(line, (c) => /^\p{N}$/u.test(c), true);
  const arg$2 = $findBy(line, (c) => [";", ","].includes(c), false);
  const arg$3 = $findBy(line, (c) => /^\p{White_Space}$/u.test(c), false);
  console.log(
    `${arg == null ? "None" : `Some(${arg})`} ${arg$1 == null ? "None" : `Some(${arg$1})`} ${arg$2 == null ? "None" : `Some(${arg$2})`} ${arg$3 == null ? "None" : `Some(${arg$3})`}`,
  );
  const arg$4 = $findBy(line, (c) => c === "ë", false);
  const arg$5 = $findBy(line, (c) => c === "~", true);
  console.log(
    `${arg$4 == null ? "None" : `Some(${arg$4})`} ${arg$5 == null ? "None" : `Some(${arg$5})`}`,
  );
  console.log(
    `${$startsBy(line, (c) => /^\p{Alphabetic}$/u.test(c), false)} ${$startsBy(line, (c) => /^[0-9]$/.test(c), true)} ${$startsBy("", () => true, false)} ${$startsBy("😀x", (c) => $byteLen(c) === 4, false)}`,
  );
  console.log(`${$startsBy("x😀", (c) => $byteLen(c) === 4, true)}`);
  const fields = $splitBy(line, (c) => [";", ","].includes(c)).map((s) => s.trim());
  console.log(`[${fields.map((item) => $debugStr(item)).join(", ")}]`);
  const words = $splitBy("a1b22c", (c) => /^\p{N}$/u.test(c));
  console.log(
    `[${words.map((item) => $debugStr(item)).join(", ")}] ${Array.from(line).some((c) => /^\p{Uppercase}$/u.test(c))}`,
  );
  console.log(`${$debugStr($trimMatches("--==x==--", (c) => ["-", "="].includes(c)))}`);
  console.log(
    `[${"  tabs	and  spaces\n"
      .split(/[\t\n\f\r ]+/)
      .filter((word) => word !== "")
      .map((item) => $debugStr(item))
      .join(", ")}]`,
  );
  console.log(
    `[${"a\vb c"
      .split(/[\t\n\f\r ]+/)
      .filter((word) => word !== "")
      .map((item) => $debugStr(item))
      .join(", ")}]`,
  );
  const name = "Zoë!";
  const arg$6 = $strGet(name, 0, 2);
  const arg$7 = $strGet(name, 2, 3);
  const arg$8 = $strGet(name, 2, 4);
  const arg$9 = $strGet(name, 4);
  const arg$10 = $strGet(name, 0, 2);
  console.log(
    `${arg$6 == null ? "None" : `Some(${$debugStr(arg$6)})`} ${arg$7 == null ? "None" : `Some(${$debugStr(arg$7)})`} ${arg$8 == null ? "None" : `Some(${$debugStr(arg$8)})`} ${arg$9 == null ? "None" : `Some(${$debugStr(arg$9)})`} ${arg$10 == null ? "None" : `Some(${$debugStr(arg$10)})`}`,
  );
  const arg$11 = name;
  const arg$12 = $strGet(name, 3, 9);
  const arg$13 = $strGet(name, 9);
  console.log(
    `${arg$11 == null ? "None" : `Some(${$debugStr(arg$11)})`} ${arg$12 == null ? "None" : `Some(${$debugStr(arg$12)})`} ${arg$13 == null ? "None" : `Some(${$debugStr(arg$13)})`}`,
  );
  const edges = $range(0, 6 + 1).map((i) => $charBoundary(name, i) !== undefined);
  console.log(`[${edges.map((item) => String(item)).join(", ")}]`);
  console.log(`${$byteLen("a")} ${$byteLen("ë")} ${$byteLen("😀")} ${"😀".length}`);
  console.log(`${String.fromCharCode(65)} ${String.fromCharCode(233)}`);
  const letters = ["h", "é", "!"].join("");
  const joined = ["ab", "cd"].join("");
  console.log(`${letters} ${joined}`);
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
