// Generated by rust-js from test/corpus/trait_default_bounds.rs. Do not edit.

import { $cmp, $eq, $partialCmp, $traitImpl } from "@rust-js/runtime";

var $f64Zero, $f64Signed, $i32Zero, $i32Signed, $u8One, $wrappingOne;

function main() {
  console.log(
    `${f64Signed().negative(-1.5)} ${f64Signed().negative(2)} ${f64Signed().negative(NaN)} ${i32Signed().at_most_zero(0)}`,
  );
  console.log(
    `${wrappingOne(u8One(), { mul: (a, b) => [(a[0] * b[0]) & 255] }).is_one([1], { eq: $eq })} ${wrappingOne(u8One(), { mul: (a, b) => [(a[0] * b[0]) & 255] }).is_one([3], { eq: $eq })} ${u8One().is_one(1, { eq: (a, b) => a === b })}`,
  );
}

export function entry() {
  main();
}

function f64Zero_zero() {
  return 0;
}

function i32Zero_zero() {
  return 0;
}

function u8One_one() {
  return 1;
}

function wrappingOne_one(TOne, std__num__Wrapping_T_Mul) {
  return [TOne.one()];
}

function f64Zero() {
  if ($f64Zero === undefined) {
    $f64Zero = { zero: f64Zero_zero };
  }
  return $f64Zero;
}

function f64Signed() {
  if ($f64Signed === undefined) {
    $f64Signed = {
      Zero: () => f64Zero(),
      PartialOrd: () => ({ partial_cmp: $partialCmp }),
      Copy: () => ({ copy: (value) => value }),
      negative: (self) => self < f64Zero_zero(),
      at_most_zero: (self) => self <= f64Zero_zero(),
    };
  }
  return $f64Signed;
}

function i32Zero() {
  if ($i32Zero === undefined) {
    $i32Zero = { zero: i32Zero_zero };
  }
  return $i32Zero;
}

function i32Signed() {
  if ($i32Signed === undefined) {
    $i32Signed = {
      Zero: () => i32Zero(),
      PartialOrd: () => ({ partial_cmp: $cmp }),
      Copy: () => ({ copy: (value) => value }),
      negative: (self) => self < i32Zero_zero(),
      at_most_zero: (self) => self <= i32Zero_zero(),
    };
  }
  return $i32Signed;
}

function u8One() {
  if ($u8One === undefined) {
    $u8One = {
      Mul: () => ({ mul: (a, b) => (a * b) & 255 }),
      one: u8One_one,
      is_one: (self, SelfPartialEq) => self === u8One_one(),
    };
  }
  return $u8One;
}

function wrappingOne(TOne, std__num__Wrapping_T_Mul) {
  if ($wrappingOne === undefined) {
    $wrappingOne = new WeakMap();
  }
  return $traitImpl($wrappingOne, [TOne, std__num__Wrapping_T_Mul], () => ({
    Mul: () => std__num__Wrapping_T_Mul,
    one: () => wrappingOne_one(TOne, std__num__Wrapping_T_Mul),
    is_one: (self, SelfPartialEq) =>
      SelfPartialEq.eq(self, wrappingOne_one(TOne, std__num__Wrapping_T_Mul)),
  }));
}
//# sourceMappingURL=case.js.map
