// Generated by rust-js from test/corpus/trait_mut_self_value.rs. Do not edit.

import { $at, $index } from "@rust-js/runtime";

var $i32Bump, $stringShout;

export function entry() {
  main();
}

function i32Bump() {
  if ($i32Bump === undefined) {
    $i32Bump = { bump: i32Bump_bump, bump_by: i32Bump_bump_by };
  }
  return $i32Bump;
}

function i32Bump_bump(self) {
  self.value = (self.value + 1) | 0;
}

function i32Bump_bump_by(self, by) {
  self.value = (self.value + by.value) | 0;
  by.value = (by.value + 1) | 0;
  return self.value;
}

function stringShout() {
  if ($stringShout === undefined) {
    $stringShout = { shout: stringShout_shout };
  }
  return $stringShout;
}

function stringShout_shout(self) {
  self.value += "!";
}

function main() {
  let n = 1;
  const self = { value: n };
  i32Bump_bump(self);
  n = self.value;
  const self$1 = { value: n };
  i32Bump_bump(self$1);
  n = self$1.value;
  let step = 10;
  const self$2 = { value: n };
  const by = { value: step };
  const result = i32Bump_bump_by(self$2, by);
  n = self$2.value;
  step = by.value;
  const total = result;
  console.log(`${n} ${step} ${total}`);
  let name = "hey";
  const self$3 = { value: name };
  stringShout_shout(self$3);
  name = self$3.value;
  const self$4 = { value: name };
  stringShout_shout(self$4);
  name = self$4.value;
  console.log(`${name}`);
  const counts = [1, 2];
  const self$5 = { value: $index(counts, 1) };
  i32Bump_bump(self$5);
  counts[$at(counts, 1)] = self$5.value;
  console.log(`[${counts.map((item) => String(item)).join(", ")}]`);
}
//# sourceMappingURL=case.js.map
