// Generated by rust-js from test/corpus/type_facts.rs. Do not edit.

export function entry() {
  main();
}

function size(TSize) {
  return TSize;
}

function describe(_, TSize, TAlign, TName) {
  return `${TName} ${TSize} ${TAlign}`;
}

function relay(u, UClone, USize, UAlign, UName) {
  return describe(UClone.clone(u), USize, UAlign, UName);
}

function later(TSize) {
  return () => TSize;
}

function both(ASize, BSize) {
  return (size(ASize) + size(BSize)) >>> 0;
}

function main() {
  console.log(`${size(1)} ${size(8)} ${size(6)}`);
  console.log(`${describe(1n, 8, 8, "u64")}`);
  console.log(`${describe(3, 2, 1, "core::option::Option<u8>")}`);
  console.log(`${relay(7, { clone: (value) => value }, 2, 2, "u16")}`);
  console.log(`${later(8)()} ${both(4, 4)}`);
}
//# sourceMappingURL=case.js.map
