// Generated by rust-js from test/corpus/unsized_struct_fn.rs. Do not edit.

export function entry() {
  main();
}

function main() {
  const total = { value: 0 };
  const add = { value: (x) => Math.imul(x, 2) };
  for (const x of [1, 2, 3]) {
    const value = add.value(x);
    total.value = (total.value + value) | 0;
  }
  console.log(`${total.value}`);
}
//# sourceMappingURL=case.js.map
