// Generated by rust-js from test/corpus/unwrap_typed_debug.rs. Do not edit.

import { $debugStr, $unwrapOk } from "@rust-js/runtime";

function find(name) {
  if (name === "pen") {
    return { TAG: "Ok", _0: 3 };
  }
  return { TAG: "Err", _0: { TAG: "Missing", name, shelf: 2 } };
}

function main() {
  console.log(`${$unwrapOk(find("pen"), undefined, stockErrorDebug_fmt)}`);
  console.log(`${$unwrapOk(find("ink"), undefined, stockErrorDebug_fmt)}`);
}

export function entry() {
  main();
}

function stockErrorDebug_fmt(stockError) {
  return `Missing { name: ${$debugStr(stockError.name)}, shelf: ${stockError.shelf == null ? "None" : `Some(${stockError.shelf})`} }`;
}
//# sourceMappingURL=case.js.map
