// Generated by rust-js from test/corpus/user_fmt_traits.rs. Do not edit.

import { $formatted, $lowerExp } from "@rust-js/runtime";

var $idLowerHex, $idUpperHex, $idOctal, $idBinary, $ratioLowerExp, $handlePointer, $flagsDisplay;

function main() {
  const id = [48879];
  console.log(
    `${idLowerHex_fmt(id)} ${idLowerHex_fmt(id, { alternate: true })} ${idUpperHex_fmt(id)} ${idOctal_fmt(id)} [${idBinary_fmt(
      [5],
      { width: 10, align: "Right" },
    )}]`,
  );
  console.log(`${ratioLowerExp_fmt([1234.5])} ${handlePointer_fmt([7])}`);
  console.log(`${flagsDisplay_fmt([5])} ${flagsDisplay_fmt([7])}`);
  const shown = `${idLowerHex_fmt([255])}-${flagsDisplay_fmt([2])}`;
  console.log(`${shown}`);
}

export function entry() {
  main();
}

function idLowerHex_fmt(id, options) {
  let f = "";
  if (options?.alternate === true) {
    f += "0x";
  }
  f += id[0].toString(16).padStart(8, "0");
  return f;
}

function idUpperHex_fmt(id, options) {
  return id[0].toString(16).toUpperCase().padStart(8, "0");
}

function idOctal_fmt(id, options) {
  let f = idLowerHex_fmt(id, options);
  f += "/";
  f += idUpperHex_fmt(id, options);
  return f;
}

function idBinary_fmt(id, options) {
  return $formatted(id[0].toString(2), options);
}

function ratioLowerExp_fmt(ratio, options) {
  return `${$lowerExp(ratio[0])}~`;
}

function handlePointer_fmt(handle, options) {
  return `@${handle[0]}`;
}

function flagsDisplay_fmt(flags, options) {
  let f = "";
  let first = true;
  for (const [bit, name] of [
    [1, "A"],
    [2, "B"],
    [4, "C"],
  ]) {
    if ((flags[0] & bit) !== 0) {
      if (!first) {
        f += " | ";
      }
      f += name;
      first = false;
    }
  }
  f += ".";
  return f;
}

export function idLowerHex() {
  if ($idLowerHex === undefined) {
    $idLowerHex = { fmt: idLowerHex_fmt };
  }
  return $idLowerHex;
}

export function idUpperHex() {
  if ($idUpperHex === undefined) {
    $idUpperHex = { fmt: idUpperHex_fmt };
  }
  return $idUpperHex;
}

export function idOctal() {
  if ($idOctal === undefined) {
    $idOctal = { fmt: idOctal_fmt };
  }
  return $idOctal;
}

export function idBinary() {
  if ($idBinary === undefined) {
    $idBinary = { fmt: idBinary_fmt };
  }
  return $idBinary;
}

export function ratioLowerExp() {
  if ($ratioLowerExp === undefined) {
    $ratioLowerExp = { fmt: ratioLowerExp_fmt };
  }
  return $ratioLowerExp;
}

export function handlePointer() {
  if ($handlePointer === undefined) {
    $handlePointer = { fmt: handlePointer_fmt };
  }
  return $handlePointer;
}

export function flagsDisplay() {
  if ($flagsDisplay === undefined) {
    $flagsDisplay = { fmt: flagsDisplay_fmt };
  }
  return $flagsDisplay;
}
//# sourceMappingURL=case.js.map
