// Generated by rust-js from test/corpus/user_deref.rs. Do not edit.

import { $index } from "@rust-js/runtime";

const Point = {
  sum(point) {
    return (point.x + point.y) | 0;
  },
  shift(point, by) {
    point.x = (point.x + by) | 0;
    point.y = (point.y + by) | 0;
  },
};

function main() {
  const t = { point: { x: 1, y: 2 }, reads: { value: 0 } };
  console.log(
    `${Point.sum(trackedDeref_deref(t))} ${trackedDeref_deref(t).x} ${pointDebug_fmt({ ...trackedDeref_deref(t) })}`,
  );
  Point.shift(trackedDerefMut_deref_mut(t), 10);
  trackedDerefMut_deref_mut(t).y = 0;
  const copied = { ...trackedDeref_deref(t) };
  trackedDerefMut_deref_mut(t).x = -1;
  console.log(`${pointDebug_fmt(copied)} ${pointDebug_fmt(t.point)} ${t.reads.value}`);
  const outer = [{ point: { x: 4, y: 5 }, reads: { value: 0 } }];
  console.log(
    `${Point.sum(trackedDeref_deref(outerDeref_deref(outer)))} ${trackedDeref_deref(outerDeref_deref(outer)).x} ${outerDeref_deref(outer).reads.value}`,
  );
  const grid = { cells: Array.from({ length: 4 }, () => ({ x: 0, y: 0 })), width: 2 };
  gridIndexMut_usize__usize__index_mut(grid, [1, 0]).x = 7;
  Point.shift(gridIndexMut_usize__usize__index_mut(grid, [0, 1]), 3);
  console.log(
    `${pointDebug_fmt({ ...gridIndex_usize__usize__index(grid, [1, 0]) })} ${pointDebug_fmt({ ...gridIndex_usize__usize__index(grid, [0, 1]) })} [${grid.cells.map((item) => pointDebug_fmt(item)).join(", ")}]`,
  );
}

export function entry() {
  main();
}

function pointDebug_fmt(point) {
  return `Point { x: ${point.x}, y: ${point.y} }`;
}

function trackedDeref_deref(tracked) {
  tracked.reads.value = (tracked.reads.value + 1) >>> 0;
  return tracked.point;
}

function trackedDerefMut_deref_mut(tracked) {
  return tracked.point;
}

function outerDeref_deref(outer) {
  return outer[0];
}

function gridIndex_usize__usize__index(grid, [row, col]) {
  return $index(grid.cells, ((Math.imul(row, grid.width) >>> 0) + col) >>> 0);
}

function gridIndexMut_usize__usize__index_mut(grid, [row, col]) {
  return $index(grid.cells, ((Math.imul(row, grid.width) >>> 0) + col) >>> 0);
}
//# sourceMappingURL=case.js.map
