// Generated by rust-js from test/corpus/user_into_iter.rs. Do not edit.

import { $iterator } from "@rust-js/runtime";

const Count = {
  doubled(count) {
    return $iterator(count, countIterator_next)
      .map((n) => Math.imul(n, 2) >>> 0)
      .toArray();
  },
};

function main() {
  console.log(
    `[${Count.doubled([0])
      .map((item) => String(item))
      .join(", ")}]`,
  );
  const it = [1];
  const arg = countIterator_next(it);
  console.log(
    `${arg == null ? "None" : `Some(${arg})`} [${$iterator(it, countIterator_next)
      .toArray()
      .map((item) => String(item))
      .join(", ")}]`,
  );
}

export function entry() {
  main();
}

function countIterator_next(count) {
  if (count[0] < 3) {
    count[0] = (count[0] + 1) >>> 0;
    return count[0];
  }
  return undefined;
}
//# sourceMappingURL=case.js.map
