// Generated by rust-js from test/corpus/user_from_str.rs. Do not edit.

import {
  $collectResults,
  $debugParseError,
  $debugStr,
  $parseInt,
  $splitOnce,
} from "@rust-js/runtime";

var $roleFromStr, $pointErrorDisplay, $pointFromStr;

function total(text) {
  let sum = 0;
  for (const part of text.split(";")) {
    const result = pointFromStr_from_str(part);
    if (result.TAG === "Err") {
      return result;
    }
    const p = result._0;
    sum = (sum + ((p.x + p.y) | 0)) | 0;
  }
  return { TAG: "Ok", _0: sum };
}

function main() {
  const arg = roleFromStr_from_str("Admin");
  const arg$1 = roleFromStr_from_str(" member ");
  const arg$2 = roleFromStr_from_str("guest");
  console.log(
    `${arg.TAG === "Ok" ? `Ok(${arg._0})` : `Err(${$debugStr(arg._0)})`} ${arg$1.TAG === "Ok" ? `Ok(${arg$1._0})` : `Err(${$debugStr(arg$1._0)})`} ${arg$2.TAG === "Ok" ? `Ok(${arg$2._0})` : `Err(${$debugStr(arg$2._0)})`}`,
  );
  const result = roleFromStr_from_str("ADMIN");
  const arg$3 = result.TAG === "Ok" ? { TAG: "Ok", _0: result._0 === "Admin" } : result;
  console.log(`${arg$3.TAG === "Ok" ? `Ok(${arg$3._0})` : `Err(${$debugStr(arg$3._0)})`}`);
  const roles = $collectResults(["admin", "member"].values().map((s) => roleFromStr_from_str(s)));
  console.log(
    `${roles.TAG === "Ok" ? `Ok([${roles._0.map((item) => item).join(", ")}])` : `Err(${$debugStr(roles._0)})`}`,
  );
  const arg$4 = pointFromStr_from_str("3, 4");
  console.log(
    `${arg$4.TAG === "Ok" ? `Ok(${pointDebug_fmt(arg$4._0)})` : `Err(${pointErrorDebug_fmt(arg$4._0)})`}`,
  );
  const match = pointFromStr_from_str("3");
  if (match.TAG === "Ok") {
    console.log(`${pointDebug_fmt(match._0)}`);
  } else {
    console.log(`${pointErrorDisplay_fmt(match._0)}`);
  }
  const e = pointFromStr_from_str("3,x");
  if (e.TAG === "Err") {
    console.log(`${pointErrorDisplay_fmt(e._0)} ${pointErrorDebug_fmt(e._0)}`);
  }
  const result$1 = total("1,2; 3,4");
  const arg$5 = result$1.TAG === "Ok" ? result$1._0 : undefined;
  console.log(`${arg$5 == null ? "None" : `Some(${arg$5})`}`);
  const result$2 = total("1,2;oops");
  console.log(
    `${result$2.TAG === "Ok" ? String(result$2._0) : pointErrorDisplay_fmt(result$2._0)}`,
  );
}

export function entry() {
  main();
}

function roleFromStr_from_str(s) {
  const match = s.trim().toLowerCase();
  if (match === "admin") {
    return { TAG: "Ok", _0: "Admin" };
  } else if (match === "member") {
    return { TAG: "Ok", _0: "Member" };
  } else {
    return { TAG: "Err", _0: `no role ${$debugStr(match)}` };
  }
}

function pointDebug_fmt(point) {
  return `Point { x: ${point.x}, y: ${point.y} }`;
}

function pointErrorDebug_fmt(pointError) {
  if (pointError === "Shape") {
    return "Shape";
  } else {
    return `Number(${$debugParseError(pointError._0, "ParseIntError")})`;
  }
}

function pointErrorDisplay_fmt(pointError) {
  if (pointError === "Shape") {
    return "expected x,y";
  } else {
    return `bad number: ${pointError._0}`;
  }
}

function pointFromStr_from_str(s) {
  const option = $splitOnce(s, ",");
  const result = option != null ? { TAG: "Ok", _0: option } : { TAG: "Err", _0: "Shape" };
  if (result.TAG === "Err") {
    return result;
  }
  const [x, y] = result._0;
  const result$1 = $parseInt(x.trim(), -2147483648, 2147483647);
  const result$2 =
    result$1.TAG === "Err" ? { TAG: "Err", _0: { TAG: "Number", _0: result$1._0 } } : result$1;
  if (result$2.TAG === "Err") {
    return result$2;
  }
  const x$1 = result$2._0;
  const result$3 = $parseInt(y.trim(), -2147483648, 2147483647);
  const result$4 =
    result$3.TAG === "Err" ? { TAG: "Err", _0: { TAG: "Number", _0: result$3._0 } } : result$3;
  if (result$4.TAG === "Err") {
    return result$4;
  }
  const y$1 = result$4._0;
  return { TAG: "Ok", _0: { x: x$1, y: y$1 } };
}

export function roleFromStr() {
  if ($roleFromStr === undefined) {
    $roleFromStr = { from_str: roleFromStr_from_str };
  }
  return $roleFromStr;
}

export function pointErrorDisplay() {
  if ($pointErrorDisplay === undefined) {
    $pointErrorDisplay = { fmt: pointErrorDisplay_fmt };
  }
  return $pointErrorDisplay;
}

export function pointFromStr() {
  if ($pointFromStr === undefined) {
    $pointFromStr = { from_str: pointFromStr_from_str };
  }
  return $pointFromStr;
}
//# sourceMappingURL=case.js.map
