// Generated by rust-js from test/corpus/utf8_decoding.rs. Do not edit.

import {
  $byteLen,
  $debugStr,
  $debugUtf8Error,
  $fromUtf8,
  $slice,
  $utf8Decode,
  $utf8ErrorMessage,
  $utf8Lossy,
} from "@rust-js/runtime";

export function entry() {
  main();
}

function show(bytes) {
  const match = $fromUtf8(bytes);
  if (match.TAG === "Ok") {
    console.log(`ok ${$debugStr(match._0)} ${$byteLen(match._0)}`);
  } else {
    console.log(
      `err ${$utf8ErrorMessage(match._0)} | ${$debugUtf8Error(match._0)} | ${match._0.valid_up_to} ${match._0.error_len == null ? "None" : `Some(${match._0.error_len})`}`,
    );
  }
}

function main() {
  const inputs = [
    [112, 108, 97, 105, 110],
    Array.from(new TextEncoder().encode("héllo €😀")),
    [97, 98, 255, 99, 100],
    [195],
    [226, 130],
    [226, 40, 161],
    [240, 159, 152],
    [237, 160, 128],
    [192, 128],
    [245, 128, 128, 128],
    [244, 144, 128, 128],
    [97, 240, 144, 128, 65],
  ];
  for (const bytes of inputs) {
    show(bytes);
  }
  const match = $fromUtf8([104, 105, 255, 33], true);
  if (match.TAG === "Ok") {
    console.log(`${match._0}`);
  } else {
    console.log(
      `${$utf8ErrorMessage(match._0.error)} | ${$debugUtf8Error(match._0, true)} | ${$debugUtf8Error(match._0.error)}`,
    );
    console.log(`[${match._0.bytes.map((item) => String(item)).join(", ")}]`);
  }
  const arg = $fromUtf8([240, 159, 146, 150], true);
  console.log(
    `${arg.TAG === "Ok" ? `Ok(${$debugStr(arg._0)})` : `Err(${$debugUtf8Error(arg._0, true)})`}`,
  );
  const lossy = [
    [102, 105, 110, 101],
    [97, 255, 98, 226, 130, 99, 240, 159, 152],
    [237, 160, 128, 122],
    [244, 144, 128, 128, 33],
    [224, 128, 128],
    [240, 128, 128, 193],
    [225, 128, 65, 241, 128, 128],
  ];
  for (const bytes$1 of lossy) {
    const text = $utf8Lossy(bytes$1);
    const kind = text.TAG === "Borrowed" ? "borrowed" : "owned";
    console.log(`${kind} ${$debugStr(text._0)} ${$byteLen(text._0)}`);
  }
  const owned = $utf8Lossy([120, 128])._0;
  console.log(`${owned}`);
  const euro = $utf8Decode([226, 130, 172]);
  console.log(`${euro} ${$fromUtf8($slice(inputs[2], 2, 3)).TAG === "Ok"}`);
}
//# sourceMappingURL=case.js.map
