// Generated by rust-js from test/corpus/wrapping_rem_zero.rs. Do not edit.

import { $wrappingRem } from "@rust-js/runtime";

export function entry() {
  main();
}

function main() {
  console.log(`${$wrappingRem(-2147483648, -1, -2147483648)}`);
  const zero = 0;
  console.log(`${$wrappingRem(7, zero, -2147483648)}`);
}
//# sourceMappingURL=case.js.map
