// Generated by rust-js from test/corpus/write_to_string.rs. Do not edit.

import { $pad } from "@rust-js/runtime";

function render(items) {
  let out = "";
  for (const [name, n] of items) {
    out += `${$pad(name, 6, "<")}${String(n).padStart(3)}\n`;
  }
  out += `total ${items.map(([, n]) => n).reduce((a, b) => (a + b) >>> 0, 0)}`;
  return out;
}

function table(out, rows) {
  for (let i = 0; i < rows; i++) {
    out.value += `row ${i}\n`;
  }
  out.value += "end";
  out.value += ".";
  return;
}

function main() {
  console.log(
    `${render([
      ["pen", 3],
      ["ink", 12],
    ])}`,
  );
  let s = "";
  const out = { value: s };
  table(out, 2);
  s = out.value;
  console.log(`${s}`);
  let t = "x";
  t += "1";
  t += "!";
  const ok = true;
  console.log(`${t} ${ok}`);
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
