// The bindings as Cargo dependencies: `react` and `web` are crates rustc
// checks, as `react/build.sh` does, with the `cfg`s of a React release
// (ADR 0043) from its build script.

import { beforeAll, expect, test } from "bun:test";
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { cfgFlags } from "../react/cfg.js";
import { bindingInputs } from "../tooling/resources.js";
import { buildCompiler, buildReact, compiler, fixture, root, run, target } from "./support";
import { cargo, check } from "./crates";

beforeAll(buildCompiler, 600_000);

/** A workspace of one library, `ui`, of `source`, using the react crate at `react`. */
function withReact(dir: string, source: string, react = join(root, "react")): string {
  writeFileSync(join(dir, "Cargo.toml"), '[workspace]\nmembers = ["ui"]\nresolver = "2"\n');
  mkdirSync(join(dir, "ui", "src"), { recursive: true });
  writeFileSync(join(dir, "ui", "Cargo.toml"),
    `[package]\nname = "ui"\nversion = "0.1.0"\nedition = "2024"\n\n[dependencies]\nreact = { package = "rust-js-react", path = ${JSON.stringify(react)} }\n`);
  writeFileSync(join(dir, "ui", "src", "lib.rs"), source);
  return join(dir, "Cargo.toml");
}
const counter = `#![allow(non_snake_case)]
use react::{JSX, jsx, use_state};

pub fn Counter() -> JSX::Element {
    let (count, set_count) = use_state(0);
    jsx! {
        <button onClick={move |_| set_count.update(|count| count + 1)}>{count}</button>
    }
}
`;
// What only React 19.2 has: gated out of 18.2's API.
const usesUseEffectEvent = `#![allow(non_snake_case)]
use react::{JSX, jsx, use_effect_event, use_state};

pub fn App() -> JSX::Element {
    let (count, set_count) = use_state(0);
    let log = use_effect_event(move || set_count.set(*count));
    jsx! {
        <button onClick={move |_| log()}>{count}</button>
    }
}
`;
/** The JS of a module, without the lines naming where it's from. */
const body = (js: string) => readFileSync(js, "utf8").split("\n").filter((line) => !line.startsWith("// Generated by rust-js") && !line.startsWith("//# sourceMappingURL")).join("\n");

test("a component of a Cargo workspace using the react crate is the JS it is outside Cargo", async () => {
  buildReact();
  const dir = fixture("cargo-react");
  const manifest = withReact(dir, counter);
  const { js } = await check(manifest, { packageName: "ui" });
  const direct = join(dir, "direct");
  run([compiler, join(dir, "ui", "src", "lib.rs"), "-o", join(direct, "lib.js"), "--library", "--manifest", join(direct, "lib.manifest.json"),
    "--", "--crate-name", "ui", "--extern", `react=${join(target, "libreact.rmeta")}`, "-L", target]);
  expect(js).toEndWith("lib.jsx");
  expect(body(js)).toContain('import { useState } from "react";');
  expect(body(js)).toBe(body(join(direct, "lib.jsx")));
}, 600_000);

// Found in review: the bindings as the tooling installs them, under the
// app's `node_modules`, are inside its workspace, whose members they are.
test("the bindings installed inside a Cargo workspace are rustc's to check, as outside it", async () => {
  const dir = fixture("cargo-react-inside");
  const resources = join(dir, "node_modules", "@rust-js/resources");
  for (const file of bindingInputs.react) cpSync(join(root, file), join(resources, file));
  const manifest = withReact(dir, counter, join(resources, "react"));
  const { js } = await check(manifest, { packageName: "ui" });
  expect(body(js)).toContain('import { useState } from "react";');
  // A check of the whole workspace too, the bindings with it.
  run(cargo(manifest, "check", "--target", "wasm32-unknown-unknown"), 600_000, { RUSTC_WORKSPACE_WRAPPER: compiler });
}, 600_000);

test("a Cargo build is for the React release it's asked for, and follows a change of it", async () => {
  const dir = fixture("cargo-react-versions");
  const manifest = withReact(dir, usesUseEffectEvent);
  const attempt = (react: string) => check(manifest, { packageName: "ui", react });
  // The build script's `cfg`s are `react/build.sh`'s, from `cfg.js`.
  const build = join(dir, "target", "wasm32-unknown-unknown", "debug", "build");
  const flags = () => {
    const runs = readdirSync(build).filter((d) => d.startsWith("rust-js-react-") && existsSync(join(build, d, "output")));
    expect(runs.length).toBe(1);
    return readFileSync(join(build, runs[0], "output"), "utf8").split("\n").filter((line) => line.startsWith("cargo::rustc-"))
      .map((line) => line.replace("cargo::rustc-cfg=", "--cfg=").replace("cargo::rustc-check-cfg=", "--check-cfg="));
  };
  await expect(attempt("18.2.0")).rejects.toThrow("unresolved import `react::use_effect_event`");
  expect(flags()).toEqual(cfgFlags("18.2.0").flags);
  await attempt("19.3.0");
  expect(flags()).toEqual(cfgFlags("19.3.0").flags);
  await expect(attempt("18.2.0")).rejects.toThrow('#[cfg(react = "19.2")]');
}, 600_000);