// A Cargo build's JS, copied beside each module's Rust (ADR 0101), is
// published as a build's output is (ADR 0091): every byte prepared before
// any file changes, a file removed only if this build wrote it and it's
// still as written, and only import specifiers relocated. Each case runs
// `writeInSource` on a build's output made by hand, without Cargo; and the
// builder asks the compiler what it is again once it's replaced.
//
//   build output (target/)            beside the Rust (src/)
//   lib.js  util.js  old.js    ──►    lib.js  util.js  old.js   + the ledger
//   lib.js  util.js            ──►    lib.js  util.js           old.js gone, if as written

import { expect, test } from "bun:test";
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { writeInSource } from "../tooling/cargo.js";
import { createNativeBuilder } from "../tooling/build.js";
import { fixture } from "./support";

const header = (rust: string) => `// Generated by rust-js from ${rust}. Do not edit.\n`;

/** A crate's build output, in `build/`, of modules beside `src/`'s Rust. */
function crate(dir: string, name: string, modules: Record<string, string>) {
  mkdirSync(join(dir, "build", name), { recursive: true });
  mkdirSync(join(dir, name, "src"), { recursive: true });
  return {
    library: { name },
    modules: Object.entries(modules).map(([module, js]) => {
      const source = join(dir, name, "src", `${module === "" ? "lib" : module}.rs`);
      const file = join(dir, "build", name, `${module === "" ? "lib" : module}.js`);
      writeFileSync(source, "");
      writeFileSync(file, header(source) + js);
      return { file, source, module: module === "" ? [] : [module] };
    }),
  };
}

test("in source, a file is removed only if this build wrote it, and it's still as written", () => {
  const dir = fixture("in-source-ownership");
  const ledger = join(dir, "build", "in-source.json");
  const src = join(dir, "app", "src");
  writeInSource([crate(dir, "app", { "": "export const a = 1;\n", util: "export const u = 1;\n", old: "export const o = 1;\n" })], ledger);
  // A file rust-js made some other way, `rust-js tool.rs -o src/tool.js`:
  // its header says rust-js, but this build never wrote it.
  writeFileSync(join(src, "tool.js"), header(join(dir, "elsewhere", "tool.rs")) + "export const t = 1;\n");
  writeInSource([crate(dir, "app", { "": "export const a = 1;\n", util: "export const u = 1;\n" })], ledger);
  expect(existsSync(join(src, "old.js"))).toBe(false);
  expect(existsSync(join(src, "tool.js"))).toBe(true);
  // What it writes again, as it was, stays.
  expect(readFileSync(join(src, "util.js"), "utf8")).toContain("export const u = 1;");
  expect(existsSync(join(src, "lib.js"))).toBe(true);
  // One it wrote, edited since: a person's now.
  writeInSource([crate(dir, "app", { "": "export const a = 1;\n", old: "export const o = 1;\n" })], ledger);
  writeFileSync(join(src, "old.js"), readFileSync(join(src, "old.js"), "utf8") + "// mine\n");
  writeInSource([crate(dir, "app", { "": "export const a = 1;\n" })], ledger);
  expect(readFileSync(join(src, "old.js"), "utf8")).toContain("// mine");
  expect(existsSync(join(src, "util.js"))).toBe(false);
});

test("in source, only import specifiers are relocated, not text that reads like one", () => {
  const dir = fixture("in-source-imports");
  const ledger = join(dir, "build", "in-source.json");
  const app = crate(dir, "app", {
    "": 'import { Model } from "../models/lib.js";\n\nexport function main(n) {\n'
      + '  console.log(`text: import { Model } from "../models/lib.js" ${n}`);\n'
      + "  console.log('plain: from \"../models/lib.js\"');\n}\n//# sourceMappingURL=lib.js.map\n",
  });
  const models = crate(dir, "models", { "": "export const Model = 1;\n" });
  writeInSource([app, models], ledger);
  const js = readFileSync(join(dir, "app", "src", "lib.js"), "utf8");
  expect(js).toContain('import { Model } from "../../models/src/lib.js";\n');
  expect(js).toContain('console.log(`text: import { Model } from "../models/lib.js" ${n}`);');
  expect(js).toContain(`console.log('plain: from "../models/lib.js"');`);
  expect(js.endsWith("//# sourceMappingURL=lib.js.map\n")).toBe(true);
});

test("in source, a build that fails leaves the previous one's files as they were", () => {
  const dir = fixture("in-source-failure");
  const ledger = join(dir, "build", "in-source.json");
  writeInSource([crate(dir, "app", { "": "export const a = 1;\n", util: "export const u = 1;\n" })], ledger);
  const before = readFileSync(join(dir, "app", "src", "lib.js"), "utf8");
  // The next build's root is new, and its other module's map can't be read.
  const next = crate(dir, "app", { "": "export const a = 2;\n", util: "export const u = 2;\n" });
  const util = next.modules.find(m => m.module.length === 1)!;
  writeFileSync(`${util.file}.map`, "{ not json");
  expect(() => writeInSource([{ ...next, modules: next.modules.map(m => m === util ? { ...m, map: `${m.file}.map` } : m) }], ledger)).toThrow();
  expect(readFileSync(join(dir, "app", "src", "lib.js"), "utf8")).toBe(before);
});

test("the builder asks a replaced compiler what it is", async () => {
  const root = fixture("compiler-identity");
  const runtime = join(root, "node_modules", "@rust-js", "runtime");
  mkdirSync(runtime, { recursive: true });
  writeFileSync(join(runtime, "package.json"), JSON.stringify({ name: "@rust-js/runtime", version: "1.0.0" }));
  const rustJs = join(root, "rust-js");
  const compiler = (version: string) => {
    writeFileSync(rustJs, `#!/bin/sh\necho '{"version":"${version}","toolchain":"1.98.1","abi":1}'\n`);
    chmodSync(rustJs, 0o755);
  };
  compiler("1.0.0");
  const builder = createNativeBuilder({ root, rustJs, bindings: [] });
  await builder.prepare();
  // A new release, installed while a dev server runs: its runtime isn't.
  compiler("2.0.0");
  await expect(builder.prepare()).rejects.toThrow("rust-js 2.0.0 needs @rust-js/runtime 2.0.0, not the installed 1.0.0");
});
