// The playground itself (ADRs 0032, 0044), as GitHub Pages serves it: its
// static build, in Chromium. It needs rust-js.wasm (`bun run wasm`), the
// compiler it runs; without one, this is skipped.

import { expect, test } from "bun:test";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { chromium } from "@playwright/test";
import { expectSnapshot, root, run } from "./support";
import { decodeMappings, lookup } from "./sourcemap";

const wasm = join(root, "wasm/target/wasm32-wasip1/release/rust-js.wasm");
if (process.env.RUST_JS_REQUIRE_WASM && !existsSync(wasm)) {
  throw new Error("WASM parity is required: build the compiler from the candidate sources with bun run wasm");
}

// The site is compiled by rust-js.wasm, and the snapshot by the native
// compiler (test/snapshots.test.ts): the same source should give the same JS.
// When it doesn't, the wasm was built from older code than the compiler's.
test.skipIf(!existsSync(wasm))("rust-js.wasm compiles the playground as the native compiler does", () => {
  run(["bun", "wasm/web/compile-rust.ts"]);
  expectSnapshot(join(root, "wasm/web/rust"), join(root, "test/snapshots/playground"), {
    // The WASI compiler sees the crate at /wasm/web/rust.
    normalize: (text) => text.replace("// Generated by rust-js from /wasm/web/rust/", "// Generated by rust-js from wasm/web/rust/"),
    hint: "rust-js.wasm writes other JS than test/snapshots/playground: if test/snapshots.test.ts passes, the wasm is out of date; rebuild it with `bun run wasm`",
    bless: false,
  });
  const file = join(root, "wasm/web/rust/components/status_line");
  const source = readFileSync(`${file}.rs`, "utf8");
  const js = readFileSync(`${file}.jsx`, "utf8").split("\n");
  const map = JSON.parse(readFileSync(`${file}.jsx.map`, "utf8"));
  const line = js.findIndex(l => l.includes("<span"));
  expect(lookup(decodeMappings(map.mappings), line, js[line].indexOf("<span"))?.srcLine)
    .toBe(source.split("\n").findIndex(l => l.includes("<span")));
}, 300_000);

test.skipIf(!existsSync(wasm))("the playground loads, compiles, runs tests and shows errors, as React components", async () => {
  run(["bun", "run", "site"]);
  const server = Bun.spawn(["bun", "wasm/web/preview.ts"], { cwd: root, env: { ...process.env, PORT: "0" }, stdout: "pipe" });
  const browser = await chromium.launch({ headless: true });
  try {
    // preview.ts prints where it serves the site.
    const reader = server.stdout.getReader();
    let printed = "";
    while (!printed.includes("\n")) printed += new TextDecoder().decode((await reader.read()).value);
    const url = printed.match(/https?:\/\/\S+/)![0];
    const page = await browser.newPage();
    const errors: string[] = [];
    const workers: string[] = [];
    page.on("worker", worker => workers.push(worker.url()));
    page.on("pageerror", (e) => errors.push(e.message));
    await page.goto(url);
    // React rendered the page, and the old code found its parts in it.
    await page.locator("#app > h1", { hasText: "rust-js playground" }).waitFor();
    const status = page.locator("#status");
    await status.filter({ hasText: "Ready." }).waitFor({ timeout: 60_000 });
    expect(await page.locator(".cm-editor").count()).toBe(2);
    // Cancel immediately after worker creation, then compile successfully again.
    const started = page.waitForEvent("worker");
    await page.locator("#compile").click();
    await started;
    await page.locator("#cancel-compile").evaluate((button: HTMLButtonElement) => button.click());
    await status.filter({ hasText: "Failed" }).waitFor({ timeout: 60_000 });
    await page.locator(".cm-content[aria-label='Generated JavaScript']", { hasText: "Compilation cancelled" }).waitFor();
    await page.locator("#test").click();
    await status.filter({ hasText: "Tests: 5 passed, 0 failed." }).waitFor({ timeout: 60_000 });
    expect(workers.some(url => url.includes("compiler-worker"))).toBe(true);
    expect(await page.locator("#result").getAttribute("sandbox")).toBe("allow-scripts");
    const preview = await page.locator("#result").elementHandle();
    const previewFrame = await preview!.contentFrame();
    expect(await previewFrame!.evaluate(() => {
      try { void parent.document; return false; } catch { return true; }
    })).toBe(true);
    await page.locator("#example").selectOption("modules");
    await page.locator("#source-files li", { hasText: "stats.rs" }).waitFor();
    await page.locator("#compile").click();
    await status.filter({ hasText: "Compiled: 5 JS files." }).waitFor({ timeout: 60_000 });
    // Another output file, from the JavaScript side's FileTree.
    await page.locator("#output-files button", { hasText: "stats.js" }).click();
    await page.locator("#output-files button[aria-current=true]", { hasText: "stats.js" }).waitFor();
    await page.locator(".cm-content[aria-label='Generated JavaScript']", { hasText: "from /in/stats.rs" }).waitFor();
    // Named imports and aliases run in the preview, including cycles and
    // two identical modules whose thread-local state must stay independent.
    await page.locator(".cm-content[aria-label='Rust source']").click();
    await page.keyboard.press("ControlOrMeta+a");
    const counter = `use std::cell::Cell;
thread_local! { static N: Cell<u32> = Cell::new(0); }
pub fn next() -> u32 { N.set(N.get() + 1); N.get() }`;
    await page.keyboard.insertText(`
mod a { ${counter} }
mod b { ${counter} }
mod left { pub fn step(n: u32) -> u32 { if n == 0 { 1 } else { super::right::step(n - 1) } } }
mod right { pub fn step(n: u32) -> u32 { if n == 0 { 2 } else { super::left::step(n - 1) } } }
#[test] fn cycle() { assert_eq!(left::step(4), 1); assert_eq!(right::step(4), 2); }
#[test] fn aliases() { let step = 40; assert_eq!(left::step(0) + right::step(0) + step, 43); }
#[test] fn independent() { assert_eq!(a::next(), 1); assert_eq!(a::next(), 2); assert_eq!(b::next(), 1); }
`);
    await page.locator("#test").click();
    await status.filter({ hasText: "Tests: 3 passed, 0 failed." }).waitFor({ timeout: 60_000 });
    // React metadata and the same JSX parser are available inside WASM.
    await page.locator(".cm-content[aria-label='Rust source']").click();
    await page.keyboard.press("ControlOrMeta+a");
    // Paste the full source so editor auto-closing does not turn a Rust
    // lifetime's apostrophe into a character literal while typing it.
    await page.keyboard.insertText(`#![allow(non_snake_case)]
use react::{JSX, jsx};
pub struct Props { pub text: &'static str }
pub fn Tile(p: Props) -> JSX::Element {
    jsx! {
        <>
            <button disabled title={let n = 2; n.to_string()}>{true}{p.text}</button>
            <div dangerouslySetInnerHTML={react::inner_html("<b>raw</b>")} />
        </>
    }
}
pub fn App() -> JSX::Element { jsx! { <Tile text="Hello JSX" /> } }
`);
    await page.evaluate(() => { (window as any).lastResult = undefined; });
    await page.locator("#compile").click();
    await page.waitForFunction(() => (window as any).lastResult !== undefined, undefined, { timeout: 60_000 });
    const jsxResult: { ok: boolean; stderr: string } = await page.evaluate(() => ({ ok: (window as any).lastResult.ok, stderr: (window as any).lastResult.stderr }));
    expect(jsxResult.ok, jsxResult.stderr).toBe(true);
    await status.filter({ hasText: "Compiled: 1 JS file." }).waitFor({ timeout: 60_000 });
    await page.locator(".cm-content[aria-label='Generated JavaScript']", { hasText: "Hello JSX" }).waitFor();
    expect(await page.locator("#output-files li").textContent()).toContain(".jsx");
    // A React app runs in the Result frame: its JSX transformed there, and
    // React's modules linked beside the program's.
    await page.locator("#example").selectOption("react_counter");
    await page.locator("#compile").click();
    await status.filter({ hasText: "Compiled: 1 JS file." }).waitFor({ timeout: 60_000 });
    const app = page.frameLocator("#result");
    await app.locator("output", { hasText: "0" }).waitFor({ timeout: 60_000 });
    await app.getByRole("button", { name: "+" }).click();
    await app.getByRole("button", { name: "+" }).click();
    await app.getByRole("button", { name: "−" }).click();
    await app.locator("output", { hasText: "1" }).waitFor();
    // TodoMVC: its stylesheets, imported as a Vite app imports them, are the
    // frame's, and every feature of its spec works.
    await page.locator("#example").selectOption("todomvc");
    await page.locator("#source-files li", { hasText: "model.rs" }).waitFor();
    await page.locator("#compile").click();
    await status.filter({ hasText: "Compiled: 3 JS files." }).waitFor({ timeout: 60_000 });
    const todo = page.frameLocator("#result");
    const input = todo.locator(".new-todo");
    await input.waitFor({ timeout: 60_000 });
    expect(await todo.locator(".todoapp h1").evaluate((h) => [getComputedStyle(h).fontSize, getComputedStyle(h).color])).toEqual(["80px", "rgb(184, 63, 69)"]);
    expect(await todo.locator("body").evaluate((b) => getComputedStyle(b).backgroundColor)).toBe("rgb(245, 245, 245)");
    // No todos: no list, no footer.
    expect(await todo.locator(".main").count()).toBe(0);
    expect(await todo.locator(".footer").count()).toBe(0);
    for (const title of ["  Buy milk  ", "Walk the dog", "   "]) {
      await input.fill(title);
      await input.press("Enter");
    }
    const items = todo.locator(".todo-list li");
    await todo.locator(".todo-count", { hasText: "2 items left" }).waitFor();
    expect(await items.locator("label").allTextContents()).toEqual(["Buy milk", "Walk the dog"]);
    // The frame is as tall as its page, which grew past the 280px it starts at.
    await page.waitForFunction(() => document.getElementById("result")!.getBoundingClientRect().height > 400);
    // A title of spaces adds nothing, and stays, as TodoMVC's React has it.
    expect(await input.inputValue()).toBe("   ");
    // Completed: its class, the count, and the button to clear them.
    await items.nth(0).locator(".toggle").check();
    await todo.locator(".todo-count", { hasText: "1 item left" }).waitFor();
    expect(await items.nth(0).getAttribute("class")).toBe("completed");
    await todo.locator(".clear-completed").waitFor();
    // Routes: each filter, and the link of the one shown.
    await todo.getByRole("link", { name: "Active" }).click();
    await todo.locator(".filters a.selected", { hasText: "Active" }).waitFor();
    expect(await items.locator("label").allTextContents()).toEqual(["Walk the dog"]);
    await todo.getByRole("link", { name: "Completed" }).click();
    await todo.locator(".filters a.selected", { hasText: "Completed" }).waitFor();
    expect(await items.locator("label").allTextContents()).toEqual(["Buy milk"]);
    await todo.getByRole("link", { name: "All" }).click();
    await todo.locator(".filters a.selected", { hasText: "All" }).waitFor();
    // Editing: Enter saves, Escape cancels, blur saves, and empty deletes.
    const dog = items.nth(1);
    await dog.locator("label").dblclick();
    await dog.locator(".edit").fill("Walk the cat");
    await dog.locator(".edit").press("Enter");
    await dog.locator("label", { hasText: "Walk the cat" }).waitFor();
    await dog.locator("label").dblclick();
    await dog.locator(".edit").fill("nope");
    await dog.locator(".edit").press("Escape");
    await dog.locator("label", { hasText: "Walk the cat" }).waitFor();
    expect(await dog.getAttribute("class")).toBe("");
    await dog.locator("label").dblclick();
    await dog.locator(".edit").fill("Walk the bird");
    await todo.locator(".todoapp h1").click();
    await dog.locator("label", { hasText: "Walk the bird" }).waitFor();
    await input.fill("Water the plants");
    await input.press("Enter");
    await items.nth(2).locator("label").dblclick();
    await items.nth(2).locator(".edit").fill("  ");
    await items.nth(2).locator(".edit").press("Enter");
    await todo.locator(".todo-count", { hasText: "1 item left" }).waitFor();
    expect(await items.count()).toBe(2);
    // All at once, then cleared: the list and the footer go.
    await todo.locator("label[for=toggle-all]").click();
    await todo.locator(".todo-count", { hasText: "0 items left" }).waitFor();
    await todo.locator(".clear-completed").click();
    await todo.locator(".footer").waitFor({ state: "detached" });
    expect(await todo.locator(".main").count()).toBe(0);
    // An unsaved edit, compiled with ⌘/Ctrl-Enter: rustc's errors, as text.
    await page.locator(".cm-content[aria-label='Rust source']").click();
    await page.keyboard.press("ControlOrMeta+a");
    await page.keyboard.type('pub fn main() { let x: i32 = "no"; }');
    await page.keyboard.press("ControlOrMeta+Enter");
    await status.filter({ hasText: "Failed" }).waitFor({ timeout: 60_000 });
    await page.locator(".cm-content[aria-label='Generated JavaScript']", { hasText: "mismatched types" }).waitFor();
    expect(await page.locator("#output-files li").textContent()).toBe("(none)");
    expect(errors).toEqual([]);
  } finally {
    await browser.close();
    server.kill();
  }
}, 180_000);
