// @rust-js/typescript (ADR 0206): TypeScript's own parser and printer, and
// the model of declarations between them, which rust-js writes its .d.ts
// with and reads a package's declarations with.

import { expect, test } from "bun:test";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { open } from "@rust-js/typescript";
import { fixture, root } from "./support";

const declarations = `import type { ReactNode } from "react";

export interface AnchorProps<T> extends HTMLProps<T>, Aria {
    href?: string | undefined;
    readonly "aria-label"?: string;
    [prop: string]: unknown;
    onClick?(event: T, ...rest: number[]): void;
}

export type Size = "md" | "lg" | 1 | true | null;

export function Link<C extends ReactNode>(props: AnchorProps<C>, children?: readonly (string | number)[]): ReactNode;

export const Icon: [
    boolean,
    {
        id: string;
    }
];

declare namespace React {
    type Handler = (event: string) => void;
}

export default Link;
`;

test("read gives a file's declarations, by TypeScript's own parser", async () => {
  const dir = fixture("typescript-read");
  const file = join(dir, "anchor.d.ts");
  writeFileSync(file, declarations);
  const ts = await open([file]);
  try {
    const { declarations: read } = await ts.read(file);
    expect(read.map((d) => d.kind)).toEqual(["import", "interface", "type", "function", "const", "namespace", "export-default"]);
    expect(read[0]).toEqual({ kind: "import", from: "react", names: ["ReactNode"], typeOnly: true });
    expect(read[1]).toEqual({
      kind: "interface",
      name: "AnchorProps",
      exported: true,
      declare: false,
      typeParameters: [{ name: "T" }],
      extends: [
        { kind: "reference", name: "HTMLProps", args: [{ kind: "reference", name: "T", args: [] }] },
        { kind: "reference", name: "Aria", args: [] },
      ],
      members: [
        {
          kind: "property",
          name: "href",
          optional: true,
          readonly: false,
          type: { kind: "union", types: [{ kind: "keyword", keyword: "string" }, { kind: "keyword", keyword: "undefined" }] },
        },
        { kind: "property", name: "aria-label", optional: true, readonly: true, type: { kind: "keyword", keyword: "string" } },
        { kind: "index", parameter: "prop", key: { kind: "keyword", keyword: "string" }, type: { kind: "keyword", keyword: "unknown" } },
        {
          kind: "method",
          name: "onClick",
          optional: true,
          typeParameters: [],
          params: [
            { name: "event", optional: false, rest: false, type: { kind: "reference", name: "T", args: [] } },
            { name: "rest", optional: false, rest: true, type: { kind: "array", element: { kind: "keyword", keyword: "number" }, readonly: false } },
          ],
          returns: { kind: "keyword", keyword: "void" },
        },
      ],
    });
    expect(read[3].typeParameters).toEqual([{ name: "C", constraint: { kind: "reference", name: "ReactNode", args: [] } }]);
    expect(read[2]).toMatchObject({
      type: {
        kind: "union",
        types: [
          { kind: "literal", value: "md" },
          { kind: "literal", value: "lg" },
          { kind: "literal", value: 1 },
          { kind: "literal", value: true },
          { kind: "keyword", keyword: "null" },
        ],
      },
    });
    // Printed by TypeScript, it's the file again, and read again, the model.
    const printed = await ts.print({ declarations: read });
    expect(printed).toBe(declarations);
    const again = join(dir, "again.d.ts");
    writeFileSync(again, printed);
    const reopened = await open([again]);
    try {
      expect((await reopened.read(again)).declarations).toEqual(read);
    } finally {
      await reopened.close();
    }
  } finally {
    await ts.close();
  }
});

test("print writes a model as TypeScript prints it, a header first", async () => {
  const ts = await open();
  try {
    const printed = await ts.print({
      header: "// Generated by rust-js from lib.rs. Do not edit.",
      declarations: [
        { kind: "import", from: "react", names: ["NamedExoticComponent", "ReactNode"], typeOnly: true },
        {
          kind: "interface",
          name: "Props",
          exported: true,
          declare: false,
          typeParameters: [],
          extends: [{ kind: "reference", name: "Omit", args: [{ kind: "reference", name: "Anchor", args: [] }, { kind: "literal", value: "href" }] }],
          members: [{ kind: "property", name: "size", optional: true, readonly: false, type: { kind: "array", element: { kind: "union", types: [{ kind: "keyword", keyword: "string" }, { kind: "keyword", keyword: "undefined" }] }, readonly: false } }],
        },
        { kind: "export-default", name: "Props" },
      ],
    });
    expect(printed).toBe(`// Generated by rust-js from lib.rs. Do not edit.

import type { NamedExoticComponent, ReactNode } from "react";

export interface Props extends Omit<Anchor, "href"> {
    size?: (string | undefined)[];
}

export default Props;
`);
  } finally {
    await ts.close();
  }
});

// What react's generator reads (ADR 0207): React's own element attributes.
test("read takes @types/react's element attributes apart", async () => {
  const file = join(root, "node_modules/@types/react/index.d.ts");
  const ts = await open([file]);
  try {
    const { declarations: read } = await ts.read(file);
    const react = read.find((d) => d.kind === "namespace" && d.name === "React");
    const anchor = react?.kind === "namespace" ? react.declarations.find((d) => d.kind === "interface" && d.name === "AnchorHTMLAttributes") : undefined;
    expect(anchor).toMatchObject({ extends: [{ kind: "reference", name: "HTMLAttributes", args: [{ kind: "reference", name: "T" }] }] });
    expect(anchor?.kind === "interface" && anchor.members.find((m) => m.kind === "property" && m.name === "href")).toMatchObject({ optional: true });
  } finally {
    await ts.close();
  }
}, 60_000);

// What it prints is erasable syntax only, TypeScript's `erasableSyntaxOnly`
// (ADR 0206): types, which TypeScript checks as a .ts file's, and no
// namespace of values, which it refuses to print.
test("print writes erasable syntax only", async () => {
  const dir = fixture("typescript-erasable");
  const ts = await open();
  try {
    const types = await ts.print({
      declarations: [
        { kind: "import", from: "./other", names: ["Other"], typeOnly: true },
        { kind: "type", name: "Size", exported: true, declare: false, typeParameters: [], type: { kind: "union", types: [{ kind: "literal", value: "md" }, { kind: "literal", value: "lg" }] } },
        { kind: "interface", name: "Props", exported: true, declare: false, typeParameters: [], extends: [{ kind: "reference", name: "Other", args: [] }], members: [{ kind: "property", name: "size", optional: true, readonly: false, type: { kind: "reference", name: "Size", args: [] } }] },
        { kind: "namespace", name: "Types", exported: true, declare: false, declarations: [{ kind: "type", name: "Inner", exported: true, declare: false, typeParameters: [], type: { kind: "keyword", keyword: "string" } }] },
      ],
    });
    writeFileSync(join(dir, "other.ts"), "export interface Other { id?: string }\n");
    writeFileSync(join(dir, "types.ts"), types);
    writeFileSync(join(dir, "tsconfig.json"), JSON.stringify({ compilerOptions: { strict: true, noEmit: true, erasableSyntaxOnly: true, verbatimModuleSyntax: true, module: "esnext", moduleResolution: "bundler" }, files: ["types.ts"] }));
    const checked = Bun.spawnSync([process.execPath, join(root, "node_modules/typescript/bin/tsc"), "-p", join(dir, "tsconfig.json")], { cwd: dir });
    expect(checked.stdout.toString()).toBe("");
    const values = { kind: "namespace" as const, name: "Values", exported: true, declare: false, declarations: [{ kind: "const" as const, name: "x", exported: true, declare: false, type: { kind: "keyword" as const, keyword: "number" } }] };
    expect(ts.print({ declarations: [values] })).rejects.toThrow("isn't erasable");
    expect(await ts.print({ declarations: [{ ...values, declare: true }] })).toContain("declare namespace Values");
  } finally {
    await ts.close();
  }
});
