// Generated by rust-js from test/jsx/ui/card.rs. Do not edit.

export function Card(p) {
  return (
    <section>
      <h1>{p.title}</h1>
      {p.children}
    </section>
  );
}
//# sourceMappingURL=card.jsx.map
