// Generated by rust-js from examples/traits.rs. Do not edit.

import { $displayF64, $f64Max, $traitImpl } from "@rust-js/runtime";

var $circleShape, $squareShape, $blobShape, $f64Shape, $vecShape, $circleLabeled;

export function circleShape() {
  if ($circleShape === undefined) {
    $circleShape = { area: circleShape_area, name: circleShape_name };
  }
  return $circleShape;
}

function circleShape_area(circle) {
  return 3.14 * circle.r * circle.r;
}

function circleShape_name(circle) {
  return "circle";
}

export function squareShape() {
  if ($squareShape === undefined) {
    $squareShape = { area: squareShape_area, name: (self) => "shape" };
  }
  return $squareShape;
}

function squareShape_area(square) {
  return square[0] * square[0];
}

export function blobShape() {
  if ($blobShape === undefined) {
    $blobShape = { area: blobShape_area, name: (self) => "shape" };
  }
  return $blobShape;
}

function blobShape_area(blob) {
  if (blob === "Dot") {
    return 0;
  }
  return 0;
}

export function f64Shape() {
  if ($f64Shape === undefined) {
    $f64Shape = { area: f64Shape_area, name: (self) => "shape" };
  }
  return $f64Shape;
}

function f64Shape_area(self) {
  return self;
}

export function vecShape(TShape) {
  if ($vecShape === undefined) {
    $vecShape = new WeakMap();
  }
  return $traitImpl($vecShape, [TShape], () => ({
    area: (arg0) => vecShape_area(arg0, TShape),
    name: (self) => "shape",
  }));
}

function vecShape_area(vec, TShape) {
  return total(vec, TShape);
}

export function circleLabeled() {
  if ($circleLabeled === undefined) {
    $circleLabeled = {
      Shape: () => circleShape(),
      label: (self) => `${circleShape_name(self)} of area ${$displayF64(circleShape_area(self))}`,
    };
  }
  return $circleLabeled;
}

export function total(shapes, TShape) {
  return shapes.map((s) => TShape.area(s)).reduce((a, b) => a + b, -0);
}

export function largest(shapes) {
  return shapes.map((s) => s.impl.area(s.value)).reduce($f64Max, 0);
}

export function fresh(TDefault, TShape) {
  return TShape.area(TDefault.default());
}

export function demo() {
  const c = { r: 1 };
  const direct = circleShape_area(c);
  const mixed = [
    { value: c, impl: circleShape() },
    { value: [2], impl: squareShape() },
    { value: 3, impl: f64Shape() },
  ];
  return (
    direct + total([[1], [2]], squareShape()) + largest(mixed) + vecShape_area([[1]], squareShape())
  );
}
//# sourceMappingURL=traits.js.map
