// Generated by rust-js from examples/fib.rs. Do not edit.

import { $div } from "@rust-js/runtime";

export function fib(n) {
  if (n < 2) {
    return n;
  }
  return (fib((n - 1) >>> 0) + fib((n - 2) >>> 0)) >>> 0;
}

export function fib_match(n) {
  if (n === 0) {
    return 0;
  }
  if (n === 1) {
    return 1;
  }
  return (fib_match((n - 1) >>> 0) + fib_match((n - 2) >>> 0)) >>> 0;
}

export function fib_iter(n) {
  let a = 0;
  let b = 1;
  let i = 0;
  while (i < n) {
    const next = (a + b) >>> 0;
    a = b;
    b = next;
    i = (i + 1) >>> 0;
  }
  return a;
}

export function fib_loop(n) {
  let a = 0;
  let b = 1;
  let i = 0;
  while (true) {
    if (i === n) {
      return a;
    }
    const next = (a + b) >>> 0;
    a = b;
    b = next;
    i = (i + 1) >>> 0;
  }
}

export function nth(order, n) {
  if (order === "Ascending") {
    return fib_iter(n);
  }
  return fib_iter((20 - n) >>> 0);
}

export function wrap_demo(x) {
  return (Math.imul(x, 3) - 7) | 0;
}

export function ratio(a, b) {
  return $div(a, b, -2147483648) | 0;
}
//# sourceMappingURL=fib.js.map
