// Generate src/jsx_syntax/literals.rs from @types/react (ADR 0228): the
// strings each tag's attribute takes, where @types/react types it as a few
// of them, `referrerPolicy`'s `"no-referrer" | "origin" | ..`, which the JSX
// parser checks a literal against, as TypeScript does.
//
//   bun react/literals.ts [out]     writes src/jsx_syntax/literals.rs, or `out`
//
// Run it when @types/react moves: `bun run generate:literals`.

import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { open } from "@rust-js/typescript";

type Model = any;

const typesFile = join(import.meta.dir, "..", "node_modules", "@types", "react", "index.d.ts");
const typesVersion = JSON.parse(readFileSync(join(typesFile, "..", "package.json"), "utf8")).version;

const ts = await open([typesFile]);
const { declarations }: { declarations: Model[] } = await ts.read(typesFile);
await ts.close();

const react = declarations.find((d: Model) => d.kind === "namespace" && d.name === "React").declarations;
const jsx = react.find((d: Model) => d.kind === "namespace" && d.name === "JSX").declarations;
const intrinsic = jsx.find((d: Model) => d.kind === "interface" && d.name === "IntrinsicElements");
const interfaces = new Map<string, Model>(react.filter((d: Model) => d.kind === "interface").map((d: Model) => [d.name, d]));
const aliases = new Map<string, Model>(
  [...declarations, ...react].filter((d: Model) => d.kind === "type").map((d: Model) => [d.name, d.type]),
);

// The strings a type is a few of: its string literals, where it takes no
// other string; a boolean beside them, a `Booleanish`'s, is a JSX `{true}`,
// which isn't a literal. None of a type that takes any string, or another.
function strings(t: Model): string[] | null {
  switch (t.kind) {
    case "literal":
      return typeof t.value === "string" ? [t.value] : typeof t.value === "boolean" ? [] : null;
    case "keyword":
      return t.keyword === "undefined" || t.keyword === "boolean" ? [] : null;
    case "union": {
      const each = t.types.map(strings);
      return each.some((s: string[] | null) => s === null) ? null : each.flat();
    }
    case "reference": {
      const alias = aliases.get(t.name.replace(/^React\./, ""));
      return alias ? strings(alias) : null;
    }
    default:
      return null;
  }
}

// Each tag's attributes, with what its interface extends: an HTML tag's
// `DetailedHTMLProps<ButtonHTMLAttributes<..>>`, an SVG tag's `SVGProps`,
// `SVGAttributes`.
const membersOf = (name: string): Model[] => {
  const i = interfaces.get(name.replace(/^React\./, ""));
  if (!i) return [];
  return [...i.members.filter((m: Model) => m.kind === "property"), ...i.extends.flatMap((e: Model) => membersOf(e.name))];
};
const byAttribute = new Map<string, Map<string, string[]>>();
for (const member of intrinsic.members) {
  const props =
    member.type.name === "React.DetailedHTMLProps" ? member.type.args[0].name : /^React\.SVG/.test(member.type.name) ? member.type.name : null;
  if (!props) continue;
  for (const prop of membersOf(props)) {
    const allowed = strings(prop.type);
    if (!byAttribute.has(prop.name)) byAttribute.set(prop.name, new Map());
    // A tag that takes any string of it is in the table too, so a tag's own
    // isn't taken for another's.
    const own = byAttribute.get(prop.name)!;
    if (!own.has(member.name)) own.set(member.name, allowed && allowed.length > 0 ? [...new Set(allowed)].sort() : []);
  }
}

const rust = (s: string) => JSON.stringify(s);
const list = (allowed: string[]) => `&[${allowed.map(rust).join(", ")}]`;
const lines: string[] = [
  `// Generated by react/literals.ts from @types/react ${typesVersion}. Do not edit.`,
  "",
  "/// The strings an attribute of a tag takes, where @types/react types it as",
  "/// a few of them: `referrerPolicy`'s `\"no-referrer\" | \"origin\" | ..`, which",
  "/// a literal of it is checked against (ADR 0228). `None` of one that takes",
  "/// any string, or another type.",
  "pub(super) fn one_of(tag: &str, attribute: &str) -> Option<&'static [&'static str]> {",
  "    let one_of: &[&str] = match (attribute, tag) {",
];
let count = 0;
for (const [attribute, tags] of [...byAttribute].sort(([a], [b]) => (a < b ? -1 : 1))) {
  const sets = [...tags.values()];
  if (sets.every((s) => s.length === 0)) continue;
  const same = sets.every((s) => list(s) === list(sets[0]));
  if (same) {
    lines.push(`        (${rust(attribute)}, _) => ${list(sets[0])},`);
    count++;
    continue;
  }
  for (const [tag, allowed] of [...tags].sort(([a], [b]) => (a < b ? -1 : 1))) {
    if (allowed.length === 0) continue;
    lines.push(`        (${rust(attribute)}, ${rust(tag)}) => ${list(allowed)},`);
    count++;
  }
}
lines.push("        _ => return None,", "    };", "    Some(one_of)", "}");
// As `cargo fmt` writes it, by the repository's rustfmt.toml.
const root = join(import.meta.dir, "..");
const formatted = spawnSync("rustfmt", ["--edition", "2024", "--config-path", root, "--emit", "stdout"], {
  input: `${lines.join("\n")}\n`,
  encoding: "utf8",
});
if (formatted.status !== 0) throw new Error(`rustfmt failed:\n${formatted.stderr}`);
writeFileSync(process.argv[2] ?? join(root, "src", "jsx_syntax", "literals.rs"), formatted.stdout);
console.log(`src/jsx_syntax/literals.rs: ${count} attributes' strings from @types/react ${typesVersion}`);
