// Generated by rust-js from test/jsx/lib.rs. Do not edit.

import { FORWARD, LAZY, MEMO as Cached, Provider, THEME as Theme } from "./wrapped.jsx";

export function Generic(p) {
  return <span>{p.value}</span>;
}

export function Group(p) {
  return <div>{p.children}</div>;
}

export function Empty() {
  return <i />;
}

export function App() {
  const Selected = Generic;
  return (
    <>
      <Generic value={7} />
      <Generic value={8} />
      <Generic value="borrowed" />
      <Generic value={[9, 10]} />
      <Group>{[1]}</Group>
      <Selected value={11} />
      <Empty />
      <Cached label="memo" />
      <Provider />
      <LAZY />
      <FORWARD label="forward" />
      <Theme value="dark">
        <Cached label="child" />
      </Theme>
      <Theme.Provider value="legacy">
        <Cached label="old" />
      </Theme.Provider>
    </>
  );
}
//# sourceMappingURL=lib.jsx.map
