// Generated by rust-js from examples/wide.rs. Do not edit.

import {
  $bigAbs,
  $bigChecked,
  $bigCheckedDiv,
  $bigClamp,
  $bigCountOnes,
  $bigDiv,
  $bigDivEuclid,
  $bigLeadingZeros,
  $bigMax,
  $bigRem,
  $bigRemEuclid,
  $bigTrailingZeros,
  $checkedPow,
  $cmp,
  $debugJsonError,
  $debugParseError,
  $displayF64,
  $displayJsonError,
  $eq,
  $f64ToBig,
  $fromJson,
  $json,
  $max,
  $orInsert,
  $parseBig,
  $sortedEntries,
  $toJson,
  $tryFromInt,
  $unwrapErr,
  $unwrapOk,
  $zeroPad,
} from "@rust-js/runtime";

export const Id = {
  new(millis, worker, sequence) {
    const worker$1 = BigInt(worker & 1023);
    const sequence$1 = BigInt(sequence & 4095);
    return [
      BigInt.asUintN(64, (millis - 1288834974657n) << 22n) |
        BigInt.asUintN(64, worker$1 << 12n) |
        sequence$1,
    ];
  },
  millis(id) {
    return BigInt.asUintN(64, (id[0] >> 22n) + 1288834974657n);
  },
  worker(id) {
    return Number((id[0] >> 12n) & 1023n);
  },
  sequence(id) {
    return Number(id[0] & 4095n);
  },
};

export function fnv1a(text) {
  let hash = 14695981039346656037n;
  for (const c of text) {
    hash = hash ^ BigInt(c.codePointAt(0));
    hash = BigInt.asUintN(64, hash * 1099511628211n);
  }
  return hash;
}

export function balances(entries) {
  const totals = new Map();
  for (const [account, cents] of entries) {
    const value = cents;
    const current = $orInsert(totals, account, 0n);
    totals.set(account, BigInt.asIntN(64, current + value));
  }
  return totals;
}

export function dollars(cents) {
  const sign = cents < 0n ? "-" : "";
  const cents$1 = $bigAbs(cents);
  return `${sign}$${cents$1 / 100n}.${$zeroPad(String(cents$1 % 100n), 2)}`;
}

export function report() {
  let out = "";
  const id = Id.new(1700000000123n, 5, 42);
  out += `${idDebug_fmt(id)} ${Id.millis(id)} ${Id.worker(id)} ${Id.sequence(id)}\n`;
  const later = Id.new(1700000000124n, 1, 0);
  out += `${$cmp(id[0], later[0]) < 0} ${$bigMax(id[0], later[0]) === later[0]}\n`;
  for (const text of ["", "a", "rust-js"]) {
    out += `${$zeroPad(fnv1a(text).toString(16), 16)} `;
  }
  out += "\n";
  const entries = [
    ["rent", -25000000n],
    ["pay", 100000000n],
    ["rent", -25000000n],
    ["big", 9223372036854775807n / 2n],
  ];
  for (const [account, cents] of $sortedEntries(balances(entries), $cmp)) {
    const arg = dollars(cents);
    out += `${account} ${arg} `;
  }
  out += "\n";
  const max = 18446744073709551615n;
  const min = -9223372036854775808n;
  out += `${max} ${BigInt.asUintN(64, max + 1n)} ${BigInt.asIntN(64, min - 1n)} ${BigInt.asUintN(64, (1n << 53n) + 1n)} ${27021597764222979n}\n`;
  out += `${18446744073709551615n} ${BigInt.asIntN(64, max)} ${Number(BigInt.asUintN(32, max))} ${Number(BigInt.asIntN(32, min))} ${$displayF64(Number(max))} ${$displayF64(Number(BigInt.asIntN(64, 1n << 60n)))}\n`;
  out += `${$f64ToBig(1.7976931348623157e308, -9223372036854775808n, 9223372036854775807n)} ${$f64ToBig(-1.5, 0n, 18446744073709551615n)} ${$f64ToBig(NaN, -9223372036854775808n, 9223372036854775807n)} ${$f64ToBig(10000000000000000000, 0n, 18446744073709551615n)}\n`;
  const arg$1 = $bigChecked(max + 1n, 0n, 18446744073709551615n);
  const arg$2 = $bigChecked(0n - min, -9223372036854775808n, 9223372036854775807n);
  const arg$3 = $bigCheckedDiv(5n, 0n, -9223372036854775808n);
  const arg$4 = $checkedPow(10n, 19, 0n, 18446744073709551615n);
  out += `${arg$1 == null ? "None" : `Some(${arg$1})`} ${arg$2 == null ? "None" : `Some(${arg$2})`} ${arg$3 == null ? "None" : `Some(${arg$3})`} ${arg$4 == null ? "None" : `Some(${arg$4})`}\n`;
  out += `${$bigClamp(max + 9n, 0n, 18446744073709551615n)} ${$bigClamp(min - 1n, -9223372036854775808n, 9223372036854775807n)} ${$bigLeadingZeros(max)} ${$bigTrailingZeros(BigInt.asUintN(64, 1n << 40n))} ${$bigCountOnes(max)}\n`;
  const arg$5 = $bigRemEuclid(-7n, 3n, -9223372036854775808n);
  const arg$6 = $bigDivEuclid(-7n, 3n, -9223372036854775808n);
  const arg$7 = $parseBig("18446744073709551615", 0n, 18446744073709551615n);
  out += `${arg$5} ${arg$6} ${arg$7.TAG === "Ok" ? `Ok(${arg$7._0})` : `Err(${$debugParseError(arg$7._0, "ParseIntError")})`} ${$parseBig("18446744073709551616", 0n, 18446744073709551615n).TAG !== "Ok"}\n`;
  const arg$8 = $tryFromInt(max, 0, 4294967295);
  out += `${arg$8.TAG === "Ok" ? `Ok(${arg$8._0})` : `Err(${$debugParseError(arg$8._0, "TryFromIntError")})`} ${$tryFromInt(BigInt.asUintN(64, 1n << 63n), -9223372036854775808n, 9223372036854775807n).TAG !== "Ok"} ${$tryFromInt(BigInt.asIntN(64, min + min), 0, 65535).TAG === "Ok"}\n`;
  const low = $unwrapErr($tryFromInt(-1n, 0, 255));
  const arg$9 = $unwrapErr($tryFromInt(300n, 0, 255));
  const arg$10 = low === $unwrapErr($tryFromInt(300n, 0, 255));
  out += `${$debugParseError(low, "TryFromIntError")} ${low} ${arg$9} ${arg$10}\n`;
  const stamps = [1700000000000n, -5n, 0n, 9223372036854775807n, -9223372036854775808n];
  stamps.sort($cmp);
  const total = stamps
    .slice(1)
    .slice(0, 3)
    .reduce((a, b) => BigInt.asIntN(64, a + b), 0n);
  const arg$11 = $max(stamps);
  out += `[${stamps.map((item) => String(item)).join(", ")}] ${total} ${arg$11 == null ? "None" : `Some(${arg$11})`}\n`;
  const payment = { id, cents: -1999n, at: 1700000000123n };
  const text$1 = $unwrapOk(
    $toJson(payment, paymentSerialize_serialize, false),
    undefined,
    $debugJsonError,
  );
  out += `${text$1}\n`;
  const back = $unwrapOk(
    $fromJson(text$1, paymentDeserialize_deserialize),
    undefined,
    $debugJsonError,
  );
  out += `${$eq(back, payment)}\n`;
  for (const text$2 of [
    '{"id":18446744073709551615,"cents":-9223372036854775808,"at":0}',
    '{"id":-1,"cents":0,"at":0}',
    '{"id":1,"cents":9223372036854775808,"at":0}',
    '{"id":1.5,"cents":0,"at":0}',
  ]) {
    const match = $fromJson(text$2, paymentDeserialize_deserialize);
    if (match.TAG === "Ok") {
      out += `${paymentDebug_fmt(match._0)}\n`;
    } else {
      out += `${$displayJsonError(match._0)}\n`;
    }
  }
  return out;
}

export function scaled(n) {
  return BigInt.asIntN(64, n * 3n);
}

export function panics(i) {
  const zero = BigInt.asIntN(64, BigInt(i) - BigInt(i));
  if (i === 0) {
    return $bigDiv(7n, zero, -9223372036854775808n);
  }
  if (i === 1) {
    return $bigDiv(-9223372036854775808n, BigInt.asIntN(64, zero - 1n), -9223372036854775808n);
  }
  if (i === 2) {
    return $bigRem(7n, zero, -9223372036854775808n);
  }
  return $unwrapOk($parseBig("x", -9223372036854775808n, 9223372036854775807n), undefined, (e) =>
    $debugParseError(e, "ParseIntError"),
  );
}

function idDebug_fmt(id) {
  return `Id(${id[0]})`;
}

function paymentDebug_fmt(payment) {
  return `Payment { id: ${idDebug_fmt(payment.id)}, cents: ${payment.cents}, at: ${payment.at} }`;
}

function paymentSerialize_serialize(payment, json) {
  json.beginObject();
  json.key("id");
  idSerialize_serialize(payment.id, json);
  json.key("cents");
  json.int(payment.cents);
  json.key("at");
  json.int(payment.at);
  json.endObject();
}

function paymentDeserialize_deserialize(json) {
  return json.struct(
    "struct Payment",
    [
      ["id", idDeserialize_deserialize],
      ["cents", $json.i64],
      ["at", $json.i64],
    ],
    ([id, cents, at]) => ({ id, cents, at }),
  );
}

function idSerialize_serialize(id, json) {
  json.int(id[0]);
}

function idDeserialize_deserialize(json) {
  return [$json.u64(json)];
}
//# sourceMappingURL=wide.js.map
