// Generated by rust-js from examples/values.rs. Do not edit.

import {
  $at,
  $cmp,
  $debugF64,
  $debugStr,
  $displayF64,
  $eq,
  $index,
  $max,
  $sortedEntries,
} from "@rust-js/runtime";

var $valueDisplay;

export const Value = {
  get(value, key) {
    if (value.TAG === "Obj") {
      return value._0.get(key);
    }
    return undefined;
  },
  at(value, i) {
    if (value.TAG === "List") {
      return value._0[i];
    }
    return undefined;
  },
  as_num(value) {
    if (value.TAG === "Num") {
      return value._0;
    }
    return undefined;
  },
  as_str(value) {
    if (value.TAG === "Str") {
      return value._0;
    }
    return undefined;
  },
  is_null(value) {
    return value === "Null";
  },
  depth(value) {
    if (value.TAG === "List") {
      return (1 + ($max(value._0.map((x) => Value.depth(x))) ?? 0)) >>> 0;
    }
    if (value.TAG === "Obj") {
      return (
        (1 +
          ($max(
            $sortedEntries(value._0, $cmp)
              .map((entry) => entry[1])
              .map(Value.depth),
          ) ?? 0)) >>>
        0
      );
    }
    return 0;
  },
  pretty(value, indent, out) {
    const pad = " ".repeat(indent);
    if (value.TAG === "List" && value._0.length === 0) {
      out.value += "[]";
    } else if (value.TAG === "List") {
      out.value += "[\n";
      for (const [i, x] of value._0.entries()) {
        out.value += pad;
        out.value += "  ";
        Value.pretty(x, (indent + 2) >>> 0, out);
        if ((i + 1) >>> 0 < value._0.length) {
          out.value += ",";
        }
        out.value += "\n";
      }
      out.value += pad;
      out.value += "]";
    } else if (value.TAG === "Obj") {
      out.value += "{";
      let first = true;
      for (const [k, x$1] of $sortedEntries(value._0, $cmp)) {
        if (!first) {
          out.value += ", ";
        }
        first = false;
        out.value += `${$debugStr(k)}: `;
        Value.pretty(x$1, indent, out);
      }
      out.value += "}";
    } else {
      out.value += valueDisplay_fmt(value);
    }
  },
};

function price(v) {
  const value = Value.get(v, "items");
  if (value == null) {
    return undefined;
  }
  const item = Value.at(value, 1);
  if (item == null) {
    return undefined;
  }
  const value$1 = Value.get(item, "price");
  if (value$1 == null) {
    return undefined;
  }
  const p = Value.as_num(value$1);
  if (p == null) {
    return undefined;
  }
  const option = Value.get(v, "qty");
  return p * ((option != null ? Value.as_num(option) : undefined) ?? 1);
}

export function tree() {
  const shop = new Map();
  shop.set("name", { TAG: "Str", _0: 'corner "shop"' });
  shop.set("open", { TAG: "Bool", _0: true });
  shop.set("qty", { TAG: "Num", _0: 3 });
  const apple = new Map();
  apple.set("price", { TAG: "Num", _0: 0.5 });
  const pear = new Map();
  pear.set("price", { TAG: "Num", _0: 1.25 });
  pear.set("tags", { TAG: "List", _0: [{ TAG: "Str", _0: "ripe" }, "Null"] });
  shop.set("items", {
    TAG: "List",
    _0: [
      { TAG: "Obj", _0: apple },
      { TAG: "Obj", _0: pear },
      { TAG: "List", _0: [] },
    ],
  });
  const v = { TAG: "Obj", _0: shop };
  let out = "";
  out += `${valueDisplay_fmt(v)}\n`;
  let p = "";
  const out$1 = { value: p };
  Value.pretty(v, 0, out$1);
  p = out$1.value;
  out += `${p}\n`;
  const option = Value.get(v, "name");
  const s = option != null ? Value.as_str(option) : undefined;
  const name = s != null ? s.toUpperCase() : undefined;
  const tmp = price(v);
  const tmp$1 = Value.depth(v);
  const option$1 = Value.get(v, "missing");
  out += `${tmp == null ? "None" : `Some(${$debugF64(tmp)})`} ${name == null ? "None" : `Some(${$debugStr(name)})`} ${tmp$1} ${option$1 == null || Value.is_null(option$1)}\n`;
  const cloneValue = (value) =>
    value.TAG === "List"
      ? { ...value, _0: value._0.map((item) => cloneValue(item)) }
      : value.TAG === "Obj"
        ? {
            ...value,
            _0: new Map(Array.from(value._0).map(([key, value]) => [key, cloneValue(value)])),
          }
        : value;
  const copy = cloneValue(v);
  out += `${$eq(copy, v)} ${$eq({ TAG: "Num", _0: 1 }, { TAG: "Num", _0: 1 })}\n`;
  return out;
}

function bump(count, by) {
  count.value = (count.value + by) >>> 0;
  return count.value;
}

function log(out, line, count) {
  if (out.value) {
    out.value += "|";
  }
  out.value += line;
  bump(count, 1);
}

function settle(slot) {
  slot.value = ((slot.value ?? 0) + 10) >>> 0;
}

export function boxes() {
  let n = 0;
  const count = { value: n };
  const result = bump(count, 5);
  n = count.value;
  const first = result;
  const count$1 = { value: n };
  const result$1 = bump(count$1, 2);
  n = count$1.value;
  const total = (((first + result$1) >>> 0) + n) >>> 0;
  let text = "";
  for (const w of ["a", "b", "c"]) {
    const out = { value: text };
    const count$2 = { value: n };
    log(out, w, count$2);
    text = out.value;
    n = count$2.value;
  }
  const stats = { hits: 1 };
  const count$3 = { value: stats.hits };
  bump(count$3, 4);
  stats.hits = count$3.value;
  const slot = { value: stats.last };
  settle(slot);
  stats.last = slot.value;
  const slot$1 = { value: stats.last };
  settle(slot$1);
  stats.last = slot$1.value;
  const counts = [1, 2, 3];
  const count$4 = { value: $index(counts, 1) };
  bump(count$4, 40);
  counts[$at(counts, 1)] = count$4.value;
  return `${first} ${total} ${n} ${text} ${stats.hits} ${stats.last == null ? "None" : `Some(${stats.last})`} [${counts.map((item) => String(item)).join(", ")}]`;
}

export function report() {
  return `${tree()}${boxes()}\n`;
}

function valueDisplay_fmt(value) {
  let f = "";
  if (value === "Null") {
    f += "null";
  } else if (value.TAG === "Bool") {
    f += String(value._0);
  } else if (value.TAG === "Num") {
    f += $displayF64(value._0);
  } else if (value.TAG === "Str") {
    f += $debugStr(value._0);
  } else if (value.TAG === "List") {
    f += "[";
    for (const [i, x] of value._0.entries()) {
      if (i > 0) {
        f += ",";
      }
      f += valueDisplay_fmt(x);
    }
    f += "]";
  } else {
    f += "{";
    for (const item of $sortedEntries(value._0, $cmp).entries()) {
      if (item[0] > 0) {
        f += ",";
      }
      f += `${$debugStr(item[1][0])}:${valueDisplay_fmt(item[1][1])}`;
    }
    f += "}";
  }
  return f;
}

export function valueDisplay() {
  if ($valueDisplay === undefined) {
    $valueDisplay = { fmt: valueDisplay_fmt };
  }
  return $valueDisplay;
}
//# sourceMappingURL=values.js.map
