// Generated by rust-js from test/jsx/lib.rs. Do not edit.

import { Card as Card$2 } from "./first.jsx";
import { Card as Card$3 } from "./second.jsx";

export function Card() {
  return <b>local</b>;
}

export function View() {
  const render = (Card) => (
    <>
      <Card$2 />
      <Card$3 />
      <span>{Card}</span>
    </>
  );
  return render(9);
}
//# sourceMappingURL=lib.jsx.map
