//! Pure method-name tables, called only after library/type identity checks.

use super::{Comb, IterComb, Num, NumOp, TextOp};
use rustc_middle::mir::BinOp;

/// Which `TextOp` a method of a `char` or a `str` is.
pub(super) fn text(name: &str, char: bool, str: bool) -> Option<TextOp> {
    Some(match name {
        "is_whitespace" if char => TextOp::Is("/^\\p{White_Space}$/u"),
        "is_alphabetic" if char => TextOp::Is("/^\\p{Alphabetic}$/u"),
        "is_numeric" if char => TextOp::Is("/^\\p{N}$/u"),
        "is_alphanumeric" if char => TextOp::Is("/^[\\p{Alphabetic}\\p{N}]$/u"),
        "is_uppercase" if char => TextOp::Is("/^\\p{Uppercase}$/u"),
        "is_lowercase" if char => TextOp::Is("/^\\p{Lowercase}$/u"),
        "is_control" if char => TextOp::Is("/^\\p{Cc}$/u"),
        "is_ascii_digit" if char => TextOp::Is("/^[0-9]$/"),
        "is_ascii_hexdigit" if char => TextOp::Is("/^[0-9A-Fa-f]$/"),
        "is_ascii_alphabetic" if char => TextOp::Is("/^[A-Za-z]$/"),
        "is_ascii_alphanumeric" if char => TextOp::Is("/^[A-Za-z0-9]$/"),
        "is_ascii_uppercase" if char => TextOp::Is("/^[A-Z]$/"),
        "is_ascii_lowercase" if char => TextOp::Is("/^[a-z]$/"),
        "is_ascii_whitespace" if char => TextOp::Is("/^[ \\t\\n\\f\\r]$/"),
        "is_ascii_punctuation" if char => TextOp::Is("/^[!-\\/:-@[-`{-~]$/"),
        "is_ascii_graphic" if char => TextOp::Is("/^[!-~]$/"),
        "is_ascii_control" if char => TextOp::Is("/^[\\0-\\x1f\\x7f]$/"),
        "is_ascii" if char => TextOp::IsAscii,
        "to_ascii_uppercase" if char => TextOp::ToAsciiUpper,
        "to_ascii_lowercase" if char => TextOp::ToAsciiLower,
        "to_digit" if char => TextOp::ToDigit,
        "to_uppercase" if char => TextOp::CharCase(true),
        "to_lowercase" if char => TextOp::CharCase(false),
        "is_digit" if char => TextOp::IsDigit,
        "split_whitespace" if str => TextOp::SplitWhitespace,
        // `lines_any`, deprecated, is `lines` (ADR 0322).
        "lines" | "lines_any" if str => TextOp::Lines,
        // `s.bytes()` is `s.as_bytes()` iterated: the same array.
        // So is a `Box<str>`'s `into_boxed_bytes()`, a copy of its own.
        "as_bytes" | "bytes" | "into_boxed_bytes" if str => TextOp::Bytes,
        "parse" if str => TextOp::Parse,
        "is_ascii" if str => TextOp::Is("/^[\\0-\\x7f]*$/"),
        _ => return None,
    })
}

/// Which `NumOp` a method of a number is.
pub(super) fn number(name: &str, num: Num) -> Option<NumOp> {
    let float = num.float();
    let signed = num.signed();
    Some(match name {
        "floor" | "ceil" | "trunc" | "sqrt" | "cbrt" | "exp" | "log10" | "log2" | "sin" | "cos" | "tan" | "asin"
        | "acos" | "atan" | "sinh" | "cosh" | "tanh" | "hypot" | "atan2"
            if float =>
        {
            NumOp::Math(match name {
                "floor" => "floor",
                "ceil" => "ceil",
                "trunc" => "trunc",
                "sqrt" => "sqrt",
                "cbrt" => "cbrt",
                "exp" => "exp",
                "log10" => "log10",
                "log2" => "log2",
                "sin" => "sin",
                "cos" => "cos",
                "tan" => "tan",
                "asin" => "asin",
                "acos" => "acos",
                "atan" => "atan",
                "sinh" => "sinh",
                "cosh" => "cosh",
                "tanh" => "tanh",
                "hypot" => "hypot",
                _ => "atan2",
            })
        }
        "ln" if float => NumOp::Math("log"),
        "exp_m1" if float => NumOp::Math("expm1"),
        "ln_1p" if float => NumOp::Math("log1p"),
        "exp2" if float => NumOp::Exp2,
        "abs" if float => NumOp::Math("abs"),
        "abs" if signed => NumOp::Abs,
        "unsigned_abs" if signed => NumOp::UnsignedAbs,
        "pow" if !float => NumOp::Pow,
        "checked_pow" if !float => NumOp::CheckedPow,
        "powi" if float => NumOp::Powi,
        "powf" if float => NumOp::Powf,
        "round" if float => NumOp::Round,
        "total_cmp" if float => NumOp::TotalCmp,
        "is_nan" if float => NumOp::IsNan,
        "is_finite" if float => NumOp::IsFinite,
        "is_infinite" if float => NumOp::IsInfinite,
        "is_normal" if float => NumOp::IsNormal { subnormal: false },
        "is_subnormal" if float => NumOp::IsNormal { subnormal: true },
        "classify" if float => NumOp::Classify,
        "checked_add" if !float => NumOp::Checked(BinOp::Add),
        "checked_sub" if !float => NumOp::Checked(BinOp::Sub),
        "checked_mul" if !float => NumOp::Checked(BinOp::Mul),
        "checked_div" if !float => NumOp::Checked(BinOp::Div),
        "checked_rem" if !float => NumOp::Checked(BinOp::Rem),
        "checked_neg" if !float => NumOp::CheckedNeg,
        "checked_abs" if signed => NumOp::CheckedAbs,
        "checked_shl" if !float => NumOp::CheckedShift(BinOp::Shl),
        "checked_shr" if !float => NumOp::CheckedShift(BinOp::Shr),
        "is_positive" if signed => NumOp::IsPositive { negative: false },
        "is_negative" if signed => NumOp::IsPositive { negative: true },
        // An `abs` and a `pow` wrap, as a release build's do.
        "wrapping_abs" if signed => NumOp::Abs,
        "wrapping_pow" if !float => NumOp::Pow,
        "wrapping_neg" if !float => NumOp::WrappingNeg,
        "wrapping_div" if !float => NumOp::WrappingDiv,
        "wrapping_rem" if !float => NumOp::WrappingRem,
        "wrapping_shl" if !float => NumOp::Wrapping(BinOp::Shl),
        "wrapping_shr" if !float => NumOp::Wrapping(BinOp::Shr),
        "overflowing_add" if !float => NumOp::Overflowing(BinOp::Add),
        "overflowing_sub" if !float => NumOp::Overflowing(BinOp::Sub),
        "overflowing_mul" if !float => NumOp::Overflowing(BinOp::Mul),
        "overflowing_neg" if !float => NumOp::OverflowingNeg,
        "saturating_pow" if !float => NumOp::SaturatingPow,
        "rotate_left" if !float => NumOp::RotateBits { left: true },
        "rotate_right" if !float => NumOp::RotateBits { left: false },
        "leading_ones" if !float => NumOp::EdgeOnes { trailing: false },
        "trailing_ones" if !float => NumOp::EdgeOnes { trailing: true },
        "swap_bytes" if !float => NumOp::SwapBytes,
        "reverse_bits" if !float => NumOp::ReverseBits,
        "to_be" | "from_be" if !float => NumOp::Endian { swap: true },
        "to_le" | "from_le" if !float => NumOp::Endian { swap: false },
        "checked_div_euclid" if !float => NumOp::CheckedEuclid { rem: false },
        "checked_rem_euclid" if !float => NumOp::CheckedEuclid { rem: true },
        "recip" if float => NumOp::Recip,
        "to_be_bytes" if float => NumOp::FloatToBytes { little: false },
        "to_le_bytes" | "to_ne_bytes" if float => NumOp::FloatToBytes { little: true },
        "from_be_bytes" if float => NumOp::FloatFromBytes { little: false },
        "from_le_bytes" | "from_ne_bytes" if float => NumOp::FloatFromBytes { little: true },
        "to_be_bytes" if !float => NumOp::ToBytes { little: false },
        "to_le_bytes" | "to_ne_bytes" if !float => NumOp::ToBytes { little: true },
        "from_be_bytes" if !float => NumOp::FromBytes { little: false },
        "from_le_bytes" | "from_ne_bytes" if !float => NumOp::FromBytes { little: true },
        "to_bits" if float => NumOp::ToBits,
        "from_bits" if float => NumOp::FromBits,
        "to_int_unchecked" if float => NumOp::ToIntUnchecked,
        "saturating_add" if !float => NumOp::Saturating(BinOp::Add),
        "saturating_sub" if !float => NumOp::Saturating(BinOp::Sub),
        "saturating_mul" if !float => NumOp::Saturating(BinOp::Mul),
        "wrapping_add" if !float => NumOp::Wrapping(BinOp::Add),
        "wrapping_sub" if !float => NumOp::Wrapping(BinOp::Sub),
        "wrapping_mul" if !float => NumOp::Wrapping(BinOp::Mul),
        "rem_euclid" if !float => NumOp::RemEuclid,
        "div_euclid" if !float => NumOp::DivEuclid,
        "signum" if signed || float => NumOp::Signum,
        "clamp" if float => NumOp::Clamp,
        "from_str_radix" if !float => NumOp::FromStrRadix,
        "div_ceil" if !float && !signed => NumOp::DivCeil,
        "fract" if float => NumOp::Fract,
        "to_radians" if float => NumOp::Angle { radians: true },
        "to_degrees" if float => NumOp::Angle { radians: false },
        "is_sign_negative" if float => NumOp::SignNegative { negated: false },
        "is_sign_positive" if float => NumOp::SignNegative { negated: true },
        "ilog2" if !float => NumOp::Ilog { base: 2 },
        "ilog10" if !float => NumOp::Ilog { base: 10 },
        "isqrt" if !float => NumOp::Isqrt,
        "midpoint" if !float => NumOp::Midpoint,
        "count_zeros" if !float => NumOp::CountZeros,
        "leading_zeros" if !float => NumOp::LeadingZeros,
        "trailing_zeros" if !float => NumOp::TrailingZeros,
        "count_ones" if !float => NumOp::CountOnes,
        "is_power_of_two" if !float && !signed => NumOp::IsPowerOfTwo,
        "is_ascii_digit" if num == Num::U8 => NumOp::AsciiIs(&[(b'0', b'9')]),
        "is_ascii_hexdigit" if num == Num::U8 => NumOp::AsciiIs(&[(b'0', b'9'), (b'A', b'F'), (b'a', b'f')]),
        "is_ascii_alphabetic" if num == Num::U8 => NumOp::AsciiIs(&[(b'A', b'Z'), (b'a', b'z')]),
        "is_ascii_alphanumeric" if num == Num::U8 => NumOp::AsciiIs(&[(b'0', b'9'), (b'A', b'Z'), (b'a', b'z')]),
        "is_ascii_uppercase" if num == Num::U8 => NumOp::AsciiIs(&[(b'A', b'Z')]),
        "is_ascii_lowercase" if num == Num::U8 => NumOp::AsciiIs(&[(b'a', b'z')]),
        "is_ascii_whitespace" if num == Num::U8 => NumOp::AsciiIs(&[(b'\t', b'\n'), (0x0c, b'\r'), (b' ', b' ')]),
        "is_ascii_punctuation" if num == Num::U8 => {
            NumOp::AsciiIs(&[(b'!', b'/'), (b':', b'@'), (b'[', b'`'), (b'{', b'~')])
        }
        "is_ascii_graphic" if num == Num::U8 => NumOp::AsciiIs(&[(b'!', b'~')]),
        "is_ascii_control" if num == Num::U8 => NumOp::AsciiIs(&[(0, 0x1f), (0x7f, 0x7f)]),
        "is_ascii" if num == Num::U8 => NumOp::AsciiIs(&[(0, 0x7f)]),
        "to_ascii_uppercase" if num == Num::U8 => NumOp::AsciiCase { upper: true },
        "to_ascii_lowercase" if num == Num::U8 => NumOp::AsciiCase { upper: false },
        "abs_diff" if !float => NumOp::AbsDiff,
        _ => return None,
    })
}

/// Which `Comb` a method of an `Option`, `Result` or `Vec` is.
pub(super) fn combinator(name: &str, option: bool, result: bool, vec: bool, slice: bool) -> Option<Comb> {
    Some(match name {
        "unwrap_or_else" if option => Comb::UnwrapOrElse,
        "unwrap_or_default" if option => Comb::UnwrapOrDefault,
        "map_or" if option => Comb::MapOr,
        "map_or_else" if option => Comb::MapOrElse,
        "and_then" if option => Comb::AndThen,
        "filter" if option => Comb::Filter,
        "ok_or" if option => Comb::OkOr,
        "ok_or_else" if option => Comb::OkOrElse,
        "or" if option => Comb::Or,
        "or_else" if option => Comb::OrElse,
        "is_some_and" if option => Comb::IsSomeAnd,
        "is_none_or" if option => Comb::IsNoneOr,
        "map" if result => Comb::ResultMap,
        "map_err" if result => Comb::MapErr,
        "map_or" if result => Comb::ResultMapOr,
        "map_or_else" if result => Comb::ResultMapOrElse,
        "and_then" if result => Comb::ResultAndThen,
        "unwrap_or_else" if result => Comb::ResultUnwrapOrElse,
        "unwrap_or_default" if result => Comb::ResultUnwrapOrDefault,
        "err" if result => Comb::Err,
        "is_ok_and" if result => Comb::IsOkAnd,
        "and" if option => Comb::And,
        "xor" if option => Comb::Xor,
        "zip" if option => Comb::Zip,
        "unzip" if option => Comb::Unzip,
        "transpose" if option => Comb::OptionTranspose,
        "inspect" if option => Comb::Inspect,
        "map_or_default" if option => Comb::MapOrDefault,
        "as_slice" if option => Comb::AsSlice,
        "and" if result => Comb::ResultAnd,
        "or" if result => Comb::ResultOr,
        "or_else" if result => Comb::ResultOrElse,
        "flatten" if result => Comb::ResultFlatten,
        "inspect" if result => Comb::ResultInspect { err: false },
        "inspect_err" if result => Comb::ResultInspect { err: true },
        "iter" if result => Comb::ResultIter,
        "iter_mut" if result => Comb::ResultIterMut,
        "as_mut" if result => Comb::ResultAsMut,
        "map_or_default" if result => Comb::ResultMapOrDefault,
        "transpose" if result => Comb::ResultTranspose,
        "cloned" | "copied" if result => Comb::ResultCloned,
        "is_err_and" if result => Comb::IsErrAnd,
        "contains" if slice => Comb::Contains,
        "binary_search" if slice => Comb::BinarySearch,
        "binary_search_by" if slice => Comb::BinarySearchBy,
        "binary_search_by_key" if slice => Comb::BinarySearchByKey,
        "rotate_left" if slice => Comb::Rotate {
            left: true,
            count: "mid",
        },
        "rotate_right" if slice => Comb::Rotate {
            left: false,
            count: "k",
        },
        "extend_from_slice" if vec => Comb::ExtendFromSlice,
        "split_off" if vec => Comb::SplitOff,
        "insert" if vec => Comb::Insert,
        "remove" if vec => Comb::Remove,
        "swap" if slice => Comb::Swap,
        "truncate" if vec => Comb::Truncate,
        "dedup" if vec => Comb::Dedup,
        "dedup_by" if vec => Comb::DedupBy,
        "dedup_by_key" if vec => Comb::DedupByKey,
        "swap_remove" if vec => Comb::SwapRemove,
        "resize" if vec => Comb::Resize,
        "resize_with" if vec => Comb::ResizeWith,
        "pop_if" if vec => Comb::PopIf,
        // A `VecDeque`'s, at its back (ADR 0327).
        "pop_back_if" if vec => Comb::PopIf,
        "windows" if slice => Comb::Windows,
        "chunks" if slice => Comb::Chunks,
        "concat" if slice => Comb::Concat,
        _ => return None,
    })
}

/// Which `Comb` a method of a `bool` is.
pub(super) fn boolean(name: &str, boolean: bool) -> Option<Comb> {
    match name {
        "then" if boolean => Some(Comb::Then),
        "then_some" if boolean => Some(Comb::ThenSome),
        _ => None,
    }
}

/// Which `IterComb` an `Iterator` method is.
pub(super) fn iterator(name: &str) -> Option<IterComb> {
    Some(match name {
        "filter_map" => IterComb::FilterMap,
        "flat_map" => IterComb::FlatMap,
        "flatten" => IterComb::Flatten,
        "zip" => IterComb::Zip,
        "chain" => IterComb::Chain,
        "take_while" => IterComb::TakeWhile,
        "skip_while" => IterComb::SkipWhile,
        "step_by" => IterComb::StepBy,
        "scan" => IterComb::Scan,
        "max_by_key" => IterComb::MaxByKey(true),
        "min_by_key" => IterComb::MaxByKey(false),
        "max_by" => IterComb::MaxBy(true),
        "min_by" => IterComb::MaxBy(false),
        "product" => IterComb::Product,
        "nth" => IterComb::Nth,
        "find_map" => IterComb::FindMap,
        "partition" => IterComb::Partition,
        "inspect" => IterComb::Inspect,
        "unzip" => IterComb::Unzip,
        _ => return None,
    })
}
