// Generated by rust-js from examples/closures.rs. Do not edit.

export function by_reference(a, b) {
  let total = 0;
  const add = (x) => {
    total = (total + x) | 0;
  };
  add(a);
  add(b);
  return total;
}

export function move_copies(n) {
  let n$1 = n;
  const n$2 = n$1;
  const get = () => n$2;
  n$1 = (n$1 + 100) | 0;
  return (Math.imul(get(), 1000) + n$1) | 0;
}

export function own_state(start) {
  const count = start;
  let count$1 = count;
  const next = () => {
    count$1 = (count$1 + 1) | 0;
    return count$1;
  };
  next();
  next();
  return [next(), count];
}

export function fresh_copy_each_time(times) {
  const n = 0;
  let total = 0;
  let i = 0;
  while (i < times) {
    let n$1 = n;
    const bump = () => {
      n$1 = (n$1 + 1) | 0;
      return n$1;
    };
    total = (total + ((Math.imul(bump(), 10) + bump()) | 0)) | 0;
    i = (i + 1) | 0;
  }
  return total;
}

export function struct_copy(x) {
  const p = { x, y: 0 };
  let x$1 = p.x;
  const shift = () => {
    x$1 = (x$1 + 1) | 0;
    return x$1;
  };
  shift();
  p.y = 5;
  return [shift(), (p.x + p.y) | 0];
}

function adder(k) {
  return (x) => (x + k) | 0;
}

export function add_both(a, b) {
  const addA = adder(a);
  const addB = adder(b);
  return addA(addB(1));
}

function apply(f, a, b) {
  return f([a, b]);
}

export function pattern_param(a, b) {
  const scale = 3;
  return apply(([x, y]) => (Math.imul(x, scale) - y) | 0, a, b);
}
//# sourceMappingURL=closures.js.map
