// Writes src/typed_arrays.rs: JS's typed arrays, each of one shape over its
// element type, and the buffers they view (ADR 0283). The shape is written
// here once, as Rust, not read from TypeScript's declarations: it's the
// crate's own binding, kept by hand in this file, of eleven classes alike.
//
//   bun builtins/typed_arrays.ts

const ELEMENTS: [string, string][] = [
  ["Int8Array", "i8"], ["Uint8Array", "u8"], ["Uint8ClampedArray", "u8"], ["Int16Array", "i16"],
  ["Uint16Array", "u16"], ["Int32Array", "i32"], ["Uint32Array", "u32"], ["Float32Array", "f32"],
  ["Float64Array", "f64"], ["BigInt64Array", "i64"], ["BigUint64Array", "u64"],
];
const BYTES: Record<string, number> = { i8: 1, u8: 1, i16: 2, u16: 2, i32: 4, u32: 4, f32: 4, f64: 8, i64: 8, u64: 8 };

const snake = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase();
const page = (path: string) => `https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/${path}`;

const out: string[] = [];
const line = (s = "") => out.push(s);

/** A method: its doc, its JS, its Rust signature. */
const method = (doc: string, js: string, signature: string) => {
  line(`    /// ${doc}`);
  line(`    #[cfg_attr(rust_js, rust_js::link_name = ${JSON.stringify(js)})]`);
  line(`    pub fn ${signature} {`);
  line(`        unreachable!()`);
  line(`    }`);
  line();
};
/** An extern function of a module: a constructor or a static. */
const extern = (doc: string, js: string, signature: string, variadic = false) => {
  line(`        /// ${doc}`);
  line(`        #[link_name = ${JSON.stringify(js)}]`);
  if (variadic) line(`        #[cfg_attr(rust_js, rust_js::variadic)]`);
  line(`        pub safe fn ${signature};`);
  line();
};
const close = () => {
  if (out.at(-1) === "") out.pop();
};

line("//! JS's typed arrays and the buffers they view (ADR 0283): `Uint8Array`'s");
line("//! bytes, `Float64Array`'s numbers, each element a Rust number of its kind,");
line("//! a `BigInt64Array`'s an `i64`, the `BigInt` rust-js makes one (ADR 0086).");
line("//! Generated by `builtins/typed_arrays.ts`; edit the shape there.");
line();
line("// A binding's parameters are its JS function's: its body never runs.");
line("#![allow(unused_variables)]");
line();
line("use super::{Defined, JsError, JsObject, StructuredClone};");
line("use core::marker::PhantomData;");

// ── Buffers ──────────────────────────────────────────────────────────────

line();
line(`/// [\`ArrayBuffer\`](${page("ArrayBuffer")}): bytes, which a typed array or a`);
line("/// `DataView` reads and writes.");
line("pub struct ArrayBuffer(PhantomData<JsObject>);");
line();
line("impl ArrayBuffer {");
method(`[\`buffer.byteLength\`](${page("ArrayBuffer/byteLength")}): how many bytes it has.`, "get byteLength", "byte_length(&self) -> u32");
method(`[\`buffer.maxByteLength\`](${page("ArrayBuffer/maxByteLength")}): how many it may grow to.`, "get maxByteLength", "max_byte_length(&self) -> u32");
method(`[\`buffer.resizable\`](${page("ArrayBuffer/resizable")}): whether \`resize\` changes it.`, "get resizable", "resizable(&self) -> bool");
method(`[\`buffer.detached\`](${page("ArrayBuffer/detached")}): whether \`transfer\` took its bytes.`, "get detached", "detached(&self) -> bool");
method(`[\`buffer.slice(begin, end)\`](${page("ArrayBuffer/slice")}): a copy of its bytes from \`begin\` to \`end\`.`, "slice", "slice(&self, begin: i32, end: i32) -> &'static ArrayBuffer");
method(`[\`buffer.resize(length)\`](${page("ArrayBuffer/resize")}): its length made \`length\`, or what it throws of a fixed one.`, "resize", "resize(&self, length: u32) -> Result<(), &'static JsError>");
method(`[\`buffer.transfer()\`](${page("ArrayBuffer/transfer")}): a new buffer of its bytes, this one detached.`, "transfer", "transfer(&self) -> &'static ArrayBuffer");
method(`[\`buffer.transferToFixedLength()\`](${page("ArrayBuffer/transferToFixedLength")}): \`transfer\`, a fixed length.`, "transferToFixedLength", "transfer_to_fixed_length(&self) -> &'static ArrayBuffer");
close();
line("}");
line();
line("pub mod array_buffer {");
line("    use super::*;");
line();
line('    unsafe extern "Rust" {');
extern(`[\`new ArrayBuffer(length)\`](${page("ArrayBuffer/ArrayBuffer")}): \`length\` bytes, each 0.`, "new ArrayBuffer", "new(length: u32) -> &'static ArrayBuffer");
extern(`[\`ArrayBuffer.isView(value)\`](${page("ArrayBuffer/isView")}): whether \`value\` is a typed array or a \`DataView\`.`, "ArrayBuffer.isView", "is_view(value: &JsObject) -> bool");
close();
line("    }");
line("}");
line();
line(`/// [\`SharedArrayBuffer\`](${page("SharedArrayBuffer")}): bytes workers share.`);
line("pub struct SharedArrayBuffer(PhantomData<JsObject>);");
line();
line("impl SharedArrayBuffer {");
method(`[\`buffer.byteLength\`](${page("SharedArrayBuffer/byteLength")}): how many bytes it has.`, "get byteLength", "byte_length(&self) -> u32");
method(`[\`buffer.growable\`](${page("SharedArrayBuffer/growable")}): whether \`grow\` changes it.`, "get growable", "growable(&self) -> bool");
method(`[\`buffer.maxByteLength\`](${page("SharedArrayBuffer/maxByteLength")}): how many it may grow to.`, "get maxByteLength", "max_byte_length(&self) -> u32");
method(`[\`buffer.grow(length)\`](${page("SharedArrayBuffer/grow")}): its length made \`length\`, or what it throws.`, "grow", "grow(&self, length: u32) -> Result<(), &'static JsError>");
method(`[\`buffer.slice(begin, end)\`](${page("SharedArrayBuffer/slice")}): a copy of its bytes from \`begin\` to \`end\`.`, "slice", "slice(&self, begin: i32, end: i32) -> &'static SharedArrayBuffer");
close();
line("}");
line();
line("pub mod shared_array_buffer {");
line("    use super::*;");
line();
line('    unsafe extern "Rust" {');
extern(`[\`new SharedArrayBuffer(length)\`](${page("SharedArrayBuffer/SharedArrayBuffer")}): \`length\` bytes, each 0.`, "new SharedArrayBuffer", "new(length: u32) -> &'static SharedArrayBuffer");
close();
line("    }");
line("}");

// ── DataView ─────────────────────────────────────────────────────────────

line();
line(`/// [\`DataView\`](${page("DataView")}): a buffer's bytes read and written as numbers`);
line("/// of any kind, at any offset, big-endian unless `little_endian` says.");
line("pub struct DataView(PhantomData<JsObject>);");
line();
line("impl DataView {");
method(`[\`view.buffer\`](${page("DataView/buffer")}): the buffer it views.`, "get buffer", "buffer(&self) -> &'static ArrayBuffer");
method(`[\`view.byteLength\`](${page("DataView/byteLength")}): how many bytes it views.`, "get byteLength", "byte_length(&self) -> u32");
method(`[\`view.byteOffset\`](${page("DataView/byteOffset")}): where in its buffer it starts.`, "get byteOffset", "byte_offset(&self) -> u32");
for (const [kind, rust] of [["Int8", "i8"], ["Uint8", "u8"], ["Int16", "i16"], ["Uint16", "u16"], ["Int32", "i32"], ["Uint32", "u32"], ["Float32", "f32"], ["Float64", "f64"], ["BigInt64", "i64"], ["BigUint64", "u64"]]) {
  const one = BYTES[rust] === 1;
  method(`[\`view.get${kind}(offset${one ? "" : ", littleEndian"})\`](${page(`DataView/get${kind}`)}): the ${rust} at \`offset\`.`, `get${kind}`, `${snake(`get${kind}`)}(&self, offset: u32${one ? "" : ", little_endian: bool"}) -> ${rust}`);
  method(`[\`view.set${kind}(offset, value${one ? "" : ", littleEndian"})\`](${page(`DataView/set${kind}`)}): \`value\` written at \`offset\`.`, `set${kind}`, `${snake(`set${kind}`)}(&self, offset: u32, value: ${rust}${one ? "" : ", little_endian: bool"})`);
}
close();
line("}");
line();
line("pub mod data_view {");
line("    use super::*;");
line();
line('    unsafe extern "Rust" {');
extern(`[\`new DataView(buffer)\`](${page("DataView/DataView")}): a view of all of \`buffer\`.`, "new DataView", "new(buffer: &ArrayBuffer) -> &'static DataView");
extern(`[\`new DataView(buffer, offset, length)\`](${page("DataView/DataView")}): of \`length\` bytes from \`offset\`.`, "new DataView", "new_with_offset_and_length(buffer: &ArrayBuffer, offset: u32, length: u32) -> &'static DataView");
close();
line("    }");
line("}");

// ── The typed arrays ─────────────────────────────────────────────────────

for (const [name, e] of ELEMENTS) {
  const module = snake(name);
  const t = (m: string) => page(`TypedArray/${m}`);
  line();
  line(`/// [\`${name}\`](${page(name)}): ${BYTES[e]}-byte \`${e}\`s in an \`ArrayBuffer\`.`);
  line(`pub struct ${name}(PhantomData<JsObject>);`);
  line();
  line(`// An object, never \`undefined\`, which a structured clone copies.`);
  line(`unsafe impl Defined for ${name} {}`);
  line(`unsafe impl StructuredClone for ${name} {}`);
  line();
  line(`impl ${name} {`);
  method(`[\`array.length\`](${t("length")}): how many elements it has.`, "get length", "length(&self) -> u32");
  method(`[\`array.buffer\`](${t("buffer")}): the buffer it views.`, "get buffer", "buffer(&self) -> &'static ArrayBuffer");
  method(`[\`array.byteLength\`](${t("byteLength")}): how many bytes it views.`, "get byteLength", "byte_length(&self) -> u32");
  method(`[\`array.byteOffset\`](${t("byteOffset")}): where in its buffer it starts.`, "get byteOffset", "byte_offset(&self) -> u32");
  method(`[\`array.BYTES_PER_ELEMENT\`](${page(`TypedArray/BYTES_PER_ELEMENT`)}): ${BYTES[e]}.`, "get BYTES_PER_ELEMENT", "bytes_per_element(&self) -> u32");
  method(`\`array[index]\`: its element at \`index\`, \`None\` past its end.`, "get []", `get(&self, index: u32) -> Option<${e}>`);
  method(`\`array[index] = value\`: \`value\` written at \`index\`; past its end, nothing.`, "set []", `set_index(&self, index: u32, value: ${e})`);
  method(`[\`array.at(index)\`](${t("at")}): its element at \`index\`, from its end if negative.`, "at", `at(&self, index: i32) -> Option<${e}>`);
  method(`[\`array.set(items)\`](${t("set")}): \`items\` written from its start.`, "set", `set(&self, items: &[${e}])`);
  method(`[\`array.set(items, offset)\`](${t("set")}): \`items\` written from \`offset\`.`, "set", `set_with_offset(&self, items: &[${e}], offset: u32)`);
  method(`[\`array.fill(value)\`](${t("fill")}): each element \`value\`; itself.`, "fill", `fill(&self, value: ${e}) -> &'static ${name}`);
  method(`[\`array.copyWithin(target, start)\`](${t("copyWithin")}): its elements from \`start\` copied to \`target\`; itself.`, "copyWithin", `copy_within(&self, target: i32, start: i32) -> &'static ${name}`);
  method(`[\`array.reverse()\`](${t("reverse")}): its elements reversed, in place; itself.`, "reverse", `reverse(&self) -> &'static ${name}`);
  method(`[\`array.sort()\`](${t("sort")}): its elements in order, in place; itself.`, "sort", `sort(&self) -> &'static ${name}`);
  method(`[\`array.sort(compare)\`](${t("sort")}): in \`compare\`'s order, negative for less; itself.`, "sort", `sort_by(&self, compare: impl FnMut(${e}, ${e}) -> f64 + 'static) -> &'static ${name}`);
  method(`[\`array.toSorted()\`](${t("toSorted")}): a sorted copy.`, "toSorted", `to_sorted(&self) -> &'static ${name}`);
  method(`[\`array.toReversed()\`](${t("toReversed")}): a reversed copy.`, "toReversed", `to_reversed(&self) -> &'static ${name}`);
  method(`[\`array.with(index, value)\`](${t("with")}): a copy with \`value\` at \`index\`, or what it throws past its end.`, "with", `with(&self, index: i32, value: ${e}) -> Result<&'static ${name}, &'static JsError>`);
  method(`[\`array.slice(start, end)\`](${t("slice")}): a copy of its elements from \`start\` to \`end\`.`, "slice", `slice(&self, start: i32, end: i32) -> &'static ${name}`);
  method(`[\`array.subarray(start, end)\`](${t("subarray")}): a view of its elements from \`start\` to \`end\`, sharing its buffer.`, "subarray", `subarray(&self, start: i32, end: i32) -> &'static ${name}`);
  method(`[\`array.includes(value)\`](${t("includes")}): whether it has \`value\`, NaN too.`, "includes", `includes(&self, value: ${e}) -> bool`);
  method(`[\`array.indexOf(value)\`](${t("indexOf")}): where it first has \`value\`, or -1.`, "indexOf", `index_of(&self, value: ${e}) -> i32`);
  method(`[\`array.lastIndexOf(value)\`](${t("lastIndexOf")}): where it last has \`value\`, or -1.`, "lastIndexOf", `last_index_of(&self, value: ${e}) -> i32`);
  method(`[\`array.every(test)\`](${t("every")}): whether each element passes \`test\`.`, "every", `every(&self, test: impl FnMut(${e}) -> bool + 'static) -> bool`);
  method(`[\`array.some(test)\`](${t("some")}): whether an element passes \`test\`.`, "some", `some(&self, test: impl FnMut(${e}) -> bool + 'static) -> bool`);
  method(`[\`array.filter(test)\`](${t("filter")}): a copy of the elements that pass \`test\`.`, "filter", `filter(&self, test: impl FnMut(${e}) -> bool + 'static) -> &'static ${name}`);
  method(`[\`array.find(test)\`](${t("find")}): the first element that passes \`test\`.`, "find", `find(&self, test: impl FnMut(${e}) -> bool + 'static) -> Option<${e}>`);
  method(`[\`array.findIndex(test)\`](${t("findIndex")}): where the first that passes \`test\` is, or -1.`, "findIndex", `find_index(&self, test: impl FnMut(${e}) -> bool + 'static) -> i32`);
  method(`[\`array.findLast(test)\`](${t("findLast")}): the last element that passes \`test\`.`, "findLast", `find_last(&self, test: impl FnMut(${e}) -> bool + 'static) -> Option<${e}>`);
  method(`[\`array.findLastIndex(test)\`](${t("findLastIndex")}): where the last that passes \`test\` is, or -1.`, "findLastIndex", `find_last_index(&self, test: impl FnMut(${e}) -> bool + 'static) -> i32`);
  method(`[\`array.forEach(f)\`](${t("forEach")}): \`f\` of each element, in order.`, "forEach", `for_each(&self, f: impl FnMut(${e}) + 'static)`);
  method(`[\`array.map(f)\`](${t("map")}): a typed array of what \`f\` makes of each element.`, "map", `map(&self, f: impl FnMut(${e}) -> ${e} + 'static) -> &'static ${name}`);
  method(`[\`array.reduce(f, initial)\`](${t("reduce")}): \`f\` of each element and what it made of the ones before, from \`initial\`.`, "reduce", `reduce<A>(&self, f: impl FnMut(A, ${e}) -> A + 'static, initial: A) -> A`);
  method(`[\`array.reduceRight(f, initial)\`](${t("reduceRight")}): \`reduce\`, from its end.`, "reduceRight", `reduce_right<A>(&self, f: impl FnMut(A, ${e}) -> A + 'static, initial: A) -> A`);
  method(`[\`array.join(separator)\`](${t("join")}): its elements as text, \`separator\` between.`, "join", "join(&self, separator: &str) -> String");
  method(`[\`array.toString()\`](${t("toString")}): its elements as text, \`,\` between.`, "toString", "to_string(&self) -> String");
  method(`[\`array.toLocaleString()\`](${t("toLocaleString")}): its elements as the user's locale writes them.`, "toLocaleString", "to_locale_string(&self) -> String");
  method(`[\`array.valueOf()\`](${t("valueOf")}): itself.`, "valueOf", `value_of(&self) -> &'static ${name}`);
  method(`[\`array.keys()\`](${t("keys")}): its indices, a JS iterator (ADR 0140).`, "keys", "keys(&self) -> Box<dyn Iterator<Item = u32>>");
  method(`[\`array.values()\`](${t("values")}): its elements, a JS iterator.`, "values", `values(&self) -> Box<dyn Iterator<Item = ${e}>>`);
  method(`[\`array.entries()\`](${t("entries")}): its indices and elements, a JS iterator.`, "entries", `entries(&self) -> Box<dyn Iterator<Item = (u32, ${e})>>`);
  close();
  line("}");
  line();
  line(`pub mod ${module} {`);
  line("    use super::*;");
  line();
  line(`    /// [\`${name}.BYTES_PER_ELEMENT\`](${page("TypedArray/BYTES_PER_ELEMENT")}): how many bytes an element is.`);
  line(`    pub const BYTES_PER_ELEMENT: u32 = ${BYTES[e]};`);
  line();
  line('    unsafe extern "Rust" {');
  extern(`[\`new ${name}(length)\`](${page(`${name}/${name}`)}): \`length\` elements, each 0.`, `new ${name}`, `new(length: u32) -> &'static ${name}`);
  extern(`[\`new ${name}(buffer)\`](${page(`${name}/${name}`)}): a view of all of \`buffer\`.`, `new ${name}`, `new_with_buffer(buffer: &ArrayBuffer) -> &'static ${name}`);
  extern(`[\`new ${name}(buffer, byteOffset, length)\`](${page(`${name}/${name}`)}): a view of \`length\` elements from \`byte_offset\`.`, `new ${name}`, `new_with_buffer_offset_and_length(buffer: &ArrayBuffer, byte_offset: u32, length: u32) -> &'static ${name}`);
  extern(`[\`${name}.from(items)\`](${t("from")}): a typed array of \`items\`.`, `${name}.from`, `from(items: &[${e}]) -> &'static ${name}`);
  extern(`[\`${name}.of(..items)\`](${t("of")}): a typed array of \`items\`.`, `${name}.of`, `of(items: &[${e}]) -> &'static ${name}`, true);
  close();
  line("    }");
  line("}");
}

await Bun.write(new URL("./src/typed_arrays.rs", import.meta.url), `${out.join("\n")}\n`);
