// Generated by rust-js from test/builtins.rs. Do not edit.

import { $range, $settle, $toFixed, $try, $unwrapErr } from "@rust-js/runtime";

export function revived(text) {
  return JSON.parse(text, hidden);
}

export function holds(value, key) {
  return key in value;
}

export function named(value, key) {
  if (key in value) {
    return value[key];
  }
  return undefined;
}

export function holds_none(value, key) {
  return key in value;
}

export function wrapped(children) {
  return { children };
}

export function as_unknown(text) {
  return text;
}

export function filled() {
  const files = {};
  files["/App.js"] = 1;
  return files;
}

function hidden(key, value) {
  if (key === "secret") {
    return undefined;
  }
  return value;
}

export function quoted(text) {
  return JSON.stringify(text);
}

export function replaced(text, pattern, flags, with$) {
  return text.replace(new RegExp(pattern, flags), with$);
}

export function parts(text, part) {
  const parts$1 = [
    text.slice(1, -1),
    text.slice(-2),
    text.substring(1, 3),
    text.substring(1),
    text.trim(),
    text.trimStart(),
    text.trimEnd(),
  ];
  const at = [text.indexOf(part), text.indexOf(part, 2), text.lastIndexOf(part)];
  return [parts$1, at, text.length];
}

export function replaced_first(text, from, to) {
  return text.replace(from, to);
}

export function split_parts(text) {
  return [text.split(","), text.split(/[,;]/)];
}

export function units(text) {
  return $range(0, text.length).map((i) => text.charAt(i));
}

export function attributes(label, level) {
  return { "aria-label": label, "aria-level": String(level) };
}

export function identical(same) {
  const a = { k: 1 };
  const b = same ? a : { k: 1 };
  return [Object.is(a, b), Object.is(NaN, NaN)];
}

export async function thrown() {
  const error = $unwrapErr($try(() => decodeURIComponent("%E0%A4%A")));
  const first = error instanceof Error ? error.message : "not an Error";
  const rejected = $unwrapErr(await $settle(Promise.reject("no")));
  const second = rejected instanceof Error ? rejected.message : "not an Error";
  return [first, second];
}

export function fixed(x, digits) {
  return [x.toFixed(digits), $toFixed(x, digits)];
}

export function after(ms, done) {
  setTimeout(done, ms);
}

export function cancelled(ms, never) {
  const id = setTimeout(never, ms);
  clearTimeout(id);
}

export function every(ms, tick) {
  return setInterval(tick, ms);
}

export function stop(id) {
  clearInterval(id);
}

async function doubled(n) {
  return Math.imul(n, 2) >>> 0;
}

export async function promised(n) {
  const pending = doubled(n);
  const result = await $settle(pending);
  return result.TAG === "Ok" ? result._0 : 0;
}
//# sourceMappingURL=builtins.js.map
