// Generate src/font/google.rs, next/font/google's 1,942 fonts, from Next.js's
// own declarations, as `scripts/update-google-fonts.js` generates them
// (ADR 0359):
//
//   bun next/generate-fonts.ts          write it
//   bun next/generate-fonts.ts --check  exit 1 where it isn't what's written
//
// A font's weights, styles, subsets and axes are each one enum of every
// font's: Next.js's build refuses a value a font hasn't. A static font's
// options and weight are required, as its declaration's are; a variable
// font's are not, and it may take axes.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { open } from "@rust-js/typescript";

const next = join(import.meta.dir, "../examples/next/node_modules/next");
const declarations = join(next, "dist/compiled/@next/font/dist/google/index.d.ts");
const output = join(import.meta.dir, "src/font/google.rs");
const version = (JSON.parse(readFileSync(join(next, "package.json"), "utf8")) as { version: string }).version;

type Type = { kind: string; value?: string; types?: Type[]; args?: Type[]; element?: Type; name?: string };
type Member = { kind: string; name: string; optional: boolean; type: Type };
type Font = { name: string; variable: boolean; axes: boolean };

// Each string literal a type allows, `'400' | Array<'400'>` its `400`.
function literals(type: Type): string[] {
  switch (type.kind) {
    case "literal":
      return [type.value!];
    case "union":
      return type.types!.flatMap(literals);
    case "reference":
      return (type.args ?? []).flatMap(literals);
    case "array":
      return literals(type.element!);
    default:
      return [];
  }
}

// `latin-ext` is `LatinExt`, `400` `W400`, `wdth` `Wdth`.
function variant(value: string, prefix = ""): string {
  const words = value.split(/[^A-Za-z0-9]+/).filter(Boolean);
  const name = words.map((w) => w[0].toUpperCase() + w.slice(1).toLowerCase()).join("");
  return /^[0-9]/.test(name) ? prefix + name : name;
}

const ts = await open([declarations]);
const { declarations: found } = (await ts.read(declarations)) as { declarations: any[] };
await ts.close();

const values = { weight: new Set<string>(), style: new Set<string>(), subsets: new Set<string>(), axes: new Set<string>() };
const fonts: Font[] = [];
for (const d of found) {
  if (d.kind !== "function") continue;
  const [options] = d.params;
  const members: Member[] = options.type.members;
  for (const m of members) {
    if (m.name in values) literals(m.type).forEach((v) => values[m.name as keyof typeof values].add(v));
  }
  const weight = members.find((m) => m.name === "weight")!;
  // A variable font's options, and weight, may be left out; a static
  // font's may not.
  if (options.optional !== weight.optional) throw new Error(`${d.name}: options and weight differ in being optional`);
  fonts.push({ name: d.name, variable: options.optional, axes: members.some((m) => m.name === "axes") });
}

const order = (a: string, b: string) => {
  const [x, y] = [Number(a), Number(b)];
  return Number.isNaN(x) || Number.isNaN(y) ? a.localeCompare(b) : x - y;
};
const enumOf = (name: string, doc: string, all: Set<string>, prefix = "") => {
  const seen = new Set<string>();
  const lines = [...all].sort(order).map((value) => {
    const v = variant(value, prefix);
    if (seen.has(v)) throw new Error(`${name}: ${value} is named ${v} twice`);
    seen.add(v);
    return `    #[cfg_attr(rust_js, rust_js::name = "${value}")]\n    ${v},`;
  });
  return `/// ${doc}\n#[derive(Clone, Copy, PartialEq, Eq, Debug)]\npub enum ${name} {\n${lines.join("\n")}\n}\n`;
};

const font = ({ name, variable, axes }: Font) => {
  const options = variable ? (axes ? "VariableFont<'_>" : "VariableFontWithoutAxes<'_>") : "StaticFont<'_>";
  const kind = variable ? "a variable font" : "a static font";
  return `    /// [${name.replaceAll("_", " ")}](https://fonts.google.com/specimen/${name.replaceAll("_", "+")}), ${kind}.
    #[link_name = "next/font/google#${name}"]
    pub safe fn ${name}(options: ${options}) -> NextFont;`;
};

const rust = `//! [\`next/font/google\`](https://nextjs.org/docs/app/api-reference/components/font#google-fonts):
//! each Google Font, a function that loads it, in a \`thread_local!\` at the
//! module's top, as Next.js's compiler needs it. Generated by
//! \`next/generate-fonts.ts\` from Next.js ${version}'s declarations. Do not edit.
//!
//! \`\`\`rust,ignore
//! thread_local! {
//!     static inter: NextFont = Inter(VariableFont { subsets: Some(&[Subset::Latin]), ..Default::default() });
//! }
//! \`\`\`

#![allow(non_snake_case)]

use super::{Display, NextFont};
use crate::OneOrMany;

${enumOf("FontWeight", "A font's weight, `\"400\"`, or `\"variable\"`: each font's that it has.", values.weight, "W")}
${enumOf("FontStyle", "A font's style.", values.style)}
${enumOf("Subset", "A font's subset, the characters preloaded.", values.subsets, "S")}
${enumOf("Axis", "A variable font's axis, beside its weight.", values.axes, "A")}
/// A static font's options, as its declaration types them: its weight, or
/// weights, required, among them, so it has no \`Default\`.
pub struct StaticFont<'a> {
    pub weight: OneOrMany<'a, FontWeight>,
    pub style: Option<OneOrMany<'a, FontStyle>>,
    pub display: Option<Display>,
    /// Its CSS variable, \`"--font-inter"\`, which [\`NextFont::variable\`] names.
    pub variable: Option<&'a str>,
    pub preload: Option<bool>,
    pub fallback: Option<&'a [&'a str]>,
    #[cfg_attr(rust_js, rust_js::name = "adjustFontFallback")]
    pub adjust_font_fallback: Option<bool>,
    pub subsets: Option<&'a [Subset]>,
}

/// A variable font's options, each \`None\` but what's given: its weight
/// \`variable\` where none is.
#[derive(Default)]
pub struct VariableFont<'a> {
    pub weight: Option<OneOrMany<'a, FontWeight>>,
    pub style: Option<OneOrMany<'a, FontStyle>>,
    pub display: Option<Display>,
    pub variable: Option<&'a str>,
    pub preload: Option<bool>,
    pub fallback: Option<&'a [&'a str]>,
    #[cfg_attr(rust_js, rust_js::name = "adjustFontFallback")]
    pub adjust_font_fallback: Option<bool>,
    pub subsets: Option<&'a [Subset]>,
    /// Its axes besides its weight, \`[Axis::Opsz]\`.
    pub axes: Option<&'a [Axis]>,
}

/// A variable font's options, of one without axes besides its weight.
#[derive(Default)]
pub struct VariableFontWithoutAxes<'a> {
    pub weight: Option<OneOrMany<'a, FontWeight>>,
    pub style: Option<OneOrMany<'a, FontStyle>>,
    pub display: Option<Display>,
    pub variable: Option<&'a str>,
    pub preload: Option<bool>,
    pub fallback: Option<&'a [&'a str]>,
    #[cfg_attr(rust_js, rust_js::name = "adjustFontFallback")]
    pub adjust_font_fallback: Option<bool>,
    pub subsets: Option<&'a [Subset]>,
}

unsafe extern "Rust" {
${fonts.map(font).join("\n\n")}
}
`;

if (process.argv.includes("--check")) {
  if (readFileSync(output, "utf8") !== rust) {
    console.error(`${output} isn't what next/generate-fonts.ts writes: run it`);
    process.exit(1);
  }
} else {
  writeFileSync(output, rust);
  console.log(`${fonts.length} fonts: ${values.weight.size} weights, ${values.subsets.size} subsets, ${values.axes.size} axes`);
}
