// Generated by rust-js from examples/strings.rs. Do not edit.

import {
  $debugF64,
  $pad,
  $plus,
  $rsplitOnce,
  $splitOnce,
  $stripPrefix,
  $stripSuffix,
  $toFixed,
  $trimEnd,
  $trimStart,
  $zeroPad,
} from "@rust-js/runtime";

export function labeled(name, n) {
  return `${name}: ${n} item${n === 1 ? "" : "s"}`;
}

export function tests(s) {
  return [s.startsWith("ab"), s.endsWith("c"), s.includes("b/"), s.includes("/")];
}

export function cases(s) {
  return [s.toUpperCase(), s.toLowerCase()];
}

export function trimmed(s) {
  return [$trimStart(s), $trimEnd(s)];
}

export function replaced(s) {
  return s.replaceAll("/", " / ").replaceAll("a", "A");
}

export function module_name(path) {
  let file;
  const match = $stripPrefix(path, "src/");
  if (match != null) {
    file = match;
  } else {
    file = path;
  }
  return $stripSuffix(file, ".rs") ?? file;
}

export function parts(path) {
  const kept = [];
  let empty = 0;
  for (const part of path.split("/")) {
    if (!part) {
      empty = (empty + 1) >>> 0;
    } else {
      kept.push(part);
    }
  }
  const last = path.split("/").at(-1) ?? "";
  return [kept, empty, last];
}

export function rejoined(path) {
  const pieces = path.split("/");
  return pieces.join(" > ");
}

export function built(n) {
  let s = "";
  for (let i = 0; i < n; i++) {
    s += String(i);
    s += ",";
  }
  s += "!";
  return s;
}

export function separator(windows) {
  const c = windows ? "\\" : "/";
  const same = c === "/";
  return c + (same ? " (unix)" : " (windows)");
}

export function folder_and_file(path) {
  let first;
  const match = $splitOnce(path, "/");
  if (match != null) {
    first = match[0];
  } else {
    first = "";
  }
  let file;
  const match$1 = $rsplitOnce(path, "/");
  if (match$1 != null) {
    file = match$1[1];
  } else {
    file = path;
  }
  return [first, file];
}

export function repeated(s, n) {
  return s.repeat(n);
}

export function kind(s) {
  if (s === "") {
    return 0;
  }
  if (s === "abc" || s === "stats.rs") {
    return 1;
  }
  if (s === "äbc/Ö") {
    return 2;
  }
  if (s === "ab/c") {
    return 3;
  }
  return 4;
}

export function tagged(s) {
  const option = $splitOnce(s, "/");
  const top = option != null ? option[0] : undefined;
  let n;
  const match = s.endsWith("/");
  if (top === "ab") {
    n = 1;
  } else if (top === "" && match) {
    n = 2;
  } else if (top == null) {
    n = 3;
  } else {
    n = 4;
  }
  return [n, top != null && (top === "a" || top === "src")];
}

function tick(c) {
  c.value = (c.value + 1) >>> 0;
  return c.value;
}

export function format_order(start) {
  const c = { value: start };
  const arg = tick(c);
  const arg$1 = tick(c);
  const arg$2 = c.value;
  return `${arg$1} ${arg} ${arg} ${arg$2}`;
}

export function padded(n, name) {
  return `[${String(n).padStart(6)}] [${String(n).padEnd(6)}] [${$pad(name, 9, "^")}] [${$pad(name, 9, ">", "*")}] [${$zeroPad(String(n), 6)}] [${$plus(String(n))}] [0x${(n >>> 0).toString(16)}] [${$zeroPad("0b" + (n >>> 0).toString(2), 10)}] [${(n >>> 0).toString(16).toUpperCase()}] [${$toFixed(n / 8, 2)}] [${Array.from(name).slice(0, 3).join("")}]`;
}

export function rounded(quarters) {
  const x = quarters / 4;
  return `${$toFixed(x, 0)} ${$toFixed(x, 1)} ${$toFixed(x, 3).padStart(8)} ${$debugF64(x)}`;
}
//# sourceMappingURL=strings.js.map
