// Generated by rust-js from wasm/web/rust/components/editor.rs. Do not edit.

import { useEffect, useRef } from "react";
import { openView, setTheme, show } from "../codemirror.js";
import { useDarkMode } from "../dark_mode.js";
import { $unwrap } from "@rust-js/runtime";

export function Editor({ state, view, onSubmit }) {
  const parent = useRef(undefined);
  const made = useRef(undefined);
  const dark = useDarkMode();
  useEffect(() => {
    const editor = openView($unwrap(parent.current, "the editor's element is mounted"), state);
    made.current = editor;
    if (view != null) {
      view.current = editor;
    }
    return () => {
      editor.destroy();
      made.current = undefined;
      if (view != null) {
        view.current = undefined;
      }
    };
  }, []);
  useEffect(() => {
    const editor = made.current;
    if (editor != null) {
      show(editor, state);
      setTheme(editor, dark);
    }
  }, [state, dark]);
  return (
    <div
      className={"min-w-0 overflow-hidden [&_.cm-editor]:h-full [&_.cm-editor]:text-[13px]"}
      ref={parent}
      onKeyDownCapture={(e) => {
        if (onSubmit != null && (e.metaKey || e.ctrlKey) && e.key === "Enter") {
          e.preventDefault();
          e.stopPropagation();
          onSubmit();
        }
      }}
    />
  );
}
//# sourceMappingURL=editor.jsx.map
