[package]
name = "frontend"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
models = { path = "../models" }
serde = "1"
serde_json = "1"
js = { package = "rust-js-builtins", version = "~0.0.1" }
react = { package = "rust-js-react", version = "~0.0.2" }
webapi = { package = "rust-js-webapi", version = "~0.0.2" }
