// Generated by rust-js from test/jsx/lib.rs. Do not edit.

import { Fragment } from "react";

import { Card, Empty } from "./ui.jsx";

export function App() {
  const attrs = { title: "spread", className: "card" };
  const props = { title: "panel", children: <i>old</i> };
  const Selected = Empty;
  return (
    <Fragment key="group">
      <div title="named" {...attrs} />
      <Card title={props.title}>
        <b>new</b>
      </Card>
      <Card title="dot">
        <i />
      </Card>
      <Card title="path">
        <u />
      </Card>
      <Selected />
    </Fragment>
  );
}
//# sourceMappingURL=lib.jsx.map
