// Generated by rust-js from examples/generic_options.rs. Do not edit.

import { $pop, $some, $someAt, $someValue, $unwrap } from "@rust-js/runtime";

export function count_some(xs) {
  let n = 0;
  for (const item of xs) {
    const o = $some(item);
    if (o != null) {
      n = (n + 1) >>> 0;
    }
  }
  return n;
}

export function pick(x, keep) {
  if (keep) {
    return $some(x);
  }
  return undefined;
}

export function kept(xs) {
  let n = 0;
  for (const item of xs) {
    const match = pick(item, true);
    if (match != null) {
      n = (n + 1) >>> 0;
    }
  }
  return n;
}

export function inner_or(x, keep, fallback) {
  return $someValue(pick(x, keep) ?? $some(fallback));
}

export function unwrapped(x) {
  return $someValue($unwrap(pick(x, true)));
}

export function mapped(x, f) {
  const option = pick(x, true);
  return option != null ? $some(f($someValue(option))) : undefined;
}

export function tried(x, keep) {
  const v = pick(x, keep);
  if (v == null) {
    return undefined;
  }
  return $some($someValue(v));
}

export function popped(xs) {
  return $pop(xs);
}

export function first_of(xs) {
  return $someAt(xs, 0);
}

export function tried_some(x, keep) {
  return tried(x, keep) != null;
}

export function popped_some(xs) {
  return popped(xs) != null;
}

export function first_some(xs) {
  return first_of(xs) != null;
}

export function units() {
  return (count_some([undefined, undefined, undefined]) + kept([undefined, undefined])) >>> 0;
}

export function nones() {
  return (count_some([undefined, 1]) + kept([undefined, undefined, 2])) >>> 0;
}

export function inner_values() {
  const a = inner_or(undefined, true, 7);
  const b = inner_or(3, false, 7);
  const c = unwrapped(undefined);
  return [a, b, c, inner_or(5, true, 9)];
}

export function mapped_values() {
  const noneInside = $unwrap(mapped(undefined, (o) => o == null));
  const doubled = $unwrap(mapped(4, (n) => Math.imul(n, 2)));
  return [noneInside, tried_some(undefined, true), doubled];
}

export function std_values() {
  const poppedNone = popped_some([1, undefined]);
  const empty = popped_some([]);
  const firstNone = first_some([undefined, 1]);
  return [poppedNone, empty, firstNone, $unwrap(popped([1, 2, 3]))];
}
//# sourceMappingURL=generic_options.js.map
