// Generated by rust-js from examples/collections.rs. Do not edit.

import {
  $add,
  $at,
  $cmp,
  $cmpIn,
  $cmpItems,
  $debugStr,
  $index,
  $insert,
  $orInsert,
  $orInsertWith,
  $remove,
  $retain,
  $sortedEntries,
  $sortedKeys,
  $unwrap,
} from "@rust-js/runtime";

export function sum_to(n) {
  let total = 0;
  for (let i = 0; i < n; i++) {
    total = (total + i) >>> 0;
  }
  return total;
}

export function end_once(n) {
  let n$1 = n;
  let times = 0;
  const end = n$1;
  for (let i = 0; i < end; i++) {
    n$1 = (n$1 + 1) | 0;
    times = (times + 1) | 0;
  }
  return (Math.imul(times, 1000) + n$1) | 0;
}

export function mut_counter(n) {
  let total = 0;
  for (let i = 0; i < n; i++) {
    let i$1 = i;
    i$1 = Math.imul(i$1, 10);
    total = (total + i$1) | 0;
  }
  return total;
}

export function evens(n) {
  let v = [];
  for (let i = 0; i < n; i++) {
    if (i % 2 === 0) {
      v.push(i);
    }
  }
  return v;
}

export function keep_over(limit) {
  let v = [5, 1, 8, 3, 9, 2];
  $retain(v, (x) => x > limit);
  return v;
}

export function lengths(n) {
  let v = evens(n);
  const before = v.length;
  v.length = 0;
  return [before, v.length === 0];
}

export function iterate(n) {
  const v = evens(n);
  let total = 0;
  for (const x of v) {
    total = (total + x) >>> 0;
  }
  for (const x$1 of v) {
    total = (total + (Math.imul(x$1, 100) >>> 0)) >>> 0;
  }
  for (const [k, w] of [
    [1, 2],
    [3, 4],
  ]) {
    total = (total + (Math.imul(k, w) >>> 0)) >>> 0;
  }
  return total;
}

export function labeled(n) {
  let found = 0;
  outer: for (let i = 0; i < n; i++) {
    for (let j = 0; j < n; j++) {
      if (j > i) {
        continue outer;
      }
      if (Math.imul(i, j) >>> 0 > 20) {
        break outer;
      }
      found = (found + 1) >>> 0;
    }
  }
  return found;
}

function toggle(todos, id) {
  for (const todo of todos) {
    if (todo.id === id) {
      todo.done = !todo.done;
    }
  }
}

export function toggled(n) {
  let todos = [];
  for (let id = 0; id < n; id++) {
    todos.push({ id, done: id % 3 === 0 });
  }
  toggle(todos, 1);
  toggle(todos, 3);
  for (const todo of todos) {
    todo.id = (todo.id + 100) >>> 0;
  }
  $retain(todos, (t) => !t.done);
  let ids = 0;
  let done = 0;
  for (const todo$1 of todos) {
    ids = (ids + todo$1.id) >>> 0;
    if (todo$1.done) {
      done = (done + 1) >>> 0;
    }
  }
  return [ids, done];
}

export function cell(times) {
  const c = { value: 0 };
  for (let i = 0; i < times; i++) {
    c.value = (c.value + 2) | 0;
  }
  return (c.value + 1) | 0;
}

export function shared(times) {
  const log = { value: [] };
  const writer = log;
  for (let i = 0; i < times; i++) {
    writer.value.push(Math.imul(i, i));
  }
  const v = log.value;
  let total = 0;
  for (const x of v) {
    total = (total + x) | 0;
  }
  return [total, v.length];
}

export function words(s) {
  const owned = s;
  const trimmed = owned.trim();
  return [trimmed, trimmed.length === 0, trimmed === "hi"];
}

export function indexed(i) {
  let v = [10, 20, 30];
  const read = $index(v, i);
  v[$at(v, i)] = (read + 1) >>> 0;
  v[$at(v, 0)] = (v[$at(v, 0)] + 5) >>> 0;
  const slice = v;
  slice[$at(slice, 2)] = Math.imul(slice[$at(slice, 2)], 2) >>> 0;
  return [read, $index(v, i), v];
}

export function element_fields(i) {
  let cells = [{ hits: 0 }, { hits: 0 }];
  $index(cells, i).hits = ($index(cells, i).hits + 1) >>> 0;
  const before = { ...$index(cells, i) };
  const r = $index(cells, i);
  r.hits = 10;
  return [before.hits, $index(cells, i).hits, $index(cells, (1 - i) >>> 0).hits];
}

export function arrays(i) {
  let a = [1, 2, 3];
  const b = a.slice();
  a[$at(a, i)] = 9;
  return [$index(a, i), $index(b, i)];
}

export function word_counts(text) {
  let counts = new Map();
  for (const word of text.split(" ")) {
    const current = $orInsert(counts, word, 0);
    counts.set(word, (current + 1) >>> 0);
  }
  let all = Array.from(counts);
  all.sort((a, b) => $cmp(a[0], b[0]) || $cmp(a[1], b[1]));
  return all;
}

export function map_basics(n) {
  let m = new Map();
  m.set("a", n);
  const old = $insert(m, "a", (n + 1) >>> 0);
  m.set("b", 3);
  const removed = $remove(m, "b");
  const first = m.get("a");
  let total = 0;
  for (const [, v] of m) {
    total = (total + v) >>> 0;
  }
  const current = $unwrap(m.get("a"));
  m.set("a", (current + 10) >>> 0);
  return [
    old,
    first,
    m.has("b"),
    m.size,
    removed,
    (total + $unwrap(m.get("a"), "no entry found for key")) >>> 0,
  ];
}

export function set_basics(n) {
  let s = new Set([3, 1, 2]);
  const new$ = $add(s, n);
  const again = $add(s, n);
  const gone = s.delete(1);
  let items = Array.from(s);
  items.sort((a, b) => a - b);
  const one = new Map([["k", n]]);
  return [
    new$,
    again,
    gone,
    s.size,
    items,
    `{${Array.from(one)
      .map(([key, value]) => `${$debugStr(key)}: ${value}`)
      .join(", ")}}`,
  ];
}

export function grouped(n) {
  let groups = new Map();
  for (let i = 1; i < n; i++) {
    const key = i % 3;
    $orInsertWith(groups, key, () => []).push(i);
  }
  const copy = new Map(Array.from(groups).map(([key, value]) => [key, value.slice()]));
  const zero = groups.get(0);
  if (zero != null) {
    zero.push(99);
  }
  let all = Array.from(copy);
  all.sort((a, b) => $cmp(a[0], b[0]) || $cmpItems(a[1], b[1], $cmp));
  return all;
}

export function sorted_maps(text) {
  let counts = new Map();
  for (const word of text.split(" ")) {
    const current = $orInsert(counts, word, 0);
    counts.set(word, (current + 1) >>> 0);
  }
  let order = [];
  for (const [word$1, n] of $sortedEntries(counts, $cmp)) {
    order.push(`${word$1}=${n}`);
  }
  const set = new Set([30, 4, 100, 7]);
  const tiers = new Map([
    ["Silver", 2],
    ["Gold", 3],
    ["Bronze", 1],
  ]);
  const tmp = $sortedEntries(counts, $cmp).slice();
  const tmp$1 = order;
  const arg = $sortedKeys(set, $cmp).toReversed();
  const tmp$2 = `{${Array.from($sortedKeys(set, $cmp))
    .map((item) => String(item))
    .join(", ")}} [${arg.map((item) => String(item)).join(", ")}]`;
  const arg$1 = $unwrap(tiers.get("Bronze"), "no entry found for key");
  return [
    tmp,
    tmp$1,
    tmp$2,
    `{${Array.from($sortedEntries(tiers, (a, b) => $cmpIn(["Gold", "Bronze", "Silver"], a, b)))
      .map(([key, value]) => `${key}: ${value}`)
      .join(", ")}} ${arg$1}`,
  ];
}
//# sourceMappingURL=collections.js.map
