// Generated by rust-js from examples/todo.rs. Do not edit.

import { $retain, $trim, $unwrap } from "@rust-js/runtime";

function create(tag) {
  return document.createElement(tag);
}

function text(tag, s) {
  const e = create(tag);
  e.textContent = s;
  return e;
}

function on(target, event, state, view, change) {
  const state$1 = state;
  target.addEventListener(event, () => {
    change(state$1.value);
    render(state$1, view);
  });
}

function add(s, title) {
  s.todos.push({ id: s.next_id, title, done: false });
  s.next_id = (s.next_id + 1) >>> 0;
}

function toggle(s, id) {
  for (const todo of s.todos) {
    if (todo.id === id) {
      todo.done = !todo.done;
    }
  }
}

function shown(filter, todo) {
  if (filter === "All") {
    return true;
  } else if (filter === "Active") {
    return !todo.done;
  } else {
    return todo.done;
  }
}

function item(state, view, todo) {
  const li = create("li");
  const id = todo.id;
  const check = create("input");
  check.type = "checkbox";
  check.checked = todo.done;
  on(check, "change", state, view, (s) => {
    toggle(s, id);
  });
  const title = text("span", todo.title);
  if (todo.done) {
    title.style.setProperty("text-decoration", "line-through");
  }
  const delete$ = text("button", "×");
  on(delete$, "click", state, view, (s) => {
    $retain(s.todos, (t) => t.id !== id);
  });
  li.append(check);
  li.append(title);
  li.append(delete$);
  return li;
}

function render(state, view) {
  const s = state.value;
  view.list.textContent = "";
  let left = 0;
  for (const todo of s.todos) {
    if (!todo.done) {
      left = (left + 1) | 0;
    }
    if (shown(s.filter, todo)) {
      view.list.append(item(state, view, todo));
    }
  }
  const noun = left === 1 ? " item left" : " items left";
  view.left.textContent = String(left) + noun;
}

export function main() {
  const app = $unwrap(document.getElementById("app"), "the page has an #app");
  const state = { value: { todos: [], next_id: 1, filter: "All" } };
  const view = { list: create("ul"), left: create("span") };
  const input = create("input");
  input.placeholder = "What needs to be done?";
  const adding = state;
  input.addEventListener("keydown", (e) => {
    const title = input.value;
    const title$1 = $trim(title);
    if (e.key === "Enter" && title$1.length !== 0) {
      add(adding.value, title$1);
      input.value = "";
      render(adding, view);
    }
  });
  const footer = create("p");
  footer.append(view.left);
  for (const [label, filter] of [
    ["All", "All"],
    ["Active", "Active"],
    ["Completed", "Completed"],
  ]) {
    const b = text("button", label);
    on(b, "click", state, view, (s) => {
      s.filter = filter;
    });
    footer.append(b);
  }
  const clear = text("button", "Clear completed");
  on(clear, "click", state, view, (s) => {
    $retain(s.todos, (t) => !t.done);
  });
  footer.append(clear);
  app.append(input);
  app.append(view.list);
  app.append(footer);
  render(state, view);
}
//# sourceMappingURL=todo.js.map
