// Generated by rust-js from /wasm/web/rust/compiler.rs. Do not edit.

import {
  ConsoleStdout,
  Directory,
  File,
  OpenFile,
  PreopenDirectory,
  WASI,
} from "@bjorn3/browser_wasi_shim";
import { $extend, $rsplitOnce, $stripSuffix, $try, $unwrap } from "@rust-js/runtime";

export function ms(t) {
  return `${t.toFixed(0)} ms`;
}

export function mb(n) {
  return `${(n / 1048576).toFixed(1)} MB`;
}

export async function load(stat) {
  const start = performance.now();
  const module = loadCompiler(start, stat);
  const sysroot = loadSysroot(start, stat);
  const webapiCrate = loadBindingCrate("webapi", start, stat);
  const jsCrate = loadBindingCrate("js", start, stat);
  const reactCrate = loadBindingCrate("react", start, stat);
  const packages = loadPackages(start, stat);
  const examples = loadExamples();
  const [modules, styles] = await packages;
  const loaded = {
    module: await module,
    sysroot: await sysroot,
    webapiCrate: await webapiCrate,
    jsCrate: await jsCrate,
    reactCrate: await reactCrate,
    modules,
    styles,
    examples: await examples,
  };
  stat("ready after", ms(performance.now() - start));
  return loaded;
}

async function loadCompiler(start, stat) {
  const module = await WebAssembly.compileStreaming(window.fetch("./rust-js.wasm"));
  stat("download + compile rust-js.wasm", ms(performance.now() - start));
  return module;
}

async function loadSysroot(start, stat) {
  const names = await (await window.fetch("./sysroot.json")).json();
  const downloads = [];
  for (const name of names) {
    downloads.push(loadSysrootFile(name));
  }
  const entries = [];
  let size = 0;
  for (const download of downloads) {
    const entry = await download;
    size = (size + entry[1].data.length) >>> 0;
    entries.push(entry);
  }
  stat(
    "download sysroot",
    `${ms(performance.now() - start)} (${entries.length} files, ${mb(size)})`,
  );
  return new Map(entries);
}

async function loadSysrootFile(name) {
  const response = await window.fetch(`./sysroot/${name}`);
  const bytes = new Uint8Array(await response.arrayBuffer());
  return [name, new File(bytes, { readonly: true })];
}

async function loadPackages(start, stat) {
  const runtime = (await window.fetch("./runtime.js")).text();
  const packages = (await window.fetch("./packages.json")).json();
  const modules = [["@rust-js/runtime", await runtime]];
  const packages$1 = await packages;
  $extend(modules, Array.from(Object.entries(packages$1.modules)));
  stat("download runtime and packages", ms(performance.now() - start));
  return [modules, Object.entries(packages$1.styles)];
}

async function loadBindingCrate(name, start, stat) {
  const bytes = await (await window.fetch(`./crates/lib${name}.rmeta`)).arrayBuffer();
  stat(`download ${name} crate`, `${ms(performance.now() - start)} (${mb(bytes.byteLength)})`);
  return new File(new Uint8Array(bytes), { readonly: true });
}

async function loadExamples() {
  return await (await window.fetch("./examples.json")).json();
}

async function fetchExampleFile(name, path) {
  const response = await window.fetch(`./examples/${name}/${path}`);
  return [path, await response.text()];
}

export async function loadExample(name, paths) {
  const downloads = [];
  for (const path of paths) {
    downloads.push(fetchExampleFile(name, path));
  }
  const texts = [];
  for (const download of downloads) {
    texts.push(await download);
  }
  return texts;
}

function dir(name, entry) {
  return new Directory(new Map([[name, entry]]));
}

function directoryOf(sources) {
  const top = new Map();
  for (const [path, text] of sources) {
    let folder = top;
    let name;
    const match = $rsplitOnce(path, "/");
    if (match != null) {
      for (const part of match[0].split("/")) {
        if (!folder.has(part)) {
          folder.set(part, new Directory(new Map()));
        }
        folder = $unwrap(folder.get(part), "no entry found for key").contents;
      }
      name = match[1];
    } else {
      name = path;
    }
    const bytes = new TextEncoder().encode(text);
    folder.set(name, new File(bytes));
  }
  return top;
}

function jsFilesIn(folder, prefix, found) {
  for (const [name, entry] of Array.from(folder.contents)) {
    if (entry instanceof Directory) {
      jsFilesIn(entry, `${prefix}${name}/`, found);
    } else if (entry instanceof File && (name.endsWith(".js") || name.endsWith(".jsx"))) {
      const text = new TextDecoder().decode(entry.data);
      found.push([prefix + name, text]);
    }
  }
}

export async function compile(loaded, sources, rootFile, test) {
  const stderr = { value: [] };
  const stdoutLines = stderr;
  const stderrLines = stderr;
  const outDir = new PreopenDirectory("/out", new Map());
  const sysrootDir = new Directory(loaded.sysroot);
  const fds = [
    new OpenFile(new File([])),
    ConsoleStdout.lineBuffered((line) => {
      stdoutLines.value.push(line);
    }),
    ConsoleStdout.lineBuffered((line) => {
      stderrLines.value.push(line);
    }),
    new PreopenDirectory("/in", directoryOf(sources)),
    outDir,
    new PreopenDirectory(
      "/sysroot",
      new Map([["lib", dir("rustlib", dir("wasm32-unknown-unknown", dir("lib", sysrootDir)))]]),
    ),
    new PreopenDirectory(
      "/crates",
      new Map([
        ["libwebapi.rmeta", loaded.webapiCrate],
        ["libjs.rmeta", loaded.jsCrate],
        ["libreact.rmeta", loaded.reactCrate],
      ]),
    ),
  ];
  let outFile;
  const match = $stripSuffix(rootFile, ".rs");
  if (match != null) {
    outFile = `/out/${match}.js`;
  } else {
    outFile = `/out/${rootFile}`;
  }
  const args = ["rust-js"];
  if (test) {
    args.push("--test");
  }
  for (const arg of [`/in/${rootFile}`, "-o", outFile]) {
    args.push(arg);
  }
  for (const arg$1 of ["--", "--target", "wasm32-unknown-unknown", "--sysroot", "/sysroot"]) {
    args.push(arg$1);
  }
  if (test) {
    args.push("--cfg=browser");
  }
  for (const arg$2 of [
    "--extern",
    "webapi=/crates/libwebapi.rmeta",
    "--extern",
    "js=/crates/libjs.rmeta",
    "--extern",
    "react=/crates/libreact.rmeta",
    "-L",
    "/crates",
  ]) {
    args.push(arg$2);
  }
  const wasi = new WASI(args, ["RUSTC_ICE=0"], fds, { debug: false });
  const t0 = performance.now();
  const imports = { wasi_snapshot_preview1: wasi.wasiImport };
  const instance = await WebAssembly.instantiate(loaded.module, imports);
  const t1 = performance.now();
  const started = $try(() => wasi.start(instance));
  const t2 = performance.now();
  const ok = started.TAG === "Ok" && started._0 === 0;
  const exit =
    started.TAG === "Ok"
      ? String(started._0)
      : `trap (${started._0 instanceof Error ? started._0.message : String(started._0)})`;
  const files = [];
  if (ok) {
    jsFilesIn(outDir.dir, "", files);
  }
  const memory = instance.exports.memory.buffer;
  return {
    exit,
    ok,
    files: new Map(files),
    stderr: stderr.value.join("\n"),
    instantiate: t1 - t0,
    run: t2 - t1,
    memory: memory.byteLength,
  };
}
//# sourceMappingURL=compiler.js.map
