// Generated by rust-js from /wasm/web/rust/lib.rs. Do not edit.

import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { App } from "./components/app.jsx";
import { $unwrap } from "@rust-js/runtime";

export function start() {
  const root = createRoot($unwrap(document.getElementById("app"), "the page has an #app"));
  root.render(
    <StrictMode>
      <App />
    </StrictMode>,
  );
}
//# sourceMappingURL=lib.jsx.map
