// Generated by rust-js from /wasm/web/rust/programs.rs. Do not edit.

import { transform } from "sucrase";
import { $extend, $stripSuffix } from "@rust-js/runtime";

const TEST_RUNNER =
  '\n    const results = registered.map(({ name, f }) => {\n      if (!f) return { name, outcome: "skip" };\n      try {\n        f();\n        return { name, outcome: "pass" };\n      } catch (e) {\n        return { name, outcome: "fail", message: e instanceof Error ? e.message : String(e) };\n      }\n    });\n    document.body.replaceChildren(...results.map(({ name, outcome, message }) => {\n      const line = document.createElement("div");\n      line.className = outcome;\n      line.textContent = { pass: "✓ ", fail: "✗ ", skip: "– " }[outcome] + name + (outcome === "skip" ? " (ignored)" : "");\n      if (message) {\n        const why = document.createElement("pre");\n        why.textContent = message;\n        line.append(why);\n      }\n      return line;\n    }));\n    const count = (outcome) => results.filter((r) => r.outcome === outcome).length;';

const FRAME_HEAD = '<!doctype html>\n<meta charset="utf-8">\n<base href="about:srcdoc">';

const FRAME_STYLE =
  "<style>\n  :root { color-scheme: light dark; font: 15px/1.5 system-ui, sans-serif; }\n  body { margin: 12px; }\n  button { font: inherit; min-width: 2.5em; padding: 2px 10px; }\n  output { display: inline-block; min-width: 3em; text-align: center; font-variant-numeric: tabular-nums; }\n  .pass { color: #2f6b3a; } .fail { color: #a3321f; } .skip { color: #6b6b66; }\n  @media (prefers-color-scheme: dark) { .pass { color: #8fcf98; } .fail { color: #ef8a78; } }\n  pre { margin: 2px 0 8px 1.5em; white-space: pre-wrap; font-size: 13px; }\n</style>";

export function resolve(from, specifier) {
  if (!specifier.startsWith(".")) {
    return specifier;
  }
  const parts = from.split("/");
  parts.pop();
  for (const part of specifier.split("/")) {
    if (part === "..") {
      parts.pop();
    } else if (part !== ".") {
      parts.push(part);
    }
  }
  return parts.join("/");
}

export function link(files) {
  const imports = /^import ([^;]+?) from "([^"]+)";/gm;
  const sourceMap = /^\/\/# sourceMappingURL=.*$/m;
  const entries = [];
  for (const [path, code] of files) {
    const from = path;
    const body = code.replace(imports, (_, names, specifier) => {
      const target = JSON.stringify(`rust-js:${resolve(from, specifier)}`);
      return `import ${names} from ${target};`;
    });
    const body$1 = body.replace(sourceMap, "");
    const specifier = JSON.stringify(`rust-js:${path}`);
    const url = JSON.stringify(
      `data:text/javascript,${encodeURIComponent(body$1)}#${encodeURIComponent(path)}`,
    );
    entries.push(`${specifier}: ${url}`);
  }
  const entries$1 = entries.join(",");
  return `<script type="importmap">{"imports":{${entries$1}}}<\/script>`;
}

export function prepare(files, modules, styles, rootFile, test, run) {
  const sources = Array.from(files)
    .map(([path, code]) => [path, code])
    .map(([path, code]) => {
      const match = path.endsWith(".jsx");
      if (match) {
        const options = { transforms: ["jsx"], jsxRuntime: "automatic", production: true };
        const code$1 = transform(code, options).code;
        return [path, code$1];
      }
      return [path, code];
    });
  $extend(sources, Array.from(modules));
  let tests;
  const option = $stripSuffix(rootFile, ".jsx");
  const match = option ?? $stripSuffix(rootFile, ".js");
  if (match != null) {
    tests = `${match}.test.js`;
  } else {
    tests = rootFile;
  }
  const hasMain = /^export (async )?function main\(\)/m;
  const runnable = test
    ? sources.some(([path]) => path === tests)
    : sources.some(([path, code]) => path === rootFile && hasMain.test(code));
  if (!runnable) {
    return "Nothing";
  }
  const cssImports = /^import "([^"]+\.css)"(;)/gm;
  const css = [];
  for (const item of sources) {
    for (const [, specifier] of Array.from(item[1].matchAll(cssImports))) {
      const value = styles.find(([name]) => name === specifier);
      if (value && !css.includes(value[1])) {
        css.push(value[1]);
      }
    }
    const known = styles.map(([name]) => name);
    item[1] = item[1].replace(cssImports, (whole, specifier) => {
      if (known.includes(specifier)) {
        return "";
      }
      return whole;
    });
  }
  const look = css.length === 0 ? FRAME_STYLE : `<style>\n${css.join("")}</style>`;
  const imports = /^import (?:[^;]+? from )?"([^"]+)";/gm;
  const external = [];
  for (const [path, code] of sources) {
    for (const [, specifier$1] of Array.from(code.matchAll(imports))) {
      const target = resolve(path, specifier$1);
      if (!sources.some(([p]) => p === target) && !external.includes(specifier$1)) {
        external.push(specifier$1);
      }
    }
  }
  if (external.length !== 0) {
    return { TAG: "Blocked", _0: external };
  }
  const report = (message) => `parent.postMessage({ run: ${run}, ${message} }, "*")`;
  const linked = link(sources);
  const entry = JSON.stringify(`rust-js:${test ? tests : rootFile}`);
  const start = test
    ? `await import(${entry});\n${TEST_RUNNER}`
    : `const root = await import(${entry});\nawait root.main();`;
  const finished = test
    ? report('tested: { passed: count("pass"), failed: count("fail"), ignored: count("skip") }')
    : report("ran: true");
  const arg = report("error: String(e.message)");
  const arg$1 = report("error: String(e.reason)");
  const arg$2 = report("height: document.documentElement.scrollHeight");
  const arg$3 = report("error: String(e)");
  return {
    TAG: "Page",
    _0: `${FRAME_HEAD}
${look}
<div id="app"></div>
${linked}
<script>
  // Errors later on, in an event handler say.
  addEventListener("error", (e) => ${arg});
  // And in async code, which rejects its promise instead (ADR 0029).
  addEventListener("unhandledrejection", (e) => ${arg$1});
  // What a test file calls, as bun test provides it (ADR 0026).
  const registered = [];
  globalThis.test = (name, f) => registered.push({ name, f });
  test.skip = (name) => registered.push({ name });
  // How tall the page is, each time it changes, for the frame to show it whole.
  new ResizeObserver(() => ${arg$2}).observe(document.documentElement);
<\/script>
<script type="module">
  try {
${start}
    ${finished};
  } catch (e) {
    ${arg$3};
  }
<\/script>`,
  };
}

export function outcome(report) {
  if (report.error != null) {
    return { TAG: "Failed", _0: report.error };
  }
  if (report.ran) {
    return "Ran";
  }
  if (report.tested) {
    return { TAG: "Tested", _0: report.tested };
  }
  return;
}
//# sourceMappingURL=programs.js.map
