// Generated by rust-js from test/jsx/lib.rs. Do not edit.

export function Card(p) {
  return <section title={p.title}>{p.content}</section>;
}

export function App(active) {
  return (
    <main>
      <Card
        title="Ready"
        content={
          active ? <button onClick={() => globalThis.record(7)}>Save</button> : <span>Waiting</span>
        }
        onSubmit={() => {
          globalThis.record(8);
        }}
      />
    </main>
  );
}

export function Tokens() {
  return <Card title={"jsx! { untouched }"} content={<span />} />;
}
//# sourceMappingURL=lib.jsx.map
