// Generated by rust-js from examples/versions.rs. Do not edit.

import {
  $cmp,
  $debugF64,
  $debugStr,
  $displayF64,
  $drain,
  $fromDigit,
  $fromU32,
  $index,
  $iter,
  $lowerExp,
  $maxBy,
  $nextSome,
  $partialCmp,
  $range,
  $scan,
  $some,
  $someValue,
  $splitOff,
  $toFixed,
  $totalCmp,
  $traitImpl,
  $zeroPad,
} from "@rust-js/runtime";

var $dogDescribe, $catDescribe, $tLabeled;

function largest(items, TPartialOrd) {
  const it = $iter(items);
  const value = $nextSome(it);
  if (value == null) {
    return undefined;
  }
  let best = $someValue(value);
  for (const item of it) {
    if (TPartialOrd.partial_cmp(item, best) > 0) {
      best = item;
    }
  }
  return $some(best);
}

export function tour() {
  let out = "";
  const pets = [{ impl: dogDescribe() }, { value: { lives: 9 }, impl: catDescribe() }];
  for (const p of pets) {
    out += `${p.impl.name(p.value)} ${p.impl.describe(p.value)} ${p.impl.shout(p.value)}\n`;
  }
  out += `${tLabeled_label(42, { fmt: String })} ${tLabeled_label("hi", { fmt: (value) => value })} ${tLabeled_label(2.5, { fmt: $displayF64 })}\n`;
  const vs = [
    { major: 1, minor: 2, patch: 3 },
    { major: 1, minor: 0, patch: 9 },
    { major: 0, minor: 0, patch: 0 },
    { major: 0, minor: 9, patch: 0 },
  ];
  vs.sort((a, b) => $cmp(a.major, b.major) || $cmp(a.minor, b.minor) || $cmp(a.patch, b.patch));
  out += `[${vs
    .map((v) => `${v.major}.${v.minor}.${v.patch}`)
    .map((item) => $debugStr(item))
    .join(", ")}]\n`;
  const tmp = $maxBy(
    vs,
    (a, b) => $cmp(a.major, b.major) || $cmp(a.minor, b.minor) || $cmp(a.patch, b.patch),
  );
  const left = $index(vs, 1);
  const right = $index(vs, 2);
  out += `${tmp == null ? "None" : `Some(${versionDebug_fmt(tmp)})`} ${($cmp(left.major, right.major) || $cmp(left.minor, right.minor) || $cmp(left.patch, right.patch)) < 0}\n`;
  const c = { name: "svc", retries: 3, verbose: false, ratio: 0 };
  out += `${configDebug_fmt(c)}\n`;
  const arg = largest([3, 9, 2], { partial_cmp: $cmp });
  const arg$1 = largest([1.5, -2], { partial_cmp: $partialCmp });
  const arg$2 = largest([], { partial_cmp: $cmp });
  out += `${arg == null ? "None" : `Some(${arg})`} ${arg$1 == null ? "None" : `Some(${$debugF64(arg$1)})`} ${arg$2 == null ? "None" : `Some(${arg$2})`}\n`;
  const running = $scan([1, 2, 3, 4], 0, (acc, x) => {
    acc.value = (acc.value + x) >>> 0;
    return acc.value;
  });
  const v = $range(1, 8 + 1);
  const tail = $splitOff(v, 5);
  const drained = $drain(v, 1, 3);
  out += `[${running.map((item) => String(item)).join(", ")}] [${v.map((item) => String(item)).join(", ")}] [${tail.map((item) => String(item)).join(", ")}] [${drained.map((item) => String(item)).join(", ")}]\n`;
  const fs = [2.5, -1, 3.25, 0];
  fs.sort((a, b) => $totalCmp(a, b));
  const total = fs.reduce((a, b) => a + b, -0);
  const arg$3 = $fromDigit(7, 10);
  out += `[${fs.map((item) => $debugF64(item)).join(", ")}] ${$displayF64(total)} ${$lowerExp(1234.5)} ${$zeroPad($toFixed(-3.14159, 3), 8)} ${arg$3 == null ? "None" : `Some(${$debugStr(arg$3, "'")})`}\n`;
  const words = ["a", "b"];
  out += `${words.join("-")} ${words.join("")}\n`;
  return out;
}

function tick(c, tag) {
  c.value = ((Math.imul(c.value, 10) >>> 0) + tag) >>> 0;
  return tag;
}

function made(c) {
  tick(c, 9);
  return { major: 7, minor: 7, patch: 7 };
}

export function edges() {
  const order = { value: 0 };
  const patch = tick(order, 1);
  const major = tick(order, 2);
  const base = made(order);
  const v = { major, minor: base.minor, patch };
  const upto = $scan([5, 3, 8, 1], 1, (acc, x) => {
    acc.value = Math.imul(acc.value, x) >>> 0;
    if (acc.value > 100) {
      return undefined;
    }
    return acc.value;
  });
  const fs = [NaN, 1, -0, 0, -Infinity, -1, Infinity];
  fs.sort((a, b) => $totalCmp(a, b));
  const digits = [
    [0, 1],
    [9, 10],
    [10, 10],
    [15, 16],
    [35, 36],
  ].map(([n, r]) => $fromDigit(n, r));
  const points = [65, 233, 55296, 128512, 1114112].map((n) => $fromU32(n));
  return `${versionDebug_fmt(v)} ${order.value} [${upto.map((item) => String(item)).join(", ")}]\n[${fs.map((item) => $debugF64(item)).join(", ")}]\n[${digits.map((item) => (item == null ? "None" : `Some(${$debugStr(item, "'")})`)).join(", ")}] [${points.map((item) => (item == null ? "None" : `Some(${$debugStr(item, "'")})`)).join(", ")}]\n${$lowerExp(1234)} ${$lowerExp(0)} ${$lowerExp(-0.00025)} ${$lowerExp(6.02e23).replace("e", "E")} ${$lowerExp(NaN)} ${$lowerExp(100)}`;
}

export function panics(i) {
  const v = [1, 2, 3];
  if (i === 0) {
    return $splitOff(v, 4);
  }
  if (i === 1) {
    return $drain(v, 2, 1);
  }
  return $drain(v, 1, 5);
}

export function report() {
  return `${tour()}${edges()}\n`;
}

function dogDescribe_name(dog) {
  return "dog";
}

function catDescribe_name(cat) {
  return `cat${cat.lives}`;
}

function catDescribe_describe(cat) {
  return `[${catDescribe_name(cat)}]`;
}

function tLabeled_label(self, TDisplay) {
  return `#${TDisplay.fmt(self)}`;
}

function versionDebug_fmt(version) {
  return `Version { major: ${version.major}, minor: ${version.minor}, patch: ${version.patch} }`;
}

function configDebug_fmt(config) {
  return `Config { name: ${$debugStr(config.name)}, retries: ${config.retries}, verbose: ${config.verbose}, ratio: ${$debugF64(config.ratio)} }`;
}

export function dogDescribe() {
  if ($dogDescribe === undefined) {
    $dogDescribe = {
      name: dogDescribe_name,
      describe: (self) => `<${dogDescribe_name(self)}>`,
      shout: (self) => dogDescribe().describe(self).toUpperCase(),
    };
  }
  return $dogDescribe;
}

export function catDescribe() {
  if ($catDescribe === undefined) {
    $catDescribe = {
      name: catDescribe_name,
      describe: catDescribe_describe,
      shout: (self) => catDescribe_describe(self).toUpperCase(),
    };
  }
  return $catDescribe;
}

export function tLabeled(TDisplay) {
  if ($tLabeled === undefined) {
    $tLabeled = new WeakMap();
  }
  return $traitImpl($tLabeled, [TDisplay], () => ({
    label: (arg0) => tLabeled_label(arg0, TDisplay),
  }));
}
//# sourceMappingURL=versions.js.map
