// The boundary matrices (ADR 0182): corpus cases that try each operation
// rust-js supports on the values where implementations go wrong, a type's
// `MIN` and `MAX`, `-0.0`, a string's Unicode traps, every pair of them,
// and print each result exactly, a float by its bits. Each is a corpus case
// like any other, compared with native Rust under each runtime.
//
//   bun scripts/matrix.ts          write test/corpus/matrix_*.rs
//   bun scripts/matrix.ts --check  fail if they aren't what this writes
//
// What's left out is listed, each with why: an operation rust-js refuses
// would refuse the whole case, and one whose answer differs by design is
// in the semantics page's differences.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const corpus = join(import.meta.dir, "..", "test", "corpus");

/** Left out of the matrices, and why. */
export const excluded: Record<string, string> = {
  "isize, usize": "rust-js's are wasm32's, 32 bits, where the native run's are 64",
  "checked_ilog2, checked_ilog10, checked_next_power_of_two": "refused yet",
  "a float's copysign, round_ties_even, mul_add, rem_euclid, div_euclid, midpoint": "refused yet",
  "a string's escape_debug, escape_default, escape_unicode, split_at_checked, encode_utf16": "refused yet",
  "a char's escape_debug, escape_default, escape_unicode, encode_utf8": "refused yet",
  "a float's powf of a power with a fraction, exp, ln, sin and the like": "their last bit is the platform's libm's natively, JS's Math's here, which differ, as two platforms' do",
};

const header = (what: string) => `// Generated by scripts/matrix.ts (ADR 0182): ${what}. Edit it there.\n`;

const integers = `${header("each integer operation on each pair of a type's boundary values")}
// One line per value, and per pair: each result, by \`{:?}\`; a float's by its
// bits, as a NaN's differ by platform.

fn f64_bits(x: f64) -> String {
    if x.is_nan() { "NaN".to_string() } else { format!("{:016x}", x.to_bits()) }
}

fn f32_bits(x: f32) -> String {
    if x.is_nan() { "NaN".to_string() } else { format!("{:08x}", x.to_bits()) }
}

macro_rules! integers {
    ($t:ident, $signed:ident) => {{
        let values: [$t; 9] = [
            $t::MIN,
            $t::MIN + 1,
            (0 as $t).wrapping_sub(1),
            0,
            1,
            2,
            7,
            $t::MAX - 1,
            $t::MAX,
        ];
        let bits = $t::BITS;
        for a in values {
            println!(
                "{} {a}: zeros {} {} ones {} {} swap {} rev {} rot {} {} neg {} {:?} pow {} {} {} {:?}",
                stringify!($t),
                a.leading_zeros(),
                a.trailing_zeros(),
                a.count_ones(),
                a.count_zeros(),
                a.swap_bytes(),
                a.reverse_bits(),
                a.rotate_left(1),
                a.rotate_right(3),
                a.wrapping_neg(),
                a.checked_neg(),
                a.wrapping_pow(0),
                a.wrapping_pow(2),
                a.wrapping_pow(bits - 1),
                a.checked_pow(3),
            );
            println!(
                "{} {a}: fmt {:x} {:b} {:o} {:#X} [{:>6}] [{:<6}] [{:^7}] [{:+}] [{:06}] parse {:?} {:?}",
                stringify!($t),
                a,
                a,
                a,
                a,
                a,
                a,
                a,
                a,
                a,
                a.to_string().parse::<$t>(),
                $t::from_str_radix(&format!("{:x}", a), 16),
            );
            println!(
                "{} {a}: as {} {} {} {} {} {} {} {} {} {} f32 {} f64 {}",
                stringify!($t),
                a as i8,
                a as i16,
                a as i32,
                a as i64,
                a as i128,
                a as u8,
                a as u16,
                a as u32,
                a as u64,
                a as u128,
                f32_bits(a as f32),
                f64_bits(a as f64),
            );
            for s in [0, 1, bits - 1, bits, bits + 1] {
                println!(
                    "{} {a} shift {s}: {} {} {:?} {:?}",
                    stringify!($t),
                    a.wrapping_shl(s),
                    a.wrapping_shr(s),
                    a.checked_shl(s),
                    a.checked_shr(s),
                );
            }
            $signed!($t, a);
            for b in values {
                let quotient = match a.checked_div(b) {
                    Some(_) => format!("{} {}", a / b, a % b),
                    None => "-".to_string(),
                };
                println!(
                    "{} {a} {b}: wrap {} {} {} chk {:?} {:?} {:?} {:?} {:?} sat {} {} {} over {:?} {:?} {:?} div {quotient} euclid {:?} {:?} cmp {} {} {:?} {} {} {}",
                    stringify!($t),
                    a.wrapping_add(b),
                    a.wrapping_sub(b),
                    a.wrapping_mul(b),
                    a.checked_add(b),
                    a.checked_sub(b),
                    a.checked_mul(b),
                    a.checked_div(b),
                    a.checked_rem(b),
                    a.saturating_add(b),
                    a.saturating_sub(b),
                    a.saturating_mul(b),
                    a.overflowing_add(b),
                    a.overflowing_sub(b),
                    a.overflowing_mul(b),
                    a.checked_div_euclid(b),
                    a.checked_rem_euclid(b),
                    a < b,
                    a == b,
                    a.cmp(&b),
                    a.min(b),
                    a.max(b),
                    a.abs_diff(b),
                );
            }
        }
    }};
}

macro_rules! signed {
    ($t:ident, $a:ident) => {
        println!(
            "{} {}: signed {} {} {:?} {}",
            stringify!($t),
            $a,
            $a.signum(),
            $a.wrapping_abs(),
            $a.checked_abs(),
            $a.unsigned_abs(),
        );
    };
}

macro_rules! unsigned {
    ($t:ident, $a:ident) => {
        println!(
            "{} {}: unsigned {}",
            stringify!($t),
            $a,
            $a.is_power_of_two(),
        );
    };
}

fn main() {
    integers!(i8, signed);
    integers!(i16, signed);
    integers!(i32, signed);
    integers!(i64, signed);
    integers!(i128, signed);
    integers!(u8, unsigned);
    integers!(u16, unsigned);
    integers!(u32, unsigned);
    integers!(u64, unsigned);
    integers!(u128, unsigned);
}
`;

const floats = `${header("each float operation on each pair of a type's boundary values")}
// One line per value, and per pair: each result, a float by its bits, as a
// NaN's differ by platform, then as it's written.

fn f64_bits(x: f64) -> String {
    if x.is_nan() { "NaN".to_string() } else { format!("{:016x}", x.to_bits()) }
}

fn f32_bits(x: f32) -> String {
    if x.is_nan() { "NaN".to_string() } else { format!("{:08x}", x.to_bits()) }
}

macro_rules! floats {
    ($t:ident, $bits:ident, $values:expr) => {{
        let values: &[$t] = &$values;
        for &a in values {
            println!(
                "{} {}: round {} {} {} {} {} abs {} {} {} sqrt {} powi {} {} recip {} neg {} clamp {}",
                stringify!($t),
                $bits(a),
                $bits(a.floor()),
                $bits(a.ceil()),
                $bits(a.round()),
                $bits(a.trunc()),
                $bits(a.fract()),
                $bits(a.abs()),
                $bits(a.signum()),
                $bits(a.to_degrees()),
                $bits(a.sqrt()),
                $bits(a.powi(3)),
                $bits(a.powi(-2)),
                $bits(a.recip()),
                $bits(-a),
                $bits(a.clamp(-1.0, 1.0)),
            );
            println!(
                "{} {}: is {} {} {} {} {} {} {:?} bits {}",
                stringify!($t),
                $bits(a),
                a.is_nan(),
                a.is_finite(),
                a.is_infinite(),
                a.is_sign_negative(),
                a.is_normal(),
                a.is_subnormal(),
                a.classify(),
                $bits($t::from_bits(a.to_bits())),
            );
            println!(
                "{} {}: fmt {} {:?} {:e} {:E} {:.0} {:.1} {:.3} [{:>12.2}] {:+} [{:08.2}] parse {:?}",
                stringify!($t),
                $bits(a),
                a,
                a,
                a,
                a,
                a,
                a,
                a,
                a,
                a,
                a,
                a.to_string().parse::<$t>().map($bits),
            );
            println!(
                "{} {}: as {} {} {} {} {} {} {} {} f32 {} f64 {}",
                stringify!($t),
                $bits(a),
                a as i8,
                a as i32,
                a as i64,
                a as i128,
                a as u8,
                a as u32,
                a as u64,
                a as u128,
                f32_bits(a as f32),
                f64_bits(a as f64),
            );
            for &b in values {
                println!(
                    "{} {} {}: {} {} {} {} {} min {} max {} pow {} cmp {:?} {:?} {} {} {}",
                    stringify!($t),
                    $bits(a),
                    $bits(b),
                    $bits(a + b),
                    $bits(a - b),
                    $bits(a * b),
                    $bits(a / b),
                    $bits(a % b),
                    $bits(a.min(b)),
                    $bits(a.max(b)),
                    if b.fract() == 0.0 || !b.is_finite() { $bits(a.powf(b)) } else { "-".to_string() },
                    a.total_cmp(&b),
                    a.partial_cmp(&b),
                    a == b,
                    a < b,
                    a >= b,
                );
            }
        }
    }};
}

fn main() {
    floats!(
        f64,
        f64_bits,
        [
            0.0,
            -0.0,
            1.0,
            -1.0,
            0.5,
            1.5,
            2.5,
            -2.5,
            0.1,
            1e-7,
            1e21,
            123456789.125,
            9007199254740993.0,
            1e-310,
            f64::MIN_POSITIVE,
            f64::EPSILON,
            f64::MAX,
            f64::MIN,
            f64::INFINITY,
            f64::NEG_INFINITY,
            f64::NAN,
        ]
    );
    floats!(
        f32,
        f32_bits,
        [
            0.0,
            -0.0,
            1.0,
            -1.0,
            0.5,
            2.5,
            -2.5,
            0.1,
            1e-7,
            16777217.0,
            1e-40,
            f32::MIN_POSITIVE,
            f32::EPSILON,
            f32::MAX,
            f32::MIN,
            f32::INFINITY,
            f32::NEG_INFINITY,
            f32::NAN,
        ]
    );
}
`;

const strings = `${header("each string method on each string, and each pair of them, where text goes wrong")}
// Each result by \`{:?}\`, which escapes as Rust's \`Debug\` does: a control
// character, a quote, a backslash, a character Unicode says to escape.

const STRINGS: &[&str] = &[
    "",
    "a",
    "ab",
    "abc",
    "A",
    " ",
    "a b",
    "a,b,,c",
    "\\t\\r\\n",
    "line\\nnext\\r\\nlast",
    "\\0",
    "a\\0b",
    "\\"'\\\\<>&-->",
    "\\u{00e9}",
    "e\\u{0301}",
    "\\u{00df}",
    "\\u{0130}",
    "\\u{01c5}",
    "\\u{1f980}",
    "\\u{e000}",
    "\\u{10ffff}",
    "\\u{0085}hello\\u{0085}",
    "\\u{feff}hello\\u{feff}",
    "\\u{2028}\\u{2029}",
    "\\u{200b}",
    "\\u{00a0} hello \\u{3000}",
    "\\u{7f}\\u{9f}",
    "-12",
    "+3.5e2",
    "1_000",
];

fn main() {
    for &a in STRINGS {
        println!(
            "{a:?}: len {} {} {} chars {:?} rev {:?} case {:?} {:?} {:?} {:?}",
            a.len(),
            a.is_empty(),
            a.chars().count(),
            a.chars().nth(1),
            a.chars().rev().collect::<String>(),
            a.to_uppercase(),
            a.to_lowercase(),
            a.to_ascii_uppercase(),
            a.to_ascii_lowercase(),
        );
        println!(
            "{a:?}: trim {:?} {:?} {:?} {:?} {:?} words {:?} lines {:?}",
            a.trim(),
            a.trim_start(),
            a.trim_end(),
            a.trim_matches(' '),
            a.trim_start_matches('a'),
            a.split_whitespace().collect::<Vec<_>>(),
            a.lines().collect::<Vec<_>>(),
        );
        println!(
            "{a:?}: split {:?} {:?} {:?} {:?} bytes {} {:?} {} {:?} {:?}",
            a.split(',').collect::<Vec<_>>(),
            a.splitn(2, ' ').collect::<Vec<_>>(),
            a.rsplit(' ').collect::<Vec<_>>(),
            a.split_once(','),
            a.bytes().map(u32::from).sum::<u32>(),
            a.char_indices().collect::<Vec<_>>(),
            a.is_char_boundary(1),
            a.get(0..1),
            a.char_indices().rev().next(),
        );
        println!(
            "{a:?}: find {:?} {:?} {:?} {} replace {:?} {:?} fmt [{:>8}] [{:<8}] [{:^8}] [{:.2}] parse {:?} {:?} lossy {:?} all {}",
            a.find('a'),
            a.rfind('a'),
            a.find("b"),
            a.matches('a').count(),
            a.replace("a", "xy"),
            a.repeat(2),
            a,
            a,
            a,
            a,
            a.parse::<i32>(),
            a.parse::<f64>(),
            String::from_utf8_lossy(a.as_bytes()),
            a.chars().all(char::is_whitespace),
        );
        for &b in STRINGS {
            println!(
                "{a:?} {b:?}: {} {} {} {:?} {} {} {} {} {:?} {:?} {:?} {}",
                a.starts_with(b),
                a.ends_with(b),
                a.contains(b),
                a.cmp(b),
                a < b,
                a.max(b),
                a == b,
                a.eq_ignore_ascii_case(b),
                a.find(b),
                a.strip_prefix(b),
                a.strip_suffix(b),
                format!("{a}{b}").len(),
            );
        }
    }
}
`;

const chars = `${header("each char method on each char, and each pair of them, where characters go wrong")}
// Each result by \`{:?}\`, and each pair's order by code point.

const CHARS: &[char] = &[
    '\\0', '\\t', '\\n', ' ', '0', '7', '9', 'a', 'f', 'g', 'z', 'A', 'F', 'Z', '_', '~', '\\u{7f}',
    '\\u{85}', '\\u{a0}', '\\u{e9}', '\\u{df}', '\\u{1c5}', '\\u{130}', '\\u{fb01}', '\\u{3a3}', '\\u{3c3}',
    '\\u{3c2}', '\\u{663}', '\\u{2167}', '\\u{2028}', '\\u{3000}', '\\u{feff}', '\\u{e000}', '\\u{fffd}',
    '\\u{1f980}', '\\u{10ffff}',
];

fn main() {
    for &c in CHARS {
        println!(
            "{c:?}: is {} {} {} {} {} {} {} ascii {} {} {} {} {} {} {} {} {} {} {} {}",
            c.is_alphabetic(),
            c.is_numeric(),
            c.is_alphanumeric(),
            c.is_whitespace(),
            c.is_uppercase(),
            c.is_lowercase(),
            c.is_control(),
            c.is_ascii(),
            c.is_ascii_digit(),
            c.is_ascii_hexdigit(),
            c.is_ascii_alphabetic(),
            c.is_ascii_alphanumeric(),
            c.is_ascii_uppercase(),
            c.is_ascii_lowercase(),
            c.is_ascii_punctuation(),
            c.is_ascii_graphic(),
            c.is_ascii_whitespace(),
            c.is_ascii_control(),
            c.is_digit(8),
        );
        println!(
            "{c:?}: case {:?} {:?} {:?} {:?} digit {:?} {:?} {:?} len {} {} as {} {} {:?} {:?} fmt [{:>4}] [{:<3}] {}",
            c.to_uppercase().collect::<String>(),
            c.to_lowercase().collect::<String>(),
            c.to_ascii_uppercase(),
            c.to_ascii_lowercase(),
            c.to_digit(10),
            c.to_digit(16),
            c.to_digit(36),
            c.len_utf8(),
            c.len_utf16(),
            c as u32,
            c as u8,
            (c as u8) as char,
            char::from_u32(c as u32 + 1),
            c,
            c,
            c.to_string().len(),
        );
        for &d in CHARS {
            println!("{c:?} {d:?}: {:?} {} {} {} {}", c.cmp(&d), c < d, c.max(d), c == d, c.eq_ignore_ascii_case(&d));
        }
    }
    for n in [0, 7, 9, 10, 15, 35, 36] {
        println!("{n}: {:?} {:?} {:?}", char::from_digit(n, 10), char::from_digit(n, 16), char::from_digit(n, 36));
    }
}
`;

/** Each matrix, by its file's name. */
export const matrices: Record<string, string> = {
  "matrix_integers.rs": integers,
  "matrix_floats.rs": floats,
  "matrix_strings.rs": strings,
  "matrix_chars.rs": chars,
};

if (import.meta.main) {
  const check = process.argv.includes("--check");
  const stale: string[] = [];
  for (const [name, source] of Object.entries(matrices)) {
    const path = join(corpus, name);
    if (check) {
      let current = "";
      try {
        current = readFileSync(path, "utf8");
      } catch {}
      if (current !== source) stale.push(name);
    } else {
      writeFileSync(path, source);
    }
  }
  if (stale.length) {
    console.error(`not what scripts/matrix.ts writes: ${stale.join(", ")}; run \`bun scripts/matrix.ts\``);
    process.exit(1);
  }
}
