// Generated by rust-js from test/jsx/lib.rs. Do not edit.

import { Suspense, createContext } from "react";

const THEME = createContext("light");

export function App() {
  return (
    <THEME.Provider value="dark">
      <Suspense key="body" fallback="loading">
        <form action="/save">
          <input ref={() => {}} />
        </form>
      </Suspense>
    </THEME.Provider>
  );
}
//# sourceMappingURL=lib.jsx.map
