// Generated by rust-js from test/web_forms.rs. Do not edit.

import { $unwrap } from "@rust-js/runtime";

export function forms() {
  const input = document.createElement("input");
  input.value = "typed";
  const app = $unwrap(document.getElementById("app"), "the page has an #app");
  app.append(input);
  app.append("!");
  const ping = new Event("ping");
  app.addEventListener("ping", (e) => {
    e.preventDefault();
  });
  window.dispatchEvent(ping);
  return $unwrap(app.textContent) + input.value;
}

export function round_trip(text) {
  const bytes = new TextEncoder().encode(text);
  const back = new TextDecoder("utf-8").decode(bytes);
  return [bytes.length, back];
}

export function bodies(url) {
  const blob = new Blob();
  const response = new Response(blob);
  return [response, window.fetch(url)];
}

export function copied(text, items) {
  const blob = new Blob([text, "!"]);
  return [blob, navigator.clipboard.write(items)];
}

export function from_frame(frame, e) {
  const sender = e.source;
  const windowOf = frame.contentWindow;
  return [Object.is(sender, windowOf), window.performance.now()];
}

export function canvas_size() {
  const canvas = document.createElement("canvas");
  canvas.width = 320;
  canvas.height = 200;
  return [canvas.width, canvas.height];
}

export function statics(blob) {
  const url = URL.createObjectURL(blob);
  URL.revokeObjectURL(url);
  return [HTMLScriptElement.supports("importmap"), url];
}

export function kinds(el, blob, param, bytes) {
  const names = el.getAttributeNames();
  const languages = navigator.languages;
  const into = new TextEncoder().encodeInto("hi", bytes);
  return [names, languages.length, blob.size, param.value, 1, into.written];
}

export function handlers(button) {
  button.onclick = (e) => {
    e.preventDefault();
  };
  const set = button.onclick != null;
  button.onclick = null;
  return set;
}
//# sourceMappingURL=web_forms.js.map
