// Generated by rust-js from frontend/src/detail.rs. Do not edit.

import { useEffect, useState } from "react";
import { Failure, contact } from "./api.js";

export function ContactPage({ id }) {
  const [loaded, setLoaded] = useState("Loading");
  useEffect(() => {
    const controller = new AbortController();
    const signal = controller.signal;
    setLoaded("Loading");
    (async () => {
      const match = await contact(id, signal);
      if (match.TAG === "Ok") {
        setLoaded({ TAG: "Contact", _0: match._0 });
      } else if (!(match.TAG === "Err" && match._0 === "Aborted")) {
        if (match.TAG === "Err" && match._0.TAG === "Refused" && match._0._0 === 404) {
          setLoaded({ TAG: "Failed", _0: `There's no contact ${id}.` });
        } else {
          setLoaded({ TAG: "Failed", _0: Failure.message(match._0) });
        }
      }
    })();
    return () => {
      controller.abort();
    };
  }, [id]);
  if (loaded === "Loading") {
    return <p className="status">Loading…</p>;
  }
  if (loaded.TAG === "Failed") {
    return (
      <p className="error" role="alert">
        {loaded._0}
      </p>
    );
  }
  return (
    <article className="contact">
      <h1>{loaded._0.name}</h1>
      <dl>
        <dt>Email</dt>
        <dd>{loaded._0.email}</dd>
        <dt>Age</dt>
        <dd>{loaded._0.age}</dd>
      </dl>
      <a href="#/">All contacts</a>
    </article>
  );
}
//# sourceMappingURL=detail.jsx.map
