// Generated by rust-js from test/jsx/lib.rs. Do not edit.

function Card(p) {
  return (
    <div>
      {p.title}
      {p.children}
    </div>
  );
}

export function App() {
  const __jsx0 = 3;
  const match = globalThis.record(1);
  const match$1 = globalThis.record(2);
  const match$2 = globalThis.record(__jsx0);
  return (
    <Card title={match} key={match$1}>
      {match$2}
    </Card>
  );
}
//# sourceMappingURL=lib.jsx.map
