// Generated by rust-js from examples/inventory.rs. Do not edit.

import {
  $cmp,
  $debugF64,
  $debugStr,
  $orInsert,
  $partialCmp,
  $toFixed,
  $unwrap,
} from "@rust-js/runtime";

var $minStockRule, $revenueRule, $storeDisplay;

export const Store = {
  apply(store, e) {
    if (e.TAG === "Restock") {
      const current = $orInsert(store.stock, e.item, 0);
      store.stock.set(e.item, (current + e.qty) >>> 0);
    } else if (e.TAG === "Sale") {
      let have = store.stock.get(e.item);
      if (have == null) {
        return { TAG: "Err", _0: `unknown item ${e.item}` };
      }
      if (have < e.qty) {
        return { TAG: "Err", _0: `not enough ${e.item}: ${have} < ${e.qty}` };
      }
      have = (have - e.qty) >>> 0;
      store.stock.set(e.item, have);
      store.revenue += e.qty * e.price;
    } else {
      store.log.push(`audit at ${$toFixed(store.revenue, 2)}`);
    }
    return { TAG: "Ok", _0: undefined };
  },
};

function discount(pct) {
  return (p) => p * (1 - pct / 100);
}

function classify(n) {
  if (n <= -1) {
    return "negative";
  }
  if (n === 0) {
    return "zero";
  }
  if (n >= 1 && n <= 9 && n % 2 === 0) {
    return "small even";
  }
  if (n >= 1 && n <= 9) {
    return "small odd";
  }
  return "large";
}

export function report() {
  let store = { stock: new Map(), revenue: 0, log: [] };
  const events = [
    { TAG: "Restock", item: "apple", qty: 10 },
    { TAG: "Restock", item: "pear", qty: 3 },
    { TAG: "Sale", item: "apple", qty: 4, price: 0.5 },
    { TAG: "Sale", item: "kiwi", qty: 1, price: 2 },
    { TAG: "Sale", item: "pear", qty: 5, price: 1 },
    "Audit",
  ];
  let out = "";
  for (const e of events) {
    const msg = Store.apply(store, e);
    if (msg.TAG === "Err") {
      out += `error: ${msg._0}\n`;
    }
  }
  const rules = [
    { value: { item: "pear", min: 5 }, impl: minStockRule() },
    { value: [10], impl: revenueRule() },
  ];
  for (const r of rules) {
    const match = r.impl.check(r.value, store);
    if (match != null) {
      out += `[${r.impl.name(r.value)}] ${match}\n`;
    } else {
      out += `[${r.impl.name(r.value)}] ok\n`;
    }
  }
  out += `${storeDisplay_fmt(store)}\n[${store.log.map((item) => $debugStr(item)).join(", ")}]\n`;
  const half = discount(50);
  let prices = [3.5, 1.25, 9, 0.75];
  prices.sort((a, b) => $unwrap($partialCmp(b, a)));
  const cheap = prices.map((p) => half(p));
  const arg = events.filter((e) => e.TAG === "Sale").length;
  out += `[${prices.map((item) => $debugF64(item)).join(", ")}] [${cheap.map((item) => $debugF64(item)).join(", ")}] ${arg}\n`;
  const counter = { value: 0 };
  const c = counter;
  const bump = (n) => {
    c.value = (c.value + n) | 0;
  };
  for (const n of [-3, 0, 4, 7, 12]) {
    bump(n);
    out += `${classify(n)} `;
  }
  out += `total=${counter.value} again=${counter.value}\n`;
  let stack = [1, 2, 3];
  let popped = [];
  while (true) {
    const top = stack.pop();
    if (top != null) {
      if (top === 2) {
        stack.push(10);
      }
      popped.push(top);
    } else {
      break;
    }
  }
  out += `[${popped.map((item) => String(item)).join(", ")}]\n`;
  out += `[${tallies(["a", "b", "a", "b", "c"])
    .map((item) => `(${$debugStr(item[0])}, ${item[1]})`)
    .join(", ")}] [${bands([0, 3, 42, 150, 250])
    .map((item) => $debugStr(item))
    .join(", ")}]\n`;
  return out;
}

export function tallies(words) {
  let counts = new Map();
  const one = 1;
  for (const w of words) {
    const current = $orInsert(counts, w, 0);
    counts.set(w, (current + one) >>> 0);
    let n = counts.get("b");
    if (n != null) {
      n = Math.imul(n, 2) >>> 0;
      counts.set("b", n);
    }
  }
  let all = Array.from(counts);
  all.sort((a, b) => $cmp(a[0], b[0]) || $cmp(a[1], b[1]));
  return all;
}

export function bands(xs) {
  return xs.map((x) => {
    if (x === 0) {
      return "none";
    }
    if (x >= 1 && x < 10) {
      return `few ${x}`;
    }
    if ((x >= 10 && x <= 99) || x >= 200) {
      return `many ${x}`;
    }
    return "odd";
  });
}

function minStockRule_name(minStock) {
  return `min-stock(${minStock.item})`;
}

function minStockRule_check(minStock, store) {
  const have = store.stock.get(minStock.item) ?? 0;
  if (have < minStock.min) {
    return `${minStock.item} low: ${have} < ${minStock.min}`;
  }
  return undefined;
}

function revenueRule_name(revenue) {
  return "revenue";
}

function revenueRule_check(revenue, store) {
  return store.revenue < revenue[0]
    ? `revenue ${$toFixed(store.revenue, 2)} under ${$toFixed(revenue[0], 2)}`
    : undefined;
}

function storeDisplay_fmt(store) {
  let f = "";
  let items = Array.from(store.stock);
  items.sort((a, b) => $cmp(a[0], b[0]) || $cmp(a[1], b[1]));
  for (const [name, qty] of items) {
    f += `${name}=${qty} `;
  }
  f += `| ${$toFixed(store.revenue, 2)}`;
  return f;
}

export function minStockRule() {
  if ($minStockRule === undefined) {
    $minStockRule = { name: minStockRule_name, check: minStockRule_check };
  }
  return $minStockRule;
}

export function revenueRule() {
  if ($revenueRule === undefined) {
    $revenueRule = { name: revenueRule_name, check: revenueRule_check };
  }
  return $revenueRule;
}

export function storeDisplay() {
  if ($storeDisplay === undefined) {
    $storeDisplay = { fmt: storeDisplay_fmt };
  }
  return $storeDisplay;
}
//# sourceMappingURL=inventory.js.map
