//! Resolve and validate all artifacts before touching output files.

use std::collections::{HashMap, HashSet};
use std::path::PathBuf;

use crate::manifest::{self, Manifest, fingerprint};
use crate::paths::{absolute, parent_dir, relative, relative_resolved, resolve};

use crate::publish::{Artifact, ArtifactPlan};
use crate::{js, program, to_oxc};

pub struct OutputPlan {
    pub input: PathBuf,
    pub output: PathBuf,
    pub test: bool,
    pub manifest: Option<PathBuf>,
    /// A library's metadata (ADR 0100): where rustc wrote it, and where it's
    /// published, with the JS, as an artifact of this plan.
    pub metadata: Option<(PathBuf, PathBuf)>,
    /// Files of the build tool's published with the JS, as artifacts of this
    /// plan, and no part of the manifest: what Cargo is told (ADR 0101).
    pub extra: Vec<(PathBuf, Vec<u8>)>,
    /// The crate's settings for the JS (ADR 0117).
    pub settings: crate::settings::Settings,
    /// The JS files the plan has, once planned, which a crate's checks read.
    pub written: Vec<PathBuf>,
    jsx: HashSet<Vec<String>>,
    /// Each `#[path]` module's file, where its JS goes beside (ADR 0273).
    located: HashMap<Vec<String>, PathBuf>,
}

impl OutputPlan {
    /// Write one `.js` and `.js.map` per module (ADR 0019).
    fn generate(
        &self,
        modules: Vec<program::LoweredModule>,
        sources: &program::Sources,
    ) -> Result<Vec<Artifact>, String> {
        let mut artifacts = Vec::new();
        let mut typed = Vec::new();
        // Each source's path is resolved once, and each module's directory:
        // a module's map asks for a path only to the sources it points into
        // (found in review).
        let resolved: Vec<PathBuf> = sources
            .files
            .iter()
            .map(|source| resolve(source.path.as_deref().unwrap_or(&self.input)))
            .collect();
        for module in modules {
            let js_path = self.js_path(&module.path);
            let rust_path = module.file.clone().unwrap_or_else(|| self.input.clone());
            let specified = |imports: &[program::LoweredImport]| {
                imports
                    .iter()
                    .map(|import| js::Import {
                        named: import.named.clone(),
                        from: self.specifier(&module.path, &import.path),
                    })
                    .collect::<Vec<_>>()
            };
            let imports = specified(&module.imports);
            let reexports = specified(&module.reexports);
            // A relative module in `#[link_name]` is relative to the root's
            // file (ADR 0028), so a file in a subdirectory climbs up to it.
            let dir = &module.path[..module.path.len().saturating_sub(1)];
            let packages = module
                .packages
                .into_iter()
                .map(|package| js::Package {
                    from: if self.located.contains_key(&module.path) {
                        self.relative_specifier(
                            &module.path,
                            &parent_dir(&self.output).join(&package.from),
                            &package.from,
                        )
                    } else {
                        relocate(&package.from, dir)
                    },
                    ..package
                })
                .collect();
            let mut js_module = js::Module {
                header: format!("// Generated by rust-js from {}. Do not edit.", rust_path.display()),
                directives: module.directives,
                packages,
                imports,
                reexports,
                helpers: Vec::new(),
                namespaces: module.namespaces,
                consts: module.consts,
                statements: module.statements,
                functions: module.functions,
                caches: module.caches,
                default_export: module.default_export,
            };

            crate::prepare::module(&mut js_module);
            // Of the helpers it asked for, and what they use, the names its
            // prepared tree reads (ADR 0103).
            let helper_sources: Vec<&'static str> = module.runtime.iter().map(|helper| helper.source()).collect();
            js_module.helpers = crate::runtime::imported_helpers(&helper_sources, &js_module.read_vars());
            let dir = resolve(parent_dir(&js_path));
            let own = resolve(&rust_path);
            let path_of = |i: usize| relative_resolved(&dir, &resolved[i]);
            let js_file_name = js_path.file_name().unwrap_or_default().to_string_lossy();
            let file = absolute(&js_path)?;
            let jsx = js_file_name.ends_with(".jsx");
            let layout = |code, map| crate::hooks::transform(&self.settings, &file, jsx, &js_file_name, code, map);
            let output = to_oxc::emit(
                &js_module,
                sources,
                &path_of,
                resolved.iter().position(|source| *source == own),
                &relative_resolved(&dir, &own),
                &js_file_name,
                &self.settings.format,
                &layout,
            );
            let map_path = PathBuf::from(format!("{}.map", js_path.display()));
            for (path, text) in [(&js_path, &output.code), (&map_path, &output.map)] {
                artifacts.push(Artifact {
                    path: path.clone(),
                    bytes: text.clone().into_bytes(),
                });
            }
            // What it exports, typed, for the TypeScript that imports it (ADR 0196).
            if self.settings.declarations
                && let Some(mut declarations) = module.declarations
            {
                declarations["header"] = js_module.header.clone().into();
                // Another module's types, from its file, as its JS imports it (ADR 0210).
                for import in declarations["declarations"].as_array_mut().into_iter().flatten() {
                    if let Some(path) = import.get("module").cloned() {
                        let path: Vec<String> = serde_json::from_value(path).map_err(|e| e.to_string())?;
                        import["from"] = self.specifier(&module.path, &path).into();
                        import.as_object_mut().expect("an import").remove("module");
                    }
                }
                typed.push((types_path(&js_path), declarations));
            }
        }
        // Printed by TypeScript, all in one session of its (ADR 0207).
        if !typed.is_empty() {
            let (paths, models): (Vec<PathBuf>, Vec<serde_json::Value>) = typed.into_iter().unzip();
            let texts = crate::typescript::print(&self.settings, &models)?;
            for (path, text) in paths.into_iter().zip(texts) {
                artifacts.push(Artifact {
                    path,
                    bytes: text.into_bytes(),
                });
            }
        }
        Ok(artifacts)
    }

    /// In test mode, `<output>.test.js` beside the output: one `test(..)`
    /// per `#[test]` function, for `bun test` (ADR 0026). `test` is the
    /// runner's global, so nothing here is specific to one runner.
    fn tests(&self, tests: &[program::TestFn]) -> Option<Artifact> {
        if !self.test {
            return None;
        }
        let mut modules: Vec<&Vec<String>> = Vec::new();
        for test in tests {
            if !modules.contains(&&test.module) {
                modules.push(&test.module);
            }
        }
        // One namespace import per module, named after it, like ADR 0019.
        let crate_name = self
            .output
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        let mut taken = vec![
            "test".to_string(),
            "shouldPanic".to_string(),
            "testResult".to_string(),
            "$debug".to_string(),
        ];
        let mut aliases = Vec::new();
        let mut code = format!(
            "// Generated by rust-js from {}: its `#[test]` functions, for `bun test`. Do not edit.\n\n",
            self.input.display()
        );
        for module in &modules {
            let base = module
                .last()
                .cloned()
                .unwrap_or_else(|| crate_name.clone())
                .replace('-', "_");
            let alias = (0..)
                .map(|k| if k == 0 { base.clone() } else { format!("{base}${k}") })
                .find(|a| !taken.contains(a))
                .unwrap();
            taken.push(alias.clone());
            code.push_str(&format!(
                "import * as {alias} from {:?};\n",
                self.specifier(&[], module)
            ));
            aliases.push(alias);
        }
        if tests.iter().any(|t| t.returns_result) {
            code.push_str(TEST_RESULT);
        }
        if tests.iter().any(|t| t.should_panic.is_some()) {
            code.push_str(SHOULD_PANIC);
        }
        code.push('\n');
        for test in tests {
            let alias = &aliases[modules.iter().position(|m| **m == test.module).unwrap()];
            let f = format!("{alias}.{}", test.name);
            let body = match &test.should_panic {
                None if test.returns_result => format!("() => testResult({f}())"),
                None => f,
                Some(expected) => format!(
                    "() => shouldPanic({f}, {})",
                    expected.as_ref().map_or("undefined".to_string(), |e| format!("{e:?}"))
                ),
            };
            let register = if test.ignore { "test.skip" } else { "test" };
            code.push_str(&format!("{register}({:?}, {body});\n", test.label));
        }
        let stem = self
            .output
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        let path = self.output.with_file_name(format!("{stem}.test.js"));
        Some(Artifact {
            path,
            bytes: code.into_bytes(),
        })
    }

    /// Where a module's JS goes: the root to the output file, `a::b` to
    /// `a/b.js` beside it, mirroring how Rust lays out `src/`. A module
    /// with JSX is a `.jsx` file, as JSX tools expect (ADR 0040).
    fn js_path(&self, module: &[String]) -> PathBuf {
        let jsx = self.jsx.contains(module);
        if let Some(file) = self.located.get(module) {
            return file.with_extension(if jsx { "jsx" } else { "js" });
        }
        if module.is_empty() {
            return if jsx {
                self.output.with_extension("jsx")
            } else {
                self.output.clone()
            };
        }
        let mut path = parent_dir(&self.output).to_path_buf();
        path.extend(module);
        path.set_extension(if jsx { "jsx" } else { "js" });
        path
    }

    /// The import specifier, in module `from`'s file, for module `to`'s file:
    /// `./util.js`, `../lib.js`. Computed from module paths alone, since the
    /// target file may not have been written yet.
    fn specifier(&self, from: &[String], to: &[String]) -> String {
        if self.located.contains_key(from) || self.located.contains_key(to) {
            let to_file = self.js_path(to);
            return self.relative_specifier(from, &to_file, "./");
        }
        // A module's file sits in the directory named by all but the last
        // segment of its path; the root's file is in the top directory.
        let dir = |path: &[String]| path.len().saturating_sub(1);
        let (from_dir, to_dir) = (&from[..dir(from)], &to[..dir(to)]);
        let common = from_dir.iter().zip(to_dir).take_while(|(a, b)| a == b).count();
        let file = self
            .js_path(to)
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        let mut specifier = if from_dir.len() == common {
            "./".to_string()
        } else {
            "../".repeat(from_dir.len() - common)
        };
        for segment in &to_dir[common..] {
            specifier.push_str(segment);
            specifier.push('/');
        }
        specifier.push_str(&file);
        specifier
    }
}

impl OutputPlan {
    /// `to`, seen from module `from`'s file: `./a.js`, `../../b.js`, a
    /// relative `specifier` as written where `to` is no file of the crate's.
    fn relative_specifier(&self, from: &[String], to: &std::path::Path, specifier: &str) -> String {
        if !specifier.starts_with("./") && !specifier.starts_with("../") {
            return specifier.to_string();
        }
        let path = relative(parent_dir(&self.js_path(from)), to);
        if path.starts_with("../") {
            path
        } else {
            format!("./{path}")
        }
    }
}

/// `#[should_panic]`: the test passes only if it panics, and if `expected`
/// is given, only if the panic message contains it, as with libtest. A
/// panic is a plain `Error` (ADR 0012); anything else thrown, a `TypeError`
/// say, is the JS going wrong, and fails the test as it is.
const SHOULD_PANIC: &str = r#"
function shouldPanic(f, expected) {
  try {
    f();
  } catch (e) {
    if (!(e instanceof Error && e.constructor === Error)) {
      throw e;
    }
    const message = e.message;
    if (expected === undefined || message.includes(expected)) {
      return;
    }
    throw new Error("panic did not contain expected string\n      panic message: " + JSON.stringify(message) + "\n expected substring: " + JSON.stringify(expected));
  }
  throw new Error("test did not panic as expected");
}
"#;

/// A `#[test]` returning a `Result`: an `Err` fails it, as libtest's does,
/// shown as `Error: ..`. By the runtime's `$debug`, which knows no types:
/// a string's or a number's as Rust shows it, a struct's without its name.
const TEST_RESULT: &str = r#"
import { $debug } from "@rust-js/runtime";

function testResult(result) {
  if (result.TAG === "Err") {
    throw new Error("Error: " + $debug(result._0));
  }
}
"#;

/// A module specifier, as seen from directory `dir` below the root's file:
/// `./greet.js` is `../greet.js` one down, and `./inner/wave.js` is
/// `./wave.js` in `inner`, as a person writes it. Package names stay as they
/// are.
fn relocate(specifier: &str, dir: &[String]) -> String {
    if !specifier.starts_with("./") && !specifier.starts_with("../") {
        return specifier.to_string();
    }
    let parts: Vec<&str> = specifier.split('/').filter(|part| *part != ".").collect();
    // The file's own name stays: `./inner` seen from `inner` is `../inner`.
    let common = dir
        .iter()
        .zip(&parts[..parts.len() - 1])
        .take_while(|(d, p)| d == p)
        .count();
    let up = "../".repeat(dir.len() - common);
    let rest = parts[common..].join("/");
    if up.is_empty() && !rest.starts_with("../") {
        format!("./{rest}")
    } else {
        format!("{up}{rest}")
    }
}

impl OutputPlan {
    pub fn new(input: PathBuf, output: PathBuf, test: bool, manifest: Option<PathBuf>) -> Self {
        Self {
            input,
            output,
            test,
            manifest,
            metadata: None,
            extra: Vec::new(),
            settings: crate::settings::Settings::default(),
            written: Vec::new(),
            jsx: HashSet::new(),
            located: HashMap::new(),
        }
    }

    pub fn plan(&mut self, linked: crate::link::Linked, sources: Vec<PathBuf>) -> Result<ArtifactPlan, String> {
        let mut lowered = linked.into_program();
        self.jsx = lowered
            .modules
            .iter()
            .filter(|m| m.jsx)
            .map(|m| m.path.clone())
            .collect();
        // A `#[path]` module's file, below the root's directory as the output
        // is: `pages/errors/[errorCode].rs` (ADR 0273). One outside it,
        // `../shared/model.rs`, is where its module path says, in the output's.
        self.located = lowered
            .modules
            .iter()
            .filter(|m| m.located)
            .filter_map(|m| {
                let below = relative(parent_dir(&self.input), m.file.as_ref()?);
                (!below.starts_with("..")).then(|| (m.path.clone(), parent_dir(&self.output).join(below)))
            })
            .collect();
        let sources: Vec<PathBuf> = sources.into_iter().map(|p| absolute(&p)).collect::<Result<_, _>>()?;
        if let Some(library) = &mut lowered.library {
            library.inputs = sources
                .iter()
                .map(|file| {
                    let bytes = std::fs::read(file).map_err(|e| e.to_string())?;
                    Ok(manifest::Artifact {
                        file: file.clone(),
                        hash: fingerprint(&bytes),
                    })
                })
                .collect::<Result<_, String>>()?;
        }
        let mut planned = Vec::new();
        let mut modules = Vec::new();
        for module in &lowered.modules {
            let requested = self.js_path(&module.path);
            let file = absolute(&requested)?;
            let map = absolute(&PathBuf::from(format!("{}.map", requested.display())))?;
            planned.extend([file.clone(), map.clone()]);
            let types = match self.settings.declarations && module.declarations.is_some() {
                true => Some(absolute(&types_path(&requested))?),
                false => None,
            };
            planned.extend(types.clone());
            let imports = module
                .imports
                .iter()
                .map(|import| absolute(&self.js_path(&import.path)))
                .collect::<Result<Vec<_>, _>>()?;
            modules.push(manifest::Module {
                module: module.path.clone(),
                file,
                map,
                types,
                source: module.file.as_deref().map(absolute).transpose()?,
                located: module.located,
                imports,
            });
        }
        let test_artifact = self.tests(&lowered.tests);
        if let Some(test) = &test_artifact {
            planned.push(absolute(&test.path)?);
        }
        // A library's metadata, as rustc wrote it: published where it's asked
        // for, with what's made from the same build, or not at all.
        let metadata = match &self.metadata {
            Some((written, path)) => {
                let path = absolute(path)?;
                planned.push(path.clone());
                let bytes = std::fs::read(written).map_err(|e| format!("cannot read the metadata rustc wrote: {e}"))?;
                Some(Artifact { path, bytes })
            }
            None => None,
        };
        let mut extra = Vec::new();
        for (path, bytes) in std::mem::take(&mut self.extra) {
            let path = absolute(&path)?;
            planned.push(path.clone());
            extra.push(Artifact { path, bytes });
        }
        let input = absolute(&self.input)?;
        let output = absolute(&self.output)?;
        let manifest_path = self.manifest.as_deref().map(absolute).transpose()?;
        let mut paths = HashSet::new();
        for path in planned.iter().chain(manifest_path.iter()) {
            if sources.contains(path) || path == &input || !paths.insert(path.clone()) {
                return Err(format!(
                    "output collision at `{}`; pick another output name",
                    path.display()
                ));
            }
            if path.exists() && !path.is_file() {
                return Err(format!("output `{}` is not a file", path.display()));
            }
        }

        let mut artifacts = self.generate(lowered.modules, &lowered.sources)?;
        artifacts.extend(test_artifact);
        artifacts.extend(metadata);
        for artifact in &mut artifacts {
            artifact.path = absolute(&artifact.path)?;
        }
        self.written = artifacts
            .iter()
            .filter(|a| a.path.extension().is_some_and(|ext| ext == "js" || ext == "jsx"))
            .map(|a| a.path.clone())
            .collect();

        let mut stale = Vec::new();
        if let Some(path) = manifest_path {
            // Only remove files owned by this input/output pair, still containing
            // exactly the bytes this compiler wrote. User edits are preserved.
            if path.exists() {
                let previous = Manifest::read(&std::fs::read(&path).map_err(|e| e.to_string())?)
                    .map_err(|e| format!("invalid manifest `{}`: {e}", path.display()))?;
                if previous.input != input || previous.output != output {
                    return Err(format!("manifest `{}` belongs to another compilation", path.display()));
                }
                for file in previous.artifacts {
                    let old = absolute(&file.file)?;
                    let generated = ["js", "jsx", "map"]
                        .iter()
                        .any(|ext| old.extension().is_some_and(|e| e == *ext));
                    if generated
                        && old.starts_with(parent_dir(&output))
                        && !sources.contains(&old)
                        && !paths.contains(&old)
                        && old != input
                        && std::fs::read(&old).is_ok_and(|bytes| fingerprint(&bytes) == file.hash)
                    {
                        stale.push(old);
                    }
                }
            }
            let manifest = Manifest {
                library: lowered.library,
                version: manifest::VERSION,
                compiler: Some(manifest::Compiler::current()),
                input,
                output,
                sources,
                modules,
                artifacts: artifacts
                    .iter()
                    .map(|a| manifest::Artifact {
                        file: a.path.clone(),
                        hash: fingerprint(&a.bytes),
                    })
                    .collect(),
            };
            artifacts.push(Artifact {
                path,
                bytes: format!(
                    "{}\n",
                    serde_json::to_string_pretty(&manifest).map_err(|e| e.to_string())?
                )
                .into_bytes(),
            });
        }
        artifacts.extend(extra);
        Ok(ArtifactPlan { artifacts, stale })
    }
}

/// `Tag.d.ts` of `Tag.jsx` or `Tag.js`: its declarations' (ADR 0196).
fn types_path(js: &std::path::Path) -> PathBuf {
    js.with_extension("d.ts")
}
