//! JS's [`Intl`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl):
//! text, numbers, dates, plurals and lists as a locale writes them (ADR 0283),
//! as TypeScript's `lib.es*.intl.d.ts` and ReScript's `Stdlib_Intl` have it.
//! A formatter is made of `locales`, `&["de-DE"]`, the user's of none, and
//! options, `&NumberFormatOptions { style: Some(NumberStyle::Currency), ..Default::default() }`,
//! of which JS throws a `RangeError` of one it can't have.
//! Generated by `builtins/intl.ts`; edit the shape there.

// A binding's parameters are its JS function's: its body never runs.
#![allow(unused_variables)]

use core::cmp::Ordering;
use core::marker::PhantomData;

use super::{Date, JsError, JsObject};

/// How a locale is matched to `locales`: `localeMatcher`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LocaleMatcher {
    #[cfg_attr(rust_js, rust_js::name = "lookup")]
    Lookup,
    #[cfg_attr(rust_js, rust_js::name = "best fit")]
    BestFit,
}

/// How wide a word is written: `"long"`, `"short"` or `"narrow"`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Style {
    #[cfg_attr(rust_js, rust_js::name = "long")]
    Long,
    #[cfg_attr(rust_js, rust_js::name = "short")]
    Short,
    #[cfg_attr(rust_js, rust_js::name = "narrow")]
    Narrow,
}

/// Which of upper and lower case is ordered first: `caseFirst`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CaseFirst {
    #[cfg_attr(rust_js, rust_js::name = "upper")]
    Upper,
    #[cfg_attr(rust_js, rust_js::name = "lower")]
    Lower,
    #[cfg_attr(rust_js, rust_js::name = "false")]
    False,
}

/// How hours are counted: `hourCycle`, `"h23"` from 0 to 23.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum HourCycle {
    #[cfg_attr(rust_js, rust_js::name = "h11")]
    H11,
    #[cfg_attr(rust_js, rust_js::name = "h12")]
    H12,
    #[cfg_attr(rust_js, rust_js::name = "h23")]
    H23,
    #[cfg_attr(rust_js, rust_js::name = "h24")]
    H24,
}

/// Which of a range's ends a part is of: `source`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RangeSource {
    #[cfg_attr(rust_js, rust_js::name = "startRange")]
    StartRange,
    #[cfg_attr(rust_js, rust_js::name = "endRange")]
    EndRange,
    #[cfg_attr(rust_js, rust_js::name = "shared")]
    Shared,
}

/// What `supported_locales_of` is given.
/// A JS object of these fields, a `None` one not given: `..Default::default()` the rest.
#[derive(Default)]
pub struct SupportedLocalesOptions {
    #[cfg_attr(rust_js, rust_js::name = "localeMatcher")]
    pub locale_matcher: Option<LocaleMatcher>,
}

/// What `supported_values_of` lists.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SupportedValuesKey {
    #[cfg_attr(rust_js, rust_js::name = "calendar")]
    Calendar,
    #[cfg_attr(rust_js, rust_js::name = "collation")]
    Collation,
    #[cfg_attr(rust_js, rust_js::name = "currency")]
    Currency,
    #[cfg_attr(rust_js, rust_js::name = "numberingSystem")]
    NumberingSystem,
    #[cfg_attr(rust_js, rust_js::name = "timeZone")]
    TimeZone,
    #[cfg_attr(rust_js, rust_js::name = "unit")]
    Unit,
}

/// [`Intl.getCanonicalLocales(locales)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/getCanonicalLocales): `locales`, each as JS writes it, once, or the `RangeError` of one that isn't a locale.
#[cfg_attr(rust_js, rust_js::link_name = "Intl.getCanonicalLocales")]
pub fn get_canonical_locales(locales: &[&str]) -> Result<Vec<String>, &'static JsError> {
    unreachable!()
}

/// [`Intl.supportedValuesOf(key)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/supportedValuesOf): the calendars, currencies, time zones or units it has.
#[cfg_attr(rust_js, rust_js::link_name = "Intl.supportedValuesOf")]
pub fn supported_values_of(key: SupportedValuesKey) -> Vec<String> {
    unreachable!()
}

/// What a collator compares for: `usage`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CollatorUsage {
    #[cfg_attr(rust_js, rust_js::name = "sort")]
    Sort,
    #[cfg_attr(rust_js, rust_js::name = "search")]
    Search,
}

/// Which differences between letters count: `sensitivity`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Sensitivity {
    #[cfg_attr(rust_js, rust_js::name = "base")]
    Base,
    #[cfg_attr(rust_js, rust_js::name = "accent")]
    Accent,
    #[cfg_attr(rust_js, rust_js::name = "case")]
    Case,
    #[cfg_attr(rust_js, rust_js::name = "variant")]
    Variant,
}

/// What [`collator::new`] is given.
/// A JS object of these fields, a `None` one not given: `..Default::default()` the rest.
#[derive(Default)]
pub struct CollatorOptions<'a> {
    pub usage: Option<CollatorUsage>,
    #[cfg_attr(rust_js, rust_js::name = "localeMatcher")]
    pub locale_matcher: Option<LocaleMatcher>,
    pub numeric: Option<bool>,
    #[cfg_attr(rust_js, rust_js::name = "caseFirst")]
    pub case_first: Option<CaseFirst>,
    pub sensitivity: Option<Sensitivity>,
    pub collation: Option<&'a str>,
    #[cfg_attr(rust_js, rust_js::name = "ignorePunctuation")]
    pub ignore_punctuation: Option<bool>,
}

/// What a collator uses.
#[derive(Clone, Debug, PartialEq)]
pub struct ResolvedCollatorOptions {
    pub locale: String,
    pub usage: CollatorUsage,
    pub sensitivity: Sensitivity,
    #[cfg_attr(rust_js, rust_js::name = "ignorePunctuation")]
    pub ignore_punctuation: bool,
    pub collation: String,
    #[cfg_attr(rust_js, rust_js::name = "caseFirst")]
    pub case_first: CaseFirst,
    pub numeric: bool,
}

/// [`Intl.Collator`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator): text compared as a locale orders it.
#[cfg_attr(rust_js, rust_js::name = "Intl.Collator")]
pub struct Collator(PhantomData<JsObject>);

impl Collator {
    /// [`collator.compare(a, b)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator/compare): how `a` is ordered to `b`, `v.sort_by(|a, b| collator.compare(a, b))`; JS's -1, 0 or 1 (ADR 0057).
    #[cfg_attr(rust_js, rust_js::link_name = "compare")]
    pub fn compare(&self, a: &str, b: &str) -> Ordering {
        unreachable!()
    }

    /// [`collator.resolvedOptions()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator/resolvedOptions): the options it uses, as its locale resolved them.
    #[cfg_attr(rust_js, rust_js::link_name = "resolvedOptions")]
    pub fn resolved_options(&self) -> ResolvedCollatorOptions {
        unreachable!()
    }
}

pub mod collator {
    use super::*;

    /// [`new Intl.Collator(locales, options)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator/Collator): one of the first of `locales` it has, or the user's of none, as `options` say.
    #[cfg_attr(rust_js, rust_js::link_name = "new Intl.Collator")]
    pub fn new(locales: &[&str], options: &CollatorOptions<'_>) -> &'static Collator {
        unreachable!()
    }

    /// [`Intl.Collator.supportedLocalesOf(locales)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator/supportedLocalesOf): those of `locales` it has, without falling back to the user's.
    #[cfg_attr(rust_js, rust_js::link_name = "Intl.Collator.supportedLocalesOf")]
    pub fn supported_locales_of(locales: &[&str], options: &SupportedLocalesOptions) -> Vec<String> {
        unreachable!()
    }
}

/// What a number is written as: `style`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NumberStyle {
    #[cfg_attr(rust_js, rust_js::name = "decimal")]
    Decimal,
    #[cfg_attr(rust_js, rust_js::name = "percent")]
    Percent,
    #[cfg_attr(rust_js, rust_js::name = "currency")]
    Currency,
    #[cfg_attr(rust_js, rust_js::name = "unit")]
    Unit,
}

/// How a currency is written: `currencyDisplay`, `"symbol"` `$`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CurrencyDisplay {
    #[cfg_attr(rust_js, rust_js::name = "code")]
    Code,
    #[cfg_attr(rust_js, rust_js::name = "symbol")]
    Symbol,
    #[cfg_attr(rust_js, rust_js::name = "name")]
    Name,
    #[cfg_attr(rust_js, rust_js::name = "narrowSymbol")]
    NarrowSymbol,
}

/// How a negative amount is written: `currencySign`, `"accounting"` `($1.00)`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CurrencySign {
    #[cfg_attr(rust_js, rust_js::name = "standard")]
    Standard,
    #[cfg_attr(rust_js, rust_js::name = "accounting")]
    Accounting,
}

/// How a number is written: `notation`, `"compact"` `1.2K`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Notation {
    #[cfg_attr(rust_js, rust_js::name = "standard")]
    Standard,
    #[cfg_attr(rust_js, rust_js::name = "scientific")]
    Scientific,
    #[cfg_attr(rust_js, rust_js::name = "engineering")]
    Engineering,
    #[cfg_attr(rust_js, rust_js::name = "compact")]
    Compact,
}

/// How a compact number's word is written: `compactDisplay`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CompactDisplay {
    #[cfg_attr(rust_js, rust_js::name = "short")]
    Short,
    #[cfg_attr(rust_js, rust_js::name = "long")]
    Long,
}

/// When a sign is written: `signDisplay`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SignDisplay {
    #[cfg_attr(rust_js, rust_js::name = "auto")]
    Auto,
    #[cfg_attr(rust_js, rust_js::name = "never")]
    Never,
    #[cfg_attr(rust_js, rust_js::name = "always")]
    Always,
    #[cfg_attr(rust_js, rust_js::name = "exceptZero")]
    ExceptZero,
    #[cfg_attr(rust_js, rust_js::name = "negative")]
    Negative,
}

/// When digits are grouped, `1,000`: `useGrouping`'s word.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GroupingMode {
    #[cfg_attr(rust_js, rust_js::name = "min2")]
    Min2,
    #[cfg_attr(rust_js, rust_js::name = "auto")]
    Auto,
    #[cfg_attr(rust_js, rust_js::name = "always")]
    Always,
}

/// When digits are grouped: `useGrouping`, `false` never, or as its word says.
#[cfg_attr(rust_js, rust_js::untagged)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum UseGrouping {
    Bool(bool),
    #[cfg_attr(rust_js, rust_js::otherwise)]
    Mode(GroupingMode),
}

/// Which of the fraction and significant digits wins: `roundingPriority`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RoundingPriority {
    #[cfg_attr(rust_js, rust_js::name = "auto")]
    Auto,
    #[cfg_attr(rust_js, rust_js::name = "morePrecision")]
    MorePrecision,
    #[cfg_attr(rust_js, rust_js::name = "lessPrecision")]
    LessPrecision,
}

/// How a number is rounded: `roundingMode`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RoundingMode {
    #[cfg_attr(rust_js, rust_js::name = "ceil")]
    Ceil,
    #[cfg_attr(rust_js, rust_js::name = "floor")]
    Floor,
    #[cfg_attr(rust_js, rust_js::name = "expand")]
    Expand,
    #[cfg_attr(rust_js, rust_js::name = "trunc")]
    Trunc,
    #[cfg_attr(rust_js, rust_js::name = "halfCeil")]
    HalfCeil,
    #[cfg_attr(rust_js, rust_js::name = "halfFloor")]
    HalfFloor,
    #[cfg_attr(rust_js, rust_js::name = "halfExpand")]
    HalfExpand,
    #[cfg_attr(rust_js, rust_js::name = "halfTrunc")]
    HalfTrunc,
    #[cfg_attr(rust_js, rust_js::name = "halfEven")]
    HalfEven,
}

/// Whether a whole number's zero fraction is written: `trailingZeroDisplay`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TrailingZeroDisplay {
    #[cfg_attr(rust_js, rust_js::name = "auto")]
    Auto,
    #[cfg_attr(rust_js, rust_js::name = "stripIfInteger")]
    StripIfInteger,
}

/// What a part of a written number is.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NumberFormatPartType {
    #[cfg_attr(rust_js, rust_js::name = "literal")]
    Literal,
    #[cfg_attr(rust_js, rust_js::name = "nan")]
    Nan,
    #[cfg_attr(rust_js, rust_js::name = "infinity")]
    Infinity,
    #[cfg_attr(rust_js, rust_js::name = "percent")]
    Percent,
    #[cfg_attr(rust_js, rust_js::name = "integer")]
    Integer,
    #[cfg_attr(rust_js, rust_js::name = "group")]
    Group,
    #[cfg_attr(rust_js, rust_js::name = "decimal")]
    Decimal,
    #[cfg_attr(rust_js, rust_js::name = "fraction")]
    Fraction,
    #[cfg_attr(rust_js, rust_js::name = "plusSign")]
    PlusSign,
    #[cfg_attr(rust_js, rust_js::name = "minusSign")]
    MinusSign,
    #[cfg_attr(rust_js, rust_js::name = "percentSign")]
    PercentSign,
    #[cfg_attr(rust_js, rust_js::name = "currency")]
    Currency,
    #[cfg_attr(rust_js, rust_js::name = "compact")]
    Compact,
    #[cfg_attr(rust_js, rust_js::name = "exponentInteger")]
    ExponentInteger,
    #[cfg_attr(rust_js, rust_js::name = "exponentMinusSign")]
    ExponentMinusSign,
    #[cfg_attr(rust_js, rust_js::name = "exponentSeparator")]
    ExponentSeparator,
    #[cfg_attr(rust_js, rust_js::name = "unit")]
    Unit,
    #[cfg_attr(rust_js, rust_js::name = "unknown")]
    Unknown,
}

/// What [`number_format::new`] is given: `currency` a code, `"USD"`, `unit` a unit, `"kilometer"`.
/// A JS object of these fields, a `None` one not given: `..Default::default()` the rest.
#[derive(Default)]
pub struct NumberFormatOptions<'a> {
    #[cfg_attr(rust_js, rust_js::name = "localeMatcher")]
    pub locale_matcher: Option<LocaleMatcher>,
    pub style: Option<NumberStyle>,
    pub currency: Option<&'a str>,
    #[cfg_attr(rust_js, rust_js::name = "currencyDisplay")]
    pub currency_display: Option<CurrencyDisplay>,
    #[cfg_attr(rust_js, rust_js::name = "useGrouping")]
    pub use_grouping: Option<UseGrouping>,
    #[cfg_attr(rust_js, rust_js::name = "minimumIntegerDigits")]
    pub minimum_integer_digits: Option<u32>,
    #[cfg_attr(rust_js, rust_js::name = "minimumFractionDigits")]
    pub minimum_fraction_digits: Option<u32>,
    #[cfg_attr(rust_js, rust_js::name = "maximumFractionDigits")]
    pub maximum_fraction_digits: Option<u32>,
    #[cfg_attr(rust_js, rust_js::name = "minimumSignificantDigits")]
    pub minimum_significant_digits: Option<u32>,
    #[cfg_attr(rust_js, rust_js::name = "maximumSignificantDigits")]
    pub maximum_significant_digits: Option<u32>,
    #[cfg_attr(rust_js, rust_js::name = "numberingSystem")]
    pub numbering_system: Option<&'a str>,
    #[cfg_attr(rust_js, rust_js::name = "compactDisplay")]
    pub compact_display: Option<CompactDisplay>,
    pub notation: Option<Notation>,
    #[cfg_attr(rust_js, rust_js::name = "signDisplay")]
    pub sign_display: Option<SignDisplay>,
    pub unit: Option<&'a str>,
    #[cfg_attr(rust_js, rust_js::name = "unitDisplay")]
    pub unit_display: Option<Style>,
    #[cfg_attr(rust_js, rust_js::name = "currencySign")]
    pub currency_sign: Option<CurrencySign>,
    #[cfg_attr(rust_js, rust_js::name = "roundingPriority")]
    pub rounding_priority: Option<RoundingPriority>,
    #[cfg_attr(rust_js, rust_js::name = "roundingIncrement")]
    pub rounding_increment: Option<u32>,
    #[cfg_attr(rust_js, rust_js::name = "roundingMode")]
    pub rounding_mode: Option<RoundingMode>,
    #[cfg_attr(rust_js, rust_js::name = "trailingZeroDisplay")]
    pub trailing_zero_display: Option<TrailingZeroDisplay>,
}

/// What a number format uses.
#[derive(Clone, Debug, PartialEq)]
pub struct ResolvedNumberFormatOptions {
    pub locale: String,
    #[cfg_attr(rust_js, rust_js::name = "numberingSystem")]
    pub numbering_system: String,
    pub style: NumberStyle,
    pub currency: Option<String>,
    #[cfg_attr(rust_js, rust_js::name = "currencyDisplay")]
    pub currency_display: Option<CurrencyDisplay>,
    #[cfg_attr(rust_js, rust_js::name = "minimumIntegerDigits")]
    pub minimum_integer_digits: u32,
    #[cfg_attr(rust_js, rust_js::name = "minimumFractionDigits")]
    pub minimum_fraction_digits: Option<u32>,
    #[cfg_attr(rust_js, rust_js::name = "maximumFractionDigits")]
    pub maximum_fraction_digits: Option<u32>,
    #[cfg_attr(rust_js, rust_js::name = "minimumSignificantDigits")]
    pub minimum_significant_digits: Option<u32>,
    #[cfg_attr(rust_js, rust_js::name = "maximumSignificantDigits")]
    pub maximum_significant_digits: Option<u32>,
    #[cfg_attr(rust_js, rust_js::name = "useGrouping")]
    pub use_grouping: UseGrouping,
    #[cfg_attr(rust_js, rust_js::name = "compactDisplay")]
    pub compact_display: Option<CompactDisplay>,
    pub notation: Notation,
    #[cfg_attr(rust_js, rust_js::name = "signDisplay")]
    pub sign_display: SignDisplay,
    pub unit: Option<String>,
    #[cfg_attr(rust_js, rust_js::name = "unitDisplay")]
    pub unit_display: Option<Style>,
    #[cfg_attr(rust_js, rust_js::name = "currencySign")]
    pub currency_sign: Option<CurrencySign>,
    #[cfg_attr(rust_js, rust_js::name = "roundingPriority")]
    pub rounding_priority: RoundingPriority,
    #[cfg_attr(rust_js, rust_js::name = "roundingMode")]
    pub rounding_mode: RoundingMode,
    #[cfg_attr(rust_js, rust_js::name = "roundingIncrement")]
    pub rounding_increment: u32,
    #[cfg_attr(rust_js, rust_js::name = "trailingZeroDisplay")]
    pub trailing_zero_display: TrailingZeroDisplay,
}

/// A part of a written number: `formatToParts`'.
#[derive(Clone, Debug, PartialEq)]
pub struct NumberFormatPart {
    pub r#type: NumberFormatPartType,
    pub value: String,
}

/// A part of a written range of numbers, and which end it's of.
#[derive(Clone, Debug, PartialEq)]
pub struct NumberRangeFormatPart {
    pub r#type: NumberFormatPartType,
    pub value: String,
    pub source: RangeSource,
}

/// [`Intl.NumberFormat`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat): numbers written as a locale writes them.
#[cfg_attr(rust_js, rust_js::name = "Intl.NumberFormat")]
pub struct NumberFormat(PhantomData<JsObject>);

impl NumberFormat {
    /// [`format.format(n)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/format): `n` written.
    #[cfg_attr(rust_js, rust_js::link_name = "format")]
    pub fn format(&self, n: f64) -> String {
        unreachable!()
    }

    /// `format.format(n)` of a `BigInt`, an `i64` (ADR 0086), as ReScript's `formatBigInt`.
    #[cfg_attr(rust_js, rust_js::link_name = "format")]
    pub fn format_big_int(&self, n: i64) -> String {
        unreachable!()
    }

    /// `format.format(text)` of a number's text, `"1.10"`, exact however long.
    #[cfg_attr(rust_js, rust_js::link_name = "format")]
    pub fn format_string(&self, text: &str) -> String {
        unreachable!()
    }

    /// [`format.formatToParts(n)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts): `n` written, part by part.
    #[cfg_attr(rust_js, rust_js::link_name = "formatToParts")]
    pub fn format_to_parts(&self, n: f64) -> Vec<NumberFormatPart> {
        unreachable!()
    }

    /// [`format.formatRange(start, end)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatRange): the range written, `$3–5`.
    #[cfg_attr(rust_js, rust_js::link_name = "formatRange")]
    pub fn format_range(&self, start: f64, end: f64) -> String {
        unreachable!()
    }

    /// [`format.formatRangeToParts(start, end)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatRangeToParts): the range written, part by part.
    #[cfg_attr(rust_js, rust_js::link_name = "formatRangeToParts")]
    pub fn format_range_to_parts(&self, start: f64, end: f64) -> Vec<NumberRangeFormatPart> {
        unreachable!()
    }

    /// [`numberformat.resolvedOptions()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/resolvedOptions): the options it uses, as its locale resolved them.
    #[cfg_attr(rust_js, rust_js::link_name = "resolvedOptions")]
    pub fn resolved_options(&self) -> ResolvedNumberFormatOptions {
        unreachable!()
    }
}

pub mod number_format {
    use super::*;

    /// [`new Intl.NumberFormat(locales, options)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat): one of the first of `locales` it has, or the user's of none, as `options` say.
    #[cfg_attr(rust_js, rust_js::link_name = "new Intl.NumberFormat")]
    pub fn new(locales: &[&str], options: &NumberFormatOptions<'_>) -> &'static NumberFormat {
        unreachable!()
    }

    /// [`Intl.NumberFormat.supportedLocalesOf(locales)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/supportedLocalesOf): those of `locales` it has, without falling back to the user's.
    #[cfg_attr(rust_js, rust_js::link_name = "Intl.NumberFormat.supportedLocalesOf")]
    pub fn supported_locales_of(locales: &[&str], options: &SupportedLocalesOptions) -> Vec<String> {
        unreachable!()
    }
}

/// How a number of a date is written: `"numeric"` `7`, `"2-digit"` `07`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NumericStyle {
    #[cfg_attr(rust_js, rust_js::name = "numeric")]
    Numeric,
    #[cfg_attr(rust_js, rust_js::name = "2-digit")]
    TwoDigit,
}

/// How a month is written: `month`, `"long"` `July`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MonthStyle {
    #[cfg_attr(rust_js, rust_js::name = "numeric")]
    Numeric,
    #[cfg_attr(rust_js, rust_js::name = "2-digit")]
    TwoDigit,
    #[cfg_attr(rust_js, rust_js::name = "long")]
    Long,
    #[cfg_attr(rust_js, rust_js::name = "short")]
    Short,
    #[cfg_attr(rust_js, rust_js::name = "narrow")]
    Narrow,
}

/// How a time zone is written: `timeZoneName`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TimeZoneNameStyle {
    #[cfg_attr(rust_js, rust_js::name = "short")]
    Short,
    #[cfg_attr(rust_js, rust_js::name = "long")]
    Long,
    #[cfg_attr(rust_js, rust_js::name = "shortOffset")]
    ShortOffset,
    #[cfg_attr(rust_js, rust_js::name = "longOffset")]
    LongOffset,
    #[cfg_attr(rust_js, rust_js::name = "shortGeneric")]
    ShortGeneric,
    #[cfg_attr(rust_js, rust_js::name = "longGeneric")]
    LongGeneric,
}

/// How the parts asked for are matched to a locale's: `formatMatcher`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FormatMatcher {
    #[cfg_attr(rust_js, rust_js::name = "basic")]
    Basic,
    #[cfg_attr(rust_js, rust_js::name = "best fit")]
    BestFit,
}

/// How much of a date or time is written: `dateStyle`, `timeStyle`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DateTimeStyle {
    #[cfg_attr(rust_js, rust_js::name = "full")]
    Full,
    #[cfg_attr(rust_js, rust_js::name = "long")]
    Long,
    #[cfg_attr(rust_js, rust_js::name = "medium")]
    Medium,
    #[cfg_attr(rust_js, rust_js::name = "short")]
    Short,
}

/// What a part of a written date is.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DateTimeFormatPartType {
    #[cfg_attr(rust_js, rust_js::name = "day")]
    Day,
    #[cfg_attr(rust_js, rust_js::name = "dayPeriod")]
    DayPeriod,
    #[cfg_attr(rust_js, rust_js::name = "era")]
    Era,
    #[cfg_attr(rust_js, rust_js::name = "hour")]
    Hour,
    #[cfg_attr(rust_js, rust_js::name = "literal")]
    Literal,
    #[cfg_attr(rust_js, rust_js::name = "minute")]
    Minute,
    #[cfg_attr(rust_js, rust_js::name = "month")]
    Month,
    #[cfg_attr(rust_js, rust_js::name = "second")]
    Second,
    #[cfg_attr(rust_js, rust_js::name = "timeZoneName")]
    TimeZoneName,
    #[cfg_attr(rust_js, rust_js::name = "weekday")]
    Weekday,
    #[cfg_attr(rust_js, rust_js::name = "year")]
    Year,
    #[cfg_attr(rust_js, rust_js::name = "fractionalSecond")]
    FractionalSecond,
}

/// What [`date_time_format::new`] and a date's `to_locale_string_with` are given: `time_zone` an IANA name, `"Asia/Tokyo"`.
/// A JS object of these fields, a `None` one not given: `..Default::default()` the rest.
#[derive(Default)]
pub struct DateTimeFormatOptions<'a> {
    #[cfg_attr(rust_js, rust_js::name = "localeMatcher")]
    pub locale_matcher: Option<LocaleMatcher>,
    pub weekday: Option<Style>,
    pub era: Option<Style>,
    pub year: Option<NumericStyle>,
    pub month: Option<MonthStyle>,
    pub day: Option<NumericStyle>,
    pub hour: Option<NumericStyle>,
    pub minute: Option<NumericStyle>,
    pub second: Option<NumericStyle>,
    #[cfg_attr(rust_js, rust_js::name = "timeZoneName")]
    pub time_zone_name: Option<TimeZoneNameStyle>,
    #[cfg_attr(rust_js, rust_js::name = "formatMatcher")]
    pub format_matcher: Option<FormatMatcher>,
    pub hour12: Option<bool>,
    #[cfg_attr(rust_js, rust_js::name = "timeZone")]
    pub time_zone: Option<&'a str>,
    pub calendar: Option<&'a str>,
    #[cfg_attr(rust_js, rust_js::name = "dayPeriod")]
    pub day_period: Option<Style>,
    #[cfg_attr(rust_js, rust_js::name = "numberingSystem")]
    pub numbering_system: Option<&'a str>,
    #[cfg_attr(rust_js, rust_js::name = "dateStyle")]
    pub date_style: Option<DateTimeStyle>,
    #[cfg_attr(rust_js, rust_js::name = "timeStyle")]
    pub time_style: Option<DateTimeStyle>,
    #[cfg_attr(rust_js, rust_js::name = "hourCycle")]
    pub hour_cycle: Option<HourCycle>,
    #[cfg_attr(rust_js, rust_js::name = "fractionalSecondDigits")]
    pub fractional_second_digits: Option<u32>,
}

/// What a date format uses.
#[derive(Clone, Debug, PartialEq)]
pub struct ResolvedDateTimeFormatOptions {
    pub locale: String,
    pub calendar: String,
    #[cfg_attr(rust_js, rust_js::name = "numberingSystem")]
    pub numbering_system: String,
    #[cfg_attr(rust_js, rust_js::name = "timeZone")]
    pub time_zone: String,
    pub hour12: Option<bool>,
    pub weekday: Option<Style>,
    pub era: Option<Style>,
    pub year: Option<NumericStyle>,
    pub month: Option<MonthStyle>,
    pub day: Option<NumericStyle>,
    pub hour: Option<NumericStyle>,
    pub minute: Option<NumericStyle>,
    pub second: Option<NumericStyle>,
    #[cfg_attr(rust_js, rust_js::name = "timeZoneName")]
    pub time_zone_name: Option<TimeZoneNameStyle>,
    #[cfg_attr(rust_js, rust_js::name = "formatMatcher")]
    pub format_matcher: Option<FormatMatcher>,
    #[cfg_attr(rust_js, rust_js::name = "dateStyle")]
    pub date_style: Option<DateTimeStyle>,
    #[cfg_attr(rust_js, rust_js::name = "timeStyle")]
    pub time_style: Option<DateTimeStyle>,
    #[cfg_attr(rust_js, rust_js::name = "hourCycle")]
    pub hour_cycle: Option<HourCycle>,
    #[cfg_attr(rust_js, rust_js::name = "dayPeriod")]
    pub day_period: Option<Style>,
    #[cfg_attr(rust_js, rust_js::name = "fractionalSecondDigits")]
    pub fractional_second_digits: Option<u32>,
}

/// A part of a written date: `formatToParts`'.
#[derive(Clone, Debug, PartialEq)]
pub struct DateTimeFormatPart {
    pub r#type: DateTimeFormatPartType,
    pub value: String,
}

/// A part of a written range of dates, and which end it's of.
#[derive(Clone, Debug, PartialEq)]
pub struct DateTimeRangeFormatPart {
    pub r#type: DateTimeFormatPartType,
    pub value: String,
    pub source: RangeSource,
}

/// [`Intl.DateTimeFormat`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat): dates written as a locale writes them.
#[cfg_attr(rust_js, rust_js::name = "Intl.DateTimeFormat")]
pub struct DateTimeFormat(PhantomData<JsObject>);

impl DateTimeFormat {
    /// [`format.format(date)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/format): `date` written.
    #[cfg_attr(rust_js, rust_js::link_name = "format")]
    pub fn format(&self, date: &Date) -> String {
        unreachable!()
    }

    /// [`format.formatToParts(date)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatToParts): `date` written, part by part.
    #[cfg_attr(rust_js, rust_js::link_name = "formatToParts")]
    pub fn format_to_parts(&self, date: &Date) -> Vec<DateTimeFormatPart> {
        unreachable!()
    }

    /// [`format.formatRange(start, end)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRange): the range written, `Jan 10 – 20, 2007`.
    #[cfg_attr(rust_js, rust_js::link_name = "formatRange")]
    pub fn format_range(&self, start: &Date, end: &Date) -> String {
        unreachable!()
    }

    /// [`format.formatRangeToParts(start, end)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRangeToParts): the range written, part by part.
    #[cfg_attr(rust_js, rust_js::link_name = "formatRangeToParts")]
    pub fn format_range_to_parts(&self, start: &Date, end: &Date) -> Vec<DateTimeRangeFormatPart> {
        unreachable!()
    }

    /// [`datetimeformat.resolvedOptions()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/resolvedOptions): the options it uses, as its locale resolved them.
    #[cfg_attr(rust_js, rust_js::link_name = "resolvedOptions")]
    pub fn resolved_options(&self) -> ResolvedDateTimeFormatOptions {
        unreachable!()
    }
}

pub mod date_time_format {
    use super::*;

    /// [`new Intl.DateTimeFormat(locales, options)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat): one of the first of `locales` it has, or the user's of none, as `options` say.
    #[cfg_attr(rust_js, rust_js::link_name = "new Intl.DateTimeFormat")]
    pub fn new(locales: &[&str], options: &DateTimeFormatOptions<'_>) -> &'static DateTimeFormat {
        unreachable!()
    }

    /// [`Intl.DateTimeFormat.supportedLocalesOf(locales)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/supportedLocalesOf): those of `locales` it has, without falling back to the user's.
    #[cfg_attr(rust_js, rust_js::link_name = "Intl.DateTimeFormat.supportedLocalesOf")]
    pub fn supported_locales_of(locales: &[&str], options: &SupportedLocalesOptions) -> Vec<String> {
        unreachable!()
    }
}

/// Which of a locale's plural forms a number takes: `"one"`, `"other"`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PluralCategory {
    #[cfg_attr(rust_js, rust_js::name = "zero")]
    Zero,
    #[cfg_attr(rust_js, rust_js::name = "one")]
    One,
    #[cfg_attr(rust_js, rust_js::name = "two")]
    Two,
    #[cfg_attr(rust_js, rust_js::name = "few")]
    Few,
    #[cfg_attr(rust_js, rust_js::name = "many")]
    Many,
    #[cfg_attr(rust_js, rust_js::name = "other")]
    Other,
}

/// Of counting, `"cardinal"` `1 file`, or ordering, `"ordinal"` `1st`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PluralRuleType {
    #[cfg_attr(rust_js, rust_js::name = "cardinal")]
    Cardinal,
    #[cfg_attr(rust_js, rust_js::name = "ordinal")]
    Ordinal,
}

/// What [`plural_rules::new`] is given.
/// A JS object of these fields, a `None` one not given: `..Default::default()` the rest.
#[derive(Default)]
pub struct PluralRulesOptions {
    #[cfg_attr(rust_js, rust_js::name = "localeMatcher")]
    pub locale_matcher: Option<LocaleMatcher>,
    pub r#type: Option<PluralRuleType>,
    #[cfg_attr(rust_js, rust_js::name = "minimumIntegerDigits")]
    pub minimum_integer_digits: Option<u32>,
    #[cfg_attr(rust_js, rust_js::name = "minimumFractionDigits")]
    pub minimum_fraction_digits: Option<u32>,
    #[cfg_attr(rust_js, rust_js::name = "maximumFractionDigits")]
    pub maximum_fraction_digits: Option<u32>,
    #[cfg_attr(rust_js, rust_js::name = "minimumSignificantDigits")]
    pub minimum_significant_digits: Option<u32>,
    #[cfg_attr(rust_js, rust_js::name = "maximumSignificantDigits")]
    pub maximum_significant_digits: Option<u32>,
}

/// What plural rules use.
#[derive(Clone, Debug, PartialEq)]
pub struct ResolvedPluralRulesOptions {
    pub locale: String,
    #[cfg_attr(rust_js, rust_js::name = "pluralCategories")]
    pub plural_categories: Vec<PluralCategory>,
    pub r#type: PluralRuleType,
    #[cfg_attr(rust_js, rust_js::name = "minimumIntegerDigits")]
    pub minimum_integer_digits: u32,
    #[cfg_attr(rust_js, rust_js::name = "minimumFractionDigits")]
    pub minimum_fraction_digits: u32,
    #[cfg_attr(rust_js, rust_js::name = "maximumFractionDigits")]
    pub maximum_fraction_digits: u32,
    #[cfg_attr(rust_js, rust_js::name = "minimumSignificantDigits")]
    pub minimum_significant_digits: Option<u32>,
    #[cfg_attr(rust_js, rust_js::name = "maximumSignificantDigits")]
    pub maximum_significant_digits: Option<u32>,
}

/// [`Intl.PluralRules`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules): which plural form a number takes in a locale.
#[cfg_attr(rust_js, rust_js::name = "Intl.PluralRules")]
pub struct PluralRules(PhantomData<JsObject>);

impl PluralRules {
    /// [`rules.select(n)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/select): the form `n` takes.
    #[cfg_attr(rust_js, rust_js::link_name = "select")]
    pub fn select(&self, n: f64) -> PluralCategory {
        unreachable!()
    }

    /// [`pluralrules.resolvedOptions()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/resolvedOptions): the options it uses, as its locale resolved them.
    #[cfg_attr(rust_js, rust_js::link_name = "resolvedOptions")]
    pub fn resolved_options(&self) -> ResolvedPluralRulesOptions {
        unreachable!()
    }
}

pub mod plural_rules {
    use super::*;

    /// [`new Intl.PluralRules(locales, options)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/PluralRules): one of the first of `locales` it has, or the user's of none, as `options` say.
    #[cfg_attr(rust_js, rust_js::link_name = "new Intl.PluralRules")]
    pub fn new(locales: &[&str], options: &PluralRulesOptions) -> &'static PluralRules {
        unreachable!()
    }

    /// [`Intl.PluralRules.supportedLocalesOf(locales)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/supportedLocalesOf): those of `locales` it has, without falling back to the user's.
    #[cfg_attr(rust_js, rust_js::link_name = "Intl.PluralRules.supportedLocalesOf")]
    pub fn supported_locales_of(locales: &[&str], options: &SupportedLocalesOptions) -> Vec<String> {
        unreachable!()
    }
}

/// A unit of time: `"day"`. JS takes its plural too, `"days"`, the same.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RelativeTimeUnit {
    #[cfg_attr(rust_js, rust_js::name = "year")]
    Year,
    #[cfg_attr(rust_js, rust_js::name = "quarter")]
    Quarter,
    #[cfg_attr(rust_js, rust_js::name = "month")]
    Month,
    #[cfg_attr(rust_js, rust_js::name = "week")]
    Week,
    #[cfg_attr(rust_js, rust_js::name = "day")]
    Day,
    #[cfg_attr(rust_js, rust_js::name = "hour")]
    Hour,
    #[cfg_attr(rust_js, rust_js::name = "minute")]
    Minute,
    #[cfg_attr(rust_js, rust_js::name = "second")]
    Second,
}

/// Whether a number is always written, `"1 day ago"`, or a word where there is one, `"auto"` `"yesterday"`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RelativeTimeNumeric {
    #[cfg_attr(rust_js, rust_js::name = "always")]
    Always,
    #[cfg_attr(rust_js, rust_js::name = "auto")]
    Auto,
}

/// What [`relative_time_format::new`] is given.
/// A JS object of these fields, a `None` one not given: `..Default::default()` the rest.
#[derive(Default)]
pub struct RelativeTimeFormatOptions {
    #[cfg_attr(rust_js, rust_js::name = "localeMatcher")]
    pub locale_matcher: Option<LocaleMatcher>,
    pub numeric: Option<RelativeTimeNumeric>,
    pub style: Option<Style>,
}

/// What a relative time format uses.
#[derive(Clone, Debug, PartialEq)]
pub struct ResolvedRelativeTimeFormatOptions {
    pub locale: String,
    pub style: Style,
    pub numeric: RelativeTimeNumeric,
    #[cfg_attr(rust_js, rust_js::name = "numberingSystem")]
    pub numbering_system: String,
}

/// A part of a written time: its number's parts are of its `unit`, which a literal has none of.
#[derive(Clone, Debug, PartialEq)]
pub struct RelativeTimeFormatPart {
    pub r#type: NumberFormatPartType,
    pub value: String,
    pub unit: Option<RelativeTimeUnit>,
}

/// [`Intl.RelativeTimeFormat`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat): a time from now written as a locale writes it, `in 3 days`.
#[cfg_attr(rust_js, rust_js::name = "Intl.RelativeTimeFormat")]
pub struct RelativeTimeFormat(PhantomData<JsObject>);

impl RelativeTimeFormat {
    /// [`format.format(value, unit)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/format): `value` `unit`s from now written, ago if negative.
    #[cfg_attr(rust_js, rust_js::link_name = "format")]
    pub fn format(&self, value: f64, unit: RelativeTimeUnit) -> String {
        unreachable!()
    }

    /// [`format.formatToParts(value, unit)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/formatToParts): written, part by part.
    #[cfg_attr(rust_js, rust_js::link_name = "formatToParts")]
    pub fn format_to_parts(&self, value: f64, unit: RelativeTimeUnit) -> Vec<RelativeTimeFormatPart> {
        unreachable!()
    }

    /// [`relativetimeformat.resolvedOptions()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/resolvedOptions): the options it uses, as its locale resolved them.
    #[cfg_attr(rust_js, rust_js::link_name = "resolvedOptions")]
    pub fn resolved_options(&self) -> ResolvedRelativeTimeFormatOptions {
        unreachable!()
    }
}

pub mod relative_time_format {
    use super::*;

    /// [`new Intl.RelativeTimeFormat(locales, options)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/RelativeTimeFormat): one of the first of `locales` it has, or the user's of none, as `options` say.
    #[cfg_attr(rust_js, rust_js::link_name = "new Intl.RelativeTimeFormat")]
    pub fn new(locales: &[&str], options: &RelativeTimeFormatOptions) -> &'static RelativeTimeFormat {
        unreachable!()
    }

    /// [`Intl.RelativeTimeFormat.supportedLocalesOf(locales)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/supportedLocalesOf): those of `locales` it has, without falling back to the user's.
    #[cfg_attr(rust_js, rust_js::link_name = "Intl.RelativeTimeFormat.supportedLocalesOf")]
    pub fn supported_locales_of(locales: &[&str], options: &SupportedLocalesOptions) -> Vec<String> {
        unreachable!()
    }
}

/// What a list says: `"conjunction"` `a, b, and c`, `"disjunction"` `a, b, or c`, `"unit"` `a, b, c`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ListFormatType {
    #[cfg_attr(rust_js, rust_js::name = "conjunction")]
    Conjunction,
    #[cfg_attr(rust_js, rust_js::name = "disjunction")]
    Disjunction,
    #[cfg_attr(rust_js, rust_js::name = "unit")]
    Unit,
}

/// What a part of a written list is: an item, or what's between.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ListFormatPartType {
    #[cfg_attr(rust_js, rust_js::name = "element")]
    Element,
    #[cfg_attr(rust_js, rust_js::name = "literal")]
    Literal,
}

/// What [`list_format::new`] is given.
/// A JS object of these fields, a `None` one not given: `..Default::default()` the rest.
#[derive(Default)]
pub struct ListFormatOptions {
    #[cfg_attr(rust_js, rust_js::name = "localeMatcher")]
    pub locale_matcher: Option<LocaleMatcher>,
    pub r#type: Option<ListFormatType>,
    pub style: Option<Style>,
}

/// What a list format uses.
#[derive(Clone, Debug, PartialEq)]
pub struct ResolvedListFormatOptions {
    pub locale: String,
    pub style: Style,
    pub r#type: ListFormatType,
}

/// A part of a written list.
#[derive(Clone, Debug, PartialEq)]
pub struct ListFormatPart {
    pub r#type: ListFormatPartType,
    pub value: String,
}

/// [`Intl.ListFormat`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat): lists written as a locale writes them.
#[cfg_attr(rust_js, rust_js::name = "Intl.ListFormat")]
pub struct ListFormat(PhantomData<JsObject>);

impl ListFormat {
    /// [`format.format(list)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/format): `list` written.
    #[cfg_attr(rust_js, rust_js::link_name = "format")]
    pub fn format(&self, list: &[&str]) -> String {
        unreachable!()
    }

    /// [`format.formatToParts(list)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/formatToParts): `list` written, part by part.
    #[cfg_attr(rust_js, rust_js::link_name = "formatToParts")]
    pub fn format_to_parts(&self, list: &[&str]) -> Vec<ListFormatPart> {
        unreachable!()
    }

    /// [`listformat.resolvedOptions()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/resolvedOptions): the options it uses, as its locale resolved them.
    #[cfg_attr(rust_js, rust_js::link_name = "resolvedOptions")]
    pub fn resolved_options(&self) -> ResolvedListFormatOptions {
        unreachable!()
    }
}

pub mod list_format {
    use super::*;

    /// [`new Intl.ListFormat(locales, options)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/ListFormat): one of the first of `locales` it has, or the user's of none, as `options` say.
    #[cfg_attr(rust_js, rust_js::link_name = "new Intl.ListFormat")]
    pub fn new(locales: &[&str], options: &ListFormatOptions) -> &'static ListFormat {
        unreachable!()
    }

    /// [`Intl.ListFormat.supportedLocalesOf(locales)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/supportedLocalesOf): those of `locales` it has, without falling back to the user's.
    #[cfg_attr(rust_js, rust_js::link_name = "Intl.ListFormat.supportedLocalesOf")]
    pub fn supported_locales_of(locales: &[&str], options: &SupportedLocalesOptions) -> Vec<String> {
        unreachable!()
    }
}

/// What's named: a language, a region, a currency..
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DisplayNamesType {
    #[cfg_attr(rust_js, rust_js::name = "language")]
    Language,
    #[cfg_attr(rust_js, rust_js::name = "region")]
    Region,
    #[cfg_attr(rust_js, rust_js::name = "script")]
    Script,
    #[cfg_attr(rust_js, rust_js::name = "calendar")]
    Calendar,
    #[cfg_attr(rust_js, rust_js::name = "dateTimeField")]
    DateTimeField,
    #[cfg_attr(rust_js, rust_js::name = "currency")]
    Currency,
}

/// What's given of a code without a name: the code, or none.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DisplayNamesFallback {
    #[cfg_attr(rust_js, rust_js::name = "code")]
    Code,
    #[cfg_attr(rust_js, rust_js::name = "none")]
    None,
}

/// How a language is named: `"dialect"` `British English`, `"standard"` `English (United Kingdom)`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LanguageDisplay {
    #[cfg_attr(rust_js, rust_js::name = "dialect")]
    Dialect,
    #[cfg_attr(rust_js, rust_js::name = "standard")]
    Standard,
}

/// What [`display_names::new`] is given; its `type` is required, as JS's is.
/// A JS object of these fields, a `None` one not given.
pub struct DisplayNamesOptions {
    #[cfg_attr(rust_js, rust_js::name = "localeMatcher")]
    pub locale_matcher: Option<LocaleMatcher>,
    pub style: Option<Style>,
    pub r#type: DisplayNamesType,
    #[cfg_attr(rust_js, rust_js::name = "languageDisplay")]
    pub language_display: Option<LanguageDisplay>,
    pub fallback: Option<DisplayNamesFallback>,
}

/// What display names use.
#[derive(Clone, Debug, PartialEq)]
pub struct ResolvedDisplayNamesOptions {
    pub locale: String,
    pub style: Style,
    pub r#type: DisplayNamesType,
    pub fallback: DisplayNamesFallback,
    #[cfg_attr(rust_js, rust_js::name = "languageDisplay")]
    pub language_display: Option<LanguageDisplay>,
}

/// [`Intl.DisplayNames`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames): languages, regions, currencies and scripts named as a locale names them.
#[cfg_attr(rust_js, rust_js::name = "Intl.DisplayNames")]
pub struct DisplayNames(PhantomData<JsObject>);

impl DisplayNames {
    /// [`names.of(code)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames/of): the name of `code`, `"fr"`, `"US"`; none of one without a name, where `fallback` is `"none"`.
    #[cfg_attr(rust_js, rust_js::link_name = "of")]
    pub fn of(&self, code: &str) -> Option<String> {
        unreachable!()
    }

    /// [`displaynames.resolvedOptions()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames/resolvedOptions): the options it uses, as its locale resolved them.
    #[cfg_attr(rust_js, rust_js::link_name = "resolvedOptions")]
    pub fn resolved_options(&self) -> ResolvedDisplayNamesOptions {
        unreachable!()
    }
}

pub mod display_names {
    use super::*;

    /// [`new Intl.DisplayNames(locales, options)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames/DisplayNames): one of the first of `locales` it has, or the user's of none, as `options` say.
    #[cfg_attr(rust_js, rust_js::link_name = "new Intl.DisplayNames")]
    pub fn new(locales: &[&str], options: &DisplayNamesOptions) -> &'static DisplayNames {
        unreachable!()
    }

    /// [`Intl.DisplayNames.supportedLocalesOf(locales)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames/supportedLocalesOf): those of `locales` it has, without falling back to the user's.
    #[cfg_attr(rust_js, rust_js::link_name = "Intl.DisplayNames.supportedLocalesOf")]
    pub fn supported_locales_of(locales: &[&str], options: &SupportedLocalesOptions) -> Vec<String> {
        unreachable!()
    }
}

/// What [`locale::new`] is given: each a part of the locale it makes, over its tag's.
/// A JS object of these fields, a `None` one not given: `..Default::default()` the rest.
#[derive(Default)]
pub struct LocaleOptions<'a> {
    pub calendar: Option<&'a str>,
    #[cfg_attr(rust_js, rust_js::name = "caseFirst")]
    pub case_first: Option<CaseFirst>,
    pub collation: Option<&'a str>,
    #[cfg_attr(rust_js, rust_js::name = "hourCycle")]
    pub hour_cycle: Option<HourCycle>,
    pub language: Option<&'a str>,
    #[cfg_attr(rust_js, rust_js::name = "numberingSystem")]
    pub numbering_system: Option<&'a str>,
    pub numeric: Option<bool>,
    pub region: Option<&'a str>,
    pub script: Option<&'a str>,
}

/// [`Intl.Locale`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale): a locale and its parts, `en-Latn-US`.
#[cfg_attr(rust_js, rust_js::name = "Intl.Locale")]
pub struct Locale(PhantomData<JsObject>);

impl Locale {
    /// [`locale.baseName`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/baseName): its language, script and region, `en-Latn-US`.
    #[cfg_attr(rust_js, rust_js::link_name = "get baseName")]
    pub fn base_name(&self) -> String {
        unreachable!()
    }

    /// [`locale.language`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/language): its language, `en`.
    #[cfg_attr(rust_js, rust_js::link_name = "get language")]
    pub fn language(&self) -> String {
        unreachable!()
    }

    /// [`locale.script`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/script): its script, `Latn`.
    #[cfg_attr(rust_js, rust_js::link_name = "get script")]
    pub fn script(&self) -> Option<String> {
        unreachable!()
    }

    /// [`locale.region`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/region): its region, `US`.
    #[cfg_attr(rust_js, rust_js::link_name = "get region")]
    pub fn region(&self) -> Option<String> {
        unreachable!()
    }

    /// [`locale.calendar`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/calendar): its calendar.
    #[cfg_attr(rust_js, rust_js::link_name = "get calendar")]
    pub fn calendar(&self) -> Option<String> {
        unreachable!()
    }

    /// [`locale.caseFirst`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/caseFirst): which case it orders first.
    #[cfg_attr(rust_js, rust_js::link_name = "get caseFirst")]
    pub fn case_first(&self) -> Option<CaseFirst> {
        unreachable!()
    }

    /// [`locale.collation`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/collation): how it orders text.
    #[cfg_attr(rust_js, rust_js::link_name = "get collation")]
    pub fn collation(&self) -> Option<String> {
        unreachable!()
    }

    /// [`locale.hourCycle`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/hourCycle): how it counts hours.
    #[cfg_attr(rust_js, rust_js::link_name = "get hourCycle")]
    pub fn hour_cycle(&self) -> Option<HourCycle> {
        unreachable!()
    }

    /// [`locale.numberingSystem`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/numberingSystem): its digits.
    #[cfg_attr(rust_js, rust_js::link_name = "get numberingSystem")]
    pub fn numbering_system(&self) -> Option<String> {
        unreachable!()
    }

    /// [`locale.numeric`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/numeric): whether it orders numbers in text by their value.
    #[cfg_attr(rust_js, rust_js::link_name = "get numeric")]
    pub fn numeric(&self) -> bool {
        unreachable!()
    }

    /// [`locale.maximize()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/maximize): with the script and region most likely of its language, `en` `en-Latn-US`.
    #[cfg_attr(rust_js, rust_js::link_name = "maximize")]
    pub fn maximize(&self) -> &'static Locale {
        unreachable!()
    }

    /// [`locale.minimize()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/minimize): without what `maximize` would add.
    #[cfg_attr(rust_js, rust_js::link_name = "minimize")]
    pub fn minimize(&self) -> &'static Locale {
        unreachable!()
    }

    /// [`locale.toString()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/toString): its tag.
    #[cfg_attr(rust_js, rust_js::link_name = "toString")]
    pub fn to_string(&self) -> String {
        unreachable!()
    }
}

pub mod locale {
    use super::*;

    /// [`new Intl.Locale(tag, options)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/Locale): the locale of `tag`, `"en-US"`, as `options` change it, or the `RangeError` of a tag that isn't one.
    #[cfg_attr(rust_js, rust_js::link_name = "new Intl.Locale")]
    pub fn new(tag: &str, options: &LocaleOptions<'_>) -> Result<&'static Locale, &'static JsError> {
        unreachable!()
    }
}

/// What text is split into: `granularity`, `"grapheme"` what a reader sees as a letter.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Granularity {
    #[cfg_attr(rust_js, rust_js::name = "grapheme")]
    Grapheme,
    #[cfg_attr(rust_js, rust_js::name = "word")]
    Word,
    #[cfg_attr(rust_js, rust_js::name = "sentence")]
    Sentence,
}

/// What [`segmenter::new`] is given.
/// A JS object of these fields, a `None` one not given: `..Default::default()` the rest.
#[derive(Default)]
pub struct SegmenterOptions {
    #[cfg_attr(rust_js, rust_js::name = "localeMatcher")]
    pub locale_matcher: Option<LocaleMatcher>,
    pub granularity: Option<Granularity>,
}

/// What a segmenter uses.
#[derive(Clone, Debug, PartialEq)]
pub struct ResolvedSegmenterOptions {
    pub locale: String,
    pub granularity: Granularity,
}

/// A segment of text: what it is, where it starts in `input`, and whether it's a word.
#[derive(Clone, Debug, PartialEq)]
pub struct SegmentData {
    pub segment: String,
    pub index: u32,
    pub input: String,
    #[cfg_attr(rust_js, rust_js::name = "isWordLike")]
    pub is_word_like: Option<bool>,
}

/// [What `segment` gives](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/segment/Segments): the segments of a text.
pub struct Segments(PhantomData<JsObject>);

impl Segments {
    /// [`segments.containing(index)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/segment/Segments/containing): the segment `index` is in, none past its end.
    #[cfg_attr(rust_js, rust_js::link_name = "containing")]
    pub fn containing(&self, index: u32) -> Option<SegmentData> {
        unreachable!()
    }
}

pub mod segments {
    use super::*;

    /// `Iterator.from(segments)`: each segment, in order, a JS iterator (ADR 0140): `segments::iter(words.segment(text))`.
    #[cfg_attr(rust_js, rust_js::link_name = "Iterator.from")]
    pub fn iter(segments: &Segments) -> Box<dyn Iterator<Item = SegmentData>> {
        unreachable!()
    }
}

/// [`Intl.Segmenter`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter): text split into what a locale sees as its letters, words or sentences.
#[cfg_attr(rust_js, rust_js::name = "Intl.Segmenter")]
pub struct Segmenter(PhantomData<JsObject>);

impl Segmenter {
    /// [`segmenter.segment(input)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/segment): `input` split.
    #[cfg_attr(rust_js, rust_js::link_name = "segment")]
    pub fn segment(&self, input: &str) -> &'static Segments {
        unreachable!()
    }

    /// [`segmenter.resolvedOptions()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/resolvedOptions): the options it uses, as its locale resolved them.
    #[cfg_attr(rust_js, rust_js::link_name = "resolvedOptions")]
    pub fn resolved_options(&self) -> ResolvedSegmenterOptions {
        unreachable!()
    }
}

pub mod segmenter {
    use super::*;

    /// [`new Intl.Segmenter(locales, options)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/Segmenter): one of the first of `locales` it has, or the user's of none, as `options` say.
    #[cfg_attr(rust_js, rust_js::link_name = "new Intl.Segmenter")]
    pub fn new(locales: &[&str], options: &SegmenterOptions) -> &'static Segmenter {
        unreachable!()
    }

    /// [`Intl.Segmenter.supportedLocalesOf(locales)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/supportedLocalesOf): those of `locales` it has, without falling back to the user's.
    #[cfg_attr(rust_js, rust_js::link_name = "Intl.Segmenter.supportedLocalesOf")]
    pub fn supported_locales_of(locales: &[&str], options: &SupportedLocalesOptions) -> Vec<String> {
        unreachable!()
    }
}
