// Generated by rust-js from examples/report.rs. Do not edit.

import {
  $cmp,
  $debugF64,
  $debugParseError,
  $debugStr,
  $index,
  $lines,
  $maxBy,
  $orInsertWith,
  $pad,
  $parseBool,
  $parseChar,
  $parseF64,
  $parseInt,
  $position,
  $sortedEntries,
  $toFixed,
  $trim,
  $unwrapErr,
  $windows,
} from "@rust-js/runtime";

var $rowErrorDisplay;

function rowErrorFromParseIntError_from(e) {
  return { TAG: "Number", _0: e };
}

export function rowErrorDisplay() {
  if ($rowErrorDisplay === undefined) {
    $rowErrorDisplay = { fmt: rowErrorDisplay_fmt };
  }
  return $rowErrorDisplay;
}

function rowErrorDisplay_fmt(rowError) {
  if (rowError.TAG === "Fields") {
    return `expected 4 fields, got ${rowError._0}`;
  }
  if (rowError.TAG === "Number") {
    return `bad number: ${rowError._0}`;
  }
  return `empty ${rowError._0}`;
}

const HEADERS = ["name", "team", "score", "age"];

function parse_row(line) {
  const parts = line.split(",").map((s) => $trim(s));
  if (parts.length !== 4) {
    return { TAG: "Err", _0: { TAG: "Fields", _0: parts.length } };
  }
  if (!parts[0]) {
    return { TAG: "Err", _0: { TAG: "Empty", _0: "name" } };
  }
  const result = $parseInt(parts[2], 0, 4294967295);
  if (result.TAG === "Err") {
    return { TAG: "Err", _0: rowErrorFromParseIntError_from(result._0) };
  }
  const score = result._0;
  const result$1 = $parseInt(parts[3], 0, 4294967295);
  if (result$1.TAG === "Err") {
    return { TAG: "Err", _0: rowErrorFromParseIntError_from(result$1._0) };
  }
  const age = result$1._0;
  return { TAG: "Ok", _0: { name: parts[0], team: parts[1], score, age } };
}

function capitalize(s) {
  return [
    ...Array.from(s)
      .slice(0, 1)
      .flatMap((c) => Array.from(c.toUpperCase())),
    ...Array.from(s).slice(1),
  ].join("");
}

function grade(score, age) {
  if (score >= 90) {
    return "A";
  }
  if (score >= 70 && score <= 89 && age < 30) {
    return "B+";
  }
  if (score >= 70 && score <= 89) {
    return "B";
  }
  return "C";
}

export function table(input) {
  let out = "";
  const rows = [];
  for (const [i, line] of $lines(input)
    .map((x, i) => [i, x])
    .slice(1)) {
    const match = parse_row(line);
    if (match.TAG === "Ok") {
      rows.push(match._0);
    } else {
      out += `line ${(i + 1) >>> 0}: ${rowErrorDisplay_fmt(match._0)}\n`;
    }
  }
  rows.sort((a, b) => $cmp(b.score, a.score) || $cmp(a.name, b.name));
  out += `${$pad(HEADERS[0], 8, "<")}|${$pad(HEADERS[2], 6, ">")}|${$pad("grade", 7, "^")}|${HEADERS[1]}\n`;
  for (const r of rows) {
    out += `${$pad(capitalize(r.name), 8, "<")}|${String(r.score).padStart(6)}|${$pad(grade(r.score, r.age), 7, "^")}|${r.team.toUpperCase()}\n`;
  }
  const byTeam = new Map();
  for (const r$1 of rows) {
    $orInsertWith(byTeam, r$1.team, () => []).push(r$1);
  }
  for (const [team, members] of $sortedEntries(byTeam, $cmp)) {
    const total = members.map((r) => r.score).reduce((a, b) => (a + b) >>> 0, 0);
    const avg = total / members.length;
    const key = (r) => [r.score, [r.age]];
    const best =
      $maxBy(members, (a, b) => {
        const left = key(a);
        const right = key(b);
        return $cmp(left[0], right[0]) || $cmp(right[1][0], left[1][0]);
      })?.name ?? "-";
    out += `${$pad(team, 6, ">")}: n=${members.length} avg=${$toFixed(avg, 1).padStart(6)} best=${best}\n`;
  }
  const ages = rows.map((r) => r.age);
  const gaps = $windows(ages, 2).map((w) => (($index(w, 1) | 0) - ($index(w, 0) | 0)) | 0);
  out += `[${gaps.map((item) => String(item)).join(", ")}]\n`;
  const arg = rows.every((r) => r.score > 50);
  const arg$1 = rows.some((r) => r.team === "red");
  const arg$2 = $position(rows, (r) => r.age > 40);
  out += `${arg} ${arg$1} ${arg$2 == null ? "None" : `Some(${arg$2})`}\n`;
  return out;
}

export function parse_errors() {
  return `${$debugParseError($unwrapErr($parseInt("", 0, 255)), "ParseIntError")} ${$debugParseError($unwrapErr($parseInt("300", 0, 255)), "ParseIntError")} ${$debugParseError($unwrapErr($parseInt("-40000", -32768, 32767)), "ParseIntError")} ${$debugParseError($unwrapErr($parseF64("x"), undefined, $debugF64), "ParseFloatError")} ${$debugParseError($unwrapErr($parseBool("no")), "ParseBoolError")} ${$debugParseError(
    $unwrapErr($parseChar("ab"), undefined, (e$1) => $debugStr(e$1, "'")),
    "ParseCharError",
  )}`;
}

export function function_values(words) {
  const upper = words.map((w) => w.toUpperCase());
  const spaces = Array.from("a b	c").map((c) => /^\p{White_Space}$/u.test(c));
  const roots = [4, 2.25, 9].map((n) => Math.sqrt(n));
  const owned = words.map((s) => s);
  return [upper, spaces, roots, owned];
}

export function report() {
  const input =
    "name,team,score,age\nann, red, 91, 34\nbob,blue,78,25\ncy,red,78,45\n,blue,5,5\ndee,blue,x,3\neve,green,64,29\nfay,red\ngus, blue ,88,31\nßen,red,70,20\n";
  const arg = table(input);
  const arg$1 = parse_errors();
  const arg$2 = function_values(["x", "é"]);
  return `${arg}${arg$1}\n([${arg$2[0].map((item) => $debugStr(item)).join(", ")}], [${arg$2[1].map((item) => String(item)).join(", ")}], [${arg$2[2].map((item) => $debugF64(item)).join(", ")}], [${arg$2[3].map((item) => $debugStr(item)).join(", ")}])\n`;
}
//# sourceMappingURL=report.js.map
